#ifndef CSR_BT_OBEX_FTP_CLIENT_STRING_H__
#define CSR_BT_OBEX_FTP_CLIENT_STRING_H__

#include "csr_synergy.h"
/****************************************************************************

               (c) Cambridge Silicon Radio Limited 2010

               All rights reserved and confidential information of CSR

REVISION:      $Revision: #1 $
****************************************************************************/

#include "csr_bt_ui_strings.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Key defines */
/* Main menu */
#define CSR_BT_FTP_CLIENT_APP_INVALID_KEY                   0x00
#define CSR_BT_FTP_CLIENT_APP_CONNECT_KEY                   0x01
#define CSR_BT_FTP_CLIENT_APP_CONNECT_AUTH_KEY              0x02
#define CSR_BT_FTP_CLIENT_APP_DISABLE_SRM_KEY               0x03
#define CSR_BT_FTP_CLIENT_APP_ENABLE_SRM_KEY                0x04
/* Connected menu */
#define CSR_BT_FTP_CLIENT_APP_DISCONNECT_KEY                0x10
#define CSR_BT_FTP_CLIENT_APP_BROWSE_LOCAL_KEY              0x11
#define CSR_BT_FTP_CLIENT_APP_BROWSE_REMOTE_KEY             0x12
#define CSR_BT_FTP_CLIENT_APP_MAKE_DIR_KEY                  0x15
#define CSR_BT_FTP_CLIENT_APP_DELETE_KEY                    0x16
#define CSR_BT_FTP_CLIENT_APP_CHANGE_TO_SELECTED_DIR_KEY    0x17
#define CSR_BT_FTP_CLIENT_APP_TRANSFER_SELECTED_FILE_KEY    0x18
#define CSR_BT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB1_KEY      0x19
#define CSR_BT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB2_KEY      0x1A
#define CSR_BT_FTP_CLIENT_APP_MOVE_KEY                      0x1B
#define CSR_BT_FTP_CLIENT_APP_COPY_KEY                      0x1C
#define CSR_BT_FTP_CLIENT_APP_SET_PERM_KEY                  0x1D


#define CSR_BT_FTP_CLIENT_APP_MOVE_TO_AMP_KEY               0x20
#define CSR_BT_FTP_CLIENT_APP_MOVE_TO_EDR_KEY               0x21

/* Text defines */
/* Main menu texts */
#define TEXT_FTP_CLIENT_APP_MAIN_MENU_STRING                    "OBEX FTP Client"
#define TEXT_FTP_CLIENT_APP_MAIN_MENU_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MAIN_MENU_STRING)
#define TEXT_FTP_CLIENT_APP_CONNECT_STRING                      "Connect to device"
#define TEXT_FTP_CLIENT_APP_CONNECT_UCS2                        CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CONNECT_STRING)
#define TEXT_FTP_CLIENT_APP_CONNECT_AUTH_STRING                 "Connect with authentication to device"
#define TEXT_FTP_CLIENT_APP_CONNECT_AUTH_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CONNECT_AUTH_STRING)
#define TEXT_FTP_CLIENT_APP_DISABLE_SRM_STRING                  "Disable SRM"
#define TEXT_FTP_CLIENT_APP_DISABLE_SRM_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_DISABLE_SRM_STRING)
#define TEXT_FTP_CLIENT_APP_ENABLE_SRM_STRING                   "Enable SRM"
#define TEXT_FTP_CLIENT_APP_ENABLE_SRM_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_ENABLE_SRM_STRING)

/* Connected menu texts */
#define TEXT_FTP_CLIENT_APP_DISCONNECT_STRING                   "Disconnect"
#define TEXT_FTP_CLIENT_APP_DISCONNECT_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_DISCONNECT_STRING)
#define TEXT_FTP_CLIENT_APP_BROWSE_LOCAL_STRING                 "Browse local device"
#define TEXT_FTP_CLIENT_APP_BROWSE_LOCAL_UCS2                   CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_BROWSE_LOCAL_STRING)
#define TEXT_FTP_CLIENT_APP_BROWSE_REMOTE_STRING                "Browse remote device"
#define TEXT_FTP_CLIENT_APP_BROWSE_REMOTE_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_BROWSE_REMOTE_STRING)
#define TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB1_STRING         "PTS: Change to non-existent folder 'sub1'"
#define TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB1_UCS2           CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB1_STRING)
#define TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB2_STRING         "PTS: Change to non-existent folder 'sub2'"
#define TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB2_UCS2           CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_PTS_NONEXISTING_SUB2_STRING)
#define TEXT_FTP_CLIENT_APP_MAKE_DIR_STRING                     "Make directory"
#define TEXT_FTP_CLIENT_APP_MAKE_DIR_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MAKE_DIR_STRING)

#define TEXT_FTP_CLIENT_APP_MOVE_STRING                         "Move Selection"
#define TEXT_FTP_CLIENT_APP_MOVE_UCS2                           CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MOVE_STRING)

#define TEXT_FTP_CLIENT_APP_COPY_STRING                         "Copy Selection"
#define TEXT_FTP_CLIENT_APP_COPY_UCS2                           CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_COPY_STRING)

#define TEXT_FTP_CLIENT_APP_SET_PERM_STRING                     "Perm:(U,G,O)=(RWGD,RWGD,RWGD)"
#define TEXT_FTP_CLIENT_APP_SET_PERM_UCS2                       CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_SET_PERM_STRING)

#define TEXT_FTP_CLIENT_APP_MOVE_TO_AMP_STRING                  "Move channel to AMP"
#define TEXT_FTP_CLIENT_APP_MOVE_TO_AMP_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MOVE_TO_AMP_STRING)
#define TEXT_FTP_CLIENT_APP_MOVE_TO_EDR_STRING                  "Move channel to BR/EDR"
#define TEXT_FTP_CLIENT_APP_MOVE_TO_EDR_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MOVE_TO_EDR_STRING)
#define TEXT_FTP_CLIENT_APP_DELETE_SELECTED_TARGET_STRING       "Delete target"
#define TEXT_FTP_CLIENT_APP_DELETE_SELECTED_TARGET_UCS2         CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_DELETE_SELECTED_TARGET_STRING)
#define TEXT_FTP_CLIENT_APP_CHANGE_TO_SELECTED_DIR_STRING       "Change to target directory"
#define TEXT_FTP_CLIENT_APP_CHANGE_TO_SELECTED_DIR_UCS2         CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CHANGE_TO_SELECTED_DIR_STRING)
#define TEXT_FTP_CLIENT_APP_TRANSFER_SELECTED_FILE_STRING       "Transfer target"
#define TEXT_FTP_CLIENT_APP_TRANSFER_SELECTED_FILE_UCS2         CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_TRANSFER_SELECTED_FILE_STRING)

/* Other texts */            
#define TEXT_FTP_CLIENT_APP_CANCEL_CONNECT_STRING               "Cancel connect attempt"
#define TEXT_FTP_CLIENT_APP_CANCEL_CONNECT_UCS2                 CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CANCEL_CONNECT_STRING)
#define TEXT_FTP_CLIENT_APP_CANCEL_SELECTION_STRING             "Cancel selection"
#define TEXT_FTP_CLIENT_APP_CANCEL_SELECTION_UCS2               CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CANCEL_SELECTION_STRING)
#define TEXT_FTP_CLIENT_APP_LOCAL_DIR_STRING                    "Local directory name:"
#define TEXT_FTP_CLIENT_APP_LOCAL_DIR_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_LOCAL_DIR_STRING)
#define TEXT_FTP_CLIENT_APP_REMOTE_DIR_STRING                   "Remote directory name:"
#define TEXT_FTP_CLIENT_APP_REMOTE_DIR_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_REMOTE_DIR_STRING)
#define TEXT_FTP_CLIENT_APP_INPUT_DIR_STRING                    "Directory name:"
#define TEXT_FTP_CLIENT_APP_INPUT_DIR_UCS2                      CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_INPUT_DIR_STRING)
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_STRING                  "File browser"
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_UCS2                    CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_FILEBROWSER_STRING)
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_LOCAL_STRING            "File browser local"
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_LOCAL_UCS2              CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_FILEBROWSER_LOCAL_STRING)
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_REMOTE_STRING           "File browser remote"
#define TEXT_FTP_CLIENT_APP_FILEBROWSER_REMOTE_UCS2             CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_FILEBROWSER_REMOTE_STRING)
#define TEXT_FTP_CLIENT_APP_FILE_TRANSFER_STRING                "File transfer"
#define TEXT_FTP_CLIENT_APP_FILE_TRANSFER_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_FILE_TRANSFER_STRING)
#define TEXT_FTP_CLIENT_APP_CONNECTING_STRING                   "Connecting..."
#define TEXT_FTP_CLIENT_APP_CONNECTING_UCS2                     CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_CONNECTING_STRING)
#define TEXT_FTP_CLIENT_APP_TO_AMP_STRING                       "ToAMP"
#define TEXT_FTP_CLIENT_APP_TO_AMP_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_TO_AMP_STRING)
#define TEXT_FTP_CLIENT_APP_TO_EDR_STRING                       "ToBREDR"
#define TEXT_FTP_CLIENT_APP_TO_EDR_UCS2                         CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_TO_EDR_STRING)

#define TEXT_FTP_CLIENT_APP_COPY_GET_PATH_STRING                "Copy: Enter path/filename"
#define TEXT_FTP_CLIENT_APP_COPY_GET_PATH_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_COPY_GET_PATH_STRING)

#define TEXT_FTP_CLIENT_APP_MOVE_GET_PATH_STRING                "Move: Enter path/filename"
#define TEXT_FTP_CLIENT_APP_MOVE_GET_PATH_UCS2                  CONVERT_TEXT_STRING_2_UCS2(TEXT_FTP_CLIENT_APP_MOVE_GET_PATH_STRING)
   

#ifdef __cplusplus
}
#endif

#endif
