####### Build
DEBUG ?= 1
LOG ?= 1
USE_DEPENDENCY_FILES ?= 0
ENABLE_SHUTDOWN ?= 1
EXCEPTION_PANIC ?= 0
INCLUDE_EXCEPTION_HANDLER_MODULE ?= 1
INSTALL_INTERNAL_APP_DEPENDENCIES ?= 1
INSTALL_INTERNAL_TEST_DEPENDENCIES ?= 0

####### Enable BLE (Bluetooth Low Energy)
CSR_BT_LE_ENABLE ?= 0

####### Enable AMP
CSR_AMP_ENABLE ?= 0

####### Link against these AMPs in demo applications
CSR_BT_APP_AMP_WIFI ?= 0
CSR_BT_APP_AMP_UWB  ?= 0

USB_WARMREST ?= 1

####### Framework config
FW_CONFIG ?= samsung

####### Local tools
DEVEL_TOOL_PATH  ?= $(FW_ROOT)/devel/tools
LOG_TOOL_PATH    ?= $(DEVEL_TOOL_PATH)/log
CREATE_PRIM_CODE ?= $(DEVEL_TOOL_PATH)/prim_code_generator/create_prim_code.sh

####### FTS 
FTS_VER ?= 10.11.19.0

####### Wireshark
WIRESHARK_DIS_DEVEL_VERSION ?= 5.0.0
WIRESHARK_VERSION           ?= 1.2.0
WIRESHARK_BUILD_DIS_ROOT    ?= "s:/install/3rdparty/sw/wireshark_disector_devel/$(WIRESHARK_DIS_DEVEL_VERSION)"
WIRESHARK_EXE_ROOT          ?= "c:/Program Files/Wireshark"
WIRESHARK_PLUGIN_ROOT       ?= $(WIRESHARK_EXE_ROOT)/plugins/$(WIRESHARK_VERSION)

####### CASTE
CASTE_ROOT ?= s:/install/test/caste/8.0.0
CASTE_CONFIG ?= default

####### Config header
CONFIG_H := csr_bt_usr_config_default.h


### change samsung code ###########
CSR_SAMSUNG_SERVICE := 1

SS_CODEC_SUPPORT ?= 0

HID_DRIVER_SUPPORT ?= 0


ifneq ($(SS_CODEC_SUPPORT),1)
CFLAGS += -DEXCLUDE_CSR_BT_SS_CODEC
endif

ifneq ($(HID_DRIVER_SUPPORT),1)
CFLAGS += -DEXCLUDE_CSR_BT_HID_DRIVER
endif

CFLAGS += -DCSR_BT_APP_SAMSUNG=1 
CFLAGS += -D__CSR_COUNT_WD__
CFLAGS += 	-DEXCLUDE_CSR_BT_BPPS_MODULE \
    -DEXCLUDE_CSR_BT_BPPC_MODULE \
	-DEXCLUDE_CSR_BT_BIPC_MODULE \
	-DEXCLUDE_CSR_BT_BIPS_MODULE \
	-DEXCLUDE_CSR_BT_FTC_MODULE \
	-DEXCLUDE_CSR_BT_FTS_MODULE \
	-DEXCLUDE_CSR_BT_MAPC_MODULE \
	-DEXCLUDE_CSR_BT_MCAP_MODULE \
	-DEXCLUDE_CSR_BT_OPC_MODULE \
	-DEXCLUDE_CSR_BT_OPS_MODULE \
	-DEXCLUDE_CSR_BT_PAC_MODULE \
	-DEXCLUDE_CSR_BT_PAS_MODULE \
	-DEXCLUDE_CSR_BT_SYNCC_MODULE \
	-DEXCLUDE_CSR_BT_SYNCS_MODULE \
	-DEXCLUDE_CSR_BT_SMLC_MODULE \
	-DEXCLUDE_CSR_BT_SMLS_MODULE \
	-DEXCLUDE_CSR_BT_BSL_MODULE \
	-DEXCLUDE_CSR_BT_DG_MODULE \
	-DEXCLUDE_CSR_BT_DUNC_MODULE \
	-DEXCLUDE_CSR_BT_HCRP_MODULE \
	-DEXCLUDE_CSR_BT_HDP_MODULE \
	-DEXCLUDE_CSR_BT_HFG_MODULE \
	-DEXCLUDE_CSR_BT_HIDD_MODULE \
	-DEXCLUDE_CSR_BT_IWU_MODULE \
	-DEXCLUDE_CSR_BT_JSR82_MODULE \
	-DEXCLUDE_CSR_BT_PAN_MODULE \
	-DEXCLUDE_CSR_BT_SAPC_MODULE \
	-DEXCLUDE_CSR_BT_SAPS_MODULE \
	-DEXCLUDE_CSR_BT_SCO_MODULE \
	-DEXCLUDE_CSR_BT_TCS_MODULE \
	-DEXCLUDE_CSR_BT_AT_MODULE \
	-DEXCLUDE_CSR_BT_AV_AUDIO_SOURCE
