# Tester excluding L2CAP. Only testing non L2CAP profiles

ifneq ($(TARGET),bdb3-nucleus-arm6kz)
    include $(TOP)/config/config-tester.mk
else
    include $(TOP)/config/config-tester-bdb.mk
endif

CSR_BT_LE_ENABLE = 0
CSR_AMP_ENABLE = 0

INSTALL_INTERNAL_APP_DEPENDENCIES = 0
INSTALL_INTERNAL_TEST_DEPENDENCIES = 1

CFLAGS += \
-DEXCLUDE_CSR_BT_AT_MODULE \
-DEXCLUDE_CSR_BT_BIPC_MODULE \
-DEXCLUDE_CSR_BT_BIPS_MODULE \
-DEXCLUDE_CSR_BT_BPPC_MODULE \
-DEXCLUDE_CSR_BT_BPPS_MODULE \
-DEXCLUDE_CSR_BT_DG_MODULE \
-DEXCLUDE_CSR_BT_DUNC_MODULE \
-DEXCLUDE_CSR_BT_DUT_MODULE \
-DEXCLUDE_CSR_BT_FTC_MODULE \
-DEXCLUDE_CSR_BT_FTS_MODULE \
-DEXCLUDE_CSR_BT_GOEP_20_MODULE \
-DEXCLUDE_CSR_BT_HFG_MODULE \
-DEXCLUDE_CSR_BT_HF_MODULE \
-DEXCLUDE_CSR_BT_JSR82_MODULE \
-DEXCLUDE_CSR_BT_MAPC_MODULE \
-DEXCLUDE_CSR_BT_MAPS_MODULE \
-DEXCLUDE_CSR_BT_OPC_MODULE \
-DEXCLUDE_CSR_BT_OPS_MODULE \
-DEXCLUDE_CSR_BT_PAC_MODULE \
-DEXCLUDE_CSR_BT_PAS_MODULE \
-DEXCLUDE_CSR_BT_RFC_MODULE \
-DEXCLUDE_CSR_BT_SAPC_MODULE \
-DEXCLUDE_CSR_BT_SAPS_MODULE \
-DEXCLUDE_CSR_BT_SCO_MODULE \
-DEXCLUDE_CSR_BT_SMLC_MODULE \
-DEXCLUDE_CSR_BT_SMLS_MODULE \
-DEXCLUDE_CSR_BT_SPP_MODULE \
-DEXCLUDE_CSR_BT_SYNCC_MODULE \
-DEXCLUDE_CSR_BT_SYNCS_MODULE \

#-DEXCLUDE_CSR_BT_AV_MODULE \
#-DEXCLUDE_CSR_BT_AVRCP_MODULE \
#-DEXCLUDE_CSR_BT_BSL_MODULE \
#-DEXCLUDE_CSR_BT_HCRP_MODULE \
#-DEXCLUDE_CSR_BT_HDP_MODULE \
#-DEXCLUDE_CSR_BT_HIDD_MODULE \
#-DEXCLUDE_CSR_BT_HIDH_MODULE \
#-DEXCLUDE_CSR_BT_L2CA_MODULE \
#-DEXCLUDE_CSR_BT_MCAP_MODULE \
#-DEXCLUDE_CSR_BT_MDER_MODULE \
#-DEXCLUDE_CSR_BT_PHDC_AG_MODULE \
#-DEXCLUDE_CSR_BT_PHDC_MGR_MODULE \
#-DEXCLUDE_CSR_BT_PROX_SRV_MODULE \
#-DEXCLUDE_CSR_BT_THERM_SRV_MODULE \
#-DEXCLUDE_CSR_BT_TPT_MODULE \

# Tester related flags:
CFLAGS += \
-DEXCLUDE_CSR_BT_GAP_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_L2CAP_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_PPI_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_RFCOMM_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_SDP_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_SPP_SPEC_TEST_CASES \
-DEXCLUDE_CSR_BT_SYNC_SPEC_TEST_CASES \
-DEXCLUDE_CSR_LOOPING_TEST_CASES \
