
INSTALL_INTERNAL_APP_DEPENDENCIES = 0
INSTALL_INTERNAL_TEST_DEPENDENCIES = 1

CSR_AMP_ENABLE ?= 0
CSR_BT_LE_ENABLE ?= 0


#-DEXCLUDE_CSR_BT_AVRCP_MODULE 
#-DEXCLUDE_CSR_BT_AV_MODULE 
#-DEXCLUDE_CSR_BT_HF_MODULE
#-DEXCLUDE_CSR_BT_HFG_MODULE \


CFLAGS += \
-DEXCLUDE_CSR_BT_HFG_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_AV_OPTIONAL \
-DEXCLUDE_CSR_BT_AVRCP_TG_MODULE \
-DEXCLUDE_CSR_BT_AVRCP_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_CM_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SPP_MODULE \
-DEXCLUDE_CSR_BT_OPTIONAL_UTILS \
-DEXCLUDE_CSR_BT_OPC_MODULE \
-DEXCLUDE_CSR_BT_OPS_MODULE \
-DEXCLUDE_CSR_BT_DG_MODULE \
-DEXCLUDE_CSR_BT_FTC_MODULE \
-DEXCLUDE_CSR_BT_FTS_MODULE \
-DEXCLUDE_CSR_BT_PAS_MODULE \
-DEXCLUDE_CSR_BT_AT_MODULE \
-DEXCLUDE_CSR_BT_BIPC_MODULE \
-DEXCLUDE_CSR_BT_BIPS_MODULE \
-DEXCLUDE_CSR_BT_BPPS_MODULE \
-DEXCLUDE_CSR_BT_BPPC_MODULE \
-DEXCLUDE_CSR_BT_BSL_MODULE \
-DEXCLUDE_CSR_BT_DUNC_MODULE \
-DEXCLUDE_CSR_BT_HCRP_MODULE \
-DEXCLUDE_CSR_BT_HIDD_MODULE \
-DEXCLUDE_CSR_BT_HIDH_MODULE \
-DEXCLUDE_CSR_BT_JSR82_MODULE \
-DEXCLUDE_CSR_BT_PAC_MODULE \
-DEXCLUDE_CSR_BT_SAPC_MODULE \
-DEXCLUDE_CSR_BT_SAPS_MODULE \
-DEXCLUDE_CSR_BT_SMLC_MODULE \
-DEXCLUDE_CSR_BT_SMLS_MODULE \
-DEXCLUDE_CSR_BT_SYNCS_MODULE \
-DEXCLUDE_CSR_BT_SYNCC_MODULE \
-DEXCLUDE_CSR_BT_MAPC_MODULE \
-DEXCLUDE_CSR_BT_MAPS_MODULE \
-DEXCLUDE_CSR_BT_HDP_MODULE \
-DEXCLUDE_CSR_BT_TPT_MODULE \
-DEXCLUDE_CSR_BT_MCAP_MODULE \
-DEXCLUDE_CSR_BT_MDER_MODULE \
-DEXCLUDE_CSR_BT_PHDC_AG_MODULE \
-DEXCLUDE_CSR_BT_PHDC_MGR_MODULE \
-DEXCLUDE_CSR_BT_GOEP_20_MODULE 

#
# Exclude generic code.
# These defines guard code that is "generic" and used by several profiles.
#
# Note: Consistency in the specified defines has to be maintained or
# build failures will occur, e.g. specifying EXCLUDE_BCHS_RFC_MODULE
# without excluding all the RFCOMM based profiles.
# TODO: Move the relevant ones into the header files - No good, the build system needs them in CFLAGS
#       to avoid building them (which will fail since the external references do not exist as the exclude
#       -flags will be defined in csr_synergy.h)
CFLAGS += \
-DEXCLUDE_CSR_BT_PPP_MODULE \
-DEXCLUDE_CSR_BT_PAN_MODULE

#-DEXCLUDE_CSR_BT_SCO_MODULE \
#-DEXCLUDE_BCCMD_MODULE 
#-DEXCLUDE_BCHS_RFC_MODULE 
#-DEXCLUDE_BCHS_L2CA_MODULE 

# Tester related flags:
CFLAGS += -DEXCLUDE_CSR_BT_BNEP_SPEC_TEST_CASES

include $(TOP)/config/config-default.mk

ifneq ($(TARGET),bdb3-nucleus-arm6kz)
    include $(TOP)/config/config-tester.mk
else
    include $(TOP)/config/config-tester-bdb.mk
endif

