include $(TOP)/config/config-default.mk

CSR_BT_LE_ENABLE = 1
CSR_AMP_ENABLE = 1

INSTALL_INTERNAL_APP_DEPENDENCIES = 0
INSTALL_INTERNAL_TEST_DEPENDENCIES = 1

CFLAGS += \
-DEXCLUDE_CSR_BT_AV_OPTIONAL \
-DEXCLUDE_CSR_BT_AVRCP_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_BPPC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_BPPS_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_CM_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_FTC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_FTS_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_GATT_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_HFG_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_HF_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_OPC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_OPS_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_OPTIONAL_UTILS \
-DEXCLUDE_CSR_BT_SC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SD_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SMLC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SMLS_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SPP_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SYNCC_MODULE_OPTIONAL \
-DEXCLUDE_CSR_BT_SYNCS_MODULE_OPTIONAL \
