#-*-Makefile-*-
###############################################################################
#
#                (c) Cambridge Silicon Radio Limited 2009
#
#                All rights reserved and confidential information of CSR
#
# REVISION:      $Revision: #1 $
###############################################################################
TOP := ../../..
include $(TOP)/local_rules.mk

all: lib 

bin:

lib: 
	$(MAKE) -C code lib

clean: 
	$(MAKE) -C code clean
