/*****************************************************************************

            (c) Cambridge Silicon Radio Limited 2010
            All rights reserved and confidential information of CSR

            Refer to LICENSE.txt included with this source for details
            on the license terms.

*****************************************************************************/

/* Note: this is an auto-generated file. */

#include "csr_synergy.h"
#include "csr_msgconv.h"
#include "csr_pmem.h"
#include "csr_util.h"
#include "csr_bt_hand_coded.h"
#include "csr_bt_sdc_converter_init.h"
#ifndef EXCLUDE_CSR_BT_SDC_MODULE
#include "csr_bt_sdc_serialize.h"
#include "sdc_prim.h"

static CsrMsgConvMsgEntry csr_bt_sdc_conv_lut[] = {
#ifndef EXCLUDE_SDC_CLOSE_SEARCH_IND
    { SDC_CLOSE_SEARCH_IND, SDC_CLOSE_SEARCH_IND_TSizeof, SDC_CLOSE_SEARCH_IND_TSer, SDC_CLOSE_SEARCH_IND_TDes, SDC_CLOSE_SEARCH_IND_TSerFree },
#endif /* EXCLUDE_SDC_CLOSE_SEARCH_IND */
#ifndef EXCLUDE_SDC_CLOSE_SEARCH_REQ
    { SDC_CLOSE_SEARCH_REQ, SDC_CLOSE_SEARCH_REQ_TSizeof, SDC_CLOSE_SEARCH_REQ_TSer, SDC_CLOSE_SEARCH_REQ_TDes, SDC_CLOSE_SEARCH_REQ_TSerFree },
#endif /* EXCLUDE_SDC_CLOSE_SEARCH_REQ */
#ifndef EXCLUDE_SDC_CONFIG_CFM
    { SDC_CONFIG_CFM, SDC_CONFIG_CFM_TSizeof, SDC_CONFIG_CFM_TSer, SDC_CONFIG_CFM_TDes, SDC_CONFIG_CFM_TSerFree },
#endif /* EXCLUDE_SDC_CONFIG_CFM */
#ifndef EXCLUDE_SDC_CONFIG_REQ
    { SDC_CONFIG_REQ, SDC_CONFIG_REQ_TSizeof, SDC_CONFIG_REQ_TSer, SDC_CONFIG_REQ_TDes, SDC_CONFIG_REQ_TSerFree },
#endif /* EXCLUDE_SDC_CONFIG_REQ */
#ifndef EXCLUDE_SDC_OPEN_SEARCH_CFM
    { SDC_OPEN_SEARCH_CFM, SDC_OPEN_SEARCH_CFM_TSizeof, SDC_OPEN_SEARCH_CFM_TSer, SDC_OPEN_SEARCH_CFM_TDes, SDC_OPEN_SEARCH_CFM_TSerFree },
#endif /* EXCLUDE_SDC_OPEN_SEARCH_CFM */
#ifndef EXCLUDE_SDC_OPEN_SEARCH_REQ
    { SDC_OPEN_SEARCH_REQ, SDC_OPEN_SEARCH_REQ_TSizeof, SDC_OPEN_SEARCH_REQ_TSer, SDC_OPEN_SEARCH_REQ_TDes, SDC_OPEN_SEARCH_REQ_TSerFree },
#endif /* EXCLUDE_SDC_OPEN_SEARCH_REQ */
#ifndef EXCLUDE_SDC_SERVICE_ATTRIBUTE_CFM
    { SDC_SERVICE_ATTRIBUTE_CFM, SDC_SERVICE_ATTRIBUTE_CFM_TSizeof, SDC_SERVICE_ATTRIBUTE_CFM_TSer, SDC_SERVICE_ATTRIBUTE_CFM_TDes, SDC_SERVICE_ATTRIBUTE_CFM_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_ATTRIBUTE_CFM */
#ifndef EXCLUDE_SDC_SERVICE_ATTRIBUTE_REQ
    { SDC_SERVICE_ATTRIBUTE_REQ, SDC_SERVICE_ATTRIBUTE_REQ_TSizeof, SDC_SERVICE_ATTRIBUTE_REQ_TSer, SDC_SERVICE_ATTRIBUTE_REQ_TDes, SDC_SERVICE_ATTRIBUTE_REQ_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_ATTRIBUTE_REQ */
#ifndef EXCLUDE_SDC_SERVICE_SEARCH_ATTRIBUTE_CFM
    { SDC_SERVICE_SEARCH_ATTRIBUTE_CFM, SDC_SERVICE_SEARCH_ATTRIBUTE_CFM_TSizeof, SDC_SERVICE_SEARCH_ATTRIBUTE_CFM_TSer, SDC_SERVICE_SEARCH_ATTRIBUTE_CFM_TDes, SDC_SERVICE_SEARCH_ATTRIBUTE_CFM_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_SEARCH_ATTRIBUTE_CFM */
#ifndef EXCLUDE_SDC_SERVICE_SEARCH_ATTRIBUTE_REQ
    { SDC_SERVICE_SEARCH_ATTRIBUTE_REQ, SDC_SERVICE_SEARCH_ATTRIBUTE_REQ_TSizeof, SDC_SERVICE_SEARCH_ATTRIBUTE_REQ_TSer, SDC_SERVICE_SEARCH_ATTRIBUTE_REQ_TDes, SDC_SERVICE_SEARCH_ATTRIBUTE_REQ_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_SEARCH_ATTRIBUTE_REQ */
#ifndef EXCLUDE_SDC_SERVICE_SEARCH_CFM
    { SDC_SERVICE_SEARCH_CFM, SDC_SERVICE_SEARCH_CFM_TSizeof, SDC_SERVICE_SEARCH_CFM_TSer, SDC_SERVICE_SEARCH_CFM_TDes, SDC_SERVICE_SEARCH_CFM_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_SEARCH_CFM */
#ifndef EXCLUDE_SDC_SERVICE_SEARCH_REQ
    { SDC_SERVICE_SEARCH_REQ, SDC_SERVICE_SEARCH_REQ_TSizeof, SDC_SERVICE_SEARCH_REQ_TSer, SDC_SERVICE_SEARCH_REQ_TDes, SDC_SERVICE_SEARCH_REQ_TSerFree },
#endif /* EXCLUDE_SDC_SERVICE_SEARCH_REQ */
#ifndef EXCLUDE_SDC_TERMINATE_PRIMITIVE_REQ
    { SDC_TERMINATE_PRIMITIVE_REQ, SDC_TERMINATE_PRIMITIVE_REQ_TSizeof, SDC_TERMINATE_PRIMITIVE_REQ_TSer, SDC_TERMINATE_PRIMITIVE_REQ_TDes, SDC_TERMINATE_PRIMITIVE_REQ_TSerFree },
#endif /* EXCLUDE_SDC_TERMINATE_PRIMITIVE_REQ */
    { 0, NULL, NULL, NULL, NULL }
};

void CsrBtSdcConverterInit(void)
{
    CsrMsgConvInsert(CSR_BT_SDC_PRIM, csr_bt_sdc_conv_lut);
}

#ifdef CSR_LOG_ENABLE
static CsrLogPrimitiveInformation csr_bt_sdc_conv_info = {
    CSR_BT_SDC_PRIM,
    "CSR_BT_SDC_PRIM",
    csr_bt_sdc_conv_lut
};

CsrLogPrimitiveInformation* CsrBtSdcTechInfoGet(void)
{
    return &csr_bt_sdc_conv_info;
}
#endif
#endif

