/*****************************************************************************

            (c) Cambridge Silicon Radio Limited 2010
            All rights reserved and confidential information of CSR

            Refer to LICENSE.txt included with this source for details
            on the license terms.

*****************************************************************************/

/* Note: this is an auto-generated file. */

#include "csr_synergy.h"
#include "csr_msgconv.h"
#include "csr_pmem.h"
#include "csr_util.h"
#include "csr_bt_hand_coded.h"
#include "csr_bt_att_converter_init.h"
#ifndef EXCLUDE_CSR_BT_ATT_MODULE
#include "csr_bt_att_serialize.h"
#include "att_prim.h"

static CsrMsgConvMsgEntry csr_bt_att_conv_lut[] = {
#ifndef EXCLUDE_ATT_ACCESS_IND
    { ATT_ACCESS_IND, ATT_ACCESS_IND_TSizeof, ATT_ACCESS_IND_TSer, ATT_ACCESS_IND_TDes, ATT_ACCESS_IND_TSerFree },
#endif /* EXCLUDE_ATT_ACCESS_IND */
#ifndef EXCLUDE_ATT_ACCESS_RSP
    { ATT_ACCESS_RSP, ATT_ACCESS_RSP_TSizeof, ATT_ACCESS_RSP_TSer, ATT_ACCESS_RSP_TDes, ATT_ACCESS_RSP_TSerFree },
#endif /* EXCLUDE_ATT_ACCESS_RSP */
#ifndef EXCLUDE_ATT_ADD_CFM
    { ATT_ADD_CFM, ATT_ADD_CFM_TSizeof, ATT_ADD_CFM_TSer, ATT_ADD_CFM_TDes, ATT_ADD_CFM_TSerFree },
#endif /* EXCLUDE_ATT_ADD_CFM */
#ifndef EXCLUDE_ATT_ADD_DB_CFM
    { ATT_ADD_DB_CFM, ATT_ADD_DB_CFM_TSizeof, ATT_ADD_DB_CFM_TSer, ATT_ADD_DB_CFM_TDes, ATT_ADD_DB_CFM_TSerFree },
#endif /* EXCLUDE_ATT_ADD_DB_CFM */
#ifndef EXCLUDE_ATT_ADD_DB_REQ
    { ATT_ADD_DB_REQ, ATT_ADD_DB_REQ_TSizeof, ATT_ADD_DB_REQ_TSer, ATT_ADD_DB_REQ_TDes, ATT_ADD_DB_REQ_TSerFree },
#endif /* EXCLUDE_ATT_ADD_DB_REQ */
#ifndef EXCLUDE_ATT_ADD_REQ
    { ATT_ADD_REQ, ATT_ADD_REQ_TSizeof, ATT_ADD_REQ_TSer, ATT_ADD_REQ_TDes, ATT_ADD_REQ_TSerFree },
#endif /* EXCLUDE_ATT_ADD_REQ */
#ifndef EXCLUDE_ATT_CONNECT_CFM
    { ATT_CONNECT_CFM, ATT_CONNECT_CFM_TSizeof, ATT_CONNECT_CFM_TSer, ATT_CONNECT_CFM_TDes, ATT_CONNECT_CFM_TSerFree },
#endif /* EXCLUDE_ATT_CONNECT_CFM */
#ifndef EXCLUDE_ATT_CONNECT_IND
    { ATT_CONNECT_IND, ATT_CONNECT_IND_TSizeof, ATT_CONNECT_IND_TSer, ATT_CONNECT_IND_TDes, ATT_CONNECT_IND_TSerFree },
#endif /* EXCLUDE_ATT_CONNECT_IND */
#ifndef EXCLUDE_ATT_CONNECT_REQ
    { ATT_CONNECT_REQ, ATT_CONNECT_REQ_TSizeof, ATT_CONNECT_REQ_TSer, ATT_CONNECT_REQ_TDes, ATT_CONNECT_REQ_TSerFree },
#endif /* EXCLUDE_ATT_CONNECT_REQ */
#ifndef EXCLUDE_ATT_CONNECT_RSP
    { ATT_CONNECT_RSP, ATT_CONNECT_RSP_TSizeof, ATT_CONNECT_RSP_TSer, ATT_CONNECT_RSP_TDes, ATT_CONNECT_RSP_TSerFree },
#endif /* EXCLUDE_ATT_CONNECT_RSP */
#ifndef EXCLUDE_ATT_DEBUG_IND
    { ATT_DEBUG_IND, ATT_DEBUG_IND_TSizeof, ATT_DEBUG_IND_TSer, ATT_DEBUG_IND_TDes, ATT_DEBUG_IND_TSerFree },
#endif /* EXCLUDE_ATT_DEBUG_IND */
#ifndef EXCLUDE_ATT_DISCONNECT_CFM
    { ATT_DISCONNECT_CFM, ATT_DISCONNECT_CFM_TSizeof, ATT_DISCONNECT_CFM_TSer, ATT_DISCONNECT_CFM_TDes, ATT_DISCONNECT_CFM_TSerFree },
#endif /* EXCLUDE_ATT_DISCONNECT_CFM */
#ifndef EXCLUDE_ATT_DISCONNECT_IND
    { ATT_DISCONNECT_IND, ATT_DISCONNECT_IND_TSizeof, ATT_DISCONNECT_IND_TSer, ATT_DISCONNECT_IND_TDes, ATT_DISCONNECT_IND_TSerFree },
#endif /* EXCLUDE_ATT_DISCONNECT_IND */
#ifndef EXCLUDE_ATT_DISCONNECT_REQ
    { ATT_DISCONNECT_REQ, ATT_DISCONNECT_REQ_TSizeof, ATT_DISCONNECT_REQ_TSer, ATT_DISCONNECT_REQ_TDes, ATT_DISCONNECT_REQ_TSerFree },
#endif /* EXCLUDE_ATT_DISCONNECT_REQ */
#ifndef EXCLUDE_ATT_EXCHANGE_MTU_CFM
    { ATT_EXCHANGE_MTU_CFM, ATT_EXCHANGE_MTU_CFM_TSizeof, ATT_EXCHANGE_MTU_CFM_TSer, ATT_EXCHANGE_MTU_CFM_TDes, ATT_EXCHANGE_MTU_CFM_TSerFree },
#endif /* EXCLUDE_ATT_EXCHANGE_MTU_CFM */
#ifndef EXCLUDE_ATT_EXCHANGE_MTU_IND
    { ATT_EXCHANGE_MTU_IND, ATT_EXCHANGE_MTU_IND_TSizeof, ATT_EXCHANGE_MTU_IND_TSer, ATT_EXCHANGE_MTU_IND_TDes, ATT_EXCHANGE_MTU_IND_TSerFree },
#endif /* EXCLUDE_ATT_EXCHANGE_MTU_IND */
#ifndef EXCLUDE_ATT_EXCHANGE_MTU_REQ
    { ATT_EXCHANGE_MTU_REQ, ATT_EXCHANGE_MTU_REQ_TSizeof, ATT_EXCHANGE_MTU_REQ_TSer, ATT_EXCHANGE_MTU_REQ_TDes, ATT_EXCHANGE_MTU_REQ_TSerFree },
#endif /* EXCLUDE_ATT_EXCHANGE_MTU_REQ */
#ifndef EXCLUDE_ATT_EXCHANGE_MTU_RSP
    { ATT_EXCHANGE_MTU_RSP, ATT_EXCHANGE_MTU_RSP_TSizeof, ATT_EXCHANGE_MTU_RSP_TSer, ATT_EXCHANGE_MTU_RSP_TDes, ATT_EXCHANGE_MTU_RSP_TSerFree },
#endif /* EXCLUDE_ATT_EXCHANGE_MTU_RSP */
#ifndef EXCLUDE_ATT_EXECUTE_WRITE_CFM
    { ATT_EXECUTE_WRITE_CFM, ATT_EXECUTE_WRITE_CFM_TSizeof, ATT_EXECUTE_WRITE_CFM_TSer, ATT_EXECUTE_WRITE_CFM_TDes, ATT_EXECUTE_WRITE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_EXECUTE_WRITE_CFM */
#ifndef EXCLUDE_ATT_EXECUTE_WRITE_REQ
    { ATT_EXECUTE_WRITE_REQ, ATT_EXECUTE_WRITE_REQ_TSizeof, ATT_EXECUTE_WRITE_REQ_TSer, ATT_EXECUTE_WRITE_REQ_TDes, ATT_EXECUTE_WRITE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_EXECUTE_WRITE_REQ */
#ifndef EXCLUDE_ATT_FIND_BY_TYPE_VALUE_CFM
    { ATT_FIND_BY_TYPE_VALUE_CFM, ATT_FIND_BY_TYPE_VALUE_CFM_TSizeof, ATT_FIND_BY_TYPE_VALUE_CFM_TSer, ATT_FIND_BY_TYPE_VALUE_CFM_TDes, ATT_FIND_BY_TYPE_VALUE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_FIND_BY_TYPE_VALUE_CFM */
#ifndef EXCLUDE_ATT_FIND_BY_TYPE_VALUE_REQ
    { ATT_FIND_BY_TYPE_VALUE_REQ, ATT_FIND_BY_TYPE_VALUE_REQ_TSizeof, ATT_FIND_BY_TYPE_VALUE_REQ_TSer, ATT_FIND_BY_TYPE_VALUE_REQ_TDes, ATT_FIND_BY_TYPE_VALUE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_FIND_BY_TYPE_VALUE_REQ */
#ifndef EXCLUDE_ATT_FIND_INFO_CFM
    { ATT_FIND_INFO_CFM, ATT_FIND_INFO_CFM_TSizeof, ATT_FIND_INFO_CFM_TSer, ATT_FIND_INFO_CFM_TDes, ATT_FIND_INFO_CFM_TSerFree },
#endif /* EXCLUDE_ATT_FIND_INFO_CFM */
#ifndef EXCLUDE_ATT_FIND_INFO_REQ
    { ATT_FIND_INFO_REQ, ATT_FIND_INFO_REQ_TSizeof, ATT_FIND_INFO_REQ_TSer, ATT_FIND_INFO_REQ_TDes, ATT_FIND_INFO_REQ_TSerFree },
#endif /* EXCLUDE_ATT_FIND_INFO_REQ */
#ifndef EXCLUDE_ATT_HANDLE_VALUE_CFM
    { ATT_HANDLE_VALUE_CFM, ATT_HANDLE_VALUE_CFM_TSizeof, ATT_HANDLE_VALUE_CFM_TSer, ATT_HANDLE_VALUE_CFM_TDes, ATT_HANDLE_VALUE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_HANDLE_VALUE_CFM */
#ifndef EXCLUDE_ATT_HANDLE_VALUE_IND
    { ATT_HANDLE_VALUE_IND, ATT_HANDLE_VALUE_IND_TSizeof, ATT_HANDLE_VALUE_IND_TSer, ATT_HANDLE_VALUE_IND_TDes, ATT_HANDLE_VALUE_IND_TSerFree },
#endif /* EXCLUDE_ATT_HANDLE_VALUE_IND */
#ifndef EXCLUDE_ATT_HANDLE_VALUE_REQ
    { ATT_HANDLE_VALUE_REQ, ATT_HANDLE_VALUE_REQ_TSizeof, ATT_HANDLE_VALUE_REQ_TSer, ATT_HANDLE_VALUE_REQ_TDes, ATT_HANDLE_VALUE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_HANDLE_VALUE_REQ */
#ifndef EXCLUDE_ATT_HANDLE_VALUE_RSP
    { ATT_HANDLE_VALUE_RSP, ATT_HANDLE_VALUE_RSP_TSizeof, ATT_HANDLE_VALUE_RSP_TSer, ATT_HANDLE_VALUE_RSP_TDes, ATT_HANDLE_VALUE_RSP_TSerFree },
#endif /* EXCLUDE_ATT_HANDLE_VALUE_RSP */
#ifndef EXCLUDE_ATT_PREPARE_WRITE_CFM
    { ATT_PREPARE_WRITE_CFM, ATT_PREPARE_WRITE_CFM_TSizeof, ATT_PREPARE_WRITE_CFM_TSer, ATT_PREPARE_WRITE_CFM_TDes, ATT_PREPARE_WRITE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_PREPARE_WRITE_CFM */
#ifndef EXCLUDE_ATT_PREPARE_WRITE_REQ
    { ATT_PREPARE_WRITE_REQ, ATT_PREPARE_WRITE_REQ_TSizeof, ATT_PREPARE_WRITE_REQ_TSer, ATT_PREPARE_WRITE_REQ_TDes, ATT_PREPARE_WRITE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_PREPARE_WRITE_REQ */
#ifndef EXCLUDE_ATT_READ_BLOB_CFM
    { ATT_READ_BLOB_CFM, ATT_READ_BLOB_CFM_TSizeof, ATT_READ_BLOB_CFM_TSer, ATT_READ_BLOB_CFM_TDes, ATT_READ_BLOB_CFM_TSerFree },
#endif /* EXCLUDE_ATT_READ_BLOB_CFM */
#ifndef EXCLUDE_ATT_READ_BLOB_REQ
    { ATT_READ_BLOB_REQ, ATT_READ_BLOB_REQ_TSizeof, ATT_READ_BLOB_REQ_TSer, ATT_READ_BLOB_REQ_TDes, ATT_READ_BLOB_REQ_TSerFree },
#endif /* EXCLUDE_ATT_READ_BLOB_REQ */
#ifndef EXCLUDE_ATT_READ_BY_GROUP_TYPE_CFM
    { ATT_READ_BY_GROUP_TYPE_CFM, ATT_READ_BY_GROUP_TYPE_CFM_TSizeof, ATT_READ_BY_GROUP_TYPE_CFM_TSer, ATT_READ_BY_GROUP_TYPE_CFM_TDes, ATT_READ_BY_GROUP_TYPE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_READ_BY_GROUP_TYPE_CFM */
#ifndef EXCLUDE_ATT_READ_BY_GROUP_TYPE_REQ
    { ATT_READ_BY_GROUP_TYPE_REQ, ATT_READ_BY_GROUP_TYPE_REQ_TSizeof, ATT_READ_BY_GROUP_TYPE_REQ_TSer, ATT_READ_BY_GROUP_TYPE_REQ_TDes, ATT_READ_BY_GROUP_TYPE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_READ_BY_GROUP_TYPE_REQ */
#ifndef EXCLUDE_ATT_READ_BY_TYPE_CFM
    { ATT_READ_BY_TYPE_CFM, ATT_READ_BY_TYPE_CFM_TSizeof, ATT_READ_BY_TYPE_CFM_TSer, ATT_READ_BY_TYPE_CFM_TDes, ATT_READ_BY_TYPE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_READ_BY_TYPE_CFM */
#ifndef EXCLUDE_ATT_READ_BY_TYPE_REQ
    { ATT_READ_BY_TYPE_REQ, ATT_READ_BY_TYPE_REQ_TSizeof, ATT_READ_BY_TYPE_REQ_TSer, ATT_READ_BY_TYPE_REQ_TDes, ATT_READ_BY_TYPE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_READ_BY_TYPE_REQ */
#ifndef EXCLUDE_ATT_READ_CFM
    { ATT_READ_CFM, ATT_READ_CFM_TSizeof, ATT_READ_CFM_TSer, ATT_READ_CFM_TDes, ATT_READ_CFM_TSerFree },
#endif /* EXCLUDE_ATT_READ_CFM */
#ifndef EXCLUDE_ATT_READ_MULTI_CFM
    { ATT_READ_MULTI_CFM, ATT_READ_MULTI_CFM_TSizeof, ATT_READ_MULTI_CFM_TSer, ATT_READ_MULTI_CFM_TDes, ATT_READ_MULTI_CFM_TSerFree },
#endif /* EXCLUDE_ATT_READ_MULTI_CFM */
#ifndef EXCLUDE_ATT_READ_MULTI_REQ
    { ATT_READ_MULTI_REQ, ATT_READ_MULTI_REQ_TSizeof, ATT_READ_MULTI_REQ_TSer, ATT_READ_MULTI_REQ_TDes, ATT_READ_MULTI_REQ_TSerFree },
#endif /* EXCLUDE_ATT_READ_MULTI_REQ */
#ifndef EXCLUDE_ATT_READ_REQ
    { ATT_READ_REQ, ATT_READ_REQ_TSizeof, ATT_READ_REQ_TSer, ATT_READ_REQ_TDes, ATT_READ_REQ_TSerFree },
#endif /* EXCLUDE_ATT_READ_REQ */
#ifndef EXCLUDE_ATT_REGISTER_CFM
    { ATT_REGISTER_CFM, ATT_REGISTER_CFM_TSizeof, ATT_REGISTER_CFM_TSer, ATT_REGISTER_CFM_TDes, ATT_REGISTER_CFM_TSerFree },
#endif /* EXCLUDE_ATT_REGISTER_CFM */
#ifndef EXCLUDE_ATT_REGISTER_REQ
    { ATT_REGISTER_REQ, ATT_REGISTER_REQ_TSizeof, ATT_REGISTER_REQ_TSer, ATT_REGISTER_REQ_TDes, ATT_REGISTER_REQ_TSerFree },
#endif /* EXCLUDE_ATT_REGISTER_REQ */
#ifndef EXCLUDE_ATT_REMOVE_CFM
    { ATT_REMOVE_CFM, ATT_REMOVE_CFM_TSizeof, ATT_REMOVE_CFM_TSer, ATT_REMOVE_CFM_TDes, ATT_REMOVE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_REMOVE_CFM */
#ifndef EXCLUDE_ATT_REMOVE_REQ
    { ATT_REMOVE_REQ, ATT_REMOVE_REQ_TSizeof, ATT_REMOVE_REQ_TSer, ATT_REMOVE_REQ_TDes, ATT_REMOVE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_REMOVE_REQ */
#ifndef EXCLUDE_ATT_UNREGISTER_CFM
    { ATT_UNREGISTER_CFM, ATT_UNREGISTER_CFM_TSizeof, ATT_UNREGISTER_CFM_TSer, ATT_UNREGISTER_CFM_TDes, ATT_UNREGISTER_CFM_TSerFree },
#endif /* EXCLUDE_ATT_UNREGISTER_CFM */
#ifndef EXCLUDE_ATT_UNREGISTER_REQ
    { ATT_UNREGISTER_REQ, ATT_UNREGISTER_REQ_TSizeof, ATT_UNREGISTER_REQ_TSer, ATT_UNREGISTER_REQ_TDes, ATT_UNREGISTER_REQ_TSerFree },
#endif /* EXCLUDE_ATT_UNREGISTER_REQ */
#ifndef EXCLUDE_ATT_WRITE_CFM
    { ATT_WRITE_CFM, ATT_WRITE_CFM_TSizeof, ATT_WRITE_CFM_TSer, ATT_WRITE_CFM_TDes, ATT_WRITE_CFM_TSerFree },
#endif /* EXCLUDE_ATT_WRITE_CFM */
#ifndef EXCLUDE_ATT_WRITE_REQ
    { ATT_WRITE_REQ, ATT_WRITE_REQ_TSizeof, ATT_WRITE_REQ_TSer, ATT_WRITE_REQ_TDes, ATT_WRITE_REQ_TSerFree },
#endif /* EXCLUDE_ATT_WRITE_REQ */
    { 0, NULL, NULL, NULL, NULL }
};

void CsrBtAttConverterInit(void)
{
    CsrMsgConvInsert(CSR_BT_ATT_PRIM, csr_bt_att_conv_lut);
}

#ifdef CSR_LOG_ENABLE
static CsrLogPrimitiveInformation csr_bt_att_conv_info = {
    CSR_BT_ATT_PRIM,
    "CSR_BT_ATT_PRIM",
    csr_bt_att_conv_lut
};

CsrLogPrimitiveInformation* CsrBtAttTechInfoGet(void)
{
    return &csr_bt_att_conv_info;
}
#endif
#endif

