/*****************************************************************************

            (c) Cambridge Silicon Radio Limited 2010
            All rights reserved and confidential information of CSR

            Refer to LICENSE.txt included with this source for details
            on the license terms.

*****************************************************************************/

/* Note: this is an auto-generated file. */

#include "csr_synergy.h"
#include "csr_msgconv.h"
#include "csr_pmem.h"
#include "csr_util.h"
#include "csr_bt_hand_coded.h"
#include "csr_bt_rfcomm_converter_init.h"
#ifndef EXCLUDE_CSR_BT_RFCOMM_MODULE
#include "csr_bt_rfcomm_serialize.h"
#include "rfcomm_prim.h"

static CsrMsgConvMsgEntry csr_bt_rfcomm_conv_lut[] = {
#ifndef EXCLUDE_RFC_CLIENT_CONNECT_CFM
    { RFC_CLIENT_CONNECT_CFM, RFC_CLIENT_CONNECT_CFM_TSizeof, RFC_CLIENT_CONNECT_CFM_TSer, RFC_CLIENT_CONNECT_CFM_TDes, RFC_CLIENT_CONNECT_CFM_TSerFree },
#endif /* EXCLUDE_RFC_CLIENT_CONNECT_CFM */
#ifndef EXCLUDE_RFC_CLIENT_CONNECT_REQ
    { RFC_CLIENT_CONNECT_REQ, RFC_CLIENT_CONNECT_REQ_TSizeof, RFC_CLIENT_CONNECT_REQ_TSer, RFC_CLIENT_CONNECT_REQ_TDes, RFC_CLIENT_CONNECT_REQ_TSerFree },
#endif /* EXCLUDE_RFC_CLIENT_CONNECT_REQ */
#ifndef EXCLUDE_RFC_DATAREAD_IND
    { RFC_DATAREAD_IND, RFC_DATAREAD_IND_TSizeof, RFC_DATAREAD_IND_TSer, RFC_DATAREAD_IND_TDes, RFC_DATAREAD_IND_TSerFree },
#endif /* EXCLUDE_RFC_DATAREAD_IND */
#ifndef EXCLUDE_RFC_DATAREAD_RSP
    { RFC_DATAREAD_RSP, RFC_DATAREAD_RSP_TSizeof, RFC_DATAREAD_RSP_TSer, RFC_DATAREAD_RSP_TDes, RFC_DATAREAD_RSP_TSerFree },
#endif /* EXCLUDE_RFC_DATAREAD_RSP */
#ifndef EXCLUDE_RFC_DATAWRITE_CFM
    { RFC_DATAWRITE_CFM, RFC_DATAWRITE_CFM_TSizeof, RFC_DATAWRITE_CFM_TSer, RFC_DATAWRITE_CFM_TDes, RFC_DATAWRITE_CFM_TSerFree },
#endif /* EXCLUDE_RFC_DATAWRITE_CFM */
#ifndef EXCLUDE_RFC_DATAWRITE_REQ
    { RFC_DATAWRITE_REQ, RFC_DATAWRITE_REQ_TSizeof, RFC_DATAWRITE_REQ_TSer, RFC_DATAWRITE_REQ_TDes, RFC_DATAWRITE_REQ_TSerFree },
#endif /* EXCLUDE_RFC_DATAWRITE_REQ */
#ifndef EXCLUDE_RFC_DISCONNECT_CFM
    { RFC_DISCONNECT_CFM, RFC_DISCONNECT_CFM_TSizeof, RFC_DISCONNECT_CFM_TSer, RFC_DISCONNECT_CFM_TDes, RFC_DISCONNECT_CFM_TSerFree },
#endif /* EXCLUDE_RFC_DISCONNECT_CFM */
#ifndef EXCLUDE_RFC_DISCONNECT_IND
    { RFC_DISCONNECT_IND, RFC_DISCONNECT_IND_TSizeof, RFC_DISCONNECT_IND_TSer, RFC_DISCONNECT_IND_TDes, RFC_DISCONNECT_IND_TSerFree },
#endif /* EXCLUDE_RFC_DISCONNECT_IND */
#ifndef EXCLUDE_RFC_DISCONNECT_REQ
    { RFC_DISCONNECT_REQ, RFC_DISCONNECT_REQ_TSizeof, RFC_DISCONNECT_REQ_TSer, RFC_DISCONNECT_REQ_TDes, RFC_DISCONNECT_REQ_TSerFree },
#endif /* EXCLUDE_RFC_DISCONNECT_REQ */
#ifndef EXCLUDE_RFC_DISCONNECT_RSP
    { RFC_DISCONNECT_RSP, RFC_DISCONNECT_RSP_TSizeof, RFC_DISCONNECT_RSP_TSer, RFC_DISCONNECT_RSP_TDes, RFC_DISCONNECT_RSP_TSerFree },
#endif /* EXCLUDE_RFC_DISCONNECT_RSP */
#ifndef EXCLUDE_RFC_ERROR_IND
    { RFC_ERROR_IND, RFC_ERROR_IND_TSizeof, RFC_ERROR_IND_TSer, RFC_ERROR_IND_TDes, RFC_ERROR_IND_TSerFree },
#endif /* EXCLUDE_RFC_ERROR_IND */
#ifndef EXCLUDE_RFC_FC_CFM
    { RFC_FC_CFM, RFC_FC_CFM_TSizeof, RFC_FC_CFM_TSer, RFC_FC_CFM_TDes, RFC_FC_CFM_TSerFree },
#endif /* EXCLUDE_RFC_FC_CFM */
#ifndef EXCLUDE_RFC_FC_IND
    { RFC_FC_IND, RFC_FC_IND_TSizeof, RFC_FC_IND_TSer, RFC_FC_IND_TDes, RFC_FC_IND_TSerFree },
#endif /* EXCLUDE_RFC_FC_IND */
#ifndef EXCLUDE_RFC_FC_REQ
    { RFC_FC_REQ, RFC_FC_REQ_TSizeof, RFC_FC_REQ_TSer, RFC_FC_REQ_TDes, RFC_FC_REQ_TSerFree },
#endif /* EXCLUDE_RFC_FC_REQ */
#ifndef EXCLUDE_RFC_INIT_CFM
    { RFC_INIT_CFM, RFC_INIT_CFM_TSizeof, RFC_INIT_CFM_TSer, RFC_INIT_CFM_TDes, RFC_INIT_CFM_TSerFree },
#endif /* EXCLUDE_RFC_INIT_CFM */
#ifndef EXCLUDE_RFC_INIT_REQ
    { RFC_INIT_REQ, RFC_INIT_REQ_TSizeof, RFC_INIT_REQ_TSer, RFC_INIT_REQ_TDes, RFC_INIT_REQ_TSerFree },
#endif /* EXCLUDE_RFC_INIT_REQ */
#ifndef EXCLUDE_RFC_L2CA_AMP_LINK_LOSS_IND
    { RFC_L2CA_AMP_LINK_LOSS_IND, RFC_L2CA_AMP_LINK_LOSS_IND_TSizeof, RFC_L2CA_AMP_LINK_LOSS_IND_TSer, RFC_L2CA_AMP_LINK_LOSS_IND_TDes, RFC_L2CA_AMP_LINK_LOSS_IND_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_AMP_LINK_LOSS_IND */
#ifndef EXCLUDE_RFC_L2CA_MOVE_CHANNEL_CFM
    { RFC_L2CA_MOVE_CHANNEL_CFM, RFC_L2CA_MOVE_CHANNEL_CFM_TSizeof, RFC_L2CA_MOVE_CHANNEL_CFM_TSer, RFC_L2CA_MOVE_CHANNEL_CFM_TDes, RFC_L2CA_MOVE_CHANNEL_CFM_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_MOVE_CHANNEL_CFM */
#ifndef EXCLUDE_RFC_L2CA_MOVE_CHANNEL_CMP_IND
    { RFC_L2CA_MOVE_CHANNEL_CMP_IND, RFC_L2CA_MOVE_CHANNEL_CMP_IND_TSizeof, RFC_L2CA_MOVE_CHANNEL_CMP_IND_TSer, RFC_L2CA_MOVE_CHANNEL_CMP_IND_TDes, RFC_L2CA_MOVE_CHANNEL_CMP_IND_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_MOVE_CHANNEL_CMP_IND */
#ifndef EXCLUDE_RFC_L2CA_MOVE_CHANNEL_IND
    { RFC_L2CA_MOVE_CHANNEL_IND, RFC_L2CA_MOVE_CHANNEL_IND_TSizeof, RFC_L2CA_MOVE_CHANNEL_IND_TSer, RFC_L2CA_MOVE_CHANNEL_IND_TDes, RFC_L2CA_MOVE_CHANNEL_IND_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_MOVE_CHANNEL_IND */
#ifndef EXCLUDE_RFC_L2CA_MOVE_CHANNEL_REQ
    { RFC_L2CA_MOVE_CHANNEL_REQ, RFC_L2CA_MOVE_CHANNEL_REQ_TSizeof, RFC_L2CA_MOVE_CHANNEL_REQ_TSer, RFC_L2CA_MOVE_CHANNEL_REQ_TDes, RFC_L2CA_MOVE_CHANNEL_REQ_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_MOVE_CHANNEL_REQ */
#ifndef EXCLUDE_RFC_L2CA_MOVE_CHANNEL_RSP
    { RFC_L2CA_MOVE_CHANNEL_RSP, RFC_L2CA_MOVE_CHANNEL_RSP_TSizeof, RFC_L2CA_MOVE_CHANNEL_RSP_TSer, RFC_L2CA_MOVE_CHANNEL_RSP_TDes, RFC_L2CA_MOVE_CHANNEL_RSP_TSerFree },
#endif /* EXCLUDE_RFC_L2CA_MOVE_CHANNEL_RSP */
#ifndef EXCLUDE_RFC_LINESTATUS_CFM
    { RFC_LINESTATUS_CFM, RFC_LINESTATUS_CFM_TSizeof, RFC_LINESTATUS_CFM_TSer, RFC_LINESTATUS_CFM_TDes, RFC_LINESTATUS_CFM_TSerFree },
#endif /* EXCLUDE_RFC_LINESTATUS_CFM */
#ifndef EXCLUDE_RFC_LINESTATUS_IND
    { RFC_LINESTATUS_IND, RFC_LINESTATUS_IND_TSizeof, RFC_LINESTATUS_IND_TSer, RFC_LINESTATUS_IND_TDes, RFC_LINESTATUS_IND_TSerFree },
#endif /* EXCLUDE_RFC_LINESTATUS_IND */
#ifndef EXCLUDE_RFC_LINESTATUS_REQ
    { RFC_LINESTATUS_REQ, RFC_LINESTATUS_REQ_TSizeof, RFC_LINESTATUS_REQ_TSer, RFC_LINESTATUS_REQ_TDes, RFC_LINESTATUS_REQ_TSerFree },
#endif /* EXCLUDE_RFC_LINESTATUS_REQ */
#ifndef EXCLUDE_RFC_MODEM_STATUS_CFM
    { RFC_MODEM_STATUS_CFM, RFC_MODEM_STATUS_CFM_TSizeof, RFC_MODEM_STATUS_CFM_TSer, RFC_MODEM_STATUS_CFM_TDes, RFC_MODEM_STATUS_CFM_TSerFree },
#endif /* EXCLUDE_RFC_MODEM_STATUS_CFM */
#ifndef EXCLUDE_RFC_MODEM_STATUS_IND
    { RFC_MODEM_STATUS_IND, RFC_MODEM_STATUS_IND_TSizeof, RFC_MODEM_STATUS_IND_TSer, RFC_MODEM_STATUS_IND_TDes, RFC_MODEM_STATUS_IND_TSerFree },
#endif /* EXCLUDE_RFC_MODEM_STATUS_IND */
#ifndef EXCLUDE_RFC_MODEM_STATUS_REQ
    { RFC_MODEM_STATUS_REQ, RFC_MODEM_STATUS_REQ_TSizeof, RFC_MODEM_STATUS_REQ_TSer, RFC_MODEM_STATUS_REQ_TDes, RFC_MODEM_STATUS_REQ_TSerFree },
#endif /* EXCLUDE_RFC_MODEM_STATUS_REQ */
#ifndef EXCLUDE_RFC_NSC_IND
    { RFC_NSC_IND, RFC_NSC_IND_TSizeof, RFC_NSC_IND_TSer, RFC_NSC_IND_TDes, RFC_NSC_IND_TSerFree },
#endif /* EXCLUDE_RFC_NSC_IND */
#ifndef EXCLUDE_RFC_PORTNEG_CFM
    { RFC_PORTNEG_CFM, RFC_PORTNEG_CFM_TSizeof, RFC_PORTNEG_CFM_TSer, RFC_PORTNEG_CFM_TDes, RFC_PORTNEG_CFM_TSerFree },
#endif /* EXCLUDE_RFC_PORTNEG_CFM */
#ifndef EXCLUDE_RFC_PORTNEG_IND
    { RFC_PORTNEG_IND, RFC_PORTNEG_IND_TSizeof, RFC_PORTNEG_IND_TSer, RFC_PORTNEG_IND_TDes, RFC_PORTNEG_IND_TSerFree },
#endif /* EXCLUDE_RFC_PORTNEG_IND */
#ifndef EXCLUDE_RFC_PORTNEG_REQ
    { RFC_PORTNEG_REQ, RFC_PORTNEG_REQ_TSizeof, RFC_PORTNEG_REQ_TSer, RFC_PORTNEG_REQ_TDes, RFC_PORTNEG_REQ_TSerFree },
#endif /* EXCLUDE_RFC_PORTNEG_REQ */
#ifndef EXCLUDE_RFC_PORTNEG_RSP
    { RFC_PORTNEG_RSP, RFC_PORTNEG_RSP_TSizeof, RFC_PORTNEG_RSP_TSer, RFC_PORTNEG_RSP_TDes, RFC_PORTNEG_RSP_TSerFree },
#endif /* EXCLUDE_RFC_PORTNEG_RSP */
#ifndef EXCLUDE_RFC_REGISTER_CFM
    { RFC_REGISTER_CFM, RFC_REGISTER_CFM_TSizeof, RFC_REGISTER_CFM_TSer, RFC_REGISTER_CFM_TDes, RFC_REGISTER_CFM_TSerFree },
#endif /* EXCLUDE_RFC_REGISTER_CFM */
#ifndef EXCLUDE_RFC_REGISTER_REQ
    { RFC_REGISTER_REQ, RFC_REGISTER_REQ_TSizeof, RFC_REGISTER_REQ_TSer, RFC_REGISTER_REQ_TDes, RFC_REGISTER_REQ_TSerFree },
#endif /* EXCLUDE_RFC_REGISTER_REQ */
#ifndef EXCLUDE_RFC_SERVER_CONNECT_CFM
    { RFC_SERVER_CONNECT_CFM, RFC_SERVER_CONNECT_CFM_TSizeof, RFC_SERVER_CONNECT_CFM_TSer, RFC_SERVER_CONNECT_CFM_TDes, RFC_SERVER_CONNECT_CFM_TSerFree },
#endif /* EXCLUDE_RFC_SERVER_CONNECT_CFM */
#ifndef EXCLUDE_RFC_SERVER_CONNECT_IND
    { RFC_SERVER_CONNECT_IND, RFC_SERVER_CONNECT_IND_TSizeof, RFC_SERVER_CONNECT_IND_TSer, RFC_SERVER_CONNECT_IND_TDes, RFC_SERVER_CONNECT_IND_TSerFree },
#endif /* EXCLUDE_RFC_SERVER_CONNECT_IND */
#ifndef EXCLUDE_RFC_SERVER_CONNECT_RSP
    { RFC_SERVER_CONNECT_RSP, RFC_SERVER_CONNECT_RSP_TSizeof, RFC_SERVER_CONNECT_RSP_TSer, RFC_SERVER_CONNECT_RSP_TDes, RFC_SERVER_CONNECT_RSP_TSerFree },
#endif /* EXCLUDE_RFC_SERVER_CONNECT_RSP */
#ifndef EXCLUDE_RFC_TEST_CFM
    { RFC_TEST_CFM, RFC_TEST_CFM_TSizeof, RFC_TEST_CFM_TSer, RFC_TEST_CFM_TDes, RFC_TEST_CFM_TSerFree },
#endif /* EXCLUDE_RFC_TEST_CFM */
#ifndef EXCLUDE_RFC_TEST_REQ
    { RFC_TEST_REQ, RFC_TEST_REQ_TSizeof, RFC_TEST_REQ_TSer, RFC_TEST_REQ_TDes, RFC_TEST_REQ_TSerFree },
#endif /* EXCLUDE_RFC_TEST_REQ */
#ifndef EXCLUDE_RFC_UNREGISTER_CFM
    { RFC_UNREGISTER_CFM, RFC_UNREGISTER_CFM_TSizeof, RFC_UNREGISTER_CFM_TSer, RFC_UNREGISTER_CFM_TDes, RFC_UNREGISTER_CFM_TSerFree },
#endif /* EXCLUDE_RFC_UNREGISTER_CFM */
#ifndef EXCLUDE_RFC_UNREGISTER_REQ
    { RFC_UNREGISTER_REQ, RFC_UNREGISTER_REQ_TSizeof, RFC_UNREGISTER_REQ_TSer, RFC_UNREGISTER_REQ_TDes, RFC_UNREGISTER_REQ_TSerFree },
#endif /* EXCLUDE_RFC_UNREGISTER_REQ */
    { 0, NULL, NULL, NULL, NULL }
};

void CsrBtRfcommConverterInit(void)
{
    CsrMsgConvInsert(CSR_BT_RFCOMM_PRIM, csr_bt_rfcomm_conv_lut);
}

#ifdef CSR_LOG_ENABLE
static CsrLogPrimitiveInformation csr_bt_rfcomm_conv_info = {
    CSR_BT_RFCOMM_PRIM,
    "CSR_BT_RFCOMM_PRIM",
    csr_bt_rfcomm_conv_lut
};

CsrLogPrimitiveInformation* CsrBtRfcommTechInfoGet(void)
{
    return &csr_bt_rfcomm_conv_info;
}
#endif
#endif

