/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   rfcomm_channel_fsm_constants.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "rfcomm_channel_fsm_constants.h"

/* Action function table */
/*{{__FSM_MARKER(RFCOMM_CHANNEL, ACTION_FN_TABLE) */
static const fsm_action_fn_t rfcomm_channel_action_fns[] =
{
    rfc_af_access_granted,
    rfc_af_client_par_neg_cmd,
    rfc_af_server_request_cmd,
    rfc_af_cancel_connection,
    rfc_af_protocol_disconnect,
    rfc_af_client_par_neg_cfm,
    rfc_af_client_disconnect,
    rfc_af_local_disconnect_request,
    rfc_af_remote_disconnect_request,
    rfc_af_access_request,
    rfc_af_server_par_neg_rsp,
    rfc_af_server_disconnect,
    rfc_af_protocol_disconnect_cfg,
    rfc_af_access_denied,
    rfc_af_client_connected,
    rfc_af_server_connected,
    rfc_af_local_disconnect_pending,
    rfc_af_client_msc_request,
    rfc_af_client_msc_confirm,
    rfc_af_server_msc_response,
    rfc_af_msc_complete,
    rfc_af_protocol_disconnect_open,
    rfc_af_local_disconnect_confirm,
    rfc_af_disconnect_xover,
};
/*}}__FSM_END_MARKER(RFCOMM_CHANNEL, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(RFCOMM_CHANNEL, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T rfcomm_channel_transitions[] = {
  /* DISCONNECTED */
  { RFC_EV_OPEN_REQ_MUX,          RFC_AC_access_granted,             RFC_ST_CONNECTING },
  { RFC_EV_OPEN_IND_MUX,          RFC_AC_access_granted,             RFC_ST_CONNECTED },
  { RFC_EV_PARNEG_REQ,            RFC_AC_client_par_neg_cmd,         RFC_ST_CLIENT_PENDING_PARNEG },
  { RFC_EV_SERVER_IND,            RFC_AC_server_request_cmd,         RFC_ST_SERVER_CONFIGURING },
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_cancel_connection,          RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  /* CLIENT_PENDING_PARNEG */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_CFM,            RFC_AC_client_par_neg_cfm,         RFC_ST_CLIENT_CONFIGURING },
  { RFC_EV_DISC_MODE_CFM,         RFC_AC_client_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  /* CLIENT_CONFIGURING */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_OPEN_REQ_DLC,          RFC_AC_access_request,             RFC_ST_CHECKING_ACCESS },
  /* SERVER_CONFIGURING */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect_cfg,    RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_IND,            RFC_AC_server_par_neg_rsp,         RFC_ST_SERVER_CONFIGURING },
  { RFC_EV_OPEN_IND_DLC,          RFC_AC_access_request,             RFC_ST_CHECKING_ACCESS },
  { RFC_EV_DISC_MODE_RSP,         RFC_AC_server_disconnect,          RFC_ST_DISCONNECTED },
  /* CHECKING_ACCESS */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_IND,            RFC_AC_server_par_neg_rsp,         RFC_ST_CHECKING_ACCESS },
  { RFC_EV_ACCESS_CONFIRM,        RFC_AC_access_granted,             RFC_ST_CONNECTING },
  { RFC_EV_ACCESS_DECLINE,        RFC_AC_access_denied,              RFC_ST_CHECKING_ACCESS },
  /* CONNECTING */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_pending,   RFC_ST_CONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_DISC_MODE_CFM,         RFC_AC_client_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_IND,            RFC_AC_server_par_neg_rsp,         RFC_ST_CONNECTING },
  { RFC_EV_DISC_MODE_RSP,         RFC_AC_server_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_ACK_CFM_MUX,           RFC_AC_client_connected,           RFC_ST_CONNECTED },
  { RFC_EV_ACK_CFM,               RFC_AC_client_connected,           RFC_ST_MSC_PENDING },
  { RFC_EV_ACK_CFM_DISC,          RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_ACK_RSP_MUX,           RFC_AC_NULL,                       RFC_ST_CONNECTED },
  { RFC_EV_ACK_RSP,               RFC_AC_server_connected,           RFC_ST_MSC_PENDING },
  /* MSC_PENDING */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_DISC_MODE_CFM,         RFC_AC_client_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_IND,            RFC_AC_server_par_neg_rsp,         RFC_ST_MSC_PENDING },
  { RFC_EV_DISC_MODE_RSP,         RFC_AC_server_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_MSC_REQ,               RFC_AC_client_msc_request,         RFC_ST_MSC_PENDING },
  { RFC_EV_MSC_CFM,               RFC_AC_client_msc_confirm,         RFC_ST_MSC_PENDING },
  { RFC_EV_MSC_RSP,               RFC_AC_server_msc_response,        RFC_ST_MSC_PENDING },
  { RFC_EV_MSC_COMPLETE,          RFC_AC_msc_complete,               RFC_ST_CONNECTED },
  /* CONNECTED */
  { RFC_EV_DISCONNECT_REQ,        RFC_AC_local_disconnect_request,   RFC_ST_DISCONNECTING },
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect_open,   RFC_ST_DISCONNECTED },
  { RFC_EV_DISC_MODE_CFM,         RFC_AC_client_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_remote_disconnect_request,  RFC_ST_DISCONNECTED },
  { RFC_EV_PARNEG_IND,            RFC_AC_server_par_neg_rsp,         RFC_ST_CONNECTED },
  { RFC_EV_DISC_MODE_RSP,         RFC_AC_server_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_MSC_CFM,               RFC_AC_client_msc_confirm,         RFC_ST_CONNECTED },
  { RFC_EV_MSC_RSP,               RFC_AC_server_msc_response,        RFC_ST_CONNECTED },
  /* DISCONNECTING */
  { RFC_EV_PROTOCOL_DISCONNECT,   RFC_AC_protocol_disconnect,        RFC_ST_DISCONNECTED },
  { RFC_EV_DISC_MODE_CFM,         RFC_AC_client_disconnect,          RFC_ST_DISCONNECTED },
  { RFC_EV_DISCONNECT_IND,        RFC_AC_disconnect_xover,           RFC_ST_DISCONNECTING },
  { RFC_EV_ACK_CFM_MUX,           RFC_AC_local_disconnect_confirm,   RFC_ST_DISCONNECTED },
  { RFC_EV_ACK_CFM_DISC,          RFC_AC_local_disconnect_confirm,   RFC_ST_DISCONNECTED }
};
/*}}__FSM_END_MARKER(RFCOMM_CHANNEL, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(RFCOMM_CHANNEL, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T rfcomm_channel_states[RFC_ST_ST_MAX+1] = {
    { &rfcomm_channel_transitions[0] },
    { &rfcomm_channel_transitions[6] },
    { &rfcomm_channel_transitions[11] },
    { &rfcomm_channel_transitions[15] },
    { &rfcomm_channel_transitions[21] },
    { &rfcomm_channel_transitions[27] },
    { &rfcomm_channel_transitions[38] },
    { &rfcomm_channel_transitions[48] },
    { &rfcomm_channel_transitions[56] },
    { &rfcomm_channel_transitions[61] },
};
/*}}__FSM_END_MARKER(RFCOMM_CHANNEL, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(RFCOMM_CHANNEL, FSM_LOGGING) */
/* State names */
const char *const rfcomm_channel_state_names[] =
{
    "RFC_ST_DISCONNECTED",
    "RFC_ST_CLIENT_PENDING_PARNEG",
    "RFC_ST_CLIENT_CONFIGURING",
    "RFC_ST_SERVER_CONFIGURING",
    "RFC_ST_CHECKING_ACCESS",
    "RFC_ST_CONNECTING",
    "RFC_ST_MSC_PENDING",
    "RFC_ST_CONNECTED",
    "RFC_ST_DISCONNECTING",
};
#define RFCOMM_CHANNEL_STATE_NAMES_PTR (rfcomm_channel_state_names)

/* Event names */
const char *const rfcomm_channel_event_names[] =
{
    "RFC_EV_OPEN_REQ_MUX",
    "RFC_EV_OPEN_IND_MUX",
    "RFC_EV_PARNEG_REQ",
    "RFC_EV_SERVER_IND",
    "RFC_EV_DISCONNECT_REQ",
    "RFC_EV_PROTOCOL_DISCONNECT",
    "RFC_EV_PARNEG_CFM",
    "RFC_EV_DISC_MODE_CFM",
    "RFC_EV_DISCONNECT_IND",
    "RFC_EV_OPEN_REQ_DLC",
    "RFC_EV_PARNEG_IND",
    "RFC_EV_OPEN_IND_DLC",
    "RFC_EV_DISC_MODE_RSP",
    "RFC_EV_ACCESS_CONFIRM",
    "RFC_EV_ACCESS_DECLINE",
    "RFC_EV_ACK_CFM_MUX",
    "RFC_EV_ACK_CFM",
    "RFC_EV_ACK_CFM_DISC",
    "RFC_EV_ACK_RSP_MUX",
    "RFC_EV_ACK_RSP",
    "RFC_EV_MSC_REQ",
    "RFC_EV_MSC_CFM",
    "RFC_EV_MSC_RSP",
    "RFC_EV_MSC_COMPLETE",
};
#define RFCOMM_CHANNEL_EVENT_NAMES_PTR (rfcomm_channel_event_names)

/*}}__FSM_END_MARKER(RFCOMM_CHANNEL, FSM_LOGGING) */
#else
#define RFCOMM_CHANNEL_STATE_NAMES_PTR (NULL)
#define RFCOMM_CHANNEL_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(RFCOMM_CHANNEL, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T rfcomm_channel_fsm =
{
    (const FSM_SPARSE16_STATES_T *) rfcomm_channel_states,
    rfcomm_channel_action_fns
    FSM_LOG_INFO("RFCOMM_CHANNEL",
    RFCOMM_CHANNEL_STATE_NAMES_PTR,
    RFCOMM_CHANNEL_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(RFCOMM_CHANNEL, FSM_DEFINITION) */

