/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   sdc_fsm_constants.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "sdc_fsm_constants.h"

/* Action function table */
/*{{__FSM_MARKER(SDC, ACTION_FN_TABLE) */
static const fsm_action_fn_t sdc_action_fns[] =
{
    sdc_fn_search_req,
    sdc_fn_attrib_req,
    sdc_fn_search_attrib_req,
    sdc_fn_open_search_req,
    sdc_fn_connect_cfm_neg,
    sdc_fn_connect_cfm_pos,
    sdc_fn_terminate_primative,
    sdc_fn_search_req_open,
    sdc_fn_attrib_req_open,
    sdc_fn_search_attrib_req_open,
    sdc_fn_close_search_req,
    sdc_fn_disconnect_ind,
    sdc_fn_disconnected,
    sdc_fn_datawrite_cfm,
    sdc_fn_datawrite_cfm_neg,
    sdc_fn_dataread_ind,
    sdc_fn_search_complete,
    sdc_fn_search_complete_open,
};
/*}}__FSM_END_MARKER(SDC, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(SDC, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T sdc_transitions[] = {
  /* READY */
  { SDC_EV_SEARCH_REQ,             SDC_AC_search_req,              SDC_ST_CONNECTING },
  { SDC_EV_ATTRIBUTE_REQ,          SDC_AC_attrib_req,              SDC_ST_CONNECTING },
  { SDC_EV_SEARCHATTRIBUTE_REQ,    SDC_AC_search_attrib_req,       SDC_ST_CONNECTING },
  { SDC_EV_OPEN_SEARCH_REQ,        SDC_AC_open_search_req,         SDC_ST_CONNECTING },
  /* CONNECTING */
  { SDC_EV_CONNECT_CFM_NEG,        SDC_AC_connect_cfm_neg,         SDC_ST_READY },
  { SDC_EV_CONNECT_CFM_POS,        SDC_AC_connect_cfm_pos,         SDC_ST_COMMUNICATING },
  { SDC_EV_CLOSE_SEARCH_REQ,       SDC_AC_NULL,                    SDC_ST_CLOSE_PENDING },
  { SDC_EV_TERMINATE_PRIMATIVE,    SDC_AC_terminate_primative,     SDC_ST_CONNECTING },
  /* COMMUNICATING */
  { SDC_EV_SEARCH_REQ,             SDC_AC_search_req_open,         SDC_ST_COMMUNICATING },
  { SDC_EV_ATTRIBUTE_REQ,          SDC_AC_attrib_req_open,         SDC_ST_COMMUNICATING },
  { SDC_EV_SEARCHATTRIBUTE_REQ,    SDC_AC_search_attrib_req_open,  SDC_ST_COMMUNICATING },
  { SDC_EV_CLOSE_SEARCH_REQ,       SDC_AC_close_search_req,        SDC_ST_CLOSING },
  { SDC_EV_TERMINATE_PRIMATIVE,    SDC_AC_terminate_primative,     SDC_ST_COMMUNICATING },
  { SDC_EV_DISCONNECT_IND,         SDC_AC_disconnect_ind,          SDC_ST_READY },
  { SDC_EV_DISCONNECT_CFM,         SDC_AC_disconnected,            SDC_ST_READY },
  { SDC_EV_DATAWRITE_CFM,          SDC_AC_datawrite_cfm,           SDC_ST_COMMUNICATING },
  { SDC_EV_DATAWRITE_CFM_NEG,      SDC_AC_datawrite_cfm_neg,       SDC_ST_COMMUNICATING },
  { SDC_EV_DATAREAD_IND,           SDC_AC_dataread_ind,            SDC_ST_COMMUNICATING },
  { SDC_EV_SEARCH_COMPLETE,        SDC_AC_search_complete,         SDC_ST_CLOSING },
  { SDC_EV_SEARCH_COMPLETE_OPEN,   SDC_AC_search_complete_open,    SDC_ST_COMMUNICATING },
  /* CLOSE_PENDING */
  { SDC_EV_CONNECT_CFM_NEG,        SDC_AC_disconnected,            SDC_ST_READY },
  { SDC_EV_CONNECT_CFM_POS,        SDC_AC_close_search_req,        SDC_ST_CLOSING },
  /* CLOSING */
  { SDC_EV_DISCONNECT_IND,         SDC_AC_disconnect_ind,          SDC_ST_READY },
  { SDC_EV_DISCONNECT_CFM,         SDC_AC_disconnected,            SDC_ST_READY }
};
/*}}__FSM_END_MARKER(SDC, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(SDC, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T sdc_states[SDC_ST_ST_MAX+1] = {
    { &sdc_transitions[0] },
    { &sdc_transitions[4] },
    { &sdc_transitions[8] },
    { &sdc_transitions[20] },
    { &sdc_transitions[22] },
    { &sdc_transitions[24] },
};
/*}}__FSM_END_MARKER(SDC, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(SDC, FSM_LOGGING) */
/* State names */
const char *const sdc_state_names[] =
{
    "SDC_ST_READY",
    "SDC_ST_CONNECTING",
    "SDC_ST_COMMUNICATING",
    "SDC_ST_CLOSE_PENDING",
    "SDC_ST_CLOSING",
};
#define SDC_STATE_NAMES_PTR (sdc_state_names)

/* Event names */
const char *const sdc_event_names[] =
{
    "SDC_EV_SEARCH_REQ",
    "SDC_EV_ATTRIBUTE_REQ",
    "SDC_EV_SEARCHATTRIBUTE_REQ",
    "SDC_EV_OPEN_SEARCH_REQ",
    "SDC_EV_CONNECT_CFM_NEG",
    "SDC_EV_CONNECT_CFM_POS",
    "SDC_EV_CLOSE_SEARCH_REQ",
    "SDC_EV_TERMINATE_PRIMATIVE",
    "SDC_EV_DISCONNECT_IND",
    "SDC_EV_DISCONNECT_CFM",
    "SDC_EV_DATAWRITE_CFM",
    "SDC_EV_DATAWRITE_CFM_NEG",
    "SDC_EV_DATAREAD_IND",
    "SDC_EV_SEARCH_COMPLETE",
    "SDC_EV_SEARCH_COMPLETE_OPEN",
};
#define SDC_EVENT_NAMES_PTR (sdc_event_names)

/*}}__FSM_END_MARKER(SDC, FSM_LOGGING) */
#else
#define SDC_STATE_NAMES_PTR (NULL)
#define SDC_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(SDC, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T sdc_fsm =
{
    (const FSM_SPARSE16_STATES_T *) sdc_states,
    sdc_action_fns
    FSM_LOG_INFO("SDC",
    SDC_STATE_NAMES_PTR,
    SDC_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(SDC, FSM_DEFINITION) */

