#ifndef _SDC_FSM_DEFINITIONS_H
#define _SDC_FSM_DEFINITIONS_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   sdc_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(SDC, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(sdc_fn_search_req);
extern FSM_ACTION_FN(sdc_fn_attrib_req);
extern FSM_ACTION_FN(sdc_fn_search_attrib_req);
extern FSM_ACTION_FN(sdc_fn_open_search_req);
extern FSM_ACTION_FN(sdc_fn_connect_cfm_neg);
extern FSM_ACTION_FN(sdc_fn_connect_cfm_pos);
extern FSM_ACTION_FN(sdc_fn_terminate_primative);
extern FSM_ACTION_FN(sdc_fn_search_req_open);
extern FSM_ACTION_FN(sdc_fn_attrib_req_open);
extern FSM_ACTION_FN(sdc_fn_search_attrib_req_open);
extern FSM_ACTION_FN(sdc_fn_close_search_req);
extern FSM_ACTION_FN(sdc_fn_disconnect_ind);
extern FSM_ACTION_FN(sdc_fn_disconnected);
extern FSM_ACTION_FN(sdc_fn_datawrite_cfm);
extern FSM_ACTION_FN(sdc_fn_datawrite_cfm_neg);
extern FSM_ACTION_FN(sdc_fn_dataread_ind);
extern FSM_ACTION_FN(sdc_fn_search_complete);
extern FSM_ACTION_FN(sdc_fn_search_complete_open);
/*}}__FSM_END_MARKER(SDC, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(SDC, STATE_DECLARATIONS) */
#define SDC_ST_ST_MAX 5
#define SDC_ST_READY         ((fsm_state_t) 0)
#define SDC_ST_CONNECTING    ((fsm_state_t) 1)
#define SDC_ST_COMMUNICATING ((fsm_state_t) 2)
#define SDC_ST_CLOSE_PENDING ((fsm_state_t) 3)
#define SDC_ST_CLOSING       ((fsm_state_t) 4)
/*}}__FSM_END_MARKER(SDC, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(SDC, EVENT_DECLARATIONS) */
#define SDC_EV_SEARCH_REQ           ((fsm_event_t) 0)
#define SDC_EV_ATTRIBUTE_REQ        ((fsm_event_t) 1)
#define SDC_EV_SEARCHATTRIBUTE_REQ  ((fsm_event_t) 2)
#define SDC_EV_OPEN_SEARCH_REQ      ((fsm_event_t) 3)
#define SDC_EV_CONNECT_CFM_NEG      ((fsm_event_t) 4)
#define SDC_EV_CONNECT_CFM_POS      ((fsm_event_t) 5)
#define SDC_EV_CLOSE_SEARCH_REQ     ((fsm_event_t) 6)
#define SDC_EV_TERMINATE_PRIMATIVE  ((fsm_event_t) 7)
#define SDC_EV_DISCONNECT_IND       ((fsm_event_t) 8)
#define SDC_EV_DISCONNECT_CFM       ((fsm_event_t) 9)
#define SDC_EV_DATAWRITE_CFM        ((fsm_event_t) 10)
#define SDC_EV_DATAWRITE_CFM_NEG    ((fsm_event_t) 11)
#define SDC_EV_DATAREAD_IND         ((fsm_event_t) 12)
#define SDC_EV_SEARCH_COMPLETE      ((fsm_event_t) 13)
#define SDC_EV_SEARCH_COMPLETE_OPEN ((fsm_event_t) 14)
/*}}__FSM_END_MARKER(SDC, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(SDC, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(SDC, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(SDC, ACTION_FN_INDEX) */
#define SDC_AC_MAX 18
#define SDC_AC_search_req             ((fsm_action_t) 0)
#define SDC_AC_attrib_req             ((fsm_action_t) 1)
#define SDC_AC_search_attrib_req      ((fsm_action_t) 2)
#define SDC_AC_open_search_req        ((fsm_action_t) 3)
#define SDC_AC_connect_cfm_neg        ((fsm_action_t) 4)
#define SDC_AC_connect_cfm_pos        ((fsm_action_t) 5)
#define SDC_AC_terminate_primative    ((fsm_action_t) 6)
#define SDC_AC_search_req_open        ((fsm_action_t) 7)
#define SDC_AC_attrib_req_open        ((fsm_action_t) 8)
#define SDC_AC_search_attrib_req_open ((fsm_action_t) 9)
#define SDC_AC_close_search_req       ((fsm_action_t) 10)
#define SDC_AC_disconnect_ind         ((fsm_action_t) 11)
#define SDC_AC_disconnected           ((fsm_action_t) 12)
#define SDC_AC_datawrite_cfm          ((fsm_action_t) 13)
#define SDC_AC_datawrite_cfm_neg      ((fsm_action_t) 14)
#define SDC_AC_dataread_ind           ((fsm_action_t) 15)
#define SDC_AC_search_complete        ((fsm_action_t) 16)
#define SDC_AC_search_complete_open   ((fsm_action_t) 17)
#define SDC_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(SDC, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(SDC, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T sdc_fsm;
/*}}__FSM_END_MARKER(SDC, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _SDC_FSM_DEFINITIONS_H */

