#ifndef _SDS_FSM_DEFINITIONS_H
#define _SDS_FSM_DEFINITIONS_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   sds_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(SDS, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(sds_fn_register_service);
extern FSM_ACTION_FN(sds_fn_unregister_service);
extern FSM_ACTION_FN(sds_fn_connection_rsp);
extern FSM_ACTION_FN(sds_fn_register_cfm_ok);
extern FSM_ACTION_FN(sds_fn_register_cfm_err);
extern FSM_ACTION_FN(sds_fn_unregister_cfm_ok);
extern FSM_ACTION_FN(sds_fn_unregister_cfm_err);
extern FSM_ACTION_FN(sds_fn_free_memory);
extern FSM_ACTION_FN(sds_fn_connect_cfm_pos);
extern FSM_ACTION_FN(sds_fn_datawrite_cfm);
extern FSM_ACTION_FN(sds_fn_datawrite_cfm_neg);
extern FSM_ACTION_FN(sds_fn_search_response);
/*}}__FSM_END_MARKER(SDS, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(SDS, STATE_DECLARATIONS) */
#define SDS_ST_ST_MAX 4
#define SDS_ST_READY         ((fsm_state_t) 0)
#define SDS_ST_MAINTAINING   ((fsm_state_t) 1)
#define SDS_ST_CONNECTING    ((fsm_state_t) 2)
#define SDS_ST_COMMUNICATING ((fsm_state_t) 3)
/*}}__FSM_END_MARKER(SDS, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(SDS, EVENT_DECLARATIONS) */
#define SDS_EV_REGISTER_REQ            ((fsm_event_t) 0)
#define SDS_EV_UNREGISTER_REQ          ((fsm_event_t) 1)
#define SDS_EV_CONNECT_IND             ((fsm_event_t) 2)
#define SDS_EV_MAINTENANCE_COMP_OK     ((fsm_event_t) 3)
#define SDS_EV_MAINTENANCE_COMP_ERR    ((fsm_event_t) 4)
#define SDS_EV_MAINTENANCE_COMP_UN_OK  ((fsm_event_t) 5)
#define SDS_EV_MAINTENANCE_COMP_UN_ERR ((fsm_event_t) 6)
#define SDS_EV_DISCONNECT_IND          ((fsm_event_t) 7)
#define SDS_EV_CONNECT_CFM_NEG         ((fsm_event_t) 8)
#define SDS_EV_CONNECT_CFM             ((fsm_event_t) 9)
#define SDS_EV_CONFIG_COMPLETE         ((fsm_event_t) 10)
#define SDS_EV_DATAWRITE_CFM           ((fsm_event_t) 11)
#define SDS_EV_DATAWRITE_CFM_NEG       ((fsm_event_t) 12)
#define SDS_EV_DATAREAD_IND            ((fsm_event_t) 13)
/*}}__FSM_END_MARKER(SDS, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(SDS, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(SDS, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(SDS, ACTION_FN_INDEX) */
#define SDS_AC_MAX 12
#define SDS_AC_register_service   ((fsm_action_t) 0)
#define SDS_AC_unregister_service ((fsm_action_t) 1)
#define SDS_AC_connection_rsp     ((fsm_action_t) 2)
#define SDS_AC_register_cfm_ok    ((fsm_action_t) 3)
#define SDS_AC_register_cfm_err   ((fsm_action_t) 4)
#define SDS_AC_unregister_cfm_ok  ((fsm_action_t) 5)
#define SDS_AC_unregister_cfm_err ((fsm_action_t) 6)
#define SDS_AC_free_memory        ((fsm_action_t) 7)
#define SDS_AC_connect_cfm_pos    ((fsm_action_t) 8)
#define SDS_AC_datawrite_cfm      ((fsm_action_t) 9)
#define SDS_AC_datawrite_cfm_neg  ((fsm_action_t) 10)
#define SDS_AC_search_response    ((fsm_action_t) 11)
#define SDS_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(SDS, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(SDS, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T sds_fsm;
/*}}__FSM_END_MARKER(SDS, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _SDS_FSM_DEFINITIONS_H */

