/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   sds_fsm_constants.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "sds_fsm_constants.h"

/* Action function table */
/*{{__FSM_MARKER(SDS, ACTION_FN_TABLE) */
static const fsm_action_fn_t sds_action_fns[] =
{
    sds_fn_register_service,
    sds_fn_unregister_service,
    sds_fn_connection_rsp,
    sds_fn_register_cfm_ok,
    sds_fn_register_cfm_err,
    sds_fn_unregister_cfm_ok,
    sds_fn_unregister_cfm_err,
    sds_fn_free_memory,
    sds_fn_connect_cfm_pos,
    sds_fn_datawrite_cfm,
    sds_fn_datawrite_cfm_neg,
    sds_fn_search_response,
};
/*}}__FSM_END_MARKER(SDS, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(SDS, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T sds_transitions[] = {
  /* READY */
  { SDS_EV_REGISTER_REQ,              SDS_AC_register_service,    SDS_ST_MAINTAINING },
  { SDS_EV_UNREGISTER_REQ,            SDS_AC_unregister_service,  SDS_ST_MAINTAINING },
  { SDS_EV_CONNECT_IND,               SDS_AC_connection_rsp,      SDS_ST_CONNECTING },
  /* MAINTAINING */
  { SDS_EV_MAINTENANCE_COMP_OK,       SDS_AC_register_cfm_ok,     SDS_ST_READY },
  { SDS_EV_MAINTENANCE_COMP_ERR,      SDS_AC_register_cfm_err,    SDS_ST_READY },
  { SDS_EV_MAINTENANCE_COMP_UN_OK,    SDS_AC_unregister_cfm_ok,   SDS_ST_READY },
  { SDS_EV_MAINTENANCE_COMP_UN_ERR,   SDS_AC_unregister_cfm_err,  SDS_ST_READY },
  /* CONNECTING */
  { SDS_EV_DISCONNECT_IND,            SDS_AC_free_memory,         SDS_ST_READY },
  { SDS_EV_CONNECT_CFM_NEG,           SDS_AC_free_memory,         SDS_ST_READY },
  { SDS_EV_CONNECT_CFM,               SDS_AC_connect_cfm_pos,     SDS_ST_CONNECTING },
  { SDS_EV_CONFIG_COMPLETE,           SDS_AC_NULL,                SDS_ST_COMMUNICATING },
  /* COMMUNICATING */
  { SDS_EV_DISCONNECT_IND,            SDS_AC_free_memory,         SDS_ST_READY },
  { SDS_EV_DATAWRITE_CFM,             SDS_AC_datawrite_cfm,       SDS_ST_COMMUNICATING },
  { SDS_EV_DATAWRITE_CFM_NEG,         SDS_AC_datawrite_cfm_neg,   SDS_ST_COMMUNICATING },
  { SDS_EV_DATAREAD_IND,              SDS_AC_search_response,     SDS_ST_COMMUNICATING }
};
/*}}__FSM_END_MARKER(SDS, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(SDS, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T sds_states[SDS_ST_ST_MAX+1] = {
    { &sds_transitions[0] },
    { &sds_transitions[3] },
    { &sds_transitions[7] },
    { &sds_transitions[11] },
    { &sds_transitions[15] },
};
/*}}__FSM_END_MARKER(SDS, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(SDS, FSM_LOGGING) */
/* State names */
const char *const sds_state_names[] =
{
    "SDS_ST_READY",
    "SDS_ST_MAINTAINING",
    "SDS_ST_CONNECTING",
    "SDS_ST_COMMUNICATING",
};
#define SDS_STATE_NAMES_PTR (sds_state_names)

/* Event names */
const char *const sds_event_names[] =
{
    "SDS_EV_REGISTER_REQ",
    "SDS_EV_UNREGISTER_REQ",
    "SDS_EV_CONNECT_IND",
    "SDS_EV_MAINTENANCE_COMP_OK",
    "SDS_EV_MAINTENANCE_COMP_ERR",
    "SDS_EV_MAINTENANCE_COMP_UN_OK",
    "SDS_EV_MAINTENANCE_COMP_UN_ERR",
    "SDS_EV_DISCONNECT_IND",
    "SDS_EV_CONNECT_CFM_NEG",
    "SDS_EV_CONNECT_CFM",
    "SDS_EV_CONFIG_COMPLETE",
    "SDS_EV_DATAWRITE_CFM",
    "SDS_EV_DATAWRITE_CFM_NEG",
    "SDS_EV_DATAREAD_IND",
};
#define SDS_EVENT_NAMES_PTR (sds_event_names)

/*}}__FSM_END_MARKER(SDS, FSM_LOGGING) */
#else
#define SDS_STATE_NAMES_PTR (NULL)
#define SDS_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(SDS, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T sds_fsm =
{
    (const FSM_SPARSE16_STATES_T *) sds_states,
    sds_action_fns
    FSM_LOG_INFO("SDS",
    SDS_STATE_NAMES_PTR,
    SDS_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(SDS, FSM_DEFINITION) */

