ifneq ($(filter-out $(CFLAGS),-DEXCLUDE_CSR_BT_PAC_MODULE -DEXCLUDE_CSR_BT_PAS_MODULE -DEXCLUDE_CSR_BT_SYNCS_MODULE -DEXCLUDE_CSR_BT_SYNCC_MODULE -DEXCLUDE_CSR_BT_BIPS_MODULE -DEXCLUDE_CSR_BT_BIPC_MODULE -DEXCLUDE_CSR_BT_BPPC_MODULE -DEXCLUDE_CSR_BT_BPPS_MODULE -DEXCLUDE_CSR_BT_FTC_MODULE -DEXCLUDE_CSR_BT_FTS_MODULE -DEXCLUDE_CSR_BT_OPC_MODULE -DEXCLUDE_CSR_BT_OPS_MODULE -DEXCLUDE_CSR_BT_SMLC_MODULE -DEXCLUDE_CSR_BT_SMLS_MODULE  -DEXCLUDE_CSR_BT_MAPC_MODULE),)
OBEX_CMN_LIB_SRC+=csr_bt_md5.c \
	csr_bt_obex_auth.c \
	csr_bt_obex_string.c \
	csr_bt_obex_lookup_lib.c \
	csr_bt_obex_extraction_lib.c \
	csr_bt_xml_lib.c \
	csr_bt_obex_util.c
endif

ifneq ($(filter-out $(CFLAGS),-DEXCLUDE_CSR_BT_PAC_MODULE -DEXCLUDE_CSR_BT_PAS_MODULE ),)
OBEX_CMN_LIB_SRC+=csr_bt_pb_obex.c
endif

LIB_SRC += $(OBEX_CMN_LIB_SRC)
API_SRC += $(OBEX_CMN_API_SRC)

PM_LIB_OBJ += $(addprefix obex/common/,$(OBEX_CMN_LIB_SRC:.c=.o))
PM_API_OBJ += $(addprefix obex/common/,$(OBEX_CMN_API_SRC:.c=.o))
