#!/bin/sh
module="bt_usb"
device="bt_usb"
mode="666"
group="root"

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./${module}.ko $* || exit 1

major=`grep $device /proc/devices | cut -d' ' -f1`
maxminor=31

# Remove stale nodes and replace them, then give gid and perms

for minor in $(seq 0 ${maxminor}); do
    devnode=${device}${minor}
    rm -f /dev/${devnode}
    mknod /dev/${devnode} c $major $minor
    chgrp $group /dev/${devnode}
    chmod $mode  /dev/${devnode}
done
ln -sf /dev/csr_usb0 /dev/csr_usb

