#-*-Makefile-*-
###############################################################################
#
#                (c) Cambridge Silicon Radio Limited 2009
#
#                All rights reserved and confidential information of CSR
#
# REVISION:      $Revision: #1 $
###############################################################################
TOP := ../..

MODULE_NAME := phdc_ag

OBJ_PATH = $(TOP)/output/$(CONFIG)/$(TARGET)/obj/applications/$(MODULE_NAME)
include $(TOP)/local_rules.mk

SRC :=  csr_bt_phdc_ag_app_main.c \
        csr_bt_phdc_ag_app.c 

include $(TOP)/applications/generic/makefile.common.app
