#-*-Makefile-*-
###############################################################################
#
#   Copyright Cambridge Silicon Radio Limited and its licensors 2011.
#   
#   All rights reserved. 
#
#   REVISION:      $Revision: #2 $
###############################################################################
TOP := ../../../..

OBJ_PATH = $(TOP)/output/$(CONFIG)/$(TARGET)/obj/src/thermometer/server/code

include $(TOP)/local_rules.mk

MODULE_NAME := therm_srv

include $(TOP)/profile_managers/pm.mk

