###############################################################################
#
#                (c) Cambridge Silicon Radio Limited 2010
#
#                All rights reserved and confidential information of CSR
#
###############################################################################

all: lib

bin:

lib clean: 
	$(MAKE) -C usb $@

