obj-$(CONFIG_ARCH_SDP92)	+= sdp92.o sdp92_clock.o sdp92_gpio.o #micomcmd_send.o pm.o sleep.o
obj-$(CONFIG_MACH_AQUILA)	+= aquila/

# CCEP 2010 Platform
obj-$(CONFIG_ARCH_SDP1001)	+= sdp1001.o sdp1001_clock.o sdp1001_gpio.o sdp1001_misc.o #micomcmd_send.o pm.o sleep.o
obj-$(CONFIG_MACH_GRIFFIN)	+= griffin/
obj-$(CONFIG_ARCH_SDP1001FPGA)	+= sdp1001fpga.o sdp1001fpga_clock.o
obj-$(CONFIG_MACH_FPGA_GENOA)	+= fpga_genoa/
obj-$(CONFIG_ARCH_SDP1002)	+= sdp1002.o sdp1002_clock.o sdp1002_gpio.o sdp1002_misc.o
obj-$(CONFIG_MACH_DALMA)	+= dalma/
obj-$(CONFIG_ARCH_SDP1004)	+= sdp1004.o sdp1004_clock.o
obj-$(CONFIG_ARCH_SDP1004FPGA)	+= sdp1004fpga.o sdp1004fpga_clock.o
obj-$(CONFIG_MACH_FIRENZE)	+= firenze/
obj-$(CONFIG_MACH_FPGA_FIRENZE)	+= fpga_firenze/

# CCEP 2011 Platform
obj-$(CONFIG_ARCH_SDP1103)	+= sdp1103.o sdp1103_clock.o sdp1103_gpio.o sdp1103_misc.o
obj-$(CONFIG_ARCH_SDP1106)	+= sdp1106.o sdp1106_clock.o sdp1106_gpio.o sdp1106_misc.o
obj-$(CONFIG_ARCH_SDP1105)	+= sdp1105.o sdp1105_clock.o sdp1105_gpio.o sdp1105_misc.o

obj-$(CONFIG_MACH_FLAMENGO)	+= flamengo/
obj-$(CONFIG_MACH_SANTOS)	+= santos/
obj-$(CONFIG_MACH_VICTORIA)	+= victoria/

obj-$(CONFIG_ARCH_SDP1106FPGA)	+= sdp1106fpga.o sdp1106fpga_clock.o
obj-$(CONFIG_MACH_FPGA_FLAMENGO)	+= fpga_flamengo/

obj-$(CONFIG_ARCH_SDP1105FPGA)	+= sdp1105fpga.o sdp1105fpga_clock.o
obj-$(CONFIG_MACH_FPGA_VICTORIA)	+= fpga_victoria/

obj-$(CONFIG_ARCH_SDP1103FPGA)	+= sdp1103fpga.o sdp1103fpga_clock.o
obj-$(CONFIG_MACH_FPGA_SANTOS)	+= fpga_santos/

# CCEP 2012 Platform
obj-$(CONFIG_ARCH_SDP1202)	+= sdp1202.0 sdp1202_clock.o sdp1202_gpio.o sdp1202_misc.o
obj-$(CONFIG_MACH_FOXAP)	+= foxap/

obj-$(CONFIG_ARCH_SDP1202FPGA)	+= sdp1202fpga.o sdp1202fpga_clock.o
obj-$(CONFIG_MACH_FPGA_FOXAP)	+= fpga_foxap/

# Multi Core Support
obj-$(CONFIG_SMP)		+= platsmp.o headsmp.o hotplug.o
obj-$(CONFIG_LOCAL_TIMERS)	+= localtimer.o

# Patch Errata
obj-$(CONFIG_SDP_ARM_A8_ERRATA_586324)	+= v7a8_cache.o

