/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_ag_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_phdc_ag_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_phdc_ag_action_fns[] =
{
    CsrBtPhdcAgFsm_PhdcConfigureEndpointReq,
    CsrBtPhdcAgFsm_HdpRegisterInd,
    CsrBtPhdcAgFsm_PhdcConfigureEndpointRes,
    CsrBtPhdcAgFsm_HdpRegisterCfm,
    CsrBtPhdcAgFsm_RegisteringPhdcUnregisterReq,
    CsrBtPhdcAgFsm_HdpUnregisterCfm,
    CsrBtPhdcAgFsm_HdpActivateCfm,
    CsrBtPhdcAgFsm_HdpDeactivateCfm,
    CsrBtPhdcAgFsm_PhdcConfigureMdsReq,
    CsrBtPhdcAgFsm_PhdcDimConfigureReq,
    CsrBtPhdcAgFsm_PhdcDimObjectRes,
    CsrBtPhdcAgFsm_PhdcDimAttribRes,
    CsrBtPhdcAgFsm_PhdcGetDeviceCapabReq,
    CsrBtPhdcAgFsm_HdpGetCapabInd,
    CsrBtPhdcAgFsm_HdpGetCapabCfm,
    CsrBtPhdcAgFsm_ActivatedPhdcUnregisterReq,
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_PHDC_AG, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_phdc_ag_transitions[] = {
  /* IDLE */
  { PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_REQ,   CSR_BT_PHDC_AG_AC_PhdcConfigureEndpointReq,      CSR_BT_PHDC_AG_ST_REGISTERING },
  /* REGISTERING */
  { PHDC_AG_EV_HDP_REGISTER_IND,              CSR_BT_PHDC_AG_AC_HdpRegisterInd,                CSR_BT_PHDC_AG_ST_REGISTERING },
  { PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_RES,   CSR_BT_PHDC_AG_AC_PhdcConfigureEndpointRes,      CSR_BT_PHDC_AG_ST_REGISTERING },
  { PHDC_AG_EV_HDP_REGISTER_CFM,              CSR_BT_PHDC_AG_AC_HdpRegisterCfm,                CSR_BT_PHDC_AG_ST_ACTIVATING },
  { PHDC_AG_EV_PHDC_UNREGISTER_REQ,           CSR_BT_PHDC_AG_AC_RegisteringPhdcUnregisterReq,  CSR_BT_PHDC_AG_ST_UNREGISTERING },
  /* UNREGISTERING */
  { PHDC_AG_EV_HDP_UNREGISTER_CFM,            CSR_BT_PHDC_AG_AC_HdpUnregisterCfm,              CSR_BT_PHDC_AG_ST_IDLE },
  /* ACTIVATING */
  { PHDC_AG_EV_HDP_ACTIVATE_CFM,              CSR_BT_PHDC_AG_AC_HdpActivateCfm,                CSR_BT_PHDC_AG_ST_ACTIVATED },
  /* DEACTIVATING */
  { PHDC_AG_EV_HDP_DEACTIVATE_CFM,            CSR_BT_PHDC_AG_AC_HdpDeactivateCfm,              CSR_BT_PHDC_AG_ST_UNREGISTERING },
  /* ACTIVATED */
  { PHDC_AG_EV_PHDC_UNREGISTER_REQ,           CSR_BT_PHDC_AG_AC_ActivatedPhdcUnregisterReq,    CSR_BT_PHDC_AG_ST_DEACTIVATING },
  { PHDC_AG_EV_PHDC_CONFIGURE_MDS_REQ,        CSR_BT_PHDC_AG_AC_PhdcConfigureMdsReq,           CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_PHDC_DIM_CONFIGURE_REQ,        CSR_BT_PHDC_AG_AC_PhdcDimConfigureReq,           CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_PHDC_DIM_OBJECT_RES,           CSR_BT_PHDC_AG_AC_PhdcDimObjectRes,              CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_PHDC_DIM_ATTRIB_RES,           CSR_BT_PHDC_AG_AC_PhdcDimAttribRes,              CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_PHDC_GET_DEVICE_CAPAB_REQ,     CSR_BT_PHDC_AG_AC_PhdcGetDeviceCapabReq,         CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_HDP_GET_CAPAB_IND,             CSR_BT_PHDC_AG_AC_HdpGetCapabInd,                CSR_BT_PHDC_AG_ST_ACTIVATED },
  { PHDC_AG_EV_HDP_GET_CAPAB_CFM,             CSR_BT_PHDC_AG_AC_HdpGetCapabCfm,                CSR_BT_PHDC_AG_ST_ACTIVATED }
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_phdc_ag_states[CSR_BT_PHDC_AG_ST_ST_MAX+1] = {
    { &csr_bt_phdc_ag_transitions[0] },
    { &csr_bt_phdc_ag_transitions[1] },
    { &csr_bt_phdc_ag_transitions[5] },
    { &csr_bt_phdc_ag_transitions[6] },
    { &csr_bt_phdc_ag_transitions[7] },
    { &csr_bt_phdc_ag_transitions[8] },
    { &csr_bt_phdc_ag_transitions[16] },
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, FSM_LOGGING) */
/* State names */
const char *const csr_bt_phdc_ag_state_names[] =
{
    "CSR_BT_PHDC_AG_ST_IDLE",
    "CSR_BT_PHDC_AG_ST_REGISTERING",
    "CSR_BT_PHDC_AG_ST_UNREGISTERING",
    "CSR_BT_PHDC_AG_ST_ACTIVATING",
    "CSR_BT_PHDC_AG_ST_DEACTIVATING",
    "CSR_BT_PHDC_AG_ST_ACTIVATED",
};
#define CSR_BT_PHDC_AG_STATE_NAMES_PTR (csr_bt_phdc_ag_state_names)

/* Event names */
const char *const csr_bt_phdc_ag_event_names[] =
{
    "PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_REQ",
    "PHDC_AG_EV_HDP_REGISTER_IND",
    "PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_RES",
    "PHDC_AG_EV_HDP_REGISTER_CFM",
    "PHDC_AG_EV_PHDC_UNREGISTER_REQ",
    "PHDC_AG_EV_HDP_UNREGISTER_CFM",
    "PHDC_AG_EV_HDP_ACTIVATE_CFM",
    "PHDC_AG_EV_HDP_DEACTIVATE_CFM",
    "PHDC_AG_EV_PHDC_CONFIGURE_MDS_REQ",
    "PHDC_AG_EV_PHDC_DIM_CONFIGURE_REQ",
    "PHDC_AG_EV_PHDC_DIM_OBJECT_RES",
    "PHDC_AG_EV_PHDC_DIM_ATTRIB_RES",
    "PHDC_AG_EV_PHDC_GET_DEVICE_CAPAB_REQ",
    "PHDC_AG_EV_HDP_GET_CAPAB_IND",
    "PHDC_AG_EV_HDP_GET_CAPAB_CFM",
};
#define CSR_BT_PHDC_AG_EVENT_NAMES_PTR (csr_bt_phdc_ag_event_names)

/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, FSM_LOGGING) */
#else
#define CSR_BT_PHDC_AG_STATE_NAMES_PTR (NULL)
#define CSR_BT_PHDC_AG_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_ag_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_phdc_ag_states,
    csr_bt_phdc_ag_action_fns
    FSM_LOG_INFO("CSR_BT_PHDC_AG",
    CSR_BT_PHDC_AG_STATE_NAMES_PTR,
    CSR_BT_PHDC_AG_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, FSM_DEFINITION) */

