#ifndef _CSR_BT_PHDC_AG_GENFSM_H
#define _CSR_BT_PHDC_AG_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_ag_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcConfigureEndpointReq);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpRegisterInd);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcConfigureEndpointRes);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpRegisterCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_RegisteringPhdcUnregisterReq);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpUnregisterCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpActivateCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpDeactivateCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcConfigureMdsReq);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcDimConfigureReq);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcDimObjectRes);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcDimAttribRes);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_PhdcGetDeviceCapabReq);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpGetCapabInd);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_HdpGetCapabCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgFsm_ActivatedPhdcUnregisterReq);
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, STATE_DECLARATIONS) */
#define CSR_BT_PHDC_AG_ST_ST_MAX 6
#define CSR_BT_PHDC_AG_ST_IDLE          ((fsm_state_t) 0)
#define CSR_BT_PHDC_AG_ST_REGISTERING   ((fsm_state_t) 1)
#define CSR_BT_PHDC_AG_ST_UNREGISTERING ((fsm_state_t) 2)
#define CSR_BT_PHDC_AG_ST_ACTIVATING    ((fsm_state_t) 3)
#define CSR_BT_PHDC_AG_ST_DEACTIVATING  ((fsm_state_t) 4)
#define CSR_BT_PHDC_AG_ST_ACTIVATED     ((fsm_state_t) 5)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, EVENT_DECLARATIONS) */
#define PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_REQ ((fsm_event_t) 0)
#define PHDC_AG_EV_HDP_REGISTER_IND            ((fsm_event_t) 1)
#define PHDC_AG_EV_PHDC_CONFIGURE_ENDPOINT_RES ((fsm_event_t) 2)
#define PHDC_AG_EV_HDP_REGISTER_CFM            ((fsm_event_t) 3)
#define PHDC_AG_EV_PHDC_UNREGISTER_REQ         ((fsm_event_t) 4)
#define PHDC_AG_EV_HDP_UNREGISTER_CFM          ((fsm_event_t) 5)
#define PHDC_AG_EV_HDP_ACTIVATE_CFM            ((fsm_event_t) 6)
#define PHDC_AG_EV_HDP_DEACTIVATE_CFM          ((fsm_event_t) 7)
#define PHDC_AG_EV_PHDC_CONFIGURE_MDS_REQ      ((fsm_event_t) 8)
#define PHDC_AG_EV_PHDC_DIM_CONFIGURE_REQ      ((fsm_event_t) 9)
#define PHDC_AG_EV_PHDC_DIM_OBJECT_RES         ((fsm_event_t) 10)
#define PHDC_AG_EV_PHDC_DIM_ATTRIB_RES         ((fsm_event_t) 11)
#define PHDC_AG_EV_PHDC_GET_DEVICE_CAPAB_REQ   ((fsm_event_t) 12)
#define PHDC_AG_EV_HDP_GET_CAPAB_IND           ((fsm_event_t) 13)
#define PHDC_AG_EV_HDP_GET_CAPAB_CFM           ((fsm_event_t) 14)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, ACTION_FN_INDEX) */
#define CSR_BT_PHDC_AG_AC_MAX 16
#define CSR_BT_PHDC_AG_AC_PhdcConfigureEndpointReq     ((fsm_action_t) 0)
#define CSR_BT_PHDC_AG_AC_HdpRegisterInd               ((fsm_action_t) 1)
#define CSR_BT_PHDC_AG_AC_PhdcConfigureEndpointRes     ((fsm_action_t) 2)
#define CSR_BT_PHDC_AG_AC_HdpRegisterCfm               ((fsm_action_t) 3)
#define CSR_BT_PHDC_AG_AC_RegisteringPhdcUnregisterReq ((fsm_action_t) 4)
#define CSR_BT_PHDC_AG_AC_HdpUnregisterCfm             ((fsm_action_t) 5)
#define CSR_BT_PHDC_AG_AC_HdpActivateCfm               ((fsm_action_t) 6)
#define CSR_BT_PHDC_AG_AC_HdpDeactivateCfm             ((fsm_action_t) 7)
#define CSR_BT_PHDC_AG_AC_PhdcConfigureMdsReq          ((fsm_action_t) 8)
#define CSR_BT_PHDC_AG_AC_PhdcDimConfigureReq          ((fsm_action_t) 9)
#define CSR_BT_PHDC_AG_AC_PhdcDimObjectRes             ((fsm_action_t) 10)
#define CSR_BT_PHDC_AG_AC_PhdcDimAttribRes             ((fsm_action_t) 11)
#define CSR_BT_PHDC_AG_AC_PhdcGetDeviceCapabReq        ((fsm_action_t) 12)
#define CSR_BT_PHDC_AG_AC_HdpGetCapabInd               ((fsm_action_t) 13)
#define CSR_BT_PHDC_AG_AC_HdpGetCapabCfm               ((fsm_action_t) 14)
#define CSR_BT_PHDC_AG_AC_ActivatedPhdcUnregisterReq   ((fsm_action_t) 15)
#define CSR_BT_PHDC_AG_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_ag_fsm;
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_PHDC_AG_GENFSM_H */

