#ifndef _CSR_BT_PHDC_AG_DEVICE_GENFSM_H
#define _CSR_BT_PHDC_AG_DEVICE_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_ag_device_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisconnectedHdpAcceptConnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisconnectedPhdcAcceptBtLinkRes);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisconnectedHdpConnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisconnectedPhdcAssociateReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_ConnectingHdpConnectAssociateChannelCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisconnectingHdpDisconnectAssociateChannelCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OtherHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OtherHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_UnassociatedHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_UnassociatedPhdcAssociateReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_UnassociatedTimerBtLinkRelExpiry);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_UnassociatedHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_AssociatingHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_AssociatingTimerToAssocExpiry);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_AssociatingHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SendingConfigHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SendingConfigHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SendingConfigPhdcAssociateReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_TimerToConfigExpiry);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_WaitingApprovalHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingPhdcDataReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingPhdcSuspendReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperationPhdcDisassociateReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingPhdcChangeUnitCodeReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingTimerToMdsExpiry);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OperatingHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SuspendHdpSuspendCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SuspendPhdcResumeReq);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SuspendHdpResumeInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_SuspendHdpResumeCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisassociatingHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisassociatingToReleaseExpiry);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_DisassociatingHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_OtherHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcAgDeviceFsm_AbortCfmHdpDataCfm);
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_DECLARATIONS) */
#define CSR_BT_PHDC_AG_DEVICE_ST_ST_MAX 11
#define CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED     ((fsm_state_t) 0)
#define CSR_BT_PHDC_AG_DEVICE_ST_CONNECTING       ((fsm_state_t) 1)
#define CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTING    ((fsm_state_t) 2)
#define CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED     ((fsm_state_t) 3)
#define CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING      ((fsm_state_t) 4)
#define CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG   ((fsm_state_t) 5)
#define CSR_BT_PHDC_AG_DEVICE_ST_WAITING_APPROVAL ((fsm_state_t) 6)
#define CSR_BT_PHDC_AG_DEVICE_ST_OPERATING        ((fsm_state_t) 7)
#define CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED        ((fsm_state_t) 8)
#define CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING   ((fsm_state_t) 9)
#define CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM        ((fsm_state_t) 10)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, EVENT_DECLARATIONS) */
#define PHDC_AG_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND ((fsm_event_t) 0)
#define PHDC_AG_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES                  ((fsm_event_t) 1)
#define PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND        ((fsm_event_t) 2)
#define PHDC_AG_DEVICE_EV_PHDC_ASSOCIATE_REQ                       ((fsm_event_t) 3)
#define PHDC_AG_DEVICE_EV_TIMER_BT_LINK_REL_EXPIRY                 ((fsm_event_t) 4)
#define PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM        ((fsm_event_t) 5)
#define PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM     ((fsm_event_t) 6)
#define PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND     ((fsm_event_t) 7)
#define PHDC_AG_DEVICE_EV_HDP_DATA_IND                             ((fsm_event_t) 8)
#define PHDC_AG_DEVICE_EV_HDP_DATA_CFM                             ((fsm_event_t) 9)
#define PHDC_AG_DEVICE_EV_INT_ABORT_REQ                            ((fsm_event_t) 10)
#define PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT                        ((fsm_event_t) 11)
#define PHDC_AG_DEVICE_EV_INT_CONFIG_ACCEPTED                      ((fsm_event_t) 12)
#define PHDC_AG_DEVICE_EV_INT_CONFIG_UNKNOWN                       ((fsm_event_t) 13)
#define PHDC_AG_DEVICE_EV_INT_CONFIG_REJECTED                      ((fsm_event_t) 14)
#define PHDC_AG_DEVICE_EV_TIMER_TO_ASSOC_EXPIRY                    ((fsm_event_t) 15)
#define PHDC_AG_DEVICE_EV_INT_DATA_IND_CONFIG_SENT                 ((fsm_event_t) 16)
#define PHDC_AG_DEVICE_EV_TIMER_TO_CONFIG_EXPIRY                   ((fsm_event_t) 17)
#define PHDC_AG_DEVICE_EV_INT_RELEASE_REQ                          ((fsm_event_t) 18)
#define PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRQ                        ((fsm_event_t) 19)
#define PHDC_AG_DEVICE_EV_PHDC_DATA_REQ                            ((fsm_event_t) 20)
#define PHDC_AG_DEVICE_EV_PHDC_SUSPEND_REQ                         ((fsm_event_t) 21)
#define PHDC_AG_DEVICE_EV_PHDC_DISASSOCIATE_REQ                    ((fsm_event_t) 22)
#define PHDC_AG_DEVICE_EV_PHDC_CHANGE_UNIT_CODE_REQ                ((fsm_event_t) 23)
#define PHDC_AG_DEVICE_EV_TIMER_TO_CER_MDS_EXPIRY                  ((fsm_event_t) 24)
#define PHDC_AG_DEVICE_EV_HDP_SUSPEND_CFM                          ((fsm_event_t) 25)
#define PHDC_AG_DEVICE_EV_PHDC_RESUME_REQ                          ((fsm_event_t) 26)
#define PHDC_AG_DEVICE_EV_HDP_RESUME_IND                           ((fsm_event_t) 27)
#define PHDC_AG_DEVICE_EV_HDP_RESUME_CFM                           ((fsm_event_t) 28)
#define PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRE                        ((fsm_event_t) 29)
#define PHDC_AG_DEVICE_EV_TIMER_TO_RELEASE_EXPIRY                  ((fsm_event_t) 30)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_INDEX) */
#define PHDC_AG_DEVICE_AC_MAX 36
#define PHDC_AG_DEVICE_AC_DisconnectedHdpAcceptConnectAssociateChannelInd ((fsm_action_t) 0)
#define PHDC_AG_DEVICE_AC_DisconnectedPhdcAcceptBtLinkRes                 ((fsm_action_t) 1)
#define PHDC_AG_DEVICE_AC_DisconnectedHdpConnectAssociateChannelInd       ((fsm_action_t) 2)
#define PHDC_AG_DEVICE_AC_DisconnectedPhdcAssociateReq                    ((fsm_action_t) 3)
#define PHDC_AG_DEVICE_AC_ConnectingHdpConnectAssociateChannelCfm         ((fsm_action_t) 4)
#define PHDC_AG_DEVICE_AC_DisconnectingHdpDisconnectAssociateChannelCfm   ((fsm_action_t) 5)
#define PHDC_AG_DEVICE_AC_OtherHdpDataInd                                 ((fsm_action_t) 6)
#define PHDC_AG_DEVICE_AC_OtherHdpDataCfm                                 ((fsm_action_t) 7)
#define PHDC_AG_DEVICE_AC_UnassociatedHdpDataInd                          ((fsm_action_t) 8)
#define PHDC_AG_DEVICE_AC_UnassociatedPhdcAssociateReq                    ((fsm_action_t) 9)
#define PHDC_AG_DEVICE_AC_UnassociatedTimerBtLinkRelExpiry                ((fsm_action_t) 10)
#define PHDC_AG_DEVICE_AC_UnassociatedHdpDisconnectAssociateChannelInd    ((fsm_action_t) 11)
#define PHDC_AG_DEVICE_AC_AssociatingHdpDataInd                           ((fsm_action_t) 12)
#define PHDC_AG_DEVICE_AC_AssociatingTimerToAssocExpiry                   ((fsm_action_t) 13)
#define PHDC_AG_DEVICE_AC_AssociatingHdpDisconnectAssociateChannelInd     ((fsm_action_t) 14)
#define PHDC_AG_DEVICE_AC_SendingConfigHdpDataCfm                         ((fsm_action_t) 15)
#define PHDC_AG_DEVICE_AC_SendingConfigHdpDataInd                         ((fsm_action_t) 16)
#define PHDC_AG_DEVICE_AC_SendingConfigPhdcAssociateReq                   ((fsm_action_t) 17)
#define PHDC_AG_DEVICE_AC_TimerToConfigExpiry                             ((fsm_action_t) 18)
#define PHDC_AG_DEVICE_AC_WaitingApprovalHdpDataInd                       ((fsm_action_t) 19)
#define PHDC_AG_DEVICE_AC_OperatingPhdcDataReq                            ((fsm_action_t) 20)
#define PHDC_AG_DEVICE_AC_OperatingHdpDataInd                             ((fsm_action_t) 21)
#define PHDC_AG_DEVICE_AC_OperatingPhdcSuspendReq                         ((fsm_action_t) 22)
#define PHDC_AG_DEVICE_AC_OperationPhdcDisassociateReq                    ((fsm_action_t) 23)
#define PHDC_AG_DEVICE_AC_OperatingPhdcChangeUnitCodeReq                  ((fsm_action_t) 24)
#define PHDC_AG_DEVICE_AC_OperatingTimerToMdsExpiry                       ((fsm_action_t) 25)
#define PHDC_AG_DEVICE_AC_OperatingHdpDisconnectAssociateChannelInd       ((fsm_action_t) 26)
#define PHDC_AG_DEVICE_AC_SuspendHdpSuspendCfm                            ((fsm_action_t) 27)
#define PHDC_AG_DEVICE_AC_SuspendPhdcResumeReq                            ((fsm_action_t) 28)
#define PHDC_AG_DEVICE_AC_SuspendHdpResumeInd                             ((fsm_action_t) 29)
#define PHDC_AG_DEVICE_AC_SuspendHdpResumeCfm                             ((fsm_action_t) 30)
#define PHDC_AG_DEVICE_AC_DisassociatingHdpDataInd                        ((fsm_action_t) 31)
#define PHDC_AG_DEVICE_AC_DisassociatingToReleaseExpiry                   ((fsm_action_t) 32)
#define PHDC_AG_DEVICE_AC_DisassociatingHdpDataCfm                        ((fsm_action_t) 33)
#define PHDC_AG_DEVICE_AC_OtherHdpDisconnectAssociateChannelInd           ((fsm_action_t) 34)
#define PHDC_AG_DEVICE_AC_AbortCfmHdpDataCfm                              ((fsm_action_t) 35)
#define PHDC_AG_DEVICE_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_ag_device_fsm;
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_PHDC_AG_DEVICE_GENFSM_H */

