/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_ag_device_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_phdc_ag_device_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_phdc_ag_device_action_fns[] =
{
    CsrBtPhdcAgDeviceFsm_DisconnectedHdpAcceptConnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_DisconnectedPhdcAcceptBtLinkRes,
    CsrBtPhdcAgDeviceFsm_DisconnectedHdpConnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_DisconnectedPhdcAssociateReq,
    CsrBtPhdcAgDeviceFsm_ConnectingHdpConnectAssociateChannelCfm,
    CsrBtPhdcAgDeviceFsm_DisconnectingHdpDisconnectAssociateChannelCfm,
    CsrBtPhdcAgDeviceFsm_OtherHdpDataInd,
    CsrBtPhdcAgDeviceFsm_OtherHdpDataCfm,
    CsrBtPhdcAgDeviceFsm_UnassociatedHdpDataInd,
    CsrBtPhdcAgDeviceFsm_UnassociatedPhdcAssociateReq,
    CsrBtPhdcAgDeviceFsm_UnassociatedTimerBtLinkRelExpiry,
    CsrBtPhdcAgDeviceFsm_UnassociatedHdpDisconnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_AssociatingHdpDataInd,
    CsrBtPhdcAgDeviceFsm_AssociatingTimerToAssocExpiry,
    CsrBtPhdcAgDeviceFsm_AssociatingHdpDisconnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_SendingConfigHdpDataCfm,
    CsrBtPhdcAgDeviceFsm_SendingConfigHdpDataInd,
    CsrBtPhdcAgDeviceFsm_SendingConfigPhdcAssociateReq,
    CsrBtPhdcAgDeviceFsm_TimerToConfigExpiry,
    CsrBtPhdcAgDeviceFsm_WaitingApprovalHdpDataInd,
    CsrBtPhdcAgDeviceFsm_OperatingPhdcDataReq,
    CsrBtPhdcAgDeviceFsm_OperatingHdpDataInd,
    CsrBtPhdcAgDeviceFsm_OperatingPhdcSuspendReq,
    CsrBtPhdcAgDeviceFsm_OperationPhdcDisassociateReq,
    CsrBtPhdcAgDeviceFsm_OperatingPhdcChangeUnitCodeReq,
    CsrBtPhdcAgDeviceFsm_OperatingTimerToMdsExpiry,
    CsrBtPhdcAgDeviceFsm_OperatingHdpDisconnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_SuspendHdpSuspendCfm,
    CsrBtPhdcAgDeviceFsm_SuspendPhdcResumeReq,
    CsrBtPhdcAgDeviceFsm_SuspendHdpResumeInd,
    CsrBtPhdcAgDeviceFsm_SuspendHdpResumeCfm,
    CsrBtPhdcAgDeviceFsm_DisassociatingHdpDataInd,
    CsrBtPhdcAgDeviceFsm_DisassociatingToReleaseExpiry,
    CsrBtPhdcAgDeviceFsm_DisassociatingHdpDataCfm,
    CsrBtPhdcAgDeviceFsm_OtherHdpDisconnectAssociateChannelInd,
    CsrBtPhdcAgDeviceFsm_AbortCfmHdpDataCfm,
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_phdc_ag_device_transitions[] = {
  /* DISCONNECTED */
  { PHDC_AG_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND,   PHDC_AG_DEVICE_AC_DisconnectedHdpAcceptConnectAssociateChannelInd,  CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES,                    PHDC_AG_DEVICE_AC_DisconnectedPhdcAcceptBtLinkRes,                  CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND,          PHDC_AG_DEVICE_AC_DisconnectedHdpConnectAssociateChannelInd,        CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_PHDC_ASSOCIATE_REQ,                         PHDC_AG_DEVICE_AC_DisconnectedPhdcAssociateReq,                     CSR_BT_PHDC_AG_DEVICE_ST_CONNECTING },
  { PHDC_AG_DEVICE_EV_TIMER_BT_LINK_REL_EXPIRY,                   PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  /* CONNECTING */
  { PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM,          PHDC_AG_DEVICE_AC_ConnectingHdpConnectAssociateChannelCfm,          CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  /* DISCONNECTING */
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM,       PHDC_AG_DEVICE_AC_DisconnectingHdpDisconnectAssociateChannelCfm,    CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_OtherHdpDataInd,                                  CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTING },
  /* UNASSOCIATED */
  { PHDC_AG_DEVICE_EV_PHDC_ASSOCIATE_REQ,                         PHDC_AG_DEVICE_AC_UnassociatedPhdcAssociateReq,                     CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  { PHDC_AG_DEVICE_EV_TIMER_BT_LINK_REL_EXPIRY,                   PHDC_AG_DEVICE_AC_UnassociatedTimerBtLinkRelExpiry,                 CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTING },
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_UnassociatedHdpDisconnectAssociateChannelInd,     CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_UnassociatedHdpDataInd,                           CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_OtherHdpDataCfm,                                  CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  { PHDC_AG_DEVICE_EV_INT_ABORT_REQ,                              PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  /* ASSOCIATING */
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_AssociatingHdpDisconnectAssociateChannelInd,      CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_AssociatingHdpDataInd,                            CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_OtherHdpDataCfm,                                  CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  { PHDC_AG_DEVICE_EV_INT_ABORT_REQ,                              PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_INT_CONFIG_ACCEPTED,                        PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_INT_CONFIG_UNKNOWN,                         PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG },
  { PHDC_AG_DEVICE_EV_INT_CONFIG_REJECTED,                        PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_TIMER_TO_ASSOC_EXPIRY,                      PHDC_AG_DEVICE_AC_AssociatingTimerToAssocExpiry,                    CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING },
  /* SENDING_CONFIG */
  { PHDC_AG_DEVICE_EV_PHDC_ASSOCIATE_REQ,                         PHDC_AG_DEVICE_AC_SendingConfigPhdcAssociateReq,                    CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG },
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_AssociatingHdpDisconnectAssociateChannelInd,      CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_SendingConfigHdpDataInd,                          CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_SendingConfigHdpDataCfm,                          CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_CONFIG_SENT,                   PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_WAITING_APPROVAL },
  { PHDC_AG_DEVICE_EV_TIMER_TO_CONFIG_EXPIRY,                     PHDC_AG_DEVICE_AC_TimerToConfigExpiry,                              CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  /* WAITING_APPROVAL */
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_AssociatingHdpDisconnectAssociateChannelInd,      CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_WaitingApprovalHdpDataInd,                        CSR_BT_PHDC_AG_DEVICE_ST_WAITING_APPROVAL },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_WAITING_APPROVAL },
  { PHDC_AG_DEVICE_EV_INT_ABORT_REQ,                              PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_INT_CONFIG_ACCEPTED,                        PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_INT_CONFIG_UNKNOWN,                         PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG },
  { PHDC_AG_DEVICE_EV_TIMER_TO_CONFIG_EXPIRY,                     PHDC_AG_DEVICE_AC_TimerToConfigExpiry,                              CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  { PHDC_AG_DEVICE_EV_INT_RELEASE_REQ,                            PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRQ,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  /* OPERATING */
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_OperatingHdpDisconnectAssociateChannelInd,        CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_OperatingHdpDataInd,                              CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_OtherHdpDataCfm,                                  CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_INT_ABORT_REQ,                              PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRQ,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  { PHDC_AG_DEVICE_EV_PHDC_DATA_REQ,                              PHDC_AG_DEVICE_AC_OperatingPhdcDataReq,                             CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_PHDC_SUSPEND_REQ,                           PHDC_AG_DEVICE_AC_OperatingPhdcSuspendReq,                          CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED },
  { PHDC_AG_DEVICE_EV_PHDC_DISASSOCIATE_REQ,                      PHDC_AG_DEVICE_AC_OperationPhdcDisassociateReq,                     CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  { PHDC_AG_DEVICE_EV_PHDC_CHANGE_UNIT_CODE_REQ,                  PHDC_AG_DEVICE_AC_OperatingPhdcChangeUnitCodeReq,                   CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  { PHDC_AG_DEVICE_EV_TIMER_TO_CER_MDS_EXPIRY,                    PHDC_AG_DEVICE_AC_OperatingTimerToMdsExpiry,                        CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  /* SUSPENDED */
  { PHDC_AG_DEVICE_EV_HDP_SUSPEND_CFM,                            PHDC_AG_DEVICE_AC_SuspendHdpSuspendCfm,                             CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED },
  { PHDC_AG_DEVICE_EV_PHDC_RESUME_REQ,                            PHDC_AG_DEVICE_AC_SuspendPhdcResumeReq,                             CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED },
  { PHDC_AG_DEVICE_EV_HDP_RESUME_IND,                             PHDC_AG_DEVICE_AC_SuspendHdpResumeInd,                              CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED },
  { PHDC_AG_DEVICE_EV_HDP_RESUME_CFM,                             PHDC_AG_DEVICE_AC_SuspendHdpResumeCfm,                              CSR_BT_PHDC_AG_DEVICE_ST_OPERATING },
  /* DISASSOCIATING */
  { PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_AG_DEVICE_AC_OtherHdpDisconnectAssociateChannelInd,            CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED },
  { PHDC_AG_DEVICE_EV_HDP_DATA_IND,                               PHDC_AG_DEVICE_AC_DisassociatingHdpDataInd,                         CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_DisassociatingHdpDataCfm,                         CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRE,                          PHDC_AG_DEVICE_AC_NULL,                                             CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED },
  { PHDC_AG_DEVICE_EV_TIMER_TO_RELEASE_EXPIRY,                    PHDC_AG_DEVICE_AC_DisassociatingToReleaseExpiry,                    CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM },
  /* ABORT_CFM */
  { PHDC_AG_DEVICE_EV_HDP_DATA_CFM,                               PHDC_AG_DEVICE_AC_AbortCfmHdpDataCfm,                               CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED }
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_phdc_ag_device_states[CSR_BT_PHDC_AG_DEVICE_ST_ST_MAX+1] = {
    { &csr_bt_phdc_ag_device_transitions[0] },
    { &csr_bt_phdc_ag_device_transitions[5] },
    { &csr_bt_phdc_ag_device_transitions[6] },
    { &csr_bt_phdc_ag_device_transitions[9] },
    { &csr_bt_phdc_ag_device_transitions[16] },
    { &csr_bt_phdc_ag_device_transitions[25] },
    { &csr_bt_phdc_ag_device_transitions[31] },
    { &csr_bt_phdc_ag_device_transitions[41] },
    { &csr_bt_phdc_ag_device_transitions[52] },
    { &csr_bt_phdc_ag_device_transitions[56] },
    { &csr_bt_phdc_ag_device_transitions[62] },
    { &csr_bt_phdc_ag_device_transitions[63] },
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_LOGGING) */
/* State names */
const char *const csr_bt_phdc_ag_device_state_names[] =
{
    "CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTED",
    "CSR_BT_PHDC_AG_DEVICE_ST_CONNECTING",
    "CSR_BT_PHDC_AG_DEVICE_ST_DISCONNECTING",
    "CSR_BT_PHDC_AG_DEVICE_ST_UNASSOCIATED",
    "CSR_BT_PHDC_AG_DEVICE_ST_ASSOCIATING",
    "CSR_BT_PHDC_AG_DEVICE_ST_SENDING_CONFIG",
    "CSR_BT_PHDC_AG_DEVICE_ST_WAITING_APPROVAL",
    "CSR_BT_PHDC_AG_DEVICE_ST_OPERATING",
    "CSR_BT_PHDC_AG_DEVICE_ST_SUSPENDED",
    "CSR_BT_PHDC_AG_DEVICE_ST_DISASSOCIATING",
    "CSR_BT_PHDC_AG_DEVICE_ST_ABORT_CFM",
};
#define CSR_BT_PHDC_AG_DEVICE_STATE_NAMES_PTR (csr_bt_phdc_ag_device_state_names)

/* Event names */
const char *const csr_bt_phdc_ag_device_event_names[] =
{
    "PHDC_AG_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_AG_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES",
    "PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_AG_DEVICE_EV_PHDC_ASSOCIATE_REQ",
    "PHDC_AG_DEVICE_EV_TIMER_BT_LINK_REL_EXPIRY",
    "PHDC_AG_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM",
    "PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM",
    "PHDC_AG_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_AG_DEVICE_EV_HDP_DATA_IND",
    "PHDC_AG_DEVICE_EV_HDP_DATA_CFM",
    "PHDC_AG_DEVICE_EV_INT_ABORT_REQ",
    "PHDC_AG_DEVICE_EV_INT_DATA_IND_ABRT",
    "PHDC_AG_DEVICE_EV_INT_CONFIG_ACCEPTED",
    "PHDC_AG_DEVICE_EV_INT_CONFIG_UNKNOWN",
    "PHDC_AG_DEVICE_EV_INT_CONFIG_REJECTED",
    "PHDC_AG_DEVICE_EV_TIMER_TO_ASSOC_EXPIRY",
    "PHDC_AG_DEVICE_EV_INT_DATA_IND_CONFIG_SENT",
    "PHDC_AG_DEVICE_EV_TIMER_TO_CONFIG_EXPIRY",
    "PHDC_AG_DEVICE_EV_INT_RELEASE_REQ",
    "PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRQ",
    "PHDC_AG_DEVICE_EV_PHDC_DATA_REQ",
    "PHDC_AG_DEVICE_EV_PHDC_SUSPEND_REQ",
    "PHDC_AG_DEVICE_EV_PHDC_DISASSOCIATE_REQ",
    "PHDC_AG_DEVICE_EV_PHDC_CHANGE_UNIT_CODE_REQ",
    "PHDC_AG_DEVICE_EV_TIMER_TO_CER_MDS_EXPIRY",
    "PHDC_AG_DEVICE_EV_HDP_SUSPEND_CFM",
    "PHDC_AG_DEVICE_EV_PHDC_RESUME_REQ",
    "PHDC_AG_DEVICE_EV_HDP_RESUME_IND",
    "PHDC_AG_DEVICE_EV_HDP_RESUME_CFM",
    "PHDC_AG_DEVICE_EV_INT_DATA_IND_RLRE",
    "PHDC_AG_DEVICE_EV_TIMER_TO_RELEASE_EXPIRY",
};
#define CSR_BT_PHDC_AG_DEVICE_EVENT_NAMES_PTR (csr_bt_phdc_ag_device_event_names)

/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_LOGGING) */
#else
#define CSR_BT_PHDC_AG_DEVICE_STATE_NAMES_PTR (NULL)
#define CSR_BT_PHDC_AG_DEVICE_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_ag_device_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_phdc_ag_device_states,
    csr_bt_phdc_ag_device_action_fns
    FSM_LOG_INFO("CSR_BT_PHDC_AG_DEVICE",
    CSR_BT_PHDC_AG_DEVICE_STATE_NAMES_PTR,
    CSR_BT_PHDC_AG_DEVICE_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_AG_DEVICE, FSM_DEFINITION) */

