#ifndef _DM_ACL_CONNECTION_FSM_DEFINITIONS_H
#define _DM_ACL_CONNECTION_FSM_DEFINITIONS_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   dm_acl_connection_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(acl_af_check_write_auth_enable);
extern FSM_ACTION_FN(acl_af_connect_complete);
extern FSM_ACTION_FN(acl_af_send_hci_connect_accept);
extern FSM_ACTION_FN(acl_af_send_hci_connect_req);
extern FSM_ACTION_FN(acl_af_send_hci_connect_cancel);
extern FSM_ACTION_FN(acl_af_send_hci_disconnect_req);
extern FSM_ACTION_FN(acl_af_link_loss);
extern FSM_ACTION_FN(acl_af_disconnect);
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, STATE_DECLARATIONS) */
#define ACL_ST_ST_MAX 6
#define ACL_ST_PENDING       ((fsm_state_t) 0)
#define ACL_ST_AUTH_CHECK    ((fsm_state_t) 1)
#define ACL_ST_CONNECTING    ((fsm_state_t) 2)
#define ACL_ST_CONNECTED     ((fsm_state_t) 3)
#define ACL_ST_DISCONNECTING ((fsm_state_t) 4)
#define ACL_ST_IDLE          ((fsm_state_t) 5)
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, EVENT_DECLARATIONS) */
#define ACL_EV_START               ((fsm_event_t) 0)
#define ACL_EV_CANCEL_REQ          ((fsm_event_t) 1)
#define ACL_EV_HCI_CONNECT_IND     ((fsm_event_t) 2)
#define ACL_EV_HCI_CONNECT_OK      ((fsm_event_t) 3)
#define ACL_EV_AUTH_OK             ((fsm_event_t) 4)
#define ACL_EV_HCI_CONNECT_FAIL    ((fsm_event_t) 5)
#define ACL_EV_HCI_CONNECT_RETRY   ((fsm_event_t) 6)
#define ACL_EV_DISCONNECT_REQ      ((fsm_event_t) 7)
#define ACL_EV_HCI_DISCONNECT_OK   ((fsm_event_t) 8)
#define ACL_EV_HCI_DISCONNECT_FAIL ((fsm_event_t) 9)
#define ACL_EV_CONNECT_REQ         ((fsm_event_t) 10)
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, ACTION_FN_INDEX) */
#define ACL_AC_MAX 8
#define ACL_AC_check_write_auth_enable ((fsm_action_t) 0)
#define ACL_AC_connect_complete        ((fsm_action_t) 1)
#define ACL_AC_send_hci_connect_accept ((fsm_action_t) 2)
#define ACL_AC_send_hci_connect_req    ((fsm_action_t) 3)
#define ACL_AC_send_hci_connect_cancel ((fsm_action_t) 4)
#define ACL_AC_send_hci_disconnect_req ((fsm_action_t) 5)
#define ACL_AC_link_loss               ((fsm_action_t) 6)
#define ACL_AC_disconnect              ((fsm_action_t) 7)
#define ACL_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T dm_acl_connection_fsm;
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _DM_ACL_CONNECTION_FSM_DEFINITIONS_H */

