/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   dm_acl_connection_fsm_constants.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "dm_acl_connection_fsm_constants.h"

/* Action function table */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, ACTION_FN_TABLE) */
static const fsm_action_fn_t dm_acl_connection_action_fns[] =
{
    acl_af_check_write_auth_enable,
    acl_af_connect_complete,
    acl_af_send_hci_connect_accept,
    acl_af_send_hci_connect_req,
    acl_af_send_hci_connect_cancel,
    acl_af_send_hci_disconnect_req,
    acl_af_link_loss,
    acl_af_disconnect,
};
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(DM_ACL_CONNECTION, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T dm_acl_connection_transitions[] = {
  /* PENDING */
  { ACL_EV_START,                 ACL_AC_check_write_auth_enable,  ACL_ST_AUTH_CHECK },
  { ACL_EV_CANCEL_REQ,            ACL_AC_connect_complete,         ACL_ST_IDLE },
  { ACL_EV_HCI_CONNECT_IND,       ACL_AC_send_hci_connect_accept,  ACL_ST_CONNECTING },
  { ACL_EV_HCI_CONNECT_OK,        ACL_AC_connect_complete,         ACL_ST_CONNECTED },
  /* AUTH_CHECK */
  { ACL_EV_CANCEL_REQ,            ACL_AC_connect_complete,         ACL_ST_IDLE },
  { ACL_EV_HCI_CONNECT_IND,       ACL_AC_send_hci_connect_accept,  ACL_ST_CONNECTING },
  { ACL_EV_HCI_CONNECT_OK,        ACL_AC_connect_complete,         ACL_ST_CONNECTED },
  { ACL_EV_AUTH_OK,               ACL_AC_send_hci_connect_req,     ACL_ST_CONNECTING },
  /* CONNECTING */
  { ACL_EV_CANCEL_REQ,            ACL_AC_send_hci_connect_cancel,  ACL_ST_DISCONNECTING },
  { ACL_EV_HCI_CONNECT_IND,       ACL_AC_send_hci_connect_accept,  ACL_ST_CONNECTING },
  { ACL_EV_HCI_CONNECT_OK,        ACL_AC_connect_complete,         ACL_ST_CONNECTED },
  { ACL_EV_HCI_CONNECT_FAIL,      ACL_AC_connect_complete,         ACL_ST_IDLE },
  { ACL_EV_HCI_CONNECT_RETRY,     ACL_AC_send_hci_connect_req,     ACL_ST_CONNECTING },
  /* CONNECTED */
  { ACL_EV_DISCONNECT_REQ,        ACL_AC_send_hci_disconnect_req,  ACL_ST_DISCONNECTING },
  { ACL_EV_HCI_DISCONNECT_OK,     ACL_AC_link_loss,                ACL_ST_IDLE },
  /* DISCONNECTING */
  { ACL_EV_HCI_CONNECT_IND,       ACL_AC_send_hci_connect_accept,  ACL_ST_CONNECTING },
  { ACL_EV_HCI_CONNECT_OK,        ACL_AC_connect_complete,         ACL_ST_CONNECTED },
  { ACL_EV_HCI_CONNECT_FAIL,      ACL_AC_connect_complete,         ACL_ST_IDLE },
  { ACL_EV_HCI_CONNECT_RETRY,     ACL_AC_connect_complete,         ACL_ST_IDLE },
  { ACL_EV_HCI_DISCONNECT_OK,     ACL_AC_disconnect,               ACL_ST_IDLE },
  { ACL_EV_HCI_DISCONNECT_FAIL,   ACL_AC_connect_complete,         ACL_ST_CONNECTED },
  /* IDLE */
  { ACL_EV_CONNECT_REQ,           ACL_AC_NULL,                     ACL_ST_PENDING }
};
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T dm_acl_connection_states[ACL_ST_ST_MAX+1] = {
    { &dm_acl_connection_transitions[0] },
    { &dm_acl_connection_transitions[4] },
    { &dm_acl_connection_transitions[8] },
    { &dm_acl_connection_transitions[13] },
    { &dm_acl_connection_transitions[15] },
    { &dm_acl_connection_transitions[21] },
    { &dm_acl_connection_transitions[22] },
};
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(DM_ACL_CONNECTION, FSM_LOGGING) */
/* State names */
const char *const dm_acl_connection_state_names[] =
{
    "ACL_ST_PENDING",
    "ACL_ST_AUTH_CHECK",
    "ACL_ST_CONNECTING",
    "ACL_ST_CONNECTED",
    "ACL_ST_DISCONNECTING",
    "ACL_ST_IDLE",
};
#define DM_ACL_CONNECTION_STATE_NAMES_PTR (dm_acl_connection_state_names)

/* Event names */
const char *const dm_acl_connection_event_names[] =
{
    "ACL_EV_START",
    "ACL_EV_CANCEL_REQ",
    "ACL_EV_HCI_CONNECT_IND",
    "ACL_EV_HCI_CONNECT_OK",
    "ACL_EV_AUTH_OK",
    "ACL_EV_HCI_CONNECT_FAIL",
    "ACL_EV_HCI_CONNECT_RETRY",
    "ACL_EV_DISCONNECT_REQ",
    "ACL_EV_HCI_DISCONNECT_OK",
    "ACL_EV_HCI_DISCONNECT_FAIL",
    "ACL_EV_CONNECT_REQ",
};
#define DM_ACL_CONNECTION_EVENT_NAMES_PTR (dm_acl_connection_event_names)

/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, FSM_LOGGING) */
#else
#define DM_ACL_CONNECTION_STATE_NAMES_PTR (NULL)
#define DM_ACL_CONNECTION_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(DM_ACL_CONNECTION, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T dm_acl_connection_fsm =
{
    (const FSM_SPARSE16_STATES_T *) dm_acl_connection_states,
    dm_acl_connection_action_fns
    FSM_LOG_INFO("DM_ACL_CONNECTION",
    DM_ACL_CONNECTION_STATE_NAMES_PTR,
    DM_ACL_CONNECTION_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(DM_ACL_CONNECTION, FSM_DEFINITION) */

