/****************************************************************************
 ****************************************************************************
 ****************************************************************************
 This file is automatically generated, do not edit by hand, changes will be
 lost.

../../../builds/autogen/dm_hci_int_cc_gen.c



Generated by:     hci_cases_gen.pl

Input files:      ../../../builds/autogen/dm_hci_types.str
                  dm_hci_interface_han_cc_cs.c

****************************************************************************
 ****************************************************************************
 ****************************************************************************/

#include "csr_synergy.h"

#include "csr_util.h"
#include "csr_bt_bluestack_types.h"
#include "bluetooth.h"
#include "csr_bt_common.h"
#include "error.h"
#include "csr_bt_core_stack_fsm.h"
#include "hci_prim.h"
#include "l2cap_prim.h"
#include "dm_prim.h"
#include "csr_bt_tasks.h"
#include "csr_bt_core_stack_pmalloc.h"
#include "dm_layer_manager.h"
#include "dm_hci_interface.h"
#include "dm_mgt_interface.h"
#include "csr_mblk.h"
#include "tbdaddr.h"

#ifdef BUILD_FOR_HOST
#include "csr_bt_core_stack_pmalloc.h"
#else
void handle_cc_autogen(HCI_UPRIM_T *hci_prim, HCI_UPRIM_T *ret_prim);
#endif


/*----------------------------------------------------------------------------*
 *  NAME
 *  handle_cc_autogen
 *
 *  DESCRIPTION
 *  Autogerated function that handles all command completes that can be handled
 *  using autogenerated code.  WARNING: Do NOT change the order of the element
 *  assignments as this could make a big difference to the code size. The tails
 *  of most case statements are similar so the compiler re-uses tails a lot.
 *
 *  RETURNS/MODIFIES
 *  Creates a local DM_UPRIM_T and sets the relevants elements before sending
 *  it upstream.
 *---------------------------------------------------------------------------*/
void handle_cc_autogen(HCI_UPRIM_T *hci_prim, HCI_UPRIM_T *ret_prim)
{
    DM_UPRIM_T dm_prim;
    HCI_EV_COMMAND_COMPLETE_T *prim = &hci_prim->hci_command_complete_event;
    HCI_COMMAND_COMPLETE_ARGS_T *arg_ptr =
                           (HCI_COMMAND_COMPLETE_ARGS_T *) prim->argument_ptr;
    CsrUint8 status = prim->status;
    hci_op_code_t opcode = prim->op_code;
    CsrUint16 size;

    switch(opcode)
    {
#ifndef CSR_BT_EXCLUDE_HCI_RESET_FAILED_CONTACT_COUNT
    case HCI_RESET_FAILED_CONTACT_COUNT:
        dm_prim.dm_reset_contact_counter_cfm.type = opcode +
            (DM_HCI_RESET_FAILED_CONTACT_COUNT_CFM -
            HCI_RESET_FAILED_CONTACT_COUNT);
        size = sizeof(DM_HCI_RESET_FAILED_CONTACT_COUNT_CFM_T);
        bd_addr_copy(&dm_prim.dm_reset_contact_counter_cfm.bd_addr,
            &ret_prim->hci_reset_failed_contact_count.bd_addr);
        dm_prim.dm_reset_contact_counter_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_VOICE_SETTING
    case HCI_READ_VOICE_SETTING:
        dm_prim.dm_read_voice_setting_cfm.type = opcode +
            (DM_HCI_READ_VOICE_SETTING_CFM -
            HCI_READ_VOICE_SETTING);
        size = sizeof(DM_HCI_READ_VOICE_SETTING_CFM_T);
        dm_prim.dm_read_voice_setting_cfm.voice_setting =
            arg_ptr->read_voice_setting_args.voice_setting;
        dm_prim.dm_read_voice_setting_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_CLEAR_WHITE_LIST
    case HCI_ULP_CLEAR_WHITE_LIST:
        ((DM_HCI_ULP_CLEAR_WHITE_LIST_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_CLEAR_WHITE_LIST_CFM -
            HCI_ULP_CLEAR_WHITE_LIST);
        size = sizeof(DM_HCI_ULP_CLEAR_WHITE_LIST_CFM_T);
        ((DM_HCI_ULP_CLEAR_WHITE_LIST_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_RECEIVER_TEST
    case HCI_ULP_RECEIVER_TEST:
        ((DM_HCI_ULP_RECEIVER_TEST_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_RECEIVER_TEST_CFM -
            HCI_ULP_RECEIVER_TEST);
        size = sizeof(DM_HCI_ULP_RECEIVER_TEST_CFM_T);
        ((DM_HCI_ULP_RECEIVER_TEST_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_SCO_FLOW_CON_ENABLE
    case HCI_READ_SCO_FLOW_CON_ENABLE:
        dm_prim.dm_read_sco_flow_control_enable_cfm.type = opcode +
            (DM_HCI_READ_SCO_FLOW_CON_ENABLE_CFM -
            HCI_READ_SCO_FLOW_CON_ENABLE);
        size = sizeof(DM_HCI_READ_SCO_FLOW_CON_ENABLE_CFM_T);
        dm_prim.dm_read_sco_flow_control_enable_cfm.FlowControlEnabled =
            arg_ptr->read_sco_flow_con_enable_args.sco_flow_control_enable;
        dm_prim.dm_read_sco_flow_control_enable_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_ACTIVITY
    case HCI_READ_PAGESCAN_ACTIVITY:
        dm_prim.dm_read_pagescan_activity_cfm.type = opcode +
            (DM_HCI_READ_PAGESCAN_ACTIVITY_CFM -
            HCI_READ_PAGESCAN_ACTIVITY);
        size = sizeof(DM_HCI_READ_PAGESCAN_ACTIVITY_CFM_T);
        dm_prim.dm_read_pagescan_activity_cfm.pagescan_window =
            arg_ptr->read_pagescan_activity_args.pagescan_window;
        dm_prim.dm_read_pagescan_activity_cfm.pagescan_interval =
            arg_ptr->read_pagescan_activity_args.pagescan_interval;
        dm_prim.dm_read_pagescan_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST
    case HCI_ULP_ADD_DEVICE_TO_WHITE_LIST:
        ((DM_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST_CFM -
            HCI_ULP_ADD_DEVICE_TO_WHITE_LIST);
        size = sizeof(DM_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST_CFM_T);
        ((DM_HCI_ULP_ADD_DEVICE_TO_WHITE_LIST_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES
    case HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES:
        ((DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM -
            HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES);
        size = sizeof(DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM_T);
        CsrMemCpy(&(((DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM_T *) &dm_prim)->feature_set),
            &arg_ptr->ulp_read_local_supported_features_args.feature_set,
            sizeof(((DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM_T *) &dm_prim)->feature_set));
        ((DM_HCI_ULP_READ_LOCAL_SUPPORTED_FEATURES_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_CREATE_CONNECTION_CANCEL
    case HCI_CREATE_CONNECTION_CANCEL:
        dm_prim.dm_create_connection_cancel_cfm.type = opcode +
            (DM_HCI_CREATE_CONNECTION_CANCEL_CFM -
            HCI_CREATE_CONNECTION_CANCEL);
        size = sizeof(DM_HCI_CREATE_CONNECTION_CANCEL_CFM_T);
        bd_addr_copy(&dm_prim.dm_create_connection_cancel_cfm.bd_addr,
            &arg_ptr->create_connection_cancel_args.bd_addr);
        dm_prim.dm_create_connection_cancel_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST
    case HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST:
        ((DM_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST_CFM -
            HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST);
        size = sizeof(DM_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST_CFM_T);
        ((DM_HCI_ULP_REMOVE_DEVICE_FROM_WHITE_LIST_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_NUM_BCAST_RETXS
    case HCI_WRITE_NUM_BCAST_RETXS:
        dm_prim.dm_write_num_bcast_txs_cfm.type = opcode +
            (DM_HCI_WRITE_NUM_BCAST_RETXS_CFM -
            HCI_WRITE_NUM_BCAST_RETXS);
        size = sizeof(DM_HCI_WRITE_NUM_BCAST_RETXS_CFM_T);
        dm_prim.dm_write_num_bcast_txs_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PAGE_SCAN_TYPE
    case HCI_READ_PAGE_SCAN_TYPE:
        dm_prim.dm_read_page_scan_type_cfm.type = opcode +
            (DM_HCI_READ_PAGE_SCAN_TYPE_CFM -
            HCI_READ_PAGE_SCAN_TYPE);
        size = sizeof(DM_HCI_READ_PAGE_SCAN_TYPE_CFM_T);
        dm_prim.dm_read_page_scan_type_cfm.mode =
            arg_ptr->read_page_scan_type_args.mode;
        dm_prim.dm_read_page_scan_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_MODE
    case HCI_READ_PAGESCAN_MODE:
        dm_prim.dm_read_pagescan_mode_cfm.type = opcode +
            (DM_HCI_READ_PAGESCAN_MODE_CFM -
            HCI_READ_PAGESCAN_MODE);
        size = sizeof(DM_HCI_READ_PAGESCAN_MODE_CFM_T);
        dm_prim.dm_read_pagescan_mode_cfm.mode =
            arg_ptr->read_pagescan_mode_args.mode;
        dm_prim.dm_read_pagescan_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_SCAN_ENABLE
    case HCI_READ_SCAN_ENABLE:
        dm_prim.dm_read_scan_enable_cfm.type = opcode +
            (DM_HCI_READ_SCAN_ENABLE_CFM -
            HCI_READ_SCAN_ENABLE);
        size = sizeof(DM_HCI_READ_SCAN_ENABLE_CFM_T);
        dm_prim.dm_read_scan_enable_cfm.scan_enable =
            arg_ptr->read_scan_enable_args.scan_enable;
        dm_prim.dm_read_scan_enable_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PIN_TYPE
    case HCI_READ_PIN_TYPE:
        dm_prim.dm_read_pin_type_cfm.type = opcode +
            (DM_HCI_READ_PIN_TYPE_CFM -
            HCI_READ_PIN_TYPE);
        size = sizeof(DM_HCI_READ_PIN_TYPE_CFM_T);
        dm_prim.dm_read_pin_type_cfm.pin_type =
            arg_ptr->read_pin_type_args.pin_type;
        dm_prim.dm_read_pin_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_CLOCK
    case HCI_READ_CLOCK:
        dm_prim.dm_read_clock_cfm.type = opcode +
            (DM_HCI_READ_CLOCK_CFM -
            HCI_READ_CLOCK);
        size = sizeof(DM_HCI_READ_CLOCK_CFM_T);
        dm_prim.dm_read_clock_cfm.accuracy =
            arg_ptr->read_clock_args.accuracy;
        dm_prim.dm_read_clock_cfm.clock =
            arg_ptr->read_clock_args.clock;
        bd_addr_copy(&dm_prim.dm_read_clock_cfm.bd_addr,
            &ret_prim->hci_read_clock.bd_addr);
        dm_prim.dm_read_clock_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_RSSI
    case HCI_READ_RSSI:
        dm_prim.dm_read_rssi_cfm.type = opcode +
            (DM_HCI_READ_RSSI_CFM -
            HCI_READ_RSSI);
        size = sizeof(DM_HCI_READ_RSSI_CFM_T);
        dm_prim.dm_read_rssi_cfm.rssi =
            arg_ptr->read_rssi_args.rssi;
        tbdaddr_copy(&dm_prim.dm_read_rssi_cfm.addrt,
            &ret_prim->hci_read_rssi.addrt);
        dm_prim.dm_read_rssi_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_TEST_END
    case HCI_ULP_TEST_END:
        ((DM_HCI_ULP_TEST_END_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_TEST_END_CFM -
            HCI_ULP_TEST_END);
        size = sizeof(DM_HCI_ULP_TEST_END_CFM_T);
        ((DM_HCI_ULP_TEST_END_CFM_T *) &dm_prim)->number_of_packets =
            arg_ptr->ulp_test_end_args.number_of_packets;
        ((DM_HCI_ULP_TEST_END_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_SET_EVENT_FILTER
    case HCI_SET_EVENT_FILTER:
        dm_prim.dm_set_event_filter_cfm.type = opcode +
            (DM_HCI_SET_EVENT_FILTER_CFM -
            HCI_SET_EVENT_FILTER);
        size = sizeof(DM_HCI_SET_EVENT_FILTER_CFM_T);
        dm_prim.dm_set_event_filter_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_PARAMETERS
    case HCI_ULP_SET_ADVERTISING_PARAMETERS:
        ((DM_HCI_ULP_SET_ADVERTISING_PARAMETERS_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_ADVERTISING_PARAMETERS_CFM -
            HCI_ULP_SET_ADVERTISING_PARAMETERS);
        size = sizeof(DM_HCI_ULP_SET_ADVERTISING_PARAMETERS_CFM_T);
        ((DM_HCI_ULP_SET_ADVERTISING_PARAMETERS_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_DEFAULT_LINK_POLICY_SETTINGS
    case HCI_READ_DEFAULT_LINK_POLICY_SETTINGS:
        dm_prim.dm_read_default_link_policy_settings_cfm.type = opcode +
            (DM_HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_CFM -
            HCI_READ_DEFAULT_LINK_POLICY_SETTINGS);
        size = sizeof(DM_HCI_READ_DEFAULT_LINK_POLICY_SETTINGS_CFM_T);
        dm_prim.dm_read_default_link_policy_settings_cfm.default_lps =
            arg_ptr->read_default_lps_args.default_lps;
        dm_prim.dm_read_default_link_policy_settings_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_MAP
    case HCI_READ_AFH_CHANNEL_MAP:
        dm_prim.dm_read_afh_channel_map_cfm.type = opcode +
            (DM_HCI_READ_AFH_CHANNEL_MAP_CFM -
            HCI_READ_AFH_CHANNEL_MAP);
        size = sizeof(DM_HCI_READ_AFH_CHANNEL_MAP_CFM_T);
        CsrMemCpy(&(dm_prim.dm_read_afh_channel_map_cfm.map),
            &arg_ptr->read_afh_channel_map_args.map,
            sizeof(dm_prim.dm_read_afh_channel_map_cfm.map));
        dm_prim.dm_read_afh_channel_map_cfm.mode =
            arg_ptr->read_afh_channel_map_args.mode;
        bd_addr_copy(&dm_prim.dm_read_afh_channel_map_cfm.bd_addr,
            &ret_prim->hci_read_afh_channel_map.bd_addr);
        dm_prim.dm_read_afh_channel_map_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_CLASS_OF_DEVICE
    case HCI_READ_CLASS_OF_DEVICE:
        dm_prim.dm_read_class_of_device_cfm.type = opcode +
            (DM_HCI_READ_CLASS_OF_DEVICE_CFM -
            HCI_READ_CLASS_OF_DEVICE);
        size = sizeof(DM_HCI_READ_CLASS_OF_DEVICE_CFM_T);
        dm_prim.dm_read_class_of_device_cfm.dev_class =
            arg_ptr->read_class_device_args.dev_class;
        dm_prim.dm_read_class_of_device_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER
    case HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER:
        ((DM_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER_CFM -
            HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER);
        size = sizeof(DM_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER_CFM_T);
        ((DM_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER_CFM_T *) &dm_prim)->tx_power =
            arg_ptr->ulp_read_advertising_channel_tx_power_args.tx_power;
        ((DM_HCI_ULP_READ_ADVERTISING_CHANNEL_TX_POWER_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_RANDOM_ADDRESS
    case HCI_ULP_SET_RANDOM_ADDRESS:
        ((DM_HCI_ULP_SET_RANDOM_ADDRESS_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_RANDOM_ADDRESS_CFM -
            HCI_ULP_SET_RANDOM_ADDRESS);
        size = sizeof(DM_HCI_ULP_SET_RANDOM_ADDRESS_CFM_T);
        ((DM_HCI_ULP_SET_RANDOM_ADDRESS_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PAGE_SCAN_TYPE
    case HCI_WRITE_PAGE_SCAN_TYPE:
        dm_prim.dm_write_page_scan_type_cfm.type = opcode +
            (DM_HCI_WRITE_PAGE_SCAN_TYPE_CFM -
            HCI_WRITE_PAGE_SCAN_TYPE);
        size = sizeof(DM_HCI_WRITE_PAGE_SCAN_TYPE_CFM_T);
        dm_prim.dm_write_page_scan_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_REMOTE_NAME_REQ_CANCEL
    case HCI_REMOTE_NAME_REQ_CANCEL:
        dm_prim.dm_remote_name_req_cancel_cfm.type = opcode +
            (DM_HCI_REMOTE_NAME_REQ_CANCEL_CFM -
            HCI_REMOTE_NAME_REQ_CANCEL);
        size = sizeof(DM_HCI_REMOTE_NAME_REQ_CANCEL_CFM_T);
        bd_addr_copy(&dm_prim.dm_remote_name_req_cancel_cfm.bd_addr,
            &arg_ptr->remote_name_req_cancel_args.bd_addr);
        dm_prim.dm_remote_name_req_cancel_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_INQUIRY_CANCEL
    case HCI_INQUIRY_CANCEL:
        dm_prim.dm_inquiry_cancel_cfm.type = opcode +
            (DM_HCI_INQUIRY_CANCEL_CFM -
            HCI_INQUIRY_CANCEL);
        size = sizeof(DM_HCI_INQUIRY_CANCEL_CFM_T);
        dm_prim.dm_inquiry_cancel_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_READ_SUPPORTED_STATES
    case HCI_ULP_READ_SUPPORTED_STATES:
        ((DM_HCI_ULP_READ_SUPPORTED_STATES_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_READ_SUPPORTED_STATES_CFM -
            HCI_ULP_READ_SUPPORTED_STATES);
        size = sizeof(DM_HCI_ULP_READ_SUPPORTED_STATES_CFM_T);
        CsrMemCpy(&(((DM_HCI_ULP_READ_SUPPORTED_STATES_CFM_T *) &dm_prim)->supported_states),
            &arg_ptr->ulp_read_supported_states_args.supported_states,
            sizeof(((DM_HCI_ULP_READ_SUPPORTED_STATES_CFM_T *) &dm_prim)->supported_states));
        ((DM_HCI_ULP_READ_SUPPORTED_STATES_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_READ_CHANNEL_MAP
    case HCI_ULP_READ_CHANNEL_MAP:
        ((DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_READ_CHANNEL_MAP_CFM -
            HCI_ULP_READ_CHANNEL_MAP);
        size = sizeof(DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T);
        CsrMemCpy(&(((DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T *) &dm_prim)->ulp_channel_map),
            &arg_ptr->ulp_read_channel_map_args.ulp_channel_map,
            sizeof(((DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T *) &dm_prim)->ulp_channel_map));
        tbdaddr_copy(&((DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T *) &dm_prim)->addrt,
            &ret_prim->hci_ulp_read_channel_map.addrt);
        ((DM_HCI_ULP_READ_CHANNEL_MAP_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PAGESCAN_PERIOD_MODE
    case HCI_READ_PAGESCAN_PERIOD_MODE:
        dm_prim.dm_read_pagescan_period_mode_cfm.type = opcode +
            (DM_HCI_READ_PAGESCAN_PERIOD_MODE_CFM -
            HCI_READ_PAGESCAN_PERIOD_MODE);
        size = sizeof(DM_HCI_READ_PAGESCAN_PERIOD_MODE_CFM_T);
        dm_prim.dm_read_pagescan_period_mode_cfm.mode =
            arg_ptr->read_pagescan_period_mode_args.mode;
        dm_prim.dm_read_pagescan_period_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_FLUSH
    case HCI_FLUSH:
        dm_prim.dm_flush_cfm.type = opcode +
            (DM_HCI_FLUSH_CFM -
            HCI_FLUSH);
        size = sizeof(DM_HCI_FLUSH_CFM_T);
        bd_addr_copy(&dm_prim.dm_flush_cfm.bd_addr,
            &ret_prim->hci_flush.bd_addr);
        dm_prim.dm_flush_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_ENABLE
    case HCI_ULP_SET_SCAN_ENABLE:
        ((DM_HCI_ULP_SET_SCAN_ENABLE_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_SCAN_ENABLE_CFM -
            HCI_ULP_SET_SCAN_ENABLE);
        size = sizeof(DM_HCI_ULP_SET_SCAN_ENABLE_CFM_T);
        ((DM_HCI_ULP_SET_SCAN_ENABLE_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISING_DATA
    case HCI_ULP_SET_ADVERTISING_DATA:
        ((DM_HCI_ULP_SET_ADVERTISING_DATA_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_ADVERTISING_DATA_CFM -
            HCI_ULP_SET_ADVERTISING_DATA);
        size = sizeof(DM_HCI_ULP_SET_ADVERTISING_DATA_CFM_T);
        ((DM_HCI_ULP_SET_ADVERTISING_DATA_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ROLE_DISCOVERY
    case HCI_ROLE_DISCOVERY:
        dm_prim.dm_role_discovery_cfm.type = opcode +
            (DM_HCI_ROLE_DISCOVERY_CFM -
            HCI_ROLE_DISCOVERY);
        size = sizeof(DM_HCI_ROLE_DISCOVERY_CFM_T);
        dm_prim.dm_role_discovery_cfm.role =
            arg_ptr->role_discovery_args.current_role;
        bd_addr_copy(&dm_prim.dm_role_discovery_cfm.bd_addr,
            &ret_prim->hci_role_discovery.bd_addr);
        dm_prim.dm_role_discovery_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL
    case HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL:
        dm_prim.dm_write_inquiry_transmit_power_level_cfm.type = opcode +
            (DM_HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_CFM -
            HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL);
        size = sizeof(DM_HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL_CFM_T);
        dm_prim.dm_write_inquiry_transmit_power_level_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_MODE
    case HCI_WRITE_PAGESCAN_MODE:
        dm_prim.dm_write_pagescan_mode_cfm.type = opcode +
            (DM_HCI_WRITE_PAGESCAN_MODE_CFM -
            HCI_WRITE_PAGESCAN_MODE);
        size = sizeof(DM_HCI_WRITE_PAGESCAN_MODE_CFM_T);
        dm_prim.dm_write_pagescan_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_COUNTRY_CODE
    case HCI_READ_COUNTRY_CODE:
        dm_prim.dm_read_country_code_cfm.type = opcode +
            (DM_HCI_READ_COUNTRY_CODE_CFM -
            HCI_READ_COUNTRY_CODE);
        size = sizeof(DM_HCI_READ_COUNTRY_CODE_CFM_T);
        dm_prim.dm_read_country_code_cfm.country_code =
            arg_ptr->read_country_code_args.country_code;
        dm_prim.dm_read_country_code_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_GET_LINK_QUALITY
    case HCI_GET_LINK_QUALITY:
        dm_prim.dm_get_link_quality_cfm.type = opcode +
            (DM_HCI_GET_LINK_QUALITY_CFM -
            HCI_GET_LINK_QUALITY);
        size = sizeof(DM_HCI_GET_LINK_QUALITY_CFM_T);
        dm_prim.dm_get_link_quality_cfm.link_quality =
            arg_ptr->get_link_quality_args.link_quality;
        bd_addr_copy(&dm_prim.dm_get_link_quality_cfm.bd_addr,
            &ret_prim->hci_get_link_quality.bd_addr);
        dm_prim.dm_get_link_quality_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PAGE_TIMEOUT
    case HCI_WRITE_PAGE_TIMEOUT:
        dm_prim.dm_write_page_to_cfm.type = opcode +
            (DM_HCI_WRITE_PAGE_TIMEOUT_CFM -
            HCI_WRITE_PAGE_TIMEOUT);
        size = sizeof(DM_HCI_WRITE_PAGE_TIMEOUT_CFM_T);
        dm_prim.dm_write_page_to_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA
    case HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA:
        dm_prim.dm_write_extended_inquiry_response_data_cfm.type = opcode +
            (DM_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA_CFM -
            HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA);
        size = sizeof(DM_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_DATA_CFM_T);
        dm_prim.dm_write_extended_inquiry_response_data_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_CONN_ACCEPT_TIMEOUT
    case HCI_WRITE_CONN_ACCEPT_TIMEOUT:
        dm_prim.dm_write_conn_accept_to_cfm.type = opcode +
            (DM_HCI_WRITE_CONN_ACCEPT_TIMEOUT_CFM -
            HCI_WRITE_CONN_ACCEPT_TIMEOUT);
        size = sizeof(DM_HCI_WRITE_CONN_ACCEPT_TIMEOUT_CFM_T);
        dm_prim.dm_write_conn_accept_to_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PIN_TYPE
    case HCI_WRITE_PIN_TYPE:
        dm_prim.dm_write_pin_type_cfm.type = opcode +
            (DM_HCI_WRITE_PIN_TYPE_CFM -
            HCI_WRITE_PIN_TYPE);
        size = sizeof(DM_HCI_WRITE_PIN_TYPE_CFM_T);
        dm_prim.dm_write_pin_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_CONN_ACCEPT_TIMEOUT
    case HCI_READ_CONN_ACCEPT_TIMEOUT:
        dm_prim.dm_read_conn_accept_to_cfm.type = opcode +
            (DM_HCI_READ_CONN_ACCEPT_TIMEOUT_CFM -
            HCI_READ_CONN_ACCEPT_TIMEOUT);
        size = sizeof(DM_HCI_READ_CONN_ACCEPT_TIMEOUT_CFM_T);
        dm_prim.dm_read_conn_accept_to_cfm.conn_accept_timeout =
            arg_ptr->read_conn_accept_timeout_args.conn_accept_timeout;
        dm_prim.dm_read_conn_accept_to_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_LINK_SUPERV_TIMEOUT
    case HCI_WRITE_LINK_SUPERV_TIMEOUT:
        dm_prim.dm_write_link_superv_timeout_cfm.type = opcode +
            (DM_HCI_WRITE_LINK_SUPERV_TIMEOUT_CFM -
            HCI_WRITE_LINK_SUPERV_TIMEOUT);
        size = sizeof(DM_HCI_WRITE_LINK_SUPERV_TIMEOUT_CFM_T);
        bd_addr_copy(&dm_prim.dm_write_link_superv_timeout_cfm.bd_addr,
            &ret_prim->hci_write_link_superv_timeout.bd_addr);
        dm_prim.dm_write_link_superv_timeout_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_PAGE_TIMEOUT
    case HCI_READ_PAGE_TIMEOUT:
        dm_prim.dm_read_page_to_cfm.type = opcode +
            (DM_HCI_READ_PAGE_TIMEOUT_CFM -
            HCI_READ_PAGE_TIMEOUT);
        size = sizeof(DM_HCI_READ_PAGE_TIMEOUT_CFM_T);
        dm_prim.dm_read_page_to_cfm.page_timeout =
            arg_ptr->read_page_timeout_args.page_timeout;
        dm_prim.dm_read_page_to_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_ENC_MODE
    case HCI_READ_ENC_MODE:
        dm_prim.dm_read_encryption_mode_cfm.type = opcode +
            (DM_HCI_READ_ENC_MODE_CFM -
            HCI_READ_ENC_MODE);
        size = sizeof(DM_HCI_READ_ENC_MODE_CFM_T);
        dm_prim.dm_read_encryption_mode_cfm.mode =
            arg_ptr->read_enc_mode_args.mode;
        dm_prim.dm_read_encryption_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ENABLE_DUT_MODE
    case HCI_ENABLE_DUT_MODE:
        dm_prim.dm_enable_device_ut_mode_cfm.type = opcode +
            (DM_HCI_ENABLE_DUT_MODE_CFM -
            HCI_ENABLE_DUT_MODE);
        size = sizeof(DM_HCI_ENABLE_DUT_MODE_CFM_T);
        dm_prim.dm_enable_device_ut_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION
    case HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION:
        ((DM_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION_CFM -
            HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION);
        size = sizeof(DM_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION_CFM_T);
        ((DM_HCI_ULP_SET_HOST_CHANNEL_CLASSIFICATION_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_VOICE_SETTING
    case HCI_WRITE_VOICE_SETTING:
        dm_prim.dm_write_voice_setting_cfm.type = opcode +
            (DM_HCI_WRITE_VOICE_SETTING_CFM -
            HCI_WRITE_VOICE_SETTING);
        size = sizeof(DM_HCI_WRITE_VOICE_SETTING_CFM_T);
        dm_prim.dm_write_voice_setting_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_STORED_LINK_KEY
    case HCI_WRITE_STORED_LINK_KEY:
        dm_prim.dm_write_stored_link_key_cfm.type = opcode +
            (DM_HCI_WRITE_STORED_LINK_KEY_CFM -
            HCI_WRITE_STORED_LINK_KEY);
        size = sizeof(DM_HCI_WRITE_STORED_LINK_KEY_CFM_T);
        dm_prim.dm_write_stored_link_key_cfm.num_keys_written =
            arg_ptr->write_stored_link_key_args.num_keys_written;
        dm_prim.dm_write_stored_link_key_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_CREATE_CONNECTION_CANCEL
    case HCI_ULP_CREATE_CONNECTION_CANCEL:
        ((DM_HCI_ULP_CREATE_CONNECTION_CANCEL_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_CREATE_CONNECTION_CANCEL_CFM -
            HCI_ULP_CREATE_CONNECTION_CANCEL);
        size = sizeof(DM_HCI_ULP_CREATE_CONNECTION_CANCEL_CFM_T);
        ((DM_HCI_ULP_CREATE_CONNECTION_CANCEL_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_INQUIRYSCAN_ACTIVITY
    case HCI_WRITE_INQUIRYSCAN_ACTIVITY:
        dm_prim.dm_write_inquiryscan_activity_cfm.type = opcode +
            (DM_HCI_WRITE_INQUIRYSCAN_ACTIVITY_CFM -
            HCI_WRITE_INQUIRYSCAN_ACTIVITY);
        size = sizeof(DM_HCI_WRITE_INQUIRYSCAN_ACTIVITY_CFM_T);
        dm_prim.dm_write_inquiryscan_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_SCAN_TYPE
    case HCI_WRITE_INQUIRY_SCAN_TYPE:
        dm_prim.dm_write_inquiry_scan_type_cfm.type = opcode +
            (DM_HCI_WRITE_INQUIRY_SCAN_TYPE_CFM -
            HCI_WRITE_INQUIRY_SCAN_TYPE);
        size = sizeof(DM_HCI_WRITE_INQUIRY_SCAN_TYPE_CFM_T);
        dm_prim.dm_write_inquiry_scan_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_HOLD_MODE_ACTIVITY
    case HCI_READ_HOLD_MODE_ACTIVITY:
        dm_prim.dm_read_hold_mode_activity_cfm.type = opcode +
            (DM_HCI_READ_HOLD_MODE_ACTIVITY_CFM -
            HCI_READ_HOLD_MODE_ACTIVITY);
        size = sizeof(DM_HCI_READ_HOLD_MODE_ACTIVITY_CFM_T);
        dm_prim.dm_read_hold_mode_activity_cfm.activity =
            arg_ptr->read_hold_mode_activity_args.activity;
        dm_prim.dm_read_hold_mode_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_PARAMETERS
    case HCI_ULP_SET_SCAN_PARAMETERS:
        ((DM_HCI_ULP_SET_SCAN_PARAMETERS_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_SCAN_PARAMETERS_CFM -
            HCI_ULP_SET_SCAN_PARAMETERS);
        size = sizeof(DM_HCI_ULP_SET_SCAN_PARAMETERS_CFM_T);
        ((DM_HCI_ULP_SET_SCAN_PARAMETERS_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_EVENT_MASK
    case HCI_ULP_SET_EVENT_MASK:
        ((DM_HCI_ULP_SET_EVENT_MASK_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_EVENT_MASK_CFM -
            HCI_ULP_SET_EVENT_MASK);
        size = sizeof(DM_HCI_ULP_SET_EVENT_MASK_CFM_T);
        ((DM_HCI_ULP_SET_EVENT_MASK_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_INQUIRY_MODE
    case HCI_READ_INQUIRY_MODE:
        dm_prim.dm_read_inquiry_mode_cfm.type = opcode +
            (DM_HCI_READ_INQUIRY_MODE_CFM -
            HCI_READ_INQUIRY_MODE);
        size = sizeof(DM_HCI_READ_INQUIRY_MODE_CFM_T);
        dm_prim.dm_read_inquiry_mode_cfm.mode =
            arg_ptr->read_inquiry_mode_args.mode;
        dm_prim.dm_read_inquiry_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_PERIOD_MODE
    case HCI_WRITE_PAGESCAN_PERIOD_MODE:
        dm_prim.dm_write_pagescan_period_mode_cfm.type = opcode +
            (DM_HCI_WRITE_PAGESCAN_PERIOD_MODE_CFM -
            HCI_WRITE_PAGESCAN_PERIOD_MODE);
        size = sizeof(DM_HCI_WRITE_PAGESCAN_PERIOD_MODE_CFM_T);
        dm_prim.dm_write_pagescan_period_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_INQUIRYSCAN_ACTIVITY
    case HCI_READ_INQUIRYSCAN_ACTIVITY:
        dm_prim.dm_read_inquiryscan_activity_cfm.type = opcode +
            (DM_HCI_READ_INQUIRYSCAN_ACTIVITY_CFM -
            HCI_READ_INQUIRYSCAN_ACTIVITY);
        size = sizeof(DM_HCI_READ_INQUIRYSCAN_ACTIVITY_CFM_T);
        dm_prim.dm_read_inquiryscan_activity_cfm.inqscan_window =
            arg_ptr->read_inqscan_activity_args.inqscan_window;
        dm_prim.dm_read_inquiryscan_activity_cfm.inqscan_interval =
            arg_ptr->read_inqscan_activity_args.inqscan_interval;
        dm_prim.dm_read_inquiryscan_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_ENCRYPT
    case HCI_ULP_ENCRYPT:
        ((DM_HCI_ULP_ENCRYPT_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_ENCRYPT_CFM -
            HCI_ULP_ENCRYPT);
        size = sizeof(DM_HCI_ULP_ENCRYPT_CFM_T);
        CsrMemCpy(&(((DM_HCI_ULP_ENCRYPT_CFM_T *) &dm_prim)->encrypted_data),
            &arg_ptr->ulp_encrypt_args.encrypted_data,
            sizeof(((DM_HCI_ULP_ENCRYPT_CFM_T *) &dm_prim)->encrypted_data));
        ((DM_HCI_ULP_ENCRYPT_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_RAND
    case HCI_ULP_RAND:
        ((DM_HCI_ULP_RAND_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_RAND_CFM -
            HCI_ULP_RAND);
        size = sizeof(DM_HCI_ULP_RAND_CFM_T);
        CsrMemCpy(&(((DM_HCI_ULP_RAND_CFM_T *) &dm_prim)->random_number),
            &arg_ptr->ulp_rand_args.random_number,
            sizeof(((DM_HCI_ULP_RAND_CFM_T *) &dm_prim)->random_number));
        ((DM_HCI_ULP_RAND_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_SNIFF_SUB_RATE
    case HCI_SNIFF_SUB_RATE:
        dm_prim.dm_sniff_sub_rate_cfm.type = opcode +
            (DM_HCI_SNIFF_SUB_RATE_CFM -
            HCI_SNIFF_SUB_RATE);
        size = sizeof(DM_HCI_SNIFF_SUB_RATE_CFM_T);
        bd_addr_copy(&dm_prim.dm_sniff_sub_rate_cfm.bd_addr,
            &ret_prim->hci_sniff_sub_rate.bd_addr);
        dm_prim.dm_sniff_sub_rate_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS
    case HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS:
        dm_prim.dm_write_default_link_policy_settings_cfm.type = opcode +
            (DM_HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_CFM -
            HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS);
        size = sizeof(DM_HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS_CFM_T);
        dm_prim.dm_write_default_link_policy_settings_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_CREATE_NEW_UNIT_KEY
    case HCI_CREATE_NEW_UNIT_KEY:
        dm_prim.dm_create_new_unit_key_cfm.type = opcode +
            (DM_HCI_CREATE_NEW_UNIT_KEY_CFM -
            HCI_CREATE_NEW_UNIT_KEY);
        size = sizeof(DM_HCI_CREATE_NEW_UNIT_KEY_CFM_T);
        dm_prim.dm_create_new_unit_key_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_AUTO_FLUSH_TIMEOUT
    case HCI_WRITE_AUTO_FLUSH_TIMEOUT:
        dm_prim.dm_write_auto_flush_timeout_cfm.type = opcode +
            (DM_HCI_WRITE_AUTO_FLUSH_TIMEOUT_CFM -
            HCI_WRITE_AUTO_FLUSH_TIMEOUT);
        size = sizeof(DM_HCI_WRITE_AUTO_FLUSH_TIMEOUT_CFM_T);
        bd_addr_copy(&dm_prim.dm_write_auto_flush_timeout_cfm.bd_addr,
            &ret_prim->hci_write_auto_flush_timeout.bd_addr);
        dm_prim.dm_write_auto_flush_timeout_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LOCAL_EXT_FEATURES
    case HCI_READ_LOCAL_EXT_FEATURES:
        dm_prim.dm_read_local_ext_features_cfm.type = opcode +
            (DM_HCI_READ_LOCAL_EXT_FEATURES_CFM -
            HCI_READ_LOCAL_EXT_FEATURES);
        size = sizeof(DM_HCI_READ_LOCAL_EXT_FEATURES_CFM_T);
        CsrMemCpy(&(dm_prim.dm_read_local_ext_features_cfm.lmp_ext_features),
            &arg_ptr->read_local_ext_features_args.lmp_ext_features,
            sizeof(dm_prim.dm_read_local_ext_features_cfm.lmp_ext_features));
        dm_prim.dm_read_local_ext_features_cfm.max_page_num =
            arg_ptr->read_local_ext_features_args.max_page_num;
        dm_prim.dm_read_local_ext_features_cfm.page_num =
            arg_ptr->read_local_ext_features_args.page_num;
        dm_prim.dm_read_local_ext_features_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL
    case HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL:
        dm_prim.dm_read_inquiry_response_tx_power_level_cfm.type = opcode +
            (DM_HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL_CFM -
            HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL);
        size = sizeof(DM_HCI_READ_INQUIRY_RESPONSE_TX_POWER_LEVEL_CFM_T);
        dm_prim.dm_read_inquiry_response_tx_power_level_cfm.tx_power =
            arg_ptr->read_inquiry_response_tx_power_level_args.tx_power;
        dm_prim.dm_read_inquiry_response_tx_power_level_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_ENCRYPTION_KEY_SIZE
    case HCI_READ_ENCRYPTION_KEY_SIZE:
        dm_prim.dm_read_encryption_key_size_cfm.type = opcode +
            (DM_HCI_READ_ENCRYPTION_KEY_SIZE_CFM -
            HCI_READ_ENCRYPTION_KEY_SIZE);
        size = sizeof(DM_HCI_READ_ENCRYPTION_KEY_SIZE_CFM_T);
        dm_prim.dm_read_encryption_key_size_cfm.key_size =
            arg_ptr->read_encryption_key_size_args.key_size;
        bd_addr_copy(&dm_prim.dm_read_encryption_key_size_cfm.bd_addr,
            &ret_prim->hci_read_encryption_key_size.bd_addr);
        dm_prim.dm_read_encryption_key_size_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_LINK_POLICY_SETTINGS
    case HCI_WRITE_LINK_POLICY_SETTINGS:
        dm_prim.dm_write_link_policy_settings_cfm.type = opcode +
            (DM_HCI_WRITE_LINK_POLICY_SETTINGS_CFM -
            HCI_WRITE_LINK_POLICY_SETTINGS);
        size = sizeof(DM_HCI_WRITE_LINK_POLICY_SETTINGS_CFM_T);
        bd_addr_copy(&dm_prim.dm_write_link_policy_settings_cfm.bd_addr,
            &ret_prim->hci_write_link_policy_settings.bd_addr);
        dm_prim.dm_write_link_policy_settings_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_FAILED_CONTACT_COUNT
    case HCI_READ_FAILED_CONTACT_COUNT:
        dm_prim.dm_failed_contact_counter_cfm.type = opcode +
            (DM_HCI_READ_FAILED_CONTACT_COUNT_CFM -
            HCI_READ_FAILED_CONTACT_COUNT);
        size = sizeof(DM_HCI_READ_FAILED_CONTACT_COUNT_CFM_T);
        dm_prim.dm_failed_contact_counter_cfm.failed_contact_count =
            arg_ptr->read_failed_contact_count_args.failed_contact_count;
        bd_addr_copy(&dm_prim.dm_failed_contact_counter_cfm.bd_addr,
            &ret_prim->hci_read_failed_contact_count.bd_addr);
        dm_prim.dm_failed_contact_counter_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_CURRENT_IAC_LAP
    case HCI_WRITE_CURRENT_IAC_LAP:
        dm_prim.dm_write_current_iac_lap_cfm.type = opcode +
            (DM_HCI_WRITE_CURRENT_IAC_LAP_CFM -
            HCI_WRITE_CURRENT_IAC_LAP);
        size = sizeof(DM_HCI_WRITE_CURRENT_IAC_LAP_CFM_T);
        dm_prim.dm_write_current_iac_lap_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_AUTO_FLUSH_TIMEOUT
    case HCI_READ_AUTO_FLUSH_TIMEOUT:
        dm_prim.dm_read_auto_flush_timeout_cfm.type = opcode +
            (DM_HCI_READ_AUTO_FLUSH_TIMEOUT_CFM -
            HCI_READ_AUTO_FLUSH_TIMEOUT);
        size = sizeof(DM_HCI_READ_AUTO_FLUSH_TIMEOUT_CFM_T);
        dm_prim.dm_read_auto_flush_timeout_cfm.FlushTimeout =
            arg_ptr->read_auto_flush_timeout_args.timeout;
        bd_addr_copy(&dm_prim.dm_read_auto_flush_timeout_cfm.bd_addr,
            &ret_prim->hci_read_auto_flush_timeout.bd_addr);
        dm_prim.dm_read_auto_flush_timeout_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_PAGESCAN_ACTIVITY
    case HCI_WRITE_PAGESCAN_ACTIVITY:
        dm_prim.dm_write_pagescan_activity_cfm.type = opcode +
            (DM_HCI_WRITE_PAGESCAN_ACTIVITY_CFM -
            HCI_WRITE_PAGESCAN_ACTIVITY);
        size = sizeof(DM_HCI_WRITE_PAGESCAN_ACTIVITY_CFM_T);
        dm_prim.dm_write_pagescan_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_STORED_LINK_KEY
    case HCI_READ_STORED_LINK_KEY:
        dm_prim.dm_read_stored_link_key_cfm.type = opcode +
            (DM_HCI_READ_STORED_LINK_KEY_CFM -
            HCI_READ_STORED_LINK_KEY);
        size = sizeof(DM_HCI_READ_STORED_LINK_KEY_CFM_T);
        dm_prim.dm_read_stored_link_key_cfm.num_keys_read =
            arg_ptr->read_stored_link_key_args.num_keys_read;
        dm_prim.dm_read_stored_link_key_cfm.max_num_keys =
            arg_ptr->read_stored_link_key_args.max_num_keys;
        dm_prim.dm_read_stored_link_key_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_SET_AFH_CHANNEL_CLASS
    case HCI_SET_AFH_CHANNEL_CLASS:
        dm_prim.dm_set_afh_channel_class_cfm.type = opcode +
            (DM_HCI_SET_AFH_CHANNEL_CLASS_CFM -
            HCI_SET_AFH_CHANNEL_CLASS);
        size = sizeof(DM_HCI_SET_AFH_CHANNEL_CLASS_CFM_T);
        dm_prim.dm_set_afh_channel_class_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LOCAL_SUPP_FEATURES
    case HCI_READ_LOCAL_SUPP_FEATURES:
        dm_prim.dm_read_local_features_cfm.type = opcode +
            (DM_HCI_READ_LOCAL_SUPP_FEATURES_CFM -
            HCI_READ_LOCAL_SUPP_FEATURES);
        size = sizeof(DM_HCI_READ_LOCAL_SUPP_FEATURES_CFM_T);
        CsrMemCpy(&(dm_prim.dm_read_local_features_cfm.lmp_supp_features),
            &arg_ptr->read_local_supp_features_args.lmp_supp_features,
            sizeof(dm_prim.dm_read_local_features_cfm.lmp_supp_features));
        dm_prim.dm_read_local_features_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LOCAL_VER_INFO
    case HCI_READ_LOCAL_VER_INFO:
        dm_prim.dm_read_local_version_cfm.type = opcode +
            (DM_HCI_READ_LOCAL_VER_INFO_CFM -
            HCI_READ_LOCAL_VER_INFO);
        size = sizeof(DM_HCI_READ_LOCAL_VER_INFO_CFM_T);
        dm_prim.dm_read_local_version_cfm.lmp_subversion =
            arg_ptr->read_local_ver_info_args.lmp_subversion;
        dm_prim.dm_read_local_version_cfm.manuf_name =
            arg_ptr->read_local_ver_info_args.manuf_name;
        dm_prim.dm_read_local_version_cfm.lmp_version =
            arg_ptr->read_local_ver_info_args.lmp_version;
        dm_prim.dm_read_local_version_cfm.hci_revision =
            arg_ptr->read_local_ver_info_args.hci_revision;
        dm_prim.dm_read_local_version_cfm.hci_version =
            arg_ptr->read_local_ver_info_args.hci_version;
        dm_prim.dm_read_local_version_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_NUM_BCAST_RETXS
    case HCI_READ_NUM_BCAST_RETXS:
        dm_prim.dm_read_num_bcast_txs_cfm.type = opcode +
            (DM_HCI_READ_NUM_BCAST_RETXS_CFM -
            HCI_READ_NUM_BCAST_RETXS);
        size = sizeof(DM_HCI_READ_NUM_BCAST_RETXS_CFM_T);
        dm_prim.dm_read_num_bcast_txs_cfm.num =
            arg_ptr->read_num_bcast_retxs_args.num;
        dm_prim.dm_read_num_bcast_txs_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_AUTH_ENABLE
    case HCI_READ_AUTH_ENABLE:
        dm_prim.dm_read_auth_enable_cfm.type = opcode +
            (DM_HCI_READ_AUTH_ENABLE_CFM -
            HCI_READ_AUTH_ENABLE);
        size = sizeof(DM_HCI_READ_AUTH_ENABLE_CFM_T);
        dm_prim.dm_read_auth_enable_cfm.auth_enable =
            arg_ptr->read_auth_enable_args.auth_enable;
        dm_prim.dm_read_auth_enable_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_ADVERTISE_ENABLE
    case HCI_ULP_SET_ADVERTISE_ENABLE:
        ((DM_HCI_ULP_SET_ADVERTISE_ENABLE_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_ADVERTISE_ENABLE_CFM -
            HCI_ULP_SET_ADVERTISE_ENABLE);
        size = sizeof(DM_HCI_ULP_SET_ADVERTISE_ENABLE_CFM_T);
        ((DM_HCI_ULP_SET_ADVERTISE_ENABLE_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_CHANGE_LOCAL_NAME
    case HCI_CHANGE_LOCAL_NAME:
        dm_prim.dm_change_local_name_cfm.type = opcode +
            (DM_HCI_CHANGE_LOCAL_NAME_CFM -
            HCI_CHANGE_LOCAL_NAME);
        size = sizeof(DM_HCI_CHANGE_LOCAL_NAME_CFM_T);
        dm_prim.dm_change_local_name_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_SCAN_ENABLE
    case HCI_WRITE_SCAN_ENABLE:
        dm_prim.dm_write_scan_enable_cfm.type = opcode +
            (DM_HCI_WRITE_SCAN_ENABLE_CFM -
            HCI_WRITE_SCAN_ENABLE);
        size = sizeof(DM_HCI_WRITE_SCAN_ENABLE_CFM_T);
        dm_prim.dm_write_scan_enable_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LINK_SUPERV_TIMEOUT
    case HCI_READ_LINK_SUPERV_TIMEOUT:
        dm_prim.dm_read_link_superv_timeout_cfm.type = opcode +
            (DM_HCI_READ_LINK_SUPERV_TIMEOUT_CFM -
            HCI_READ_LINK_SUPERV_TIMEOUT);
        size = sizeof(DM_HCI_READ_LINK_SUPERV_TIMEOUT_CFM_T);
        dm_prim.dm_read_link_superv_timeout_cfm.timeout =
            arg_ptr->read_link_superv_timeout_args.timeout;
        bd_addr_copy(&dm_prim.dm_read_link_superv_timeout_cfm.bd_addr,
            &ret_prim->hci_read_link_superv_timeout.bd_addr);
        dm_prim.dm_read_link_superv_timeout_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_NUM_SUPPORTED_IAC
    case HCI_READ_NUM_SUPPORTED_IAC:
        dm_prim.dm_read_num_supported_iac_cfm.type = opcode +
            (DM_HCI_READ_NUM_SUPPORTED_IAC_CFM -
            HCI_READ_NUM_SUPPORTED_IAC);
        size = sizeof(DM_HCI_READ_NUM_SUPPORTED_IAC_CFM_T);
        dm_prim.dm_read_num_supported_iac_cfm.num =
            arg_ptr->read_num_supported_iac_args.num;
        dm_prim.dm_read_num_supported_iac_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_TX_POWER_LEVEL
    case HCI_READ_TX_POWER_LEVEL:
        dm_prim.dm_read_tx_power_level_cfm.type = opcode +
            (DM_HCI_READ_TX_POWER_LEVEL_CFM -
            HCI_READ_TX_POWER_LEVEL);
        size = sizeof(DM_HCI_READ_TX_POWER_LEVEL_CFM_T);
        dm_prim.dm_read_tx_power_level_cfm.pwr_level =
            arg_ptr->read_tx_power_level_args.pwr_level;
        tbdaddr_copy(&dm_prim.dm_read_tx_power_level_cfm.addrt,
            &ret_prim->hci_read_tx_power_level.addrt);
        dm_prim.dm_read_tx_power_level_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_CLASS_OF_DEVICE
    case HCI_WRITE_CLASS_OF_DEVICE:
        dm_prim.dm_write_class_of_device_cfm.type = opcode +
            (DM_HCI_WRITE_CLASS_OF_DEVICE_CFM -
            HCI_WRITE_CLASS_OF_DEVICE);
        size = sizeof(DM_HCI_WRITE_CLASS_OF_DEVICE_CFM_T);
        dm_prim.dm_write_class_of_device_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_TRANSMITTER_TEST
    case HCI_ULP_TRANSMITTER_TEST:
        ((DM_HCI_ULP_TRANSMITTER_TEST_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_TRANSMITTER_TEST_CFM -
            HCI_ULP_TRANSMITTER_TEST);
        size = sizeof(DM_HCI_ULP_TRANSMITTER_TEST_CFM_T);
        ((DM_HCI_ULP_TRANSMITTER_TEST_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_PERIODIC_INQUIRY_MODE
    case HCI_PERIODIC_INQUIRY_MODE:
        dm_prim.dm_periodic_inquiry_cfm.type = opcode +
            (DM_HCI_PERIODIC_INQUIRY_MODE_CFM -
            HCI_PERIODIC_INQUIRY_MODE);
        size = sizeof(DM_HCI_PERIODIC_INQUIRY_MODE_CFM_T);
        dm_prim.dm_periodic_inquiry_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LINK_POLICY_SETTINGS
    case HCI_READ_LINK_POLICY_SETTINGS:
        dm_prim.dm_read_lp_settings_cfm.type = opcode +
            (DM_HCI_READ_LINK_POLICY_SETTINGS_CFM -
            HCI_READ_LINK_POLICY_SETTINGS);
        size = sizeof(DM_HCI_READ_LINK_POLICY_SETTINGS_CFM_T);
        dm_prim.dm_read_lp_settings_cfm.link_policy =
            arg_ptr->read_link_policy_settings_args.link_policy_settings;
        bd_addr_copy(&dm_prim.dm_read_lp_settings_cfm.bd_addr,
            &ret_prim->hci_read_link_policy_settings.bd_addr);
        dm_prim.dm_read_lp_settings_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_INQUIRY_MODE
    case HCI_WRITE_INQUIRY_MODE:
        dm_prim.dm_write_inquiry_mode_cfm.type = opcode +
            (DM_HCI_WRITE_INQUIRY_MODE_CFM -
            HCI_WRITE_INQUIRY_MODE);
        size = sizeof(DM_HCI_WRITE_INQUIRY_MODE_CFM_T);
        dm_prim.dm_write_inquiry_mode_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_SET_SCAN_RESPONSE_DATA
    case HCI_ULP_SET_SCAN_RESPONSE_DATA:
        ((DM_HCI_ULP_SET_SCAN_RESPONSE_DATA_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_SET_SCAN_RESPONSE_DATA_CFM -
            HCI_ULP_SET_SCAN_RESPONSE_DATA);
        size = sizeof(DM_HCI_ULP_SET_SCAN_RESPONSE_DATA_CFM_T);
        ((DM_HCI_ULP_SET_SCAN_RESPONSE_DATA_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_AFH_CHANNEL_CLASS_M
    case HCI_WRITE_AFH_CHANNEL_CLASS_M:
        dm_prim.dm_write_afh_channel_class_m_cfm.type = opcode +
            (DM_HCI_WRITE_AFH_CHANNEL_CLASS_M_CFM -
            HCI_WRITE_AFH_CHANNEL_CLASS_M);
        size = sizeof(DM_HCI_WRITE_AFH_CHANNEL_CLASS_M_CFM_T);
        dm_prim.dm_write_afh_channel_class_m_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_DELETE_STORED_LINK_KEY
    case HCI_DELETE_STORED_LINK_KEY:
        dm_prim.dm_delete_stored_link_key_cfm.type = opcode +
            (DM_HCI_DELETE_STORED_LINK_KEY_CFM -
            HCI_DELETE_STORED_LINK_KEY);
        size = sizeof(DM_HCI_DELETE_STORED_LINK_KEY_CFM_T);
        dm_prim.dm_delete_stored_link_key_cfm.num_keys_deleted =
            arg_ptr->delete_stored_link_key_args.num_keys_deleted;
        dm_prim.dm_delete_stored_link_key_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_BD_ADDR
    case HCI_READ_BD_ADDR:
        dm_prim.dm_read_bd_addr_cfm.type = opcode +
            (DM_HCI_READ_BD_ADDR_CFM -
            HCI_READ_BD_ADDR);
        size = sizeof(DM_HCI_READ_BD_ADDR_CFM_T);
        bd_addr_copy(&dm_prim.dm_read_bd_addr_cfm.bd_addr,
            &arg_ptr->read_bd_addr_args.bd_addr);
        dm_prim.dm_read_bd_addr_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_EXIT_PERIODIC_INQUIRY_MODE
    case HCI_EXIT_PERIODIC_INQUIRY_MODE:
        dm_prim.dm_exit_periodic_inquiry_cfm.type = opcode +
            (DM_HCI_EXIT_PERIODIC_INQUIRY_MODE_CFM -
            HCI_EXIT_PERIODIC_INQUIRY_MODE);
        size = sizeof(DM_HCI_EXIT_PERIODIC_INQUIRY_MODE_CFM_T);
        dm_prim.dm_exit_periodic_inquiry_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_SCO_FLOW_CON_ENABLE
    case HCI_WRITE_SCO_FLOW_CON_ENABLE:
        dm_prim.dm_write_sco_flow_control_enable_cfm.type = opcode +
            (DM_HCI_WRITE_SCO_FLOW_CON_ENABLE_CFM -
            HCI_WRITE_SCO_FLOW_CON_ENABLE);
        size = sizeof(DM_HCI_WRITE_SCO_FLOW_CON_ENABLE_CFM_T);
        dm_prim.dm_write_sco_flow_control_enable_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_INQUIRY_SCAN_TYPE
    case HCI_READ_INQUIRY_SCAN_TYPE:
        dm_prim.dm_read_inquiry_scan_type_cfm.type = opcode +
            (DM_HCI_READ_INQUIRY_SCAN_TYPE_CFM -
            HCI_READ_INQUIRY_SCAN_TYPE);
        size = sizeof(DM_HCI_READ_INQUIRY_SCAN_TYPE_CFM_T);
        dm_prim.dm_read_inquiry_scan_type_cfm.mode =
            arg_ptr->read_inquiry_scan_type_args.mode;
        dm_prim.dm_read_inquiry_scan_type_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_WRITE_HOLD_MODE_ACTIVITY
    case HCI_WRITE_HOLD_MODE_ACTIVITY:
        dm_prim.dm_write_hold_mode_activity_cfm.type = opcode +
            (DM_HCI_WRITE_HOLD_MODE_ACTIVITY_CFM -
            HCI_WRITE_HOLD_MODE_ACTIVITY);
        size = sizeof(DM_HCI_WRITE_HOLD_MODE_ACTIVITY_CFM_T);
        dm_prim.dm_write_hold_mode_activity_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_ULP_READ_WHITE_LIST_SIZE
    case HCI_ULP_READ_WHITE_LIST_SIZE:
        ((DM_HCI_ULP_READ_WHITE_LIST_SIZE_CFM_T *) &dm_prim)->type = opcode +
            (DM_HCI_ULP_READ_WHITE_LIST_SIZE_CFM -
            HCI_ULP_READ_WHITE_LIST_SIZE);
        size = sizeof(DM_HCI_ULP_READ_WHITE_LIST_SIZE_CFM_T);
        ((DM_HCI_ULP_READ_WHITE_LIST_SIZE_CFM_T *) &dm_prim)->white_list_size =
            arg_ptr->ulp_read_white_list_size_args.white_list_size;
        ((DM_HCI_ULP_READ_WHITE_LIST_SIZE_CFM_T *) &dm_prim)->status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_AFH_CHANNEL_CLASS_M
    case HCI_READ_AFH_CHANNEL_CLASS_M:
        dm_prim.dm_read_afh_channel_class_m_cfm.type = opcode +
            (DM_HCI_READ_AFH_CHANNEL_CLASS_M_CFM -
            HCI_READ_AFH_CHANNEL_CLASS_M);
        size = sizeof(DM_HCI_READ_AFH_CHANNEL_CLASS_M_CFM_T);
        dm_prim.dm_read_afh_channel_class_m_cfm.class_mode =
            arg_ptr->read_afh_channel_class_m_args.class_mode;
        dm_prim.dm_read_afh_channel_class_m_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif
#ifndef CSR_BT_EXCLUDE_HCI_READ_LMP_HANDLE
    case HCI_READ_LMP_HANDLE:
        dm_prim.dm_read_lmp_handle_cfm.type = opcode +
            (DM_HCI_READ_LMP_HANDLE_CFM -
            HCI_READ_LMP_HANDLE);
        size = sizeof(DM_HCI_READ_LMP_HANDLE_CFM_T);
        dm_prim.dm_read_lmp_handle_cfm.reserved =
            arg_ptr->read_lmp_handle_args.reserved;
        dm_prim.dm_read_lmp_handle_cfm.lmp_handle =
            arg_ptr->read_lmp_handle_args.lmp_handle;
        dm_prim.dm_read_lmp_handle_cfm.handle =
            arg_ptr->read_lmp_handle_args.handle;
        dm_prim.dm_read_lmp_handle_cfm.status = status;
        DM_SendMessageAMphandle(pcopy(&dm_prim, size));
        break;
#endif

        default:
            /* dm_ret_not_used(hci_prim, ret_prim); */
            return;
    }
}
