/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   dm_sm_fsm_constants.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "dm_sm_fsm_constants.h"

/* Action function table */
/*{{__FSM_MARKER(DM_SM, ACTION_FN_TABLE) */
static const fsm_action_fn_t dm_sm_action_fns[] =
{
    sm_af_authenticate_req,
    sm_af_encrypt_req,
    sm_af_check_connection,
    sm_af_auth_cfm_ok,
    sm_af_auth_cfm_fail,
    sm_af_enc_cfm_ok,
    sm_af_hci_set_encryption,
    sm_af_enc_cfm_fail,
    sm_af_bond_req,
    sm_af_bond_cfm_fail,
    sm_af_access_authenticate,
    sm_af_access_authorise,
    sm_af_access_fail,
    sm_af_check_acl_detach,
    sm_af_access_encrypt,
    sm_af_access_success,
    sm_af_bond_cfm_ok,
    sm_af_bond_cfm_cancel,
    sm_af_kill_request,
};
/*}}__FSM_END_MARKER(DM_SM, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(DM_SM, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T dm_sm_transitions[] = {
  /* IDLE */
  { SM_EV_AUTHENTICATE_REQ,      SM_AC_authenticate_req,     SM_ST_AUTHENTICATING },
  { SM_EV_ENCRYPT_REQ,           SM_AC_encrypt_req,          SM_ST_ENCRYPTING_AUTH },
  { SM_EV_BONDING_REQ,           SM_AC_check_connection,     SM_ST_BONDING_PENDING },
  { SM_EV_ACCESS_REQ,            SM_AC_check_connection,     SM_ST_ACCESS_PENDING },
  /* AUTHENTICATING */
  { SM_EV_HCI_AUTH_OK,           SM_AC_auth_cfm_ok,          SM_ST_DEATHBED },
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_auth_cfm_fail,        SM_ST_DEATHBED },
  { SM_EV_RETRY_AUTHENTICATE,    SM_AC_authenticate_req,     SM_ST_AUTHENTICATING },
  /* ENCRYPTING_AUTH */
  { SM_EV_HCI_AUTH_OK,           SM_AC_hci_set_encryption,   SM_ST_ENCRYPTING },
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_enc_cfm_fail,         SM_ST_DEATHBED },
  { SM_EV_OK,                    SM_AC_enc_cfm_ok,           SM_ST_DEATHBED },
  /* ENCRYPTING */
  { SM_EV_HCI_ENC_CHANGE_OK,     SM_AC_enc_cfm_ok,           SM_ST_DEATHBED },
  { SM_EV_HCI_ENC_CHANGE_FAIL,   SM_AC_enc_cfm_fail,         SM_ST_DEATHBED },
  { SM_EV_RETRY_ENCRYPTION,      SM_AC_hci_set_encryption,   SM_ST_ENCRYPTING },
  /* BONDING_PENDING */
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_bond_cfm_fail,        SM_ST_DEATHBED },
  { SM_EV_ACL_READY,             SM_AC_bond_req,             SM_ST_BONDING },
  { SM_EV_CANCEL_BONDING,        SM_AC_NULL,                 SM_ST_BONDING_CANCEL },
  /* ACCESS_PENDING */
  { SM_EV_ACL_READY,             SM_AC_access_authenticate,  SM_ST_ACCESS_AUTHENTICATING },
  /* ACCESS_AUTHENTICATING */
  { SM_EV_HCI_AUTH_OK,           SM_AC_access_authorise,     SM_ST_ACCESS_AUTHORISING },
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_access_fail,          SM_ST_DEATHBED },
  { SM_EV_RETRY_AUTHENTICATE,    SM_AC_access_authenticate,  SM_ST_ACCESS_AUTHENTICATING },
  { SM_EV_HCI_ENC_CHANGE_OK,     SM_AC_check_acl_detach,     SM_ST_ACCESS_AUTHENTICATING },
  /* ACCESS_AUTHORISING */
  { SM_EV_AUTHORISE_OK,          SM_AC_access_encrypt,       SM_ST_ACCESS_ENCRYPTING },
  { SM_EV_AUTHORISE_FAIL,        SM_AC_access_fail,          SM_ST_DEATHBED },
  /* ACCESS_ENCRYPTING */
  { SM_EV_HCI_ENC_CHANGE_OK,     SM_AC_access_success,       SM_ST_DEATHBED },
  { SM_EV_HCI_ENC_CHANGE_FAIL,   SM_AC_access_fail,          SM_ST_DEATHBED },
  { SM_EV_RETRY_ENCRYPTION,      SM_AC_access_encrypt,       SM_ST_ENCRYPTING },
  /* BONDING */
  { SM_EV_HCI_AUTH_OK,           SM_AC_bond_cfm_ok,          SM_ST_DEATHBED },
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_bond_cfm_fail,        SM_ST_DEATHBED },
  { SM_EV_CANCEL_BONDING,        SM_AC_NULL,                 SM_ST_BONDING_CANCEL },
  /* BONDING_CANCEL */
  { SM_EV_HCI_AUTH_OK,           SM_AC_bond_cfm_ok,          SM_ST_DEATHBED },
  { SM_EV_HCI_AUTH_FAIL,         SM_AC_bond_cfm_cancel,      SM_ST_DEATHBED },
  { SM_EV_ACL_READY,             SM_AC_bond_cfm_cancel,      SM_ST_DEATHBED },
  /* DEATHBED */
  { SM_EV_PURGE,                 SM_AC_kill_request,         SM_ST_DEATHBED },
  { SM_EV_PURGED,                SM_AC_NULL,                 SM_ST_IDLE }
};
/*}}__FSM_END_MARKER(DM_SM, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(DM_SM, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T dm_sm_states[SM_ST_ST_MAX+1] = {
    { &dm_sm_transitions[0] },
    { &dm_sm_transitions[4] },
    { &dm_sm_transitions[7] },
    { &dm_sm_transitions[10] },
    { &dm_sm_transitions[13] },
    { &dm_sm_transitions[16] },
    { &dm_sm_transitions[17] },
    { &dm_sm_transitions[21] },
    { &dm_sm_transitions[23] },
    { &dm_sm_transitions[26] },
    { &dm_sm_transitions[29] },
    { &dm_sm_transitions[32] },
    { &dm_sm_transitions[34] },
};
/*}}__FSM_END_MARKER(DM_SM, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(DM_SM, FSM_LOGGING) */
/* State names */
const char *const dm_sm_state_names[] =
{
    "SM_ST_IDLE",
    "SM_ST_AUTHENTICATING",
    "SM_ST_ENCRYPTING_AUTH",
    "SM_ST_ENCRYPTING",
    "SM_ST_BONDING_PENDING",
    "SM_ST_ACCESS_PENDING",
    "SM_ST_ACCESS_AUTHENTICATING",
    "SM_ST_ACCESS_AUTHORISING",
    "SM_ST_ACCESS_ENCRYPTING",
    "SM_ST_BONDING",
    "SM_ST_BONDING_CANCEL",
    "SM_ST_DEATHBED",
};
#define DM_SM_STATE_NAMES_PTR (dm_sm_state_names)

/* Event names */
const char *const dm_sm_event_names[] =
{
    "SM_EV_AUTHENTICATE_REQ",
    "SM_EV_ENCRYPT_REQ",
    "SM_EV_BONDING_REQ",
    "SM_EV_ACCESS_REQ",
    "SM_EV_HCI_AUTH_OK",
    "SM_EV_HCI_AUTH_FAIL",
    "SM_EV_RETRY_AUTHENTICATE",
    "SM_EV_OK",
    "SM_EV_HCI_ENC_CHANGE_OK",
    "SM_EV_HCI_ENC_CHANGE_FAIL",
    "SM_EV_RETRY_ENCRYPTION",
    "SM_EV_ACL_READY",
    "SM_EV_CANCEL_BONDING",
    "SM_EV_AUTHORISE_OK",
    "SM_EV_AUTHORISE_FAIL",
    "SM_EV_PURGE",
    "SM_EV_PURGED",
};
#define DM_SM_EVENT_NAMES_PTR (dm_sm_event_names)

/*}}__FSM_END_MARKER(DM_SM, FSM_LOGGING) */
#else
#define DM_SM_STATE_NAMES_PTR (NULL)
#define DM_SM_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(DM_SM, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T dm_sm_fsm =
{
    (const FSM_SPARSE16_STATES_T *) dm_sm_states,
    dm_sm_action_fns
    FSM_LOG_INFO("DM_SM",
    DM_SM_STATE_NAMES_PTR,
    DM_SM_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(DM_SM, FSM_DEFINITION) */

