/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_mgr_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_phdc_mgr_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_phdc_mgr_action_fns[] =
{
    CsrBtPhdcMgrFsm_IdleSPhdcConfigureEndpointReq,
    CsrBtPhdcMgrFsm_AnyStatePhdcUnregisterReq,
    CsrBtPhdcMgrFsm_RegisteringSHdpRegisterInd,
    CsrBtPhdcMgrFsm_RegisteringSPhdcConfigureEndpointRes,
    CsrBtPhdcMgrFsm_RegisteringSHdpRegisterCfm,
    CsrBtPhdcMgrFsm_UnregisteringSHdpUnregisterCfm,
    CsrBtPhdcMgrFsm_ActivatingSHdpActivateCfm,
    CsrBtPhdcMgrFsm_DeactivatingSHdpDeactivateCfm,
    CsrBtPhdcMgrFsm_DeactivatingSHdpDisconnectAssociateChannelCfm,
    CsrBtPhdcMgrFsm_AnyStateHdpCtrlGetCapabInd,
    CsrBtPhdcMgrFsm_AnyStatePhdcGetDeviceCapabReq,
    CsrBtPhdcMgrFsm_AnyStateHdpCtrlGetCapabCfm,
    CsrBtPhdcMgrFsm_AnyStateHdpResumeInd,
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_phdc_mgr_transitions[] = {
  /* IDLE */
  { PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_REQ,            PHDC_MGR_AC_IdleSPhdcConfigureEndpointReq,                  CSR_BT_PHDC_MGR_ST_REGISTERING },
  { PHDC_MGR_EV_PHDC_UNREGISTER_REQ,                    PHDC_MGR_AC_AnyStatePhdcUnregisterReq,                      CSR_BT_PHDC_MGR_ST_IDLE },
  /* REGISTERING */
  { PHDC_MGR_EV_PHDC_UNREGISTER_REQ,                    PHDC_MGR_AC_AnyStatePhdcUnregisterReq,                      CSR_BT_PHDC_MGR_ST_UNREGISTERING },
  { PHDC_MGR_EV_HDP_REGISTER_IND,                       PHDC_MGR_AC_RegisteringSHdpRegisterInd,                     CSR_BT_PHDC_MGR_ST_REGISTERING },
  { PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_RES,            PHDC_MGR_AC_RegisteringSPhdcConfigureEndpointRes,           CSR_BT_PHDC_MGR_ST_REGISTERING },
  { PHDC_MGR_EV_HDP_REGISTER_CFM,                       PHDC_MGR_AC_RegisteringSHdpRegisterCfm,                     CSR_BT_PHDC_MGR_ST_ACTIVATING },
  /* UNREGISTERING */
  { PHDC_MGR_EV_HDP_UNREGISTER_CFM,                     PHDC_MGR_AC_UnregisteringSHdpUnregisterCfm,                 CSR_BT_PHDC_MGR_ST_IDLE },
  /* ACTIVATING */
  { PHDC_MGR_EV_HDP_ACTIVATE_CFM,                       PHDC_MGR_AC_ActivatingSHdpActivateCfm,                      CSR_BT_PHDC_MGR_ST_ACTIVATED },
  /* DEACTIVATING */
  { PHDC_MGR_EV_HDP_DEACTIVATE_CFM,                     PHDC_MGR_AC_DeactivatingSHdpDeactivateCfm,                  CSR_BT_PHDC_MGR_ST_UNREGISTERING },
  { PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM,   PHDC_MGR_AC_DeactivatingSHdpDisconnectAssociateChannelCfm,  CSR_BT_PHDC_MGR_ST_DEACTIVATING },
  { PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,   PHDC_MGR_AC_NULL,                                           CSR_BT_PHDC_MGR_ST_DEACTIVATING },
  /* ACTIVATED */
  { PHDC_MGR_EV_PHDC_UNREGISTER_REQ,                    PHDC_MGR_AC_AnyStatePhdcUnregisterReq,                      CSR_BT_PHDC_MGR_ST_DEACTIVATING },
  { PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_IND,                 PHDC_MGR_AC_AnyStateHdpCtrlGetCapabInd,                     CSR_BT_PHDC_MGR_ST_ACTIVATED },
  { PHDC_MGR_EV_PHDC_GET_DEVICE_CAPAB_REQ,              PHDC_MGR_AC_AnyStatePhdcGetDeviceCapabReq,                  CSR_BT_PHDC_MGR_ST_ACTIVATED },
  { PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_CFM,                 PHDC_MGR_AC_AnyStateHdpCtrlGetCapabCfm,                     CSR_BT_PHDC_MGR_ST_ACTIVATED },
  { PHDC_MGR_EV_HDP_RESUME_IND,                         PHDC_MGR_AC_AnyStateHdpResumeInd,                           CSR_BT_PHDC_MGR_ST_ACTIVATED }
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_phdc_mgr_states[CSR_BT_PHDC_MGR_ST_ST_MAX+1] = {
    { &csr_bt_phdc_mgr_transitions[0] },
    { &csr_bt_phdc_mgr_transitions[2] },
    { &csr_bt_phdc_mgr_transitions[6] },
    { &csr_bt_phdc_mgr_transitions[7] },
    { &csr_bt_phdc_mgr_transitions[8] },
    { &csr_bt_phdc_mgr_transitions[11] },
    { &csr_bt_phdc_mgr_transitions[16] },
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, FSM_LOGGING) */
/* State names */
const char *const csr_bt_phdc_mgr_state_names[] =
{
    "CSR_BT_PHDC_MGR_ST_IDLE",
    "CSR_BT_PHDC_MGR_ST_REGISTERING",
    "CSR_BT_PHDC_MGR_ST_UNREGISTERING",
    "CSR_BT_PHDC_MGR_ST_ACTIVATING",
    "CSR_BT_PHDC_MGR_ST_DEACTIVATING",
    "CSR_BT_PHDC_MGR_ST_ACTIVATED",
};
#define CSR_BT_PHDC_MGR_STATE_NAMES_PTR (csr_bt_phdc_mgr_state_names)

/* Event names */
const char *const csr_bt_phdc_mgr_event_names[] =
{
    "PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_REQ",
    "PHDC_MGR_EV_PHDC_UNREGISTER_REQ",
    "PHDC_MGR_EV_HDP_REGISTER_IND",
    "PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_RES",
    "PHDC_MGR_EV_HDP_REGISTER_CFM",
    "PHDC_MGR_EV_HDP_UNREGISTER_CFM",
    "PHDC_MGR_EV_HDP_ACTIVATE_CFM",
    "PHDC_MGR_EV_HDP_DEACTIVATE_CFM",
    "PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM",
    "PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_IND",
    "PHDC_MGR_EV_PHDC_GET_DEVICE_CAPAB_REQ",
    "PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_CFM",
    "PHDC_MGR_EV_HDP_RESUME_IND",
};
#define CSR_BT_PHDC_MGR_EVENT_NAMES_PTR (csr_bt_phdc_mgr_event_names)

/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, FSM_LOGGING) */
#else
#define CSR_BT_PHDC_MGR_STATE_NAMES_PTR (NULL)
#define CSR_BT_PHDC_MGR_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_mgr_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_phdc_mgr_states,
    csr_bt_phdc_mgr_action_fns
    FSM_LOG_INFO("CSR_BT_PHDC_MGR",
    CSR_BT_PHDC_MGR_STATE_NAMES_PTR,
    CSR_BT_PHDC_MGR_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, FSM_DEFINITION) */

