/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_mgr_device_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_phdc_mgr_device_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_phdc_mgr_device_action_fns[] =
{
    CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpAcceptConnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_DisconnectedSPhdcAcceptBtLinkRes,
    CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpConnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_DisconnectedSPhdcSetupBtLinkReq,
    CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpDisconnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_ConnectingSHdpConnectAssociateChannelCfm,
    CsrBtPhdcMgrDeviceFsm_DisconnectingSHdpDisconnectAssociateChannelCfm,
    CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDataInd,
    CsrBtPhdcMgrDeviceFsm_UnassociatedSPhdcAcceptAssociateRes,
    CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_UnassociatedSIntTimedOutInactivity,
    CsrBtPhdcMgrDeviceFsm_AnyStateIntTimedOutReleaseReq,
    CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDisconnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_ConfigWaitingSHdpDataInd,
    CsrBtPhdcMgrDeviceFsm_ConfigWaitingSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_ConfigWaitingSIntTimedOutConfig,
    CsrBtPhdcMgrDeviceFsm_AnyStatePhdcDisassociateReq,
    CsrBtPhdcMgrDeviceFsm_ConfigCheckingSHdpDataInd,
    CsrBtPhdcMgrDeviceFsm_ConfigCheckingSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_ConfigCheckingSIntTimedOutGet,
    CsrBtPhdcMgrDeviceFsm_OperatingSHdpDataInd,
    CsrBtPhdcMgrDeviceFsm_OperatingSHdpDisconnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_AwaitingCfmSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_AbortCfmSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_ReleaseCfmSHdpDataCfm,
    CsrBtPhdcMgrDeviceFsm_DisassociatingSHdpDataInd,
    CsrBtPhdcMgrDeviceFsm_DisassociatingSHdpDisconnectAssociateChannelInd,
    CsrBtPhdcMgrDeviceFsm_DisassociatingSIntTimedOutInactivity,
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_phdc_mgr_device_transitions[] = {
  /* DISCONNECTED */
  { PHDC_MGR_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND,   PHDC_MGR_DEVICE_AC_DisconnectedSHdpAcceptConnectAssociateChannelInd,  CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES,                    PHDC_MGR_DEVICE_AC_DisconnectedSPhdcAcceptBtLinkRes,                  CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND,          PHDC_MGR_DEVICE_AC_DisconnectedSHdpConnectAssociateChannelInd,        CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_PHDC_SETUP_BT_LINK_REQ,                     PHDC_MGR_DEVICE_AC_DisconnectedSPhdcSetupBtLinkReq,                   CSR_BT_PHDC_MGR_DEVICE_ST_CONNECTING },
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_DisconnectedSHdpDisconnectAssociateChannelInd,     CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  /* CONNECTING */
  { PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM,          PHDC_MGR_DEVICE_AC_ConnectingSHdpConnectAssociateChannelCfm,          CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  /* DISCONNECTING */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTING },
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM,       PHDC_MGR_DEVICE_AC_DisconnectingSHdpDisconnectAssociateChannelCfm,    CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  /* UNASSOCIATED */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_UnassociatedSHdpDisconnectAssociateChannelInd,     CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_IND,                               PHDC_MGR_DEVICE_AC_UnassociatedSHdpDataInd,                           CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_ASSOCIATE_RES,                  PHDC_MGR_DEVICE_AC_UnassociatedSPhdcAcceptAssociateRes,               CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_UnassociatedSHdpDataCfm,                           CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_WAITING },
  { PHDC_MGR_DEVICE_EV_INT_KNOWN_CONFIG,                           PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_INT_TO_INACTIVITY,                          PHDC_MGR_DEVICE_AC_UnassociatedSIntTimedOutInactivity,                CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTING },
  { PHDC_MGR_DEVICE_EV_INT_TO_RLRQ,                                PHDC_MGR_DEVICE_AC_AnyStateIntTimedOutReleaseReq,                     CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_IND,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM },
  { PHDC_MGR_DEVICE_EV_INT_ABORT_IND,                              PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT,                                  PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_AWAITING_CFM,                           PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM },
  /* CONFIG_WAITING */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_UnassociatedSHdpDisconnectAssociateChannelInd,     CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_IND,                               PHDC_MGR_DEVICE_AC_ConfigWaitingSHdpDataInd,                          CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_WAITING },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_ConfigWaitingSHdpDataCfm,                          CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_CHECKING },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_IND,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_RELEASE_CFM },
  { PHDC_MGR_DEVICE_EV_INT_ABORT_IND,                              PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT,                                  PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_TO_CONFIG,                              PHDC_MGR_DEVICE_AC_ConfigWaitingSIntTimedOutConfig,                   CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM },
  { PHDC_MGR_DEVICE_EV_INT_ACCEPT_CONFIG,                          PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_INT_UNKNOWN_CONFIG,                         PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_DATA_ERROR,                             PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ,                      PHDC_MGR_DEVICE_AC_AnyStatePhdcDisassociateReq,                       CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  /* CONFIG_CHECKING */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_UnassociatedSHdpDisconnectAssociateChannelInd,     CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_IND,                               PHDC_MGR_DEVICE_AC_ConfigCheckingSHdpDataInd,                         CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_CHECKING },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_ConfigCheckingSHdpDataCfm,                         CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_INT_TO_RLRQ,                                PHDC_MGR_DEVICE_AC_AnyStateIntTimedOutReleaseReq,                     CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_IND,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT_IND,                              PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT,                                  PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_DATA_ERROR,                             PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_CHECKING },
  { PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ,                      PHDC_MGR_DEVICE_AC_AnyStatePhdcDisassociateReq,                       CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  { PHDC_MGR_DEVICE_EV_INT_TO_GET,                                 PHDC_MGR_DEVICE_AC_ConfigCheckingSIntTimedOutGet,                     CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE,                                PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_RELEASE_CFM },
  /* OPERATING */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_OperatingSHdpDisconnectAssociateChannelInd,        CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_IND,                               PHDC_MGR_DEVICE_AC_OperatingSHdpDataInd,                              CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_INT_TO_INACTIVITY,                          PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_IND,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_RELEASE_CFM },
  { PHDC_MGR_DEVICE_EV_INT_ABORT_IND,                              PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT,                                  PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_DATA_ERROR,                             PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING },
  { PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ,                      PHDC_MGR_DEVICE_AC_AnyStatePhdcDisassociateReq,                       CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  /* AWAITING_CFM */
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_AwaitingCfmSHdpDataCfm,                            CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  /* ABORT_CFM */
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_AbortCfmSHdpDataCfm,                               CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  /* RELEASE_CFM */
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_ReleaseCfmSHdpDataCfm,                             CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_TO_RLRQ,                                PHDC_MGR_DEVICE_AC_AnyStateIntTimedOutReleaseReq,                     CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  /* DISASSOCIATING */
  { PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND,       PHDC_MGR_DEVICE_AC_DisassociatingSHdpDisconnectAssociateChannelInd,   CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_IND,                               PHDC_MGR_DEVICE_AC_DisassociatingSHdpDataInd,                         CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  { PHDC_MGR_DEVICE_EV_HDP_DATA_CFM,                               PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  { PHDC_MGR_DEVICE_EV_INT_TO_INACTIVITY,                          PHDC_MGR_DEVICE_AC_DisassociatingSIntTimedOutInactivity,              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_TO_RLRQ,                                PHDC_MGR_DEVICE_AC_AnyStateIntTimedOutReleaseReq,                     CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_IND,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  { PHDC_MGR_DEVICE_EV_INT_ABORT_IND,                              PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED },
  { PHDC_MGR_DEVICE_EV_INT_ABORT,                                  PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM },
  { PHDC_MGR_DEVICE_EV_INT_DATA_ERROR,                             PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM },
  { PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ,                      PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING },
  { PHDC_MGR_DEVICE_EV_INT_RELEASE_CFM,                            PHDC_MGR_DEVICE_AC_NULL,                                              CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED }
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_phdc_mgr_device_states[CSR_BT_PHDC_MGR_DEVICE_ST_ST_MAX+1] = {
    { &csr_bt_phdc_mgr_device_transitions[0] },
    { &csr_bt_phdc_mgr_device_transitions[5] },
    { &csr_bt_phdc_mgr_device_transitions[6] },
    { &csr_bt_phdc_mgr_device_transitions[8] },
    { &csr_bt_phdc_mgr_device_transitions[19] },
    { &csr_bt_phdc_mgr_device_transitions[30] },
    { &csr_bt_phdc_mgr_device_transitions[41] },
    { &csr_bt_phdc_mgr_device_transitions[50] },
    { &csr_bt_phdc_mgr_device_transitions[51] },
    { &csr_bt_phdc_mgr_device_transitions[52] },
    { &csr_bt_phdc_mgr_device_transitions[54] },
    { &csr_bt_phdc_mgr_device_transitions[65] },
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_LOGGING) */
/* State names */
const char *const csr_bt_phdc_mgr_device_state_names[] =
{
    "CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED",
    "CSR_BT_PHDC_MGR_DEVICE_ST_CONNECTING",
    "CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTING",
    "CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED",
    "CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_WAITING",
    "CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_CHECKING",
    "CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING",
    "CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM",
    "CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM",
    "CSR_BT_PHDC_MGR_DEVICE_ST_RELEASE_CFM",
    "CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING",
};
#define CSR_BT_PHDC_MGR_DEVICE_STATE_NAMES_PTR (csr_bt_phdc_mgr_device_state_names)

/* Event names */
const char *const csr_bt_phdc_mgr_device_event_names[] =
{
    "PHDC_MGR_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES",
    "PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_MGR_DEVICE_EV_PHDC_SETUP_BT_LINK_REQ",
    "PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND",
    "PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM",
    "PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM",
    "PHDC_MGR_DEVICE_EV_HDP_DATA_IND",
    "PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_ASSOCIATE_RES",
    "PHDC_MGR_DEVICE_EV_HDP_DATA_CFM",
    "PHDC_MGR_DEVICE_EV_INT_KNOWN_CONFIG",
    "PHDC_MGR_DEVICE_EV_INT_TO_INACTIVITY",
    "PHDC_MGR_DEVICE_EV_INT_TO_RLRQ",
    "PHDC_MGR_DEVICE_EV_INT_RELEASE_IND",
    "PHDC_MGR_DEVICE_EV_INT_ABORT_IND",
    "PHDC_MGR_DEVICE_EV_INT_ABORT",
    "PHDC_MGR_DEVICE_EV_INT_AWAITING_CFM",
    "PHDC_MGR_DEVICE_EV_INT_TO_CONFIG",
    "PHDC_MGR_DEVICE_EV_INT_ACCEPT_CONFIG",
    "PHDC_MGR_DEVICE_EV_INT_UNKNOWN_CONFIG",
    "PHDC_MGR_DEVICE_EV_INT_DATA_ERROR",
    "PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ",
    "PHDC_MGR_DEVICE_EV_INT_TO_GET",
    "PHDC_MGR_DEVICE_EV_INT_RELEASE",
    "PHDC_MGR_DEVICE_EV_INT_RELEASE_CFM",
};
#define CSR_BT_PHDC_MGR_DEVICE_EVENT_NAMES_PTR (csr_bt_phdc_mgr_device_event_names)

/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_LOGGING) */
#else
#define CSR_BT_PHDC_MGR_DEVICE_STATE_NAMES_PTR (NULL)
#define CSR_BT_PHDC_MGR_DEVICE_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_mgr_device_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_phdc_mgr_device_states,
    csr_bt_phdc_mgr_device_action_fns
    FSM_LOG_INFO("CSR_BT_PHDC_MGR_DEVICE",
    CSR_BT_PHDC_MGR_DEVICE_STATE_NAMES_PTR,
    CSR_BT_PHDC_MGR_DEVICE_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_DEFINITION) */

