#ifndef _CSR_BT_PHDC_MGR_GENFSM_H
#define _CSR_BT_PHDC_MGR_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_mgr_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_IdleSPhdcConfigureEndpointReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_AnyStatePhdcUnregisterReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_RegisteringSHdpRegisterInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_RegisteringSPhdcConfigureEndpointRes);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_RegisteringSHdpRegisterCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_UnregisteringSHdpUnregisterCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_ActivatingSHdpActivateCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_DeactivatingSHdpDeactivateCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_DeactivatingSHdpDisconnectAssociateChannelCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_AnyStateHdpCtrlGetCapabInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_AnyStatePhdcGetDeviceCapabReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_AnyStateHdpCtrlGetCapabCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrFsm_AnyStateHdpResumeInd);
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, STATE_DECLARATIONS) */
#define CSR_BT_PHDC_MGR_ST_ST_MAX 6
#define CSR_BT_PHDC_MGR_ST_IDLE          ((fsm_state_t) 0)
#define CSR_BT_PHDC_MGR_ST_REGISTERING   ((fsm_state_t) 1)
#define CSR_BT_PHDC_MGR_ST_UNREGISTERING ((fsm_state_t) 2)
#define CSR_BT_PHDC_MGR_ST_ACTIVATING    ((fsm_state_t) 3)
#define CSR_BT_PHDC_MGR_ST_DEACTIVATING  ((fsm_state_t) 4)
#define CSR_BT_PHDC_MGR_ST_ACTIVATED     ((fsm_state_t) 5)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, EVENT_DECLARATIONS) */
#define PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_REQ          ((fsm_event_t) 0)
#define PHDC_MGR_EV_PHDC_UNREGISTER_REQ                  ((fsm_event_t) 1)
#define PHDC_MGR_EV_HDP_REGISTER_IND                     ((fsm_event_t) 2)
#define PHDC_MGR_EV_PHDC_CONFIGURE_ENDPOINT_RES          ((fsm_event_t) 3)
#define PHDC_MGR_EV_HDP_REGISTER_CFM                     ((fsm_event_t) 4)
#define PHDC_MGR_EV_HDP_UNREGISTER_CFM                   ((fsm_event_t) 5)
#define PHDC_MGR_EV_HDP_ACTIVATE_CFM                     ((fsm_event_t) 6)
#define PHDC_MGR_EV_HDP_DEACTIVATE_CFM                   ((fsm_event_t) 7)
#define PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM ((fsm_event_t) 8)
#define PHDC_MGR_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND ((fsm_event_t) 9)
#define PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_IND               ((fsm_event_t) 10)
#define PHDC_MGR_EV_PHDC_GET_DEVICE_CAPAB_REQ            ((fsm_event_t) 11)
#define PHDC_MGR_EV_HDP_CTRL_GET_CAPAB_CFM               ((fsm_event_t) 12)
#define PHDC_MGR_EV_HDP_RESUME_IND                       ((fsm_event_t) 13)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_INDEX) */
#define PHDC_MGR_AC_MAX 13
#define PHDC_MGR_AC_IdleSPhdcConfigureEndpointReq                 ((fsm_action_t) 0)
#define PHDC_MGR_AC_AnyStatePhdcUnregisterReq                     ((fsm_action_t) 1)
#define PHDC_MGR_AC_RegisteringSHdpRegisterInd                    ((fsm_action_t) 2)
#define PHDC_MGR_AC_RegisteringSPhdcConfigureEndpointRes          ((fsm_action_t) 3)
#define PHDC_MGR_AC_RegisteringSHdpRegisterCfm                    ((fsm_action_t) 4)
#define PHDC_MGR_AC_UnregisteringSHdpUnregisterCfm                ((fsm_action_t) 5)
#define PHDC_MGR_AC_ActivatingSHdpActivateCfm                     ((fsm_action_t) 6)
#define PHDC_MGR_AC_DeactivatingSHdpDeactivateCfm                 ((fsm_action_t) 7)
#define PHDC_MGR_AC_DeactivatingSHdpDisconnectAssociateChannelCfm ((fsm_action_t) 8)
#define PHDC_MGR_AC_AnyStateHdpCtrlGetCapabInd                    ((fsm_action_t) 9)
#define PHDC_MGR_AC_AnyStatePhdcGetDeviceCapabReq                 ((fsm_action_t) 10)
#define PHDC_MGR_AC_AnyStateHdpCtrlGetCapabCfm                    ((fsm_action_t) 11)
#define PHDC_MGR_AC_AnyStateHdpResumeInd                          ((fsm_action_t) 12)
#define PHDC_MGR_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_mgr_fsm;
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_PHDC_MGR_GENFSM_H */

