#ifndef _CSR_BT_PHDC_MGR_DEVICE_GENFSM_H
#define _CSR_BT_PHDC_MGR_DEVICE_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_phdc_mgr_device_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpAcceptConnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectedSPhdcAcceptBtLinkRes);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpConnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectedSPhdcSetupBtLinkReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectedSHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConnectingSHdpConnectAssociateChannelCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisconnectingSHdpDisconnectAssociateChannelCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_UnassociatedSPhdcAcceptAssociateRes);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_UnassociatedSIntTimedOutInactivity);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_AnyStateIntTimedOutReleaseReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_UnassociatedSHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigWaitingSHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigWaitingSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigWaitingSIntTimedOutConfig);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_AnyStatePhdcDisassociateReq);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigCheckingSHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigCheckingSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ConfigCheckingSIntTimedOutGet);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_OperatingSHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_OperatingSHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_AwaitingCfmSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_AbortCfmSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_ReleaseCfmSHdpDataCfm);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisassociatingSHdpDataInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisassociatingSHdpDisconnectAssociateChannelInd);
extern FSM_ACTION_FN(CsrBtPhdcMgrDeviceFsm_DisassociatingSIntTimedOutInactivity);
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_DECLARATIONS) */
#define CSR_BT_PHDC_MGR_DEVICE_ST_ST_MAX 11
#define CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTED    ((fsm_state_t) 0)
#define CSR_BT_PHDC_MGR_DEVICE_ST_CONNECTING      ((fsm_state_t) 1)
#define CSR_BT_PHDC_MGR_DEVICE_ST_DISCONNECTING   ((fsm_state_t) 2)
#define CSR_BT_PHDC_MGR_DEVICE_ST_UNASSOCIATED    ((fsm_state_t) 3)
#define CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_WAITING  ((fsm_state_t) 4)
#define CSR_BT_PHDC_MGR_DEVICE_ST_CONFIG_CHECKING ((fsm_state_t) 5)
#define CSR_BT_PHDC_MGR_DEVICE_ST_OPERATING       ((fsm_state_t) 6)
#define CSR_BT_PHDC_MGR_DEVICE_ST_AWAITING_CFM    ((fsm_state_t) 7)
#define CSR_BT_PHDC_MGR_DEVICE_ST_ABORT_CFM       ((fsm_state_t) 8)
#define CSR_BT_PHDC_MGR_DEVICE_ST_RELEASE_CFM     ((fsm_state_t) 9)
#define CSR_BT_PHDC_MGR_DEVICE_ST_DISASSOCIATING  ((fsm_state_t) 10)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, EVENT_DECLARATIONS) */
#define PHDC_MGR_DEVICE_EV_HDP_ACCEPT_CONNECT_ASSOCIATE_CHANNEL_IND ((fsm_event_t) 0)
#define PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_BT_LINK_RES                  ((fsm_event_t) 1)
#define PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_IND        ((fsm_event_t) 2)
#define PHDC_MGR_DEVICE_EV_PHDC_SETUP_BT_LINK_REQ                   ((fsm_event_t) 3)
#define PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_IND     ((fsm_event_t) 4)
#define PHDC_MGR_DEVICE_EV_HDP_CONNECT_ASSOCIATE_CHANNEL_CFM        ((fsm_event_t) 5)
#define PHDC_MGR_DEVICE_EV_HDP_DISCONNECT_ASSOCIATE_CHANNEL_CFM     ((fsm_event_t) 6)
#define PHDC_MGR_DEVICE_EV_HDP_DATA_IND                             ((fsm_event_t) 7)
#define PHDC_MGR_DEVICE_EV_PHDC_ACCEPT_ASSOCIATE_RES                ((fsm_event_t) 8)
#define PHDC_MGR_DEVICE_EV_HDP_DATA_CFM                             ((fsm_event_t) 9)
#define PHDC_MGR_DEVICE_EV_INT_KNOWN_CONFIG                         ((fsm_event_t) 10)
#define PHDC_MGR_DEVICE_EV_INT_TO_INACTIVITY                        ((fsm_event_t) 11)
#define PHDC_MGR_DEVICE_EV_INT_TO_RLRQ                              ((fsm_event_t) 12)
#define PHDC_MGR_DEVICE_EV_INT_RELEASE_IND                          ((fsm_event_t) 13)
#define PHDC_MGR_DEVICE_EV_INT_ABORT_IND                            ((fsm_event_t) 14)
#define PHDC_MGR_DEVICE_EV_INT_ABORT                                ((fsm_event_t) 15)
#define PHDC_MGR_DEVICE_EV_INT_AWAITING_CFM                         ((fsm_event_t) 16)
#define PHDC_MGR_DEVICE_EV_INT_TO_CONFIG                            ((fsm_event_t) 17)
#define PHDC_MGR_DEVICE_EV_INT_ACCEPT_CONFIG                        ((fsm_event_t) 18)
#define PHDC_MGR_DEVICE_EV_INT_UNKNOWN_CONFIG                       ((fsm_event_t) 19)
#define PHDC_MGR_DEVICE_EV_INT_DATA_ERROR                           ((fsm_event_t) 20)
#define PHDC_MGR_DEVICE_EV_PHDC_DISASSOCIATE_REQ                    ((fsm_event_t) 21)
#define PHDC_MGR_DEVICE_EV_INT_TO_GET                               ((fsm_event_t) 22)
#define PHDC_MGR_DEVICE_EV_INT_RELEASE                              ((fsm_event_t) 23)
#define PHDC_MGR_DEVICE_EV_INT_RELEASE_CFM                          ((fsm_event_t) 24)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_INDEX) */
#define PHDC_MGR_DEVICE_AC_MAX 28
#define PHDC_MGR_DEVICE_AC_DisconnectedSHdpAcceptConnectAssociateChannelInd ((fsm_action_t) 0)
#define PHDC_MGR_DEVICE_AC_DisconnectedSPhdcAcceptBtLinkRes                 ((fsm_action_t) 1)
#define PHDC_MGR_DEVICE_AC_DisconnectedSHdpConnectAssociateChannelInd       ((fsm_action_t) 2)
#define PHDC_MGR_DEVICE_AC_DisconnectedSPhdcSetupBtLinkReq                  ((fsm_action_t) 3)
#define PHDC_MGR_DEVICE_AC_DisconnectedSHdpDisconnectAssociateChannelInd    ((fsm_action_t) 4)
#define PHDC_MGR_DEVICE_AC_ConnectingSHdpConnectAssociateChannelCfm         ((fsm_action_t) 5)
#define PHDC_MGR_DEVICE_AC_DisconnectingSHdpDisconnectAssociateChannelCfm   ((fsm_action_t) 6)
#define PHDC_MGR_DEVICE_AC_UnassociatedSHdpDataInd                          ((fsm_action_t) 7)
#define PHDC_MGR_DEVICE_AC_UnassociatedSPhdcAcceptAssociateRes              ((fsm_action_t) 8)
#define PHDC_MGR_DEVICE_AC_UnassociatedSHdpDataCfm                          ((fsm_action_t) 9)
#define PHDC_MGR_DEVICE_AC_UnassociatedSIntTimedOutInactivity               ((fsm_action_t) 10)
#define PHDC_MGR_DEVICE_AC_AnyStateIntTimedOutReleaseReq                    ((fsm_action_t) 11)
#define PHDC_MGR_DEVICE_AC_UnassociatedSHdpDisconnectAssociateChannelInd    ((fsm_action_t) 12)
#define PHDC_MGR_DEVICE_AC_ConfigWaitingSHdpDataInd                         ((fsm_action_t) 13)
#define PHDC_MGR_DEVICE_AC_ConfigWaitingSHdpDataCfm                         ((fsm_action_t) 14)
#define PHDC_MGR_DEVICE_AC_ConfigWaitingSIntTimedOutConfig                  ((fsm_action_t) 15)
#define PHDC_MGR_DEVICE_AC_AnyStatePhdcDisassociateReq                      ((fsm_action_t) 16)
#define PHDC_MGR_DEVICE_AC_ConfigCheckingSHdpDataInd                        ((fsm_action_t) 17)
#define PHDC_MGR_DEVICE_AC_ConfigCheckingSHdpDataCfm                        ((fsm_action_t) 18)
#define PHDC_MGR_DEVICE_AC_ConfigCheckingSIntTimedOutGet                    ((fsm_action_t) 19)
#define PHDC_MGR_DEVICE_AC_OperatingSHdpDataInd                             ((fsm_action_t) 20)
#define PHDC_MGR_DEVICE_AC_OperatingSHdpDisconnectAssociateChannelInd       ((fsm_action_t) 21)
#define PHDC_MGR_DEVICE_AC_AwaitingCfmSHdpDataCfm                           ((fsm_action_t) 22)
#define PHDC_MGR_DEVICE_AC_AbortCfmSHdpDataCfm                              ((fsm_action_t) 23)
#define PHDC_MGR_DEVICE_AC_ReleaseCfmSHdpDataCfm                            ((fsm_action_t) 24)
#define PHDC_MGR_DEVICE_AC_DisassociatingSHdpDataInd                        ((fsm_action_t) 25)
#define PHDC_MGR_DEVICE_AC_DisassociatingSHdpDisconnectAssociateChannelInd  ((fsm_action_t) 26)
#define PHDC_MGR_DEVICE_AC_DisassociatingSIntTimedOutInactivity             ((fsm_action_t) 27)
#define PHDC_MGR_DEVICE_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_phdc_mgr_device_fsm;
/*}}__FSM_END_MARKER(CSR_BT_PHDC_MGR_DEVICE, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_PHDC_MGR_DEVICE_GENFSM_H */

