#ifndef _CSR_BT_AMPM_LOGICAL_GENFSM_H
#define _CSR_BT_AMPM_LOGICAL_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_logical_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmCreateLogicalLink);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmDisconnectUnstartedLink);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmDeleteReq);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkEstablished);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmEstablishmentFailed);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmPhyLinkDisconnectInd);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmCancelLogicalLink);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmCancelFailed);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmModifyFlowspecReq);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmDisconnectLogicalLink);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkFailure);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkFailureLsto);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmModifySuccess);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmModifyFailed);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkDisconnected);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkDisconnectFailed);
extern FSM_ACTION_FN(CsrBtAmpmLogicalFsmLinkDisconnectTimeout);
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, STATE_DECLARATIONS) */
#define AMPM_LOGICAL_ST_ST_MAX 6
#define AMPM_LOGICAL_ST_NULL               ((fsm_state_t) 0)
#define AMPM_LOGICAL_ST_CREATING_LINK      ((fsm_state_t) 1)
#define AMPM_LOGICAL_ST_LINK_ESTABLISHED   ((fsm_state_t) 2)
#define AMPM_LOGICAL_ST_MODIFYING_FLOWSPEC ((fsm_state_t) 3)
#define AMPM_LOGICAL_ST_DISCONNECTING      ((fsm_state_t) 4)
#define AMPM_LOGICAL_ST_CANCELLING         ((fsm_state_t) 5)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, EVENT_DECLARATIONS) */
#define AMPM_LOGICAL_EV_CREATE_REQ            ((fsm_event_t) 0)
#define AMPM_LOGICAL_EV_DISCONNECT_REQ        ((fsm_event_t) 1)
#define AMPM_LOGICAL_EV_PHY_DISCONNECT        ((fsm_event_t) 2)
#define AMPM_LOGICAL_EV_DELETE_REQ            ((fsm_event_t) 3)
#define AMPM_LOGICAL_EV_COMPLETE_SUCCESS      ((fsm_event_t) 4)
#define AMPM_LOGICAL_EV_COMPLETE_FAILURE      ((fsm_event_t) 5)
#define AMPM_LOGICAL_EV_COMMAND_FAILURE       ((fsm_event_t) 6)
#define AMPM_LOGICAL_EV_RESPONSE_TIMEOUT      ((fsm_event_t) 7)
#define AMPM_LOGICAL_EV_CANCEL_FAILURE        ((fsm_event_t) 8)
#define AMPM_LOGICAL_EV_MODIFIED_FLOWSPEC_REQ ((fsm_event_t) 9)
#define AMPM_LOGICAL_EV_DISCONNECT_SUCCESS    ((fsm_event_t) 10)
#define AMPM_LOGICAL_EV_DISCONNECT_LSTO       ((fsm_event_t) 11)
#define AMPM_LOGICAL_EV_FLOWSPEC_SUCCESS      ((fsm_event_t) 12)
#define AMPM_LOGICAL_EV_FLOWSPEC_FAILURE      ((fsm_event_t) 13)
#define AMPM_LOGICAL_EV_DISCONNECT_FAILURE    ((fsm_event_t) 14)
#define AMPM_LOGICAL_EV_CANCEL_SUCCESS        ((fsm_event_t) 15)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_INDEX) */
#define AMPM_LOGICAL_AC_MAX 17
#define AMPM_LOGICAL_AC_CreateLogicalLink       ((fsm_action_t) 0)
#define AMPM_LOGICAL_AC_DisconnectUnstartedLink ((fsm_action_t) 1)
#define AMPM_LOGICAL_AC_DeleteReq               ((fsm_action_t) 2)
#define AMPM_LOGICAL_AC_LinkEstablished         ((fsm_action_t) 3)
#define AMPM_LOGICAL_AC_EstablishmentFailed     ((fsm_action_t) 4)
#define AMPM_LOGICAL_AC_PhyLinkDisconnectInd    ((fsm_action_t) 5)
#define AMPM_LOGICAL_AC_CancelLogicalLink       ((fsm_action_t) 6)
#define AMPM_LOGICAL_AC_CancelFailed            ((fsm_action_t) 7)
#define AMPM_LOGICAL_AC_ModifyFlowspecReq       ((fsm_action_t) 8)
#define AMPM_LOGICAL_AC_DisconnectLogicalLink   ((fsm_action_t) 9)
#define AMPM_LOGICAL_AC_LinkFailure             ((fsm_action_t) 10)
#define AMPM_LOGICAL_AC_LinkFailureLsto         ((fsm_action_t) 11)
#define AMPM_LOGICAL_AC_ModifySuccess           ((fsm_action_t) 12)
#define AMPM_LOGICAL_AC_ModifyFailed            ((fsm_action_t) 13)
#define AMPM_LOGICAL_AC_LinkDisconnected        ((fsm_action_t) 14)
#define AMPM_LOGICAL_AC_LinkDisconnectFailed    ((fsm_action_t) 15)
#define AMPM_LOGICAL_AC_LinkDisconnectTimeout   ((fsm_action_t) 16)
#define AMPM_LOGICAL_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_logical_fsm;
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_AMPM_LOGICAL_GENFSM_H */

