/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_phy_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_ampm_phy_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_ampm_phy_action_fns[] =
{
    CsrBtAmpmPhyFsmSendGetRemoteAmpAssocReq,
    CsrBtAmpmPhyFsmSendHciAcceptPhysicalLink,
    CsrBtAmpmPhyFsmDiscoveryReq,
    CsrBtAmpmPhyFsmSetupFail,
    CsrBtAmpmPhyFsmDeleteReq,
    CsrBtAmpmPhyFsmSendPowerOnInd,
    CsrBtAmpmPhyFsmPowerOnSuccess,
    CsrBtAmpmPhyFsmSendHciCreatePhysicalLink,
    CsrBtAmpmPhyFsmSendHciWriteRemoteAmpAssoc,
    CsrBtAmpmPhyFsmAcceptorStartPhyLinkFail,
    CsrBtAmpmPhyFsmPeerCancellingConnection,
    CsrBtAmpmPhyFsmSetupPalDisconnected,
    CsrBtAmpmPhyFsmAcceptorStartPhyLinkSuccess,
    CsrBtAmpmPhyFsmAcceptorStartPalDisconnected,
    CsrBtAmpmPhyFsmReadLocalAmpAssoc,
    CsrBtAmpmPhyFsmSendAmpCreatePhyLinkReq,
    CsrBtAmpmPhyFsmHciPhyLinkCompletePend,
    CsrBtAmpmPhyFsmPeerDisconnectingLink,
    CsrBtAmpmPhyFsmAmpCreatePhyLinkRspPend,
    CsrBtAmpmPhyFsmConnected,
    CsrBtAmpmPhyFsmAmpCreatePhylinkRespTimeoutInd,
    CsrBtAmpmPhyFsmSetupPeerFailed,
    CsrBtAmpmPhyFsmLinkDropLsto,
    CsrBtAmpmPhyFsmConnectReqWhenConnected,
    CsrBtAmpmPhyFsmPeerDisconnectingEstablishedLink,
    CsrBtAmpmPhyFsmAmpmDisconnectingEstablishedLink,
    CsrBtAmpmPhyFsmPalDisconnectingEstablishedLink,
    CsrBtAmpmPhyFsmSupervisionTimeout,
    CsrBtAmpmPhyFsmPalDisconnected,
    CsrBtAmpmPhyFsmPeerRspToDisconnect,
    CsrBtAmpmPhyFsmPeerDisconnected,
    CsrBtAmpmPhyFsmPeerDisconnectReq,
    CsrBtAmpmPhyFsmDisconnectTimeoutInd,
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_ampm_phy_transitions[] = {
  /* NULL */
  { AMPM_PHY_EV_CONNECT_REQ,                      AMPM_PHY_AC_SendGetRemoteAmpAssocReq,          AMPM_PHY_ST_WAIT_REMOTE_ASSOC },
  { AMPM_PHY_EV_CREATE_PHYSICAL_REQ,              AMPM_PHY_AC_SendHciAcceptPhysicalLink,         AMPM_PHY_ST_ACPT_WAIT_PHY_LINK },
  { AMPM_PHY_EV_DISCOVERY_REQ,                    AMPM_PHY_AC_DiscoveryReq,                      AMPM_PHY_ST_WAIT_AMP_DISCOVERY },
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_POWER_ON_IND,                     AMPM_PHY_AC_SendPowerOnInd,                    AMPM_PHY_ST_WAIT_POWER_ON },
  /* WAIT_POWER_ON */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_POWER_ON_SUCCESS,                 AMPM_PHY_AC_PowerOnSuccess,                    AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_POWER_ON_FAIL,                    AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  /* WAIT_AMP_DISCOVERY */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_DISCOVERY_FAILURE,                AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_DISCOVERY_SUCCESS,                AMPM_PHY_AC_SendGetRemoteAmpAssocReq,          AMPM_PHY_ST_WAIT_REMOTE_ASSOC },
  /* WAIT_REMOTE_ASSOC */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_COMMAND_REJECT,               AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_ASSOC_RESPONSE_FAILURE,           AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_ASSOC_RESPONSE_SUCCESS,           AMPM_PHY_AC_SendHciCreatePhysicalLink,         AMPM_PHY_ST_INIT_WAIT_PHY_LINK },
  /* INIT_WAIT_PHY_LINK */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_PHYSICAL_FAILURE,             AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_PHYSICAL_SUCCESS,             AMPM_PHY_AC_SendHciWriteRemoteAmpAssoc,        AMPM_PHY_ST_INIT_WRITE_REMOTE_ASSOC },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  /* ACPT_WAIT_PHY_LINK */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_PHYSICAL_FAILURE,             AMPM_PHY_AC_AcceptorStartPhyLinkFail,          AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_PHYSICAL_SUCCESS,             AMPM_PHY_AC_SendHciWriteRemoteAmpAssoc,        AMPM_PHY_ST_ACPT_WRITE_REMOTE_ASSOC },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_AcceptorStartPhyLinkFail,          AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerCancellingConnection,          AMPM_PHY_ST_DISCONNECT_PENDING },
  /* INIT_WRITE_REMOTE_ASSOC */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_FAILURE,   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_SUCCESS,   AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_HCI_SELECT },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_SetupPalDisconnected,              AMPM_PHY_ST_NULL },
  /* ACPT_WRITE_REMOTE_ASSOC */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_AcceptorStartPhyLinkFail,          AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerCancellingConnection,          AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_FAILURE,   AMPM_PHY_AC_AcceptorStartPhyLinkFail,          AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_SUCCESS,   AMPM_PHY_AC_AcceptorStartPhyLinkSuccess,       AMPM_PHY_ST_LINK_COMPLETE },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_AcceptorStartPalDisconnected,      AMPM_PHY_ST_NULL },
  /* HCI_SELECT */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_CHANNEL_SELECT,               AMPM_PHY_AC_ReadLocalAmpAssoc,                 AMPM_PHY_ST_LOCAL_ASSOC },
  /* LOCAL_ASSOC */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_SetupPalDisconnected,              AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_FAILURE,     AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_SUCCESS,     AMPM_PHY_AC_SendAmpCreatePhyLinkReq,           AMPM_PHY_ST_LINK_COMPLETE },
  /* LINK_COMPLETE */
  { AMPM_PHY_EV_CONNECT_REQ,                      AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_LINK_COMPLETE },
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_COMMAND_REJECT,               AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_AmpCreatePhylinkRespTimeoutInd,    AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerDisconnectingLink,             AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_SetupPalDisconnected,              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_FAIL,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_SUCCESS,      AMPM_PHY_AC_HciPhyLinkCompletePend,            AMPM_PHY_ST_LOCAL_RESPONSE },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_INIT,           AMPM_PHY_AC_AmpCreatePhyLinkRspPend,           AMPM_PHY_ST_PEER_RESPONSE },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_SUCCESS,        AMPM_PHY_AC_Connected,                         AMPM_PHY_ST_READ_LSTO },
  /* LOCAL_RESPONSE */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerDisconnectingLink,             AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_SetupPalDisconnected,              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_INIT,           AMPM_PHY_AC_Connected,                         AMPM_PHY_ST_READ_LSTO },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_SUCCESS,        AMPM_PHY_AC_Connected,                         AMPM_PHY_ST_READ_LSTO },
  /* PEER_RESPONSE */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_COMMAND_REJECT,               AMPM_PHY_AC_SetupPeerFailed,                   AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_FAIL,         AMPM_PHY_AC_SetupPeerFailed,                   AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_SUCCESS,      AMPM_PHY_AC_Connected,                         AMPM_PHY_ST_READ_LSTO },
  { AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE,           AMPM_PHY_AC_SetupPalDisconnected,              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_LSTO,               AMPM_PHY_AC_LinkDropLsto,                      AMPM_PHY_ST_NULL },
  /* CONNECTED */
  { AMPM_PHY_EV_CONNECT_REQ,                      AMPM_PHY_AC_ConnectReqWhenConnected,           AMPM_PHY_ST_CONNECTED },
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_AmpmDisconnectingEstablishedLink,  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerDisconnectingEstablishedLink,  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE,           AMPM_PHY_AC_PalDisconnectingEstablishedLink,   AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_LSTO,               AMPM_PHY_AC_LinkDropLsto,                      AMPM_PHY_ST_NULL },
  /* READ_LSTO */
  { AMPM_PHY_EV_CONNECT_REQ,                      AMPM_PHY_AC_ConnectReqWhenConnected,           AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_AmpmDisconnectingEstablishedLink,  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerDisconnectingEstablishedLink,  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE,           AMPM_PHY_AC_PalDisconnectingEstablishedLink,   AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_LSTO,               AMPM_PHY_AC_LinkDropLsto,                      AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_HCI_READ_LSTO_SUCCESS,            AMPM_PHY_AC_SupervisionTimeout,                AMPM_PHY_ST_CONNECTED },
  { AMPM_PHY_EV_HCI_READ_LSTO_FAILURE,            AMPM_PHY_AC_SetupFail,                         AMPM_PHY_ST_DISCONNECT_PENDING },
  /* DISCONNECT_PENDING */
  { AMPM_PHY_EV_DISCONNECT_REQ,                   AMPM_PHY_AC_PeerDisconnected,                  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_DELETE_REQ,                       AMPM_PHY_AC_DeleteReq,                         AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_COMMAND_REJECT,               AMPM_PHY_AC_PeerDisconnected,                  AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYSICAL_FAILURE,             AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYSICAL_SUCCESS,             AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND,         AMPM_PHY_AC_DisconnectTimeoutInd,              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_DISC_PHYS_REQ,                AMPM_PHY_AC_PeerDisconnectReq,                 AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL,           AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_FAIL,         AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_SUCCESS,      AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_PHYS_COMPLETE_SUCCESS,        AMPM_PHY_AC_NULL,                              AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE,           AMPM_PHY_AC_PalDisconnected,                   AMPM_PHY_ST_DISCONNECT_PENDING },
  { AMPM_PHY_EV_HCI_DISC_PHYS_LSTO,               AMPM_PHY_AC_LinkDropLsto,                      AMPM_PHY_ST_NULL },
  { AMPM_PHY_EV_AMP_DISC_PHYS_RSP,                AMPM_PHY_AC_PeerRspToDisconnect,               AMPM_PHY_ST_DISCONNECT_PENDING }
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_ampm_phy_states[AMPM_PHY_ST_ST_MAX+1] = {
    { &csr_bt_ampm_phy_transitions[0] },
    { &csr_bt_ampm_phy_transitions[6] },
    { &csr_bt_ampm_phy_transitions[10] },
    { &csr_bt_ampm_phy_transitions[14] },
    { &csr_bt_ampm_phy_transitions[19] },
    { &csr_bt_ampm_phy_transitions[24] },
    { &csr_bt_ampm_phy_transitions[30] },
    { &csr_bt_ampm_phy_transitions[36] },
    { &csr_bt_ampm_phy_transitions[43] },
    { &csr_bt_ampm_phy_transitions[48] },
    { &csr_bt_ampm_phy_transitions[54] },
    { &csr_bt_ampm_phy_transitions[65] },
    { &csr_bt_ampm_phy_transitions[72] },
    { &csr_bt_ampm_phy_transitions[79] },
    { &csr_bt_ampm_phy_transitions[85] },
    { &csr_bt_ampm_phy_transitions[93] },
    { &csr_bt_ampm_phy_transitions[107] },
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, FSM_LOGGING) */
/* State names */
const char *const csr_bt_ampm_phy_state_names[] =
{
    "AMPM_PHY_ST_NULL",
    "AMPM_PHY_ST_WAIT_POWER_ON",
    "AMPM_PHY_ST_WAIT_AMP_DISCOVERY",
    "AMPM_PHY_ST_WAIT_REMOTE_ASSOC",
    "AMPM_PHY_ST_INIT_WAIT_PHY_LINK",
    "AMPM_PHY_ST_ACPT_WAIT_PHY_LINK",
    "AMPM_PHY_ST_INIT_WRITE_REMOTE_ASSOC",
    "AMPM_PHY_ST_ACPT_WRITE_REMOTE_ASSOC",
    "AMPM_PHY_ST_HCI_SELECT",
    "AMPM_PHY_ST_LOCAL_ASSOC",
    "AMPM_PHY_ST_LINK_COMPLETE",
    "AMPM_PHY_ST_LOCAL_RESPONSE",
    "AMPM_PHY_ST_PEER_RESPONSE",
    "AMPM_PHY_ST_CONNECTED",
    "AMPM_PHY_ST_READ_LSTO",
    "AMPM_PHY_ST_DISCONNECT_PENDING",
};
#define CSR_BT_AMPM_PHY_STATE_NAMES_PTR (csr_bt_ampm_phy_state_names)

/* Event names */
const char *const csr_bt_ampm_phy_event_names[] =
{
    "AMPM_PHY_EV_CONNECT_REQ",
    "AMPM_PHY_EV_CREATE_PHYSICAL_REQ",
    "AMPM_PHY_EV_DISCOVERY_REQ",
    "AMPM_PHY_EV_DISCONNECT_REQ",
    "AMPM_PHY_EV_DELETE_REQ",
    "AMPM_PHY_EV_POWER_ON_IND",
    "AMPM_PHY_EV_POWER_ON_SUCCESS",
    "AMPM_PHY_EV_POWER_ON_FAIL",
    "AMPM_PHY_EV_DISCOVERY_FAILURE",
    "AMPM_PHY_EV_DISCOVERY_SUCCESS",
    "AMPM_PHY_EV_AMP_COMMAND_REJECT",
    "AMPM_PHY_EV_ASSOC_RESPONSE_FAILURE",
    "AMPM_PHY_EV_ASSOC_RESPONSE_SUCCESS",
    "AMPM_PHY_EV_HCI_PHYSICAL_FAILURE",
    "AMPM_PHY_EV_HCI_PHYSICAL_SUCCESS",
    "AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND",
    "AMPM_PHY_EV_AMP_DISC_PHYS_REQ",
    "AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_FAILURE",
    "AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_SUCCESS",
    "AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL",
    "AMPM_PHY_EV_HCI_CHANNEL_SELECT",
    "AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_FAILURE",
    "AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_SUCCESS",
    "AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_FAIL",
    "AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_SUCCESS",
    "AMPM_PHY_EV_HCI_PHYS_COMPLETE_INIT",
    "AMPM_PHY_EV_HCI_PHYS_COMPLETE_SUCCESS",
    "AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE",
    "AMPM_PHY_EV_HCI_DISC_PHYS_LSTO",
    "AMPM_PHY_EV_HCI_READ_LSTO_SUCCESS",
    "AMPM_PHY_EV_HCI_READ_LSTO_FAILURE",
    "AMPM_PHY_EV_AMP_DISC_PHYS_RSP",
};
#define CSR_BT_AMPM_PHY_EVENT_NAMES_PTR (csr_bt_ampm_phy_event_names)

/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, FSM_LOGGING) */
#else
#define CSR_BT_AMPM_PHY_STATE_NAMES_PTR (NULL)
#define CSR_BT_AMPM_PHY_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_phy_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_ampm_phy_states,
    csr_bt_ampm_phy_action_fns
    FSM_LOG_INFO("CSR_BT_AMPM_PHY",
    CSR_BT_AMPM_PHY_STATE_NAMES_PTR,
    CSR_BT_AMPM_PHY_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, FSM_DEFINITION) */

