#ifndef _CSR_BT_AMPM_PHY_GENFSM_H
#define _CSR_BT_AMPM_PHY_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_phy_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendGetRemoteAmpAssocReq);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendHciAcceptPhysicalLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmDiscoveryReq);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSetupFail);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmDeleteReq);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendPowerOnInd);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPowerOnSuccess);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendHciCreatePhysicalLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendHciWriteRemoteAmpAssoc);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAcceptorStartPhyLinkFail);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerCancellingConnection);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSetupPalDisconnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAcceptorStartPhyLinkSuccess);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAcceptorStartPalDisconnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmReadLocalAmpAssoc);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSendAmpCreatePhyLinkReq);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmHciPhyLinkCompletePend);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerDisconnectingLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAmpCreatePhyLinkRspPend);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmConnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAmpCreatePhylinkRespTimeoutInd);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSetupPeerFailed);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmLinkDropLsto);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmConnectReqWhenConnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerDisconnectingEstablishedLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmAmpmDisconnectingEstablishedLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPalDisconnectingEstablishedLink);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmSupervisionTimeout);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPalDisconnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerRspToDisconnect);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerDisconnected);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmPeerDisconnectReq);
extern FSM_ACTION_FN(CsrBtAmpmPhyFsmDisconnectTimeoutInd);
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, STATE_DECLARATIONS) */
#define AMPM_PHY_ST_ST_MAX 16
#define AMPM_PHY_ST_NULL                    ((fsm_state_t) 0)
#define AMPM_PHY_ST_WAIT_POWER_ON           ((fsm_state_t) 1)
#define AMPM_PHY_ST_WAIT_AMP_DISCOVERY      ((fsm_state_t) 2)
#define AMPM_PHY_ST_WAIT_REMOTE_ASSOC       ((fsm_state_t) 3)
#define AMPM_PHY_ST_INIT_WAIT_PHY_LINK      ((fsm_state_t) 4)
#define AMPM_PHY_ST_ACPT_WAIT_PHY_LINK      ((fsm_state_t) 5)
#define AMPM_PHY_ST_INIT_WRITE_REMOTE_ASSOC ((fsm_state_t) 6)
#define AMPM_PHY_ST_ACPT_WRITE_REMOTE_ASSOC ((fsm_state_t) 7)
#define AMPM_PHY_ST_HCI_SELECT              ((fsm_state_t) 8)
#define AMPM_PHY_ST_LOCAL_ASSOC             ((fsm_state_t) 9)
#define AMPM_PHY_ST_LINK_COMPLETE           ((fsm_state_t) 10)
#define AMPM_PHY_ST_LOCAL_RESPONSE          ((fsm_state_t) 11)
#define AMPM_PHY_ST_PEER_RESPONSE           ((fsm_state_t) 12)
#define AMPM_PHY_ST_CONNECTED               ((fsm_state_t) 13)
#define AMPM_PHY_ST_READ_LSTO               ((fsm_state_t) 14)
#define AMPM_PHY_ST_DISCONNECT_PENDING      ((fsm_state_t) 15)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, EVENT_DECLARATIONS) */
#define AMPM_PHY_EV_CONNECT_REQ                    ((fsm_event_t) 0)
#define AMPM_PHY_EV_CREATE_PHYSICAL_REQ            ((fsm_event_t) 1)
#define AMPM_PHY_EV_DISCOVERY_REQ                  ((fsm_event_t) 2)
#define AMPM_PHY_EV_DISCONNECT_REQ                 ((fsm_event_t) 3)
#define AMPM_PHY_EV_DELETE_REQ                     ((fsm_event_t) 4)
#define AMPM_PHY_EV_POWER_ON_IND                   ((fsm_event_t) 5)
#define AMPM_PHY_EV_POWER_ON_SUCCESS               ((fsm_event_t) 6)
#define AMPM_PHY_EV_POWER_ON_FAIL                  ((fsm_event_t) 7)
#define AMPM_PHY_EV_DISCOVERY_FAILURE              ((fsm_event_t) 8)
#define AMPM_PHY_EV_DISCOVERY_SUCCESS              ((fsm_event_t) 9)
#define AMPM_PHY_EV_AMP_COMMAND_REJECT             ((fsm_event_t) 10)
#define AMPM_PHY_EV_ASSOC_RESPONSE_FAILURE         ((fsm_event_t) 11)
#define AMPM_PHY_EV_ASSOC_RESPONSE_SUCCESS         ((fsm_event_t) 12)
#define AMPM_PHY_EV_HCI_PHYSICAL_FAILURE           ((fsm_event_t) 13)
#define AMPM_PHY_EV_HCI_PHYSICAL_SUCCESS           ((fsm_event_t) 14)
#define AMPM_PHY_EV_HCI_RESPONSE_TIMEOUT_IND       ((fsm_event_t) 15)
#define AMPM_PHY_EV_AMP_DISC_PHYS_REQ              ((fsm_event_t) 16)
#define AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_FAILURE ((fsm_event_t) 17)
#define AMPM_PHY_EV_HCI_WRITE_REMOTE_ASSOC_SUCCESS ((fsm_event_t) 18)
#define AMPM_PHY_EV_HCI_PHYS_COMPLETE_FAIL         ((fsm_event_t) 19)
#define AMPM_PHY_EV_HCI_CHANNEL_SELECT             ((fsm_event_t) 20)
#define AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_FAILURE   ((fsm_event_t) 21)
#define AMPM_PHY_EV_HCI_READ_LOCAL_ASSOC_SUCCESS   ((fsm_event_t) 22)
#define AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_FAIL       ((fsm_event_t) 23)
#define AMPM_PHY_EV_AMP_CREATE_PHYS_RSP_SUCCESS    ((fsm_event_t) 24)
#define AMPM_PHY_EV_HCI_PHYS_COMPLETE_INIT         ((fsm_event_t) 25)
#define AMPM_PHY_EV_HCI_PHYS_COMPLETE_SUCCESS      ((fsm_event_t) 26)
#define AMPM_PHY_EV_HCI_DISC_PHYS_COMPLETE         ((fsm_event_t) 27)
#define AMPM_PHY_EV_HCI_DISC_PHYS_LSTO             ((fsm_event_t) 28)
#define AMPM_PHY_EV_HCI_READ_LSTO_SUCCESS          ((fsm_event_t) 29)
#define AMPM_PHY_EV_HCI_READ_LSTO_FAILURE          ((fsm_event_t) 30)
#define AMPM_PHY_EV_AMP_DISC_PHYS_RSP              ((fsm_event_t) 31)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_INDEX) */
#define AMPM_PHY_AC_MAX 33
#define AMPM_PHY_AC_SendGetRemoteAmpAssocReq         ((fsm_action_t) 0)
#define AMPM_PHY_AC_SendHciAcceptPhysicalLink        ((fsm_action_t) 1)
#define AMPM_PHY_AC_DiscoveryReq                     ((fsm_action_t) 2)
#define AMPM_PHY_AC_SetupFail                        ((fsm_action_t) 3)
#define AMPM_PHY_AC_DeleteReq                        ((fsm_action_t) 4)
#define AMPM_PHY_AC_SendPowerOnInd                   ((fsm_action_t) 5)
#define AMPM_PHY_AC_PowerOnSuccess                   ((fsm_action_t) 6)
#define AMPM_PHY_AC_SendHciCreatePhysicalLink        ((fsm_action_t) 7)
#define AMPM_PHY_AC_SendHciWriteRemoteAmpAssoc       ((fsm_action_t) 8)
#define AMPM_PHY_AC_AcceptorStartPhyLinkFail         ((fsm_action_t) 9)
#define AMPM_PHY_AC_PeerCancellingConnection         ((fsm_action_t) 10)
#define AMPM_PHY_AC_SetupPalDisconnected             ((fsm_action_t) 11)
#define AMPM_PHY_AC_AcceptorStartPhyLinkSuccess      ((fsm_action_t) 12)
#define AMPM_PHY_AC_AcceptorStartPalDisconnected     ((fsm_action_t) 13)
#define AMPM_PHY_AC_ReadLocalAmpAssoc                ((fsm_action_t) 14)
#define AMPM_PHY_AC_SendAmpCreatePhyLinkReq          ((fsm_action_t) 15)
#define AMPM_PHY_AC_HciPhyLinkCompletePend           ((fsm_action_t) 16)
#define AMPM_PHY_AC_PeerDisconnectingLink            ((fsm_action_t) 17)
#define AMPM_PHY_AC_AmpCreatePhyLinkRspPend          ((fsm_action_t) 18)
#define AMPM_PHY_AC_Connected                        ((fsm_action_t) 19)
#define AMPM_PHY_AC_AmpCreatePhylinkRespTimeoutInd   ((fsm_action_t) 20)
#define AMPM_PHY_AC_SetupPeerFailed                  ((fsm_action_t) 21)
#define AMPM_PHY_AC_LinkDropLsto                     ((fsm_action_t) 22)
#define AMPM_PHY_AC_ConnectReqWhenConnected          ((fsm_action_t) 23)
#define AMPM_PHY_AC_PeerDisconnectingEstablishedLink ((fsm_action_t) 24)
#define AMPM_PHY_AC_AmpmDisconnectingEstablishedLink ((fsm_action_t) 25)
#define AMPM_PHY_AC_PalDisconnectingEstablishedLink  ((fsm_action_t) 26)
#define AMPM_PHY_AC_SupervisionTimeout               ((fsm_action_t) 27)
#define AMPM_PHY_AC_PalDisconnected                  ((fsm_action_t) 28)
#define AMPM_PHY_AC_PeerRspToDisconnect              ((fsm_action_t) 29)
#define AMPM_PHY_AC_PeerDisconnected                 ((fsm_action_t) 30)
#define AMPM_PHY_AC_PeerDisconnectReq                ((fsm_action_t) 31)
#define AMPM_PHY_AC_DisconnectTimeoutInd             ((fsm_action_t) 32)
#define AMPM_PHY_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_PHY, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_phy_fsm;
/*}}__FSM_END_MARKER(CSR_BT_AMPM_PHY, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_AMPM_PHY_GENFSM_H */

