/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_l2cap_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_ampm_l2cap_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_ampm_l2cap_action_fns[] =
{
    CsrBtAmpmL2capFsmObtainPhysicalLink,
    CsrBtAmpmL2capFsmCreateChannel,
    CsrBtAmpmL2capFsmDisconnectChannelBeforePhysical,
    CsrBtAmpmL2capFsmDeleteReq,
    CsrBtAmpmL2capFsmPhysicalLinkReadyInd,
    CsrBtAmpmL2capFsmSendDmAmpmConnectRspFail,
    CsrBtAmpmL2capFsmDisconnectChannel,
    CsrBtAmpmL2capFsmChannelReadyInd,
    CsrBtAmpmL2capFsmSendDmAmpmConnectChannelRspFail,
    CsrBtAmpmL2capFsmDisconnectChannelBeforeLogical,
    CsrBtAmpmL2capFsmChannelDisconnected,
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_ampm_l2cap_transitions[] = {
  /* NULL */
  { AMPM_L2CAP_EV_DM_AMPM_CONNECT,              AMPM_L2CAP_AC_ObtainPhysicalLink,               AMPM_L2CAP_ST_WAIT_PHYSICAL_LINK },
  { AMPM_L2CAP_EV_DM_AMPM_CONNECT_CHANNEL,      AMPM_L2CAP_AC_CreateChannel,                    AMPM_L2CAP_ST_ESTABLISHING_CHANNEL },
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannelBeforePhysical,  AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  /* WAIT_PHYSICAL_LINK */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannelBeforePhysical,  AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_READY,          AMPM_L2CAP_AC_PhysicalLinkReadyInd,             AMPM_L2CAP_ST_WAIT_CHANNEL_FLOWSPECS },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_SendDmAmpmConnectRspFail,         AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_SendDmAmpmConnectRspFail,         AMPM_L2CAP_ST_NULL },
  /* WAIT_CHANNEL_FLOWSPECS */
  { AMPM_L2CAP_EV_DM_AMPM_CONNECT_CHANNEL,      AMPM_L2CAP_AC_CreateChannel,                    AMPM_L2CAP_ST_ESTABLISHING_CHANNEL },
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannel,                AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_DISCONNECT },
  { AMPM_L2CAP_EV_PENDING_CONNECT_CHANNEL,      AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_CONNECT },
  /* WAITING_CONNECT */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannel,                AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_CONNECT },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_DISCONNECT },
  { AMPM_L2CAP_EV_TRIGGER_PENDING,              AMPM_L2CAP_AC_CreateChannel,                    AMPM_L2CAP_ST_ESTABLISHING_CHANNEL },
  /* ESTABLISHING_CHANNEL */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannelBeforeLogical,   AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_SendDmAmpmConnectChannelRspFail,  AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_CHANNEL_READY_IND,            AMPM_L2CAP_AC_ChannelReadyInd,                  AMPM_L2CAP_ST_READY },
  { AMPM_L2CAP_EV_LINK_MODIFIED_SUCCESS,        AMPM_L2CAP_AC_ChannelReadyInd,                  AMPM_L2CAP_ST_READY },
  { AMPM_L2CAP_EV_LINK_MODIFIED_FAILURE,        AMPM_L2CAP_AC_SendDmAmpmConnectChannelRspFail,  AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND,       AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_DISCONNECTING },
  /* READY */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_DisconnectChannel,                AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND,       AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_PENDING_DISCONNECT_CHANNEL,   AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_DISCONNECT },
  /* WAITING_DISCONNECT */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_WAITING_DISCONNECT },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_TRIGGER_PENDING,              AMPM_L2CAP_AC_DisconnectChannel,                AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND,       AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  /* DISCONNECTING */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_CHANNEL_READY_IND,            AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_DISCONNECTING },
  { AMPM_L2CAP_EV_LINK_MODIFIED_SUCCESS,        AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_LINK_MODIFIED_FAILURE,        AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND,       AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NULL },
  /* NO_LOGICAL_LINK */
  { AMPM_L2CAP_EV_DISCONNECT_CHANNEL,           AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_DELETE_REQ,                   AMPM_L2CAP_AC_DeleteReq,                        AMPM_L2CAP_ST_NULL },
  { AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT,     AMPM_L2CAP_AC_NULL,                             AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_LINK_FAILURE,                 AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_LINK_MODIFIED_SUCCESS,        AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_LINK_MODIFIED_FAILURE,        AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK },
  { AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND,       AMPM_L2CAP_AC_ChannelDisconnected,              AMPM_L2CAP_ST_NO_LOGICAL_LINK }
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_ampm_l2cap_states[AMPM_L2CAP_ST_ST_MAX+1] = {
    { &csr_bt_ampm_l2cap_transitions[0] },
    { &csr_bt_ampm_l2cap_transitions[4] },
    { &csr_bt_ampm_l2cap_transitions[9] },
    { &csr_bt_ampm_l2cap_transitions[15] },
    { &csr_bt_ampm_l2cap_transitions[20] },
    { &csr_bt_ampm_l2cap_transitions[28] },
    { &csr_bt_ampm_l2cap_transitions[34] },
    { &csr_bt_ampm_l2cap_transitions[40] },
    { &csr_bt_ampm_l2cap_transitions[48] },
    { &csr_bt_ampm_l2cap_transitions[55] },
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, FSM_LOGGING) */
/* State names */
const char *const csr_bt_ampm_l2cap_state_names[] =
{
    "AMPM_L2CAP_ST_NULL",
    "AMPM_L2CAP_ST_WAIT_PHYSICAL_LINK",
    "AMPM_L2CAP_ST_WAIT_CHANNEL_FLOWSPECS",
    "AMPM_L2CAP_ST_WAITING_CONNECT",
    "AMPM_L2CAP_ST_ESTABLISHING_CHANNEL",
    "AMPM_L2CAP_ST_READY",
    "AMPM_L2CAP_ST_WAITING_DISCONNECT",
    "AMPM_L2CAP_ST_DISCONNECTING",
    "AMPM_L2CAP_ST_NO_LOGICAL_LINK",
};
#define CSR_BT_AMPM_L2CAP_STATE_NAMES_PTR (csr_bt_ampm_l2cap_state_names)

/* Event names */
const char *const csr_bt_ampm_l2cap_event_names[] =
{
    "AMPM_L2CAP_EV_DM_AMPM_CONNECT",
    "AMPM_L2CAP_EV_DM_AMPM_CONNECT_CHANNEL",
    "AMPM_L2CAP_EV_DISCONNECT_CHANNEL",
    "AMPM_L2CAP_EV_DELETE_REQ",
    "AMPM_L2CAP_EV_PHYSICAL_LINK_READY",
    "AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT",
    "AMPM_L2CAP_EV_LINK_FAILURE",
    "AMPM_L2CAP_EV_PENDING_CONNECT_CHANNEL",
    "AMPM_L2CAP_EV_TRIGGER_PENDING",
    "AMPM_L2CAP_EV_CHANNEL_READY_IND",
    "AMPM_L2CAP_EV_LINK_MODIFIED_SUCCESS",
    "AMPM_L2CAP_EV_LINK_MODIFIED_FAILURE",
    "AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND",
    "AMPM_L2CAP_EV_PENDING_DISCONNECT_CHANNEL",
};
#define CSR_BT_AMPM_L2CAP_EVENT_NAMES_PTR (csr_bt_ampm_l2cap_event_names)

/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, FSM_LOGGING) */
#else
#define CSR_BT_AMPM_L2CAP_STATE_NAMES_PTR (NULL)
#define CSR_BT_AMPM_L2CAP_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_l2cap_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_ampm_l2cap_states,
    csr_bt_ampm_l2cap_action_fns
    FSM_LOG_INFO("CSR_BT_AMPM_L2CAP",
    CSR_BT_AMPM_L2CAP_STATE_NAMES_PTR,
    CSR_BT_AMPM_L2CAP_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, FSM_DEFINITION) */

