/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_logical_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_ampm_logical_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_ampm_logical_action_fns[] =
{
    CsrBtAmpmLogicalFsmCreateLogicalLink,
    CsrBtAmpmLogicalFsmDisconnectUnstartedLink,
    CsrBtAmpmLogicalFsmDeleteReq,
    CsrBtAmpmLogicalFsmLinkEstablished,
    CsrBtAmpmLogicalFsmEstablishmentFailed,
    CsrBtAmpmLogicalFsmPhyLinkDisconnectInd,
    CsrBtAmpmLogicalFsmCancelLogicalLink,
    CsrBtAmpmLogicalFsmCancelFailed,
    CsrBtAmpmLogicalFsmModifyFlowspecReq,
    CsrBtAmpmLogicalFsmDisconnectLogicalLink,
    CsrBtAmpmLogicalFsmLinkFailure,
    CsrBtAmpmLogicalFsmLinkFailureLsto,
    CsrBtAmpmLogicalFsmModifySuccess,
    CsrBtAmpmLogicalFsmModifyFailed,
    CsrBtAmpmLogicalFsmLinkDisconnected,
    CsrBtAmpmLogicalFsmLinkDisconnectFailed,
    CsrBtAmpmLogicalFsmLinkDisconnectTimeout,
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_ampm_logical_transitions[] = {
  /* NULL */
  { AMPM_LOGICAL_EV_CREATE_REQ,              AMPM_LOGICAL_AC_CreateLogicalLink,        AMPM_LOGICAL_ST_CREATING_LINK },
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_DisconnectUnstartedLink,  AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_DisconnectUnstartedLink,  AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  /* CREATING_LINK */
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_CancelLogicalLink,        AMPM_LOGICAL_ST_CANCELLING },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_PhyLinkDisconnectInd,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_COMPLETE_SUCCESS,        AMPM_LOGICAL_AC_LinkEstablished,          AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  { AMPM_LOGICAL_EV_COMPLETE_FAILURE,        AMPM_LOGICAL_AC_EstablishmentFailed,      AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_COMMAND_FAILURE,         AMPM_LOGICAL_AC_EstablishmentFailed,      AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_RESPONSE_TIMEOUT,        AMPM_LOGICAL_AC_EstablishmentFailed,      AMPM_LOGICAL_ST_NULL },
  /* LINK_ESTABLISHED */
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_DisconnectLogicalLink,    AMPM_LOGICAL_ST_DISCONNECTING },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_PhyLinkDisconnectInd,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_CANCEL_FAILURE,          AMPM_LOGICAL_AC_CancelFailed,             AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  { AMPM_LOGICAL_EV_MODIFIED_FLOWSPEC_REQ,   AMPM_LOGICAL_AC_ModifyFlowspecReq,        AMPM_LOGICAL_ST_MODIFYING_FLOWSPEC },
  { AMPM_LOGICAL_EV_DISCONNECT_SUCCESS,      AMPM_LOGICAL_AC_LinkFailure,              AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DISCONNECT_LSTO,         AMPM_LOGICAL_AC_LinkFailureLsto,          AMPM_LOGICAL_ST_NULL },
  /* MODIFYING_FLOWSPEC */
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_DisconnectLogicalLink,    AMPM_LOGICAL_ST_DISCONNECTING },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_PhyLinkDisconnectInd,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_RESPONSE_TIMEOUT,        AMPM_LOGICAL_AC_ModifyFailed,             AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  { AMPM_LOGICAL_EV_DISCONNECT_SUCCESS,      AMPM_LOGICAL_AC_LinkFailure,              AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DISCONNECT_LSTO,         AMPM_LOGICAL_AC_LinkFailureLsto,          AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_FLOWSPEC_SUCCESS,        AMPM_LOGICAL_AC_ModifySuccess,            AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  { AMPM_LOGICAL_EV_FLOWSPEC_FAILURE,        AMPM_LOGICAL_AC_ModifyFailed,             AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  /* DISCONNECTING */
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_NULL,                     AMPM_LOGICAL_ST_DISCONNECTING },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_PhyLinkDisconnectInd,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_COMMAND_FAILURE,         AMPM_LOGICAL_AC_LinkDisconnectFailed,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_RESPONSE_TIMEOUT,        AMPM_LOGICAL_AC_LinkDisconnectTimeout,    AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DISCONNECT_SUCCESS,      AMPM_LOGICAL_AC_LinkDisconnected,         AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_FLOWSPEC_SUCCESS,        AMPM_LOGICAL_AC_NULL,                     AMPM_LOGICAL_ST_DISCONNECTING },
  { AMPM_LOGICAL_EV_FLOWSPEC_FAILURE,        AMPM_LOGICAL_AC_NULL,                     AMPM_LOGICAL_ST_DISCONNECTING },
  { AMPM_LOGICAL_EV_DISCONNECT_FAILURE,      AMPM_LOGICAL_AC_LinkDisconnectFailed,     AMPM_LOGICAL_ST_NULL },
  /* CANCELLING */
  { AMPM_LOGICAL_EV_DISCONNECT_REQ,          AMPM_LOGICAL_AC_NULL,                     AMPM_LOGICAL_ST_CANCELLING },
  { AMPM_LOGICAL_EV_PHY_DISCONNECT,          AMPM_LOGICAL_AC_PhyLinkDisconnectInd,     AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_DELETE_REQ,              AMPM_LOGICAL_AC_DeleteReq,                AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_COMPLETE_SUCCESS,        AMPM_LOGICAL_AC_LinkEstablished,          AMPM_LOGICAL_ST_LINK_ESTABLISHED },
  { AMPM_LOGICAL_EV_COMPLETE_FAILURE,        AMPM_LOGICAL_AC_NULL,                     AMPM_LOGICAL_ST_CANCELLING },
  { AMPM_LOGICAL_EV_RESPONSE_TIMEOUT,        AMPM_LOGICAL_AC_LinkDisconnectTimeout,    AMPM_LOGICAL_ST_NULL },
  { AMPM_LOGICAL_EV_CANCEL_FAILURE,          AMPM_LOGICAL_AC_CancelFailed,             AMPM_LOGICAL_ST_CREATING_LINK },
  { AMPM_LOGICAL_EV_CANCEL_SUCCESS,          AMPM_LOGICAL_AC_LinkDisconnected,         AMPM_LOGICAL_ST_NULL }
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_ampm_logical_states[AMPM_LOGICAL_ST_ST_MAX+1] = {
    { &csr_bt_ampm_logical_transitions[0] },
    { &csr_bt_ampm_logical_transitions[4] },
    { &csr_bt_ampm_logical_transitions[11] },
    { &csr_bt_ampm_logical_transitions[18] },
    { &csr_bt_ampm_logical_transitions[26] },
    { &csr_bt_ampm_logical_transitions[35] },
    { &csr_bt_ampm_logical_transitions[43] },
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, FSM_LOGGING) */
/* State names */
const char *const csr_bt_ampm_logical_state_names[] =
{
    "AMPM_LOGICAL_ST_NULL",
    "AMPM_LOGICAL_ST_CREATING_LINK",
    "AMPM_LOGICAL_ST_LINK_ESTABLISHED",
    "AMPM_LOGICAL_ST_MODIFYING_FLOWSPEC",
    "AMPM_LOGICAL_ST_DISCONNECTING",
    "AMPM_LOGICAL_ST_CANCELLING",
};
#define CSR_BT_AMPM_LOGICAL_STATE_NAMES_PTR (csr_bt_ampm_logical_state_names)

/* Event names */
const char *const csr_bt_ampm_logical_event_names[] =
{
    "AMPM_LOGICAL_EV_CREATE_REQ",
    "AMPM_LOGICAL_EV_DISCONNECT_REQ",
    "AMPM_LOGICAL_EV_PHY_DISCONNECT",
    "AMPM_LOGICAL_EV_DELETE_REQ",
    "AMPM_LOGICAL_EV_COMPLETE_SUCCESS",
    "AMPM_LOGICAL_EV_COMPLETE_FAILURE",
    "AMPM_LOGICAL_EV_COMMAND_FAILURE",
    "AMPM_LOGICAL_EV_RESPONSE_TIMEOUT",
    "AMPM_LOGICAL_EV_CANCEL_FAILURE",
    "AMPM_LOGICAL_EV_MODIFIED_FLOWSPEC_REQ",
    "AMPM_LOGICAL_EV_DISCONNECT_SUCCESS",
    "AMPM_LOGICAL_EV_DISCONNECT_LSTO",
    "AMPM_LOGICAL_EV_FLOWSPEC_SUCCESS",
    "AMPM_LOGICAL_EV_FLOWSPEC_FAILURE",
    "AMPM_LOGICAL_EV_DISCONNECT_FAILURE",
    "AMPM_LOGICAL_EV_CANCEL_SUCCESS",
};
#define CSR_BT_AMPM_LOGICAL_EVENT_NAMES_PTR (csr_bt_ampm_logical_event_names)

/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, FSM_LOGGING) */
#else
#define CSR_BT_AMPM_LOGICAL_STATE_NAMES_PTR (NULL)
#define CSR_BT_AMPM_LOGICAL_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOGICAL, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_logical_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_ampm_logical_states,
    csr_bt_ampm_logical_action_fns
    FSM_LOG_INFO("CSR_BT_AMPM_LOGICAL",
    CSR_BT_AMPM_LOGICAL_STATE_NAMES_PTR,
    CSR_BT_AMPM_LOGICAL_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOGICAL, FSM_DEFINITION) */

