/****************************************************************************

              (c) Cambridge Silicon Radio Limited 2009

              All rights reserved and confidential information of CSR

              Warning: This file was autogenerated from 'bt_amp_hci.xml'

****************************************************************************/

#include "csr_synergy.h"

#include "csr_pmem.h"
#include "csr_bt_amp_hci.h"
#include "csr_bt_ampm_prim.h"
#include "csr_bt_ampm_main.h"
#include "csr_bt_ampm_local.h"
#include "csr_bt_ampm_send_hci_command.h" 

/* Generates the HCI command structure for CsrBtAmpHciNoOperationCmd  */
void CsrBtAmpmSendHciNoOperation(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciNoOperationCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciNoOperationCmd));
    cmd->opcode = CSR_BT_AMP_HCI_NO_OPERATION_CODE;
    cmd->length = sizeof(CsrBtAmpHciNoOperationCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciCreatePhysicalLinkCmd  */
void CsrBtAmpmSendHciCreatePhysicalLink(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrUint8 dedicatedAmpKeyLength,
    CsrBtAmpLinkKeyType dedicatedAmpKeyType,
    CsrUint8 *dedicatedAmpKey)
{
    CsrBtAmpHciCreatePhysicalLinkCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciCreatePhysicalLinkCmd));
    cmd->opcode = CSR_BT_AMP_HCI_CREATE_PHYSICAL_LINK_CODE;
    cmd->length = sizeof(CsrBtAmpHciCreatePhysicalLinkCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->dedicatedAmpKeyLength = dedicatedAmpKeyLength;
    cmd->dedicatedAmpKeyType = dedicatedAmpKeyType;
    cmd->dedicatedAmpKey = dedicatedAmpKey;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciAcceptPhysicalLinkRequestCmd  */
void CsrBtAmpmSendHciAcceptPhysicalLinkRequest(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrUint8 dedicatedAmpKeyLength,
    CsrBtAmpLinkKeyType dedicatedAmpKeyType,
    CsrUint8 *dedicatedAmpKey)
{
    CsrBtAmpHciAcceptPhysicalLinkRequestCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciAcceptPhysicalLinkRequestCmd));
    cmd->opcode = CSR_BT_AMP_HCI_ACCEPT_PHYSICAL_LINK_REQUEST_CODE;
    cmd->length = sizeof(CsrBtAmpHciAcceptPhysicalLinkRequestCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->dedicatedAmpKeyLength = dedicatedAmpKeyLength;
    cmd->dedicatedAmpKeyType = dedicatedAmpKeyType;
    cmd->dedicatedAmpKey = dedicatedAmpKey;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciDisconnectPhysicalLinkCmd  */
void CsrBtAmpmSendHciDisconnectPhysicalLink(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrBtAmpHciStatusCode reason)
{
    CsrBtAmpHciDisconnectPhysicalLinkCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciDisconnectPhysicalLinkCmd));
    cmd->opcode = CSR_BT_AMP_HCI_DISCONNECT_PHYSICAL_LINK_CODE;
    cmd->length = sizeof(CsrBtAmpHciDisconnectPhysicalLinkCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->reason = reason;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciCreateLogicalLinkCmd  */
void CsrBtAmpmSendHciCreateLogicalLink(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrBtAmpAmpFlowSpec txFlowSpec,
    CsrBtAmpAmpFlowSpec rxFlowSpec)
{
    CsrBtAmpHciCreateLogicalLinkCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciCreateLogicalLinkCmd));
    cmd->opcode = CSR_BT_AMP_HCI_CREATE_LOGICAL_LINK_CODE;
    cmd->length = sizeof(CsrBtAmpHciCreateLogicalLinkCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->txFlowSpec = txFlowSpec;
    cmd->rxFlowSpec = rxFlowSpec;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciAcceptLogicalLinkCmd  */
void CsrBtAmpmSendHciAcceptLogicalLink(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrBtAmpAmpFlowSpec txFlowSpec,
    CsrBtAmpAmpFlowSpec rxFlowSpec)
{
    CsrBtAmpHciAcceptLogicalLinkCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciAcceptLogicalLinkCmd));
    cmd->opcode = CSR_BT_AMP_HCI_ACCEPT_LOGICAL_LINK_CODE;
    cmd->length = sizeof(CsrBtAmpHciAcceptLogicalLinkCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->txFlowSpec = txFlowSpec;
    cmd->rxFlowSpec = rxFlowSpec;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciDisconnectLogicalLinkCmd  */
void CsrBtAmpmSendHciDisconnectLogicalLink(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 logicalLinkHandle)
{
    CsrBtAmpHciDisconnectLogicalLinkCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciDisconnectLogicalLinkCmd));
    cmd->opcode = CSR_BT_AMP_HCI_DISCONNECT_LOGICAL_LINK_CODE;
    cmd->length = sizeof(CsrBtAmpHciDisconnectLogicalLinkCmd); /* Does not include secondary structures */
    cmd->logicalLinkHandle = logicalLinkHandle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciLogicalLinkCancelCmd  */
void CsrBtAmpmSendHciLogicalLinkCancel(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrUint8 txFlowSpecId)
{
    CsrBtAmpHciLogicalLinkCancelCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciLogicalLinkCancelCmd));
    cmd->opcode = CSR_BT_AMP_HCI_LOGICAL_LINK_CANCEL_CODE;
    cmd->length = sizeof(CsrBtAmpHciLogicalLinkCancelCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->txFlowSpecId = txFlowSpecId;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciFlowSpecModifyCmd  */
void CsrBtAmpmSendHciFlowSpecModify(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle,
    CsrBtAmpAmpFlowSpec txFlowSpec,
    CsrBtAmpAmpFlowSpec rxFlowSpec)
{
    CsrBtAmpHciFlowSpecModifyCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciFlowSpecModifyCmd));
    cmd->opcode = CSR_BT_AMP_HCI_FLOW_SPEC_MODIFY_CODE;
    cmd->length = sizeof(CsrBtAmpHciFlowSpecModifyCmd); /* Does not include secondary structures */
    cmd->handle = handle;
    cmd->txFlowSpec = txFlowSpec;
    cmd->rxFlowSpec = rxFlowSpec;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciSetEventMaskCmd  */
void CsrBtAmpmSendHciSetEventMask(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrBtAmpEventMask eventMask)
{
    CsrBtAmpHciSetEventMaskCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciSetEventMaskCmd));
    cmd->opcode = CSR_BT_AMP_HCI_SET_EVENT_MASK_CODE;
    cmd->length = sizeof(CsrBtAmpHciSetEventMaskCmd); /* Does not include secondary structures */
    cmd->eventMask = eventMask;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciResetCmd  */
void CsrBtAmpmSendHciReset(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciResetCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciResetCmd));
    cmd->opcode = CSR_BT_AMP_HCI_RESET_CODE;
    cmd->length = sizeof(CsrBtAmpHciResetCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciFlushCmd  */
void CsrBtAmpmSendHciFlush(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciFlushCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciFlushCmd));
    cmd->opcode = CSR_BT_AMP_HCI_FLUSH_CODE;
    cmd->length = sizeof(CsrBtAmpHciFlushCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadConnectionAcceptTimeoutCmd  */
void CsrBtAmpmSendHciReadConnectionAcceptTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadConnectionAcceptTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadConnectionAcceptTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_CONNECTION_ACCEPT_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadConnectionAcceptTimeoutCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteConnectionAcceptTimeoutCmd  */
void CsrBtAmpmSendHciWriteConnectionAcceptTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 connAcceptTimeout)
{
    CsrBtAmpHciWriteConnectionAcceptTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteConnectionAcceptTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_CONNECTION_ACCEPT_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteConnectionAcceptTimeoutCmd); /* Does not include secondary structures */
    cmd->connAcceptTimeout = connAcceptTimeout;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLinkSupervisionTimeoutCmd  */
void CsrBtAmpmSendHciReadLinkSupervisionTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciReadLinkSupervisionTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLinkSupervisionTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LINK_SUPERVISION_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLinkSupervisionTimeoutCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteLinkSupervisionTimeoutCmd  */
void CsrBtAmpmSendHciWriteLinkSupervisionTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle,
    CsrUint16 linkSupervisionTimeout)
{
    CsrBtAmpHciWriteLinkSupervisionTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteLinkSupervisionTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_LINK_SUPERVISION_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteLinkSupervisionTimeoutCmd); /* Does not include secondary structures */
    cmd->handle = handle;
    cmd->linkSupervisionTimeout = linkSupervisionTimeout;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciEnhancedFlushCmd  */
void CsrBtAmpmSendHciEnhancedFlush(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle,
    CsrBtAmpPacketType packetType)
{
    CsrBtAmpHciEnhancedFlushCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciEnhancedFlushCmd));
    cmd->opcode = CSR_BT_AMP_HCI_ENHANCED_FLUSH_CODE;
    cmd->length = sizeof(CsrBtAmpHciEnhancedFlushCmd); /* Does not include secondary structures */
    cmd->handle = handle;
    cmd->packetType = packetType;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLogicalLinkAcceptTimeoutCmd  */
void CsrBtAmpmSendHciReadLogicalLinkAcceptTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLogicalLinkAcceptTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLogicalLinkAcceptTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOGICAL_LINK_ACCEPT_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLogicalLinkAcceptTimeoutCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteLogicalLinkAcceptTimeoutCmd  */
void CsrBtAmpmSendHciWriteLogicalLinkAcceptTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 logicalLinkAcceptTimeout)
{
    CsrBtAmpHciWriteLogicalLinkAcceptTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteLogicalLinkAcceptTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_LOGICAL_LINK_ACCEPT_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteLogicalLinkAcceptTimeoutCmd); /* Does not include secondary structures */
    cmd->logicalLinkAcceptTimeout = logicalLinkAcceptTimeout;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciSetEventMaskPage2Cmd  */
void CsrBtAmpmSendHciSetEventMaskPage2(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrBtAmpEventMaskPage2 eventMaskPage2)
{
    CsrBtAmpHciSetEventMaskPage2Cmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciSetEventMaskPage2Cmd));
    cmd->opcode = CSR_BT_AMP_HCI_SET_EVENT_MASK_PAGE2_CODE;
    cmd->length = sizeof(CsrBtAmpHciSetEventMaskPage2Cmd); /* Does not include secondary structures */
    cmd->eventMaskPage2 = eventMaskPage2;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLocationDataCmd  */
void CsrBtAmpmSendHciReadLocationData(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLocationDataCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLocationDataCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOCATION_DATA_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLocationDataCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteLocationDataCmd  */
void CsrBtAmpmSendHciWriteLocationData(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrBtAmpLocationDomainAware locationDomainAware,
    CsrUint16 locationDomain,
    CsrBtAmpLocationDomainOptions locationDomainOptions,
    CsrBtAmpLocationOptions locationOptions)
{
    CsrBtAmpHciWriteLocationDataCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteLocationDataCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_LOCATION_DATA_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteLocationDataCmd); /* Does not include secondary structures */
    cmd->locationDomainAware = locationDomainAware;
    cmd->locationDomain = locationDomain;
    cmd->locationDomainOptions = locationDomainOptions;
    cmd->locationOptions = locationOptions;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadBestEffortFlushTimeoutCmd  */
void CsrBtAmpmSendHciReadBestEffortFlushTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 logicalLinkHandle)
{
    CsrBtAmpHciReadBestEffortFlushTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadBestEffortFlushTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_BEST_EFFORT_FLUSH_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadBestEffortFlushTimeoutCmd); /* Does not include secondary structures */
    cmd->logicalLinkHandle = logicalLinkHandle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteBestEffortFlushTimeoutCmd  */
void CsrBtAmpmSendHciWriteBestEffortFlushTimeout(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 logicalLinkHandle,
    CsrUint32 bestEffortFlushTimeout)
{
    CsrBtAmpHciWriteBestEffortFlushTimeoutCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteBestEffortFlushTimeoutCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_BEST_EFFORT_FLUSH_TIMEOUT_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteBestEffortFlushTimeoutCmd); /* Does not include secondary structures */
    cmd->logicalLinkHandle = logicalLinkHandle;
    cmd->bestEffortFlushTimeout = bestEffortFlushTimeout;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciShortRangeModeCmd  */
void CsrBtAmpmSendHciShortRangeMode(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrBtAmpShortRangeMode shortRangeMode)
{
    CsrBtAmpHciShortRangeModeCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciShortRangeModeCmd));
    cmd->opcode = CSR_BT_AMP_HCI_SHORT_RANGE_MODE_CODE;
    cmd->length = sizeof(CsrBtAmpHciShortRangeModeCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->shortRangeMode = shortRangeMode;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLocalVersionInformationCmd  */
void CsrBtAmpmSendHciReadLocalVersionInformation(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLocalVersionInformationCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLocalVersionInformationCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOCAL_VERSION_INFORMATION_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLocalVersionInformationCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLocalSupportedCommandsCmd  */
void CsrBtAmpmSendHciReadLocalSupportedCommands(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLocalSupportedCommandsCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLocalSupportedCommandsCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOCAL_SUPPORTED_COMMANDS_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLocalSupportedCommandsCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadDataBlockSizeCmd  */
void CsrBtAmpmSendHciReadDataBlockSize(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadDataBlockSizeCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadDataBlockSizeCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_DATA_BLOCK_SIZE_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadDataBlockSizeCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadFailedContactCounterCmd  */
void CsrBtAmpmSendHciReadFailedContactCounter(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciReadFailedContactCounterCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadFailedContactCounterCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_FAILED_CONTACT_COUNTER_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadFailedContactCounterCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciResetFailedContactCounterCmd  */
void CsrBtAmpmSendHciResetFailedContactCounter(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciResetFailedContactCounterCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciResetFailedContactCounterCmd));
    cmd->opcode = CSR_BT_AMP_HCI_RESET_FAILED_CONTACT_COUNTER_CODE;
    cmd->length = sizeof(CsrBtAmpHciResetFailedContactCounterCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLinkQualityCmd  */
void CsrBtAmpmSendHciReadLinkQuality(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciReadLinkQualityCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLinkQualityCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LINK_QUALITY_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLinkQualityCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadRssiCmd  */
void CsrBtAmpmSendHciReadRssi(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint16 handle)
{
    CsrBtAmpHciReadRssiCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadRssiCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_RSSI_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadRssiCmd); /* Does not include secondary structures */
    cmd->handle = handle;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLocalAmpInfoCmd  */
void CsrBtAmpmSendHciReadLocalAmpInfo(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLocalAmpInfoCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLocalAmpInfoCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOCAL_AMP_INFO_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLocalAmpInfoCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLocalAmpAssocCmd  */
void CsrBtAmpmSendHciReadLocalAmpAssoc(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrUint16 lengthSoFar,
    CsrUint16 maxRemoteAmpAssocLength)
{
    CsrBtAmpHciReadLocalAmpAssocCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLocalAmpAssocCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOCAL_AMP_ASSOC_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLocalAmpAssocCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->lengthSoFar = lengthSoFar;
    cmd->maxRemoteAmpAssocLength = maxRemoteAmpAssocLength;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteRemoteAmpAssocCmd  */
void CsrBtAmpmSendHciWriteRemoteAmpAssoc(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 physicalLinkHandle,
    CsrUint16 lengthSoFar,
    CsrUint16 remainingLength,
    CsrBtAmpAmpAssoc assocFragment)
{
    CsrBtAmpHciWriteRemoteAmpAssocCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteRemoteAmpAssocCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_REMOTE_AMP_ASSOC_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteRemoteAmpAssocCmd); /* Does not include secondary structures */
    cmd->physicalLinkHandle = physicalLinkHandle;
    cmd->lengthSoFar = lengthSoFar;
    cmd->remainingLength = remainingLength;
    cmd->assocFragment = assocFragment;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReadLoopbackModeCmd  */
void CsrBtAmpmSendHciReadLoopbackMode(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciReadLoopbackModeCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReadLoopbackModeCmd));
    cmd->opcode = CSR_BT_AMP_HCI_READ_LOOPBACK_MODE_CODE;
    cmd->length = sizeof(CsrBtAmpHciReadLoopbackModeCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciWriteLoopbackModeCmd  */
void CsrBtAmpmSendHciWriteLoopbackMode(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrBtAmpHciLoopbackMode loopbackMode)
{
    CsrBtAmpHciWriteLoopbackModeCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciWriteLoopbackModeCmd));
    cmd->opcode = CSR_BT_AMP_HCI_WRITE_LOOPBACK_MODE_CODE;
    cmd->length = sizeof(CsrBtAmpHciWriteLoopbackModeCmd); /* Does not include secondary structures */
    cmd->loopbackMode = loopbackMode;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciEnableAmpTestModeCmd  */
void CsrBtAmpmSendHciEnableAmpTestMode(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrBtAmpTestMode enable)
{
    CsrBtAmpHciEnableAmpTestModeCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciEnableAmpTestModeCmd));
    cmd->opcode = CSR_BT_AMP_HCI_ENABLE_AMP_TEST_MODE_CODE;
    cmd->length = sizeof(CsrBtAmpHciEnableAmpTestModeCmd); /* Does not include secondary structures */
    cmd->enable = enable;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciSetAmpTransmitPowerTestCmd  */
void CsrBtAmpmSendHciSetAmpTransmitPowerTest(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 powerLevel)
{
    CsrBtAmpHciSetAmpTransmitPowerTestCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciSetAmpTransmitPowerTestCmd));
    cmd->opcode = CSR_BT_AMP_HCI_SET_AMP_TRANSMIT_POWER_TEST_CODE;
    cmd->length = sizeof(CsrBtAmpHciSetAmpTransmitPowerTestCmd); /* Does not include secondary structures */
    cmd->powerLevel = powerLevel;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciEnableAmpReceiverReportsCmd  */
void CsrBtAmpmSendHciEnableAmpReceiverReports(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 enable,
    CsrUint8 interval)
{
    CsrBtAmpHciEnableAmpReceiverReportsCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciEnableAmpReceiverReportsCmd));
    cmd->opcode = CSR_BT_AMP_HCI_ENABLE_AMP_RECEIVER_REPORTS_CODE;
    cmd->length = sizeof(CsrBtAmpHciEnableAmpReceiverReportsCmd); /* Does not include secondary structures */
    cmd->enable = enable;
    cmd->interval = interval;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciTransmitterAmpTestCmd  */
void CsrBtAmpmSendHciTransmitterAmpTest(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 testScenario)
{
    CsrBtAmpHciTransmitterAmpTestCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciTransmitterAmpTestCmd));
    cmd->opcode = CSR_BT_AMP_HCI_TRANSMITTER_AMP_TEST_CODE;
    cmd->length = sizeof(CsrBtAmpHciTransmitterAmpTestCmd); /* Does not include secondary structures */
    cmd->testScenario = testScenario;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciReceiverAmpTestCmd  */
void CsrBtAmpmSendHciReceiverAmpTest(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender,
    CsrUint8 testScenario)
{
    CsrBtAmpHciReceiverAmpTestCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciReceiverAmpTestCmd));
    cmd->opcode = CSR_BT_AMP_HCI_RECEIVER_AMP_TEST_CODE;
    cmd->length = sizeof(CsrBtAmpHciReceiverAmpTestCmd); /* Does not include secondary structures */
    cmd->testScenario = testScenario;

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}

/* Generates the HCI command structure for CsrBtAmpHciAmpTestEndCmd  */
void CsrBtAmpmSendHciAmpTestEnd(
    CsrBtAmpmInstance *inst,
    CsrUint8 ampId,
    void *sender)
{
    CsrBtAmpHciAmpTestEndCmd *cmd;

    cmd = CsrPmemZalloc(sizeof(CsrBtAmpHciAmpTestEndCmd));
    cmd->opcode = CSR_BT_AMP_HCI_AMP_TEST_END_CODE;
    cmd->length = sizeof(CsrBtAmpHciAmpTestEndCmd); /* Does not include secondary structures */

    CsrBtAmpmLocalHciTxCmd(inst, ampId, sender, (CsrUint8*)cmd);
}


