#ifndef _CSR_BT_AMPM_BTDEV_GENFSM_H
#define _CSR_BT_AMPM_BTDEV_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_btdev_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmCheckExtFeatures);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmL2caMapFixedCidInd);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmDeleteReq);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmFixedChannelSupported);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpmChannelSupported);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmL2caMapFixedCidCfm);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmRunDiscovery);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpDiscoverRsp);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpDiscoverRejected);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpDiscoverReq);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpChangeInd);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmAmpGetInfoRsp);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmLocalAmpChangeInd);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmDisconnectReq);
extern FSM_ACTION_FN(CsrBtAmpmBtdevFsmDisconnectInd);
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, STATE_DECLARATIONS) */
#define AMPM_BTDEV_ST_ST_MAX 4
#define AMPM_BTDEV_ST_NULL              ((fsm_state_t) 0)
#define AMPM_BTDEV_ST_CHECKING_FEATURES ((fsm_state_t) 1)
#define AMPM_BTDEV_ST_WAITING_FOR_CID   ((fsm_state_t) 2)
#define AMPM_BTDEV_ST_CONNECTED         ((fsm_state_t) 3)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, EVENT_DECLARATIONS) */
#define AMPM_BTDEV_EV_DISCOVER_EV               ((fsm_event_t) 0)
#define AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND    ((fsm_event_t) 1)
#define AMPM_BTDEV_EV_DELETE_REQ                ((fsm_event_t) 2)
#define AMPM_BTDEV_EV_DISCONNECT_IND            ((fsm_event_t) 3)
#define AMPM_BTDEV_EV_FIXED_CHANS_SUPPORTED_IND ((fsm_event_t) 4)
#define AMPM_BTDEV_EV_AMPM_CHAN_SUPPORTED_IND   ((fsm_event_t) 5)
#define AMPM_BTDEV_EV_LOCAL_AMP_CHANGE_IND      ((fsm_event_t) 6)
#define AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_CFM    ((fsm_event_t) 7)
#define AMPM_BTDEV_EV_AMP_DISCOVER_RESPONSE     ((fsm_event_t) 8)
#define AMPM_BTDEV_EV_AMP_COMMAND_REJECT        ((fsm_event_t) 9)
#define AMPM_BTDEV_EV_AMP_DISCOVER_REQUEST      ((fsm_event_t) 10)
#define AMPM_BTDEV_EV_AMP_CHANGE_NOTIFY         ((fsm_event_t) 11)
#define AMPM_BTDEV_EV_AMP_GET_INFO_RESPONSE     ((fsm_event_t) 12)
#define AMPM_BTDEV_EV_DISCONNECT_REQ            ((fsm_event_t) 13)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_INDEX) */
#define AMPM_BTDEV_AC_MAX 15
#define AMPM_BTDEV_AC_CheckExtFeatures      ((fsm_action_t) 0)
#define AMPM_BTDEV_AC_L2caMapFixedCidInd    ((fsm_action_t) 1)
#define AMPM_BTDEV_AC_DeleteReq             ((fsm_action_t) 2)
#define AMPM_BTDEV_AC_FixedChannelSupported ((fsm_action_t) 3)
#define AMPM_BTDEV_AC_AmpmChannelSupported  ((fsm_action_t) 4)
#define AMPM_BTDEV_AC_L2caMapFixedCidCfm    ((fsm_action_t) 5)
#define AMPM_BTDEV_AC_RunDiscovery          ((fsm_action_t) 6)
#define AMPM_BTDEV_AC_AmpDiscoverRsp        ((fsm_action_t) 7)
#define AMPM_BTDEV_AC_AmpDiscoverRejected   ((fsm_action_t) 8)
#define AMPM_BTDEV_AC_AmpDiscoverReq        ((fsm_action_t) 9)
#define AMPM_BTDEV_AC_AmpChangeInd          ((fsm_action_t) 10)
#define AMPM_BTDEV_AC_AmpGetInfoRsp         ((fsm_action_t) 11)
#define AMPM_BTDEV_AC_LocalAmpChangeInd     ((fsm_action_t) 12)
#define AMPM_BTDEV_AC_DisconnectReq         ((fsm_action_t) 13)
#define AMPM_BTDEV_AC_DisconnectInd         ((fsm_action_t) 14)
#define AMPM_BTDEV_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_btdev_fsm;
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_AMPM_BTDEV_GENFSM_H */

