#ifndef _CSR_BT_AMPM_L2CAP_GENFSM_H
#define _CSR_BT_AMPM_L2CAP_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_l2cap_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmObtainPhysicalLink);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmCreateChannel);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmDisconnectChannelBeforePhysical);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmDeleteReq);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmPhysicalLinkReadyInd);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmSendDmAmpmConnectRspFail);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmDisconnectChannel);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmChannelReadyInd);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmSendDmAmpmConnectChannelRspFail);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmDisconnectChannelBeforeLogical);
extern FSM_ACTION_FN(CsrBtAmpmL2capFsmChannelDisconnected);
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, STATE_DECLARATIONS) */
#define AMPM_L2CAP_ST_ST_MAX 9
#define AMPM_L2CAP_ST_NULL                   ((fsm_state_t) 0)
#define AMPM_L2CAP_ST_WAIT_PHYSICAL_LINK     ((fsm_state_t) 1)
#define AMPM_L2CAP_ST_WAIT_CHANNEL_FLOWSPECS ((fsm_state_t) 2)
#define AMPM_L2CAP_ST_WAITING_CONNECT        ((fsm_state_t) 3)
#define AMPM_L2CAP_ST_ESTABLISHING_CHANNEL   ((fsm_state_t) 4)
#define AMPM_L2CAP_ST_READY                  ((fsm_state_t) 5)
#define AMPM_L2CAP_ST_WAITING_DISCONNECT     ((fsm_state_t) 6)
#define AMPM_L2CAP_ST_DISCONNECTING          ((fsm_state_t) 7)
#define AMPM_L2CAP_ST_NO_LOGICAL_LINK        ((fsm_state_t) 8)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, EVENT_DECLARATIONS) */
#define AMPM_L2CAP_EV_DM_AMPM_CONNECT            ((fsm_event_t) 0)
#define AMPM_L2CAP_EV_DM_AMPM_CONNECT_CHANNEL    ((fsm_event_t) 1)
#define AMPM_L2CAP_EV_DISCONNECT_CHANNEL         ((fsm_event_t) 2)
#define AMPM_L2CAP_EV_DELETE_REQ                 ((fsm_event_t) 3)
#define AMPM_L2CAP_EV_PHYSICAL_LINK_READY        ((fsm_event_t) 4)
#define AMPM_L2CAP_EV_PHYSICAL_LINK_DISCONNECT   ((fsm_event_t) 5)
#define AMPM_L2CAP_EV_LINK_FAILURE               ((fsm_event_t) 6)
#define AMPM_L2CAP_EV_PENDING_CONNECT_CHANNEL    ((fsm_event_t) 7)
#define AMPM_L2CAP_EV_TRIGGER_PENDING            ((fsm_event_t) 8)
#define AMPM_L2CAP_EV_CHANNEL_READY_IND          ((fsm_event_t) 9)
#define AMPM_L2CAP_EV_LINK_MODIFIED_SUCCESS      ((fsm_event_t) 10)
#define AMPM_L2CAP_EV_LINK_MODIFIED_FAILURE      ((fsm_event_t) 11)
#define AMPM_L2CAP_EV_CHANNEL_DISCONNECT_IND     ((fsm_event_t) 12)
#define AMPM_L2CAP_EV_PENDING_DISCONNECT_CHANNEL ((fsm_event_t) 13)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_INDEX) */
#define AMPM_L2CAP_AC_MAX 11
#define AMPM_L2CAP_AC_ObtainPhysicalLink              ((fsm_action_t) 0)
#define AMPM_L2CAP_AC_CreateChannel                   ((fsm_action_t) 1)
#define AMPM_L2CAP_AC_DisconnectChannelBeforePhysical ((fsm_action_t) 2)
#define AMPM_L2CAP_AC_DeleteReq                       ((fsm_action_t) 3)
#define AMPM_L2CAP_AC_PhysicalLinkReadyInd            ((fsm_action_t) 4)
#define AMPM_L2CAP_AC_SendDmAmpmConnectRspFail        ((fsm_action_t) 5)
#define AMPM_L2CAP_AC_DisconnectChannel               ((fsm_action_t) 6)
#define AMPM_L2CAP_AC_ChannelReadyInd                 ((fsm_action_t) 7)
#define AMPM_L2CAP_AC_SendDmAmpmConnectChannelRspFail ((fsm_action_t) 8)
#define AMPM_L2CAP_AC_DisconnectChannelBeforeLogical  ((fsm_action_t) 9)
#define AMPM_L2CAP_AC_ChannelDisconnected             ((fsm_action_t) 10)
#define AMPM_L2CAP_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_L2CAP, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_l2cap_fsm;
/*}}__FSM_END_MARKER(CSR_BT_AMPM_L2CAP, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_AMPM_L2CAP_GENFSM_H */

