/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_local_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_ampm_local_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_ampm_local_action_fns[] =
{
    CsrBtAmpmLocalFsmReadInfoReqPending,
    CsrBtAmpmLocalFsmDeleteReq,
    CsrBtAmpmLocalFsmHciNopCmdComplete,
    CsrBtAmpmLocalFsmReadInfoSuccess,
    CsrBtAmpmLocalFsmReadInfoFailure,
    CsrBtAmpmLocalFsmReadAssocSuccess,
    CsrBtAmpmLocalFsmReadAssocFailure,
    CsrBtAmpmLocalFsmReadAssocCompleted,
    CsrBtAmpmLocalFsmWriteRemoteAssocSuccess,
    CsrBtAmpmLocalFsmWriteRemoteAssocFailure,
    CsrBtAmpmLocalFsmWriteRemoteAssocCompleted,
    CsrBtAmpmLocalFsmReadAssocReq,
    CsrBtAmpmLocalFsmWriteRemoteAssocReq,
    CsrBtAmpmLocalFsmPowerOnInd,
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_ampm_local_transitions[] = {
  /* NULL */
  { AMPM_LOCAL_EV_READ_INFO_REQ,              AMPM_LOCAL_AC_ReadInfoReqPending,         AMPM_LOCAL_ST_WAIT_INFO },
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_HciNopCmdComplete,          AMPM_LOCAL_ST_NULL },
  /* WAIT_INFO */
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_WAIT_INFO },
  { AMPM_LOCAL_EV_HCI_READ_INFO_SUCCESS,      AMPM_LOCAL_AC_ReadInfoSuccess,            AMPM_LOCAL_ST_REGISTERED },
  { AMPM_LOCAL_EV_HCI_READ_INFO_FAILURE,      AMPM_LOCAL_AC_ReadInfoFailure,            AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_RESPONSE_TIMEOUT_IND,   AMPM_LOCAL_AC_ReadInfoFailure,            AMPM_LOCAL_ST_NULL },
  /* WAIT_ASSOC */
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_WAIT_ASSOC },
  { AMPM_LOCAL_EV_HCI_RESPONSE_TIMEOUT_IND,   AMPM_LOCAL_AC_ReadAssocFailure,           AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_READ_ASSOC_REQ,             AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_WAIT_ASSOC },
  { AMPM_LOCAL_EV_HCI_READ_ASSOC_SUCCESS,     AMPM_LOCAL_AC_ReadAssocSuccess,           AMPM_LOCAL_ST_WAIT_ASSOC },
  { AMPM_LOCAL_EV_HCI_READ_ASSOC_FAILURE,     AMPM_LOCAL_AC_ReadAssocFailure,           AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_READ_ASSOC_COMPLETE,    AMPM_LOCAL_AC_ReadAssocCompleted,         AMPM_LOCAL_ST_REGISTERED },
  /* WRITING_REMOTE_ASSOC */
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC },
  { AMPM_LOCAL_EV_HCI_RESPONSE_TIMEOUT_IND,   AMPM_LOCAL_AC_WriteRemoteAssocFailure,    AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_READ_ASSOC_REQ,             AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC },
  { AMPM_LOCAL_EV_REMOTE_ASSOC_SUCCESS,       AMPM_LOCAL_AC_WriteRemoteAssocSuccess,    AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC },
  { AMPM_LOCAL_EV_REMOTE_ASSOC_FAILURE,       AMPM_LOCAL_AC_WriteRemoteAssocFailure,    AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_REMOTE_ASSOC_COMPLETE,      AMPM_LOCAL_AC_WriteRemoteAssocCompleted,  AMPM_LOCAL_ST_REGISTERED },
  /* REGISTERED */
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_REGISTERED },
  { AMPM_LOCAL_EV_READ_ASSOC_REQ,             AMPM_LOCAL_AC_ReadAssocReq,               AMPM_LOCAL_ST_WAIT_ASSOC },
  { AMPM_LOCAL_EV_WRITE_REMOTE_ASSOC_REQ,     AMPM_LOCAL_AC_WriteRemoteAssocReq,        AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC },
  { AMPM_LOCAL_EV_POWER_ON_GET_ASSOC_REQ,     AMPM_LOCAL_AC_PowerOnInd,                 AMPM_LOCAL_ST_POWER_ON_READ_ASSOC },
  /* POWER_ON_READ_ASSOC */
  { AMPM_LOCAL_EV_DELETE_REQ,                 AMPM_LOCAL_AC_DeleteReq,                  AMPM_LOCAL_ST_NULL },
  { AMPM_LOCAL_EV_HCI_NOP_EVENT,              AMPM_LOCAL_AC_NULL,                       AMPM_LOCAL_ST_POWER_ON_READ_ASSOC },
  { AMPM_LOCAL_EV_POWER_ON_OK,                AMPM_LOCAL_AC_ReadAssocReq,               AMPM_LOCAL_ST_WAIT_ASSOC },
  { AMPM_LOCAL_EV_POWER_ON_FAILURE,           AMPM_LOCAL_AC_ReadAssocFailure,           AMPM_LOCAL_ST_NULL }
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_ampm_local_states[AMPM_LOCAL_ST_ST_MAX+1] = {
    { &csr_bt_ampm_local_transitions[0] },
    { &csr_bt_ampm_local_transitions[3] },
    { &csr_bt_ampm_local_transitions[8] },
    { &csr_bt_ampm_local_transitions[15] },
    { &csr_bt_ampm_local_transitions[22] },
    { &csr_bt_ampm_local_transitions[27] },
    { &csr_bt_ampm_local_transitions[31] },
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, FSM_LOGGING) */
/* State names */
const char *const csr_bt_ampm_local_state_names[] =
{
    "AMPM_LOCAL_ST_NULL",
    "AMPM_LOCAL_ST_WAIT_INFO",
    "AMPM_LOCAL_ST_WAIT_ASSOC",
    "AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC",
    "AMPM_LOCAL_ST_REGISTERED",
    "AMPM_LOCAL_ST_POWER_ON_READ_ASSOC",
};
#define CSR_BT_AMPM_LOCAL_STATE_NAMES_PTR (csr_bt_ampm_local_state_names)

/* Event names */
const char *const csr_bt_ampm_local_event_names[] =
{
    "AMPM_LOCAL_EV_READ_INFO_REQ",
    "AMPM_LOCAL_EV_DELETE_REQ",
    "AMPM_LOCAL_EV_HCI_NOP_EVENT",
    "AMPM_LOCAL_EV_HCI_READ_INFO_SUCCESS",
    "AMPM_LOCAL_EV_HCI_READ_INFO_FAILURE",
    "AMPM_LOCAL_EV_HCI_RESPONSE_TIMEOUT_IND",
    "AMPM_LOCAL_EV_READ_ASSOC_REQ",
    "AMPM_LOCAL_EV_HCI_READ_ASSOC_SUCCESS",
    "AMPM_LOCAL_EV_HCI_READ_ASSOC_FAILURE",
    "AMPM_LOCAL_EV_HCI_READ_ASSOC_COMPLETE",
    "AMPM_LOCAL_EV_REMOTE_ASSOC_SUCCESS",
    "AMPM_LOCAL_EV_REMOTE_ASSOC_FAILURE",
    "AMPM_LOCAL_EV_REMOTE_ASSOC_COMPLETE",
    "AMPM_LOCAL_EV_WRITE_REMOTE_ASSOC_REQ",
    "AMPM_LOCAL_EV_POWER_ON_GET_ASSOC_REQ",
    "AMPM_LOCAL_EV_POWER_ON_OK",
    "AMPM_LOCAL_EV_POWER_ON_FAILURE",
};
#define CSR_BT_AMPM_LOCAL_EVENT_NAMES_PTR (csr_bt_ampm_local_event_names)

/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, FSM_LOGGING) */
#else
#define CSR_BT_AMPM_LOCAL_STATE_NAMES_PTR (NULL)
#define CSR_BT_AMPM_LOCAL_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_local_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_ampm_local_states,
    csr_bt_ampm_local_action_fns
    FSM_LOG_INFO("CSR_BT_AMPM_LOCAL",
    CSR_BT_AMPM_LOCAL_STATE_NAMES_PTR,
    CSR_BT_AMPM_LOCAL_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, FSM_DEFINITION) */

