/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_btdev_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_ampm_btdev_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_ampm_btdev_action_fns[] =
{
    CsrBtAmpmBtdevFsmCheckExtFeatures,
    CsrBtAmpmBtdevFsmL2caMapFixedCidInd,
    CsrBtAmpmBtdevFsmDeleteReq,
    CsrBtAmpmBtdevFsmFixedChannelSupported,
    CsrBtAmpmBtdevFsmAmpmChannelSupported,
    CsrBtAmpmBtdevFsmL2caMapFixedCidCfm,
    CsrBtAmpmBtdevFsmRunDiscovery,
    CsrBtAmpmBtdevFsmAmpDiscoverRsp,
    CsrBtAmpmBtdevFsmAmpDiscoverRejected,
    CsrBtAmpmBtdevFsmAmpDiscoverReq,
    CsrBtAmpmBtdevFsmAmpChangeInd,
    CsrBtAmpmBtdevFsmAmpGetInfoRsp,
    CsrBtAmpmBtdevFsmLocalAmpChangeInd,
    CsrBtAmpmBtdevFsmDisconnectReq,
    CsrBtAmpmBtdevFsmDisconnectInd,
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_ampm_btdev_transitions[] = {
  /* NULL */
  { AMPM_BTDEV_EV_DISCOVER_EV,                 AMPM_BTDEV_AC_CheckExtFeatures,       AMPM_BTDEV_ST_CHECKING_FEATURES },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND,      AMPM_BTDEV_AC_L2caMapFixedCidInd,     AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_DELETE_REQ,                  AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_DISCONNECT_IND,              AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  /* CHECKING_FEATURES */
  { AMPM_BTDEV_EV_DISCOVER_EV,                 AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CHECKING_FEATURES },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND,      AMPM_BTDEV_AC_L2caMapFixedCidInd,     AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_DELETE_REQ,                  AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_DISCONNECT_IND,              AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_FIXED_CHANS_SUPPORTED_IND,   AMPM_BTDEV_AC_FixedChannelSupported,  AMPM_BTDEV_ST_CHECKING_FEATURES },
  { AMPM_BTDEV_EV_AMPM_CHAN_SUPPORTED_IND,     AMPM_BTDEV_AC_AmpmChannelSupported,   AMPM_BTDEV_ST_WAITING_FOR_CID },
  { AMPM_BTDEV_EV_LOCAL_AMP_CHANGE_IND,        AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CHECKING_FEATURES },
  /* WAITING_FOR_CID */
  { AMPM_BTDEV_EV_DISCOVER_EV,                 AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_WAITING_FOR_CID },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND,      AMPM_BTDEV_AC_L2caMapFixedCidInd,     AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_DELETE_REQ,                  AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_DISCONNECT_IND,              AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_LOCAL_AMP_CHANGE_IND,        AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_WAITING_FOR_CID },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_CFM,      AMPM_BTDEV_AC_L2caMapFixedCidCfm,     AMPM_BTDEV_ST_CONNECTED },
  /* CONNECTED */
  { AMPM_BTDEV_EV_DISCOVER_EV,                 AMPM_BTDEV_AC_RunDiscovery,           AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND,      AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_DELETE_REQ,                  AMPM_BTDEV_AC_DeleteReq,              AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_DISCONNECT_IND,              AMPM_BTDEV_AC_DisconnectInd,          AMPM_BTDEV_ST_NULL },
  { AMPM_BTDEV_EV_FIXED_CHANS_SUPPORTED_IND,   AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMPM_CHAN_SUPPORTED_IND,     AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_LOCAL_AMP_CHANGE_IND,        AMPM_BTDEV_AC_LocalAmpChangeInd,      AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_CFM,      AMPM_BTDEV_AC_NULL,                   AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMP_DISCOVER_RESPONSE,       AMPM_BTDEV_AC_AmpDiscoverRsp,         AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMP_COMMAND_REJECT,          AMPM_BTDEV_AC_AmpDiscoverRejected,    AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMP_DISCOVER_REQUEST,        AMPM_BTDEV_AC_AmpDiscoverReq,         AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMP_CHANGE_NOTIFY,           AMPM_BTDEV_AC_AmpChangeInd,           AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_AMP_GET_INFO_RESPONSE,       AMPM_BTDEV_AC_AmpGetInfoRsp,          AMPM_BTDEV_ST_CONNECTED },
  { AMPM_BTDEV_EV_DISCONNECT_REQ,              AMPM_BTDEV_AC_DisconnectReq,          AMPM_BTDEV_ST_NULL }
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_ampm_btdev_states[AMPM_BTDEV_ST_ST_MAX+1] = {
    { &csr_bt_ampm_btdev_transitions[0] },
    { &csr_bt_ampm_btdev_transitions[4] },
    { &csr_bt_ampm_btdev_transitions[11] },
    { &csr_bt_ampm_btdev_transitions[17] },
    { &csr_bt_ampm_btdev_transitions[31] },
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, FSM_LOGGING) */
/* State names */
const char *const csr_bt_ampm_btdev_state_names[] =
{
    "AMPM_BTDEV_ST_NULL",
    "AMPM_BTDEV_ST_CHECKING_FEATURES",
    "AMPM_BTDEV_ST_WAITING_FOR_CID",
    "AMPM_BTDEV_ST_CONNECTED",
};
#define CSR_BT_AMPM_BTDEV_STATE_NAMES_PTR (csr_bt_ampm_btdev_state_names)

/* Event names */
const char *const csr_bt_ampm_btdev_event_names[] =
{
    "AMPM_BTDEV_EV_DISCOVER_EV",
    "AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_IND",
    "AMPM_BTDEV_EV_DELETE_REQ",
    "AMPM_BTDEV_EV_DISCONNECT_IND",
    "AMPM_BTDEV_EV_FIXED_CHANS_SUPPORTED_IND",
    "AMPM_BTDEV_EV_AMPM_CHAN_SUPPORTED_IND",
    "AMPM_BTDEV_EV_LOCAL_AMP_CHANGE_IND",
    "AMPM_BTDEV_EV_L2CA_MAP_FIXED_CID_CFM",
    "AMPM_BTDEV_EV_AMP_DISCOVER_RESPONSE",
    "AMPM_BTDEV_EV_AMP_COMMAND_REJECT",
    "AMPM_BTDEV_EV_AMP_DISCOVER_REQUEST",
    "AMPM_BTDEV_EV_AMP_CHANGE_NOTIFY",
    "AMPM_BTDEV_EV_AMP_GET_INFO_RESPONSE",
    "AMPM_BTDEV_EV_DISCONNECT_REQ",
};
#define CSR_BT_AMPM_BTDEV_EVENT_NAMES_PTR (csr_bt_ampm_btdev_event_names)

/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, FSM_LOGGING) */
#else
#define CSR_BT_AMPM_BTDEV_STATE_NAMES_PTR (NULL)
#define CSR_BT_AMPM_BTDEV_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_BTDEV, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_btdev_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_ampm_btdev_states,
    csr_bt_ampm_btdev_action_fns
    FSM_LOG_INFO("CSR_BT_AMPM_BTDEV",
    CSR_BT_AMPM_BTDEV_STATE_NAMES_PTR,
    CSR_BT_AMPM_BTDEV_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_AMPM_BTDEV, FSM_DEFINITION) */

