#ifndef _CSR_BT_AMPM_LOCAL_GENFSM_H
#define _CSR_BT_AMPM_LOCAL_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_ampm_local_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadInfoReqPending);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmDeleteReq);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmHciNopCmdComplete);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadInfoSuccess);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadInfoFailure);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadAssocSuccess);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadAssocFailure);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadAssocCompleted);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmWriteRemoteAssocSuccess);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmWriteRemoteAssocFailure);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmWriteRemoteAssocCompleted);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmReadAssocReq);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmWriteRemoteAssocReq);
extern FSM_ACTION_FN(CsrBtAmpmLocalFsmPowerOnInd);
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, STATE_DECLARATIONS) */
#define AMPM_LOCAL_ST_ST_MAX 6
#define AMPM_LOCAL_ST_NULL                 ((fsm_state_t) 0)
#define AMPM_LOCAL_ST_WAIT_INFO            ((fsm_state_t) 1)
#define AMPM_LOCAL_ST_WAIT_ASSOC           ((fsm_state_t) 2)
#define AMPM_LOCAL_ST_WRITING_REMOTE_ASSOC ((fsm_state_t) 3)
#define AMPM_LOCAL_ST_REGISTERED           ((fsm_state_t) 4)
#define AMPM_LOCAL_ST_POWER_ON_READ_ASSOC  ((fsm_state_t) 5)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, EVENT_DECLARATIONS) */
#define AMPM_LOCAL_EV_READ_INFO_REQ            ((fsm_event_t) 0)
#define AMPM_LOCAL_EV_DELETE_REQ               ((fsm_event_t) 1)
#define AMPM_LOCAL_EV_HCI_NOP_EVENT            ((fsm_event_t) 2)
#define AMPM_LOCAL_EV_HCI_READ_INFO_SUCCESS    ((fsm_event_t) 3)
#define AMPM_LOCAL_EV_HCI_READ_INFO_FAILURE    ((fsm_event_t) 4)
#define AMPM_LOCAL_EV_HCI_RESPONSE_TIMEOUT_IND ((fsm_event_t) 5)
#define AMPM_LOCAL_EV_READ_ASSOC_REQ           ((fsm_event_t) 6)
#define AMPM_LOCAL_EV_HCI_READ_ASSOC_SUCCESS   ((fsm_event_t) 7)
#define AMPM_LOCAL_EV_HCI_READ_ASSOC_FAILURE   ((fsm_event_t) 8)
#define AMPM_LOCAL_EV_HCI_READ_ASSOC_COMPLETE  ((fsm_event_t) 9)
#define AMPM_LOCAL_EV_REMOTE_ASSOC_SUCCESS     ((fsm_event_t) 10)
#define AMPM_LOCAL_EV_REMOTE_ASSOC_FAILURE     ((fsm_event_t) 11)
#define AMPM_LOCAL_EV_REMOTE_ASSOC_COMPLETE    ((fsm_event_t) 12)
#define AMPM_LOCAL_EV_WRITE_REMOTE_ASSOC_REQ   ((fsm_event_t) 13)
#define AMPM_LOCAL_EV_POWER_ON_GET_ASSOC_REQ   ((fsm_event_t) 14)
#define AMPM_LOCAL_EV_POWER_ON_OK              ((fsm_event_t) 15)
#define AMPM_LOCAL_EV_POWER_ON_FAILURE         ((fsm_event_t) 16)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_INDEX) */
#define AMPM_LOCAL_AC_MAX 14
#define AMPM_LOCAL_AC_ReadInfoReqPending        ((fsm_action_t) 0)
#define AMPM_LOCAL_AC_DeleteReq                 ((fsm_action_t) 1)
#define AMPM_LOCAL_AC_HciNopCmdComplete         ((fsm_action_t) 2)
#define AMPM_LOCAL_AC_ReadInfoSuccess           ((fsm_action_t) 3)
#define AMPM_LOCAL_AC_ReadInfoFailure           ((fsm_action_t) 4)
#define AMPM_LOCAL_AC_ReadAssocSuccess          ((fsm_action_t) 5)
#define AMPM_LOCAL_AC_ReadAssocFailure          ((fsm_action_t) 6)
#define AMPM_LOCAL_AC_ReadAssocCompleted        ((fsm_action_t) 7)
#define AMPM_LOCAL_AC_WriteRemoteAssocSuccess   ((fsm_action_t) 8)
#define AMPM_LOCAL_AC_WriteRemoteAssocFailure   ((fsm_action_t) 9)
#define AMPM_LOCAL_AC_WriteRemoteAssocCompleted ((fsm_action_t) 10)
#define AMPM_LOCAL_AC_ReadAssocReq              ((fsm_action_t) 11)
#define AMPM_LOCAL_AC_WriteRemoteAssocReq       ((fsm_action_t) 12)
#define AMPM_LOCAL_AC_PowerOnInd                ((fsm_action_t) 13)
#define AMPM_LOCAL_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_AMPM_LOCAL, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_ampm_local_fsm;
/*}}__FSM_END_MARKER(CSR_BT_AMPM_LOCAL, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_AMPM_LOCAL_GENFSM_H */

