/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_gatt_conn_genfsm.c

\brief  FSM constants.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_gatt_conn_genfsm.h"

/* Action function table */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, ACTION_FN_TABLE) */
static const fsm_action_fn_t csr_bt_gatt_conn_action_fns[] =
{
    CsrBtGattConnFsmCentralReq,
    CsrBtGattConnFsmPeripheralReq,
    CsrBtGattConnFsmBredrConnectReq,
    CsrBtGattConnFsmBredrAcceptReq,
    CsrBtGattConnFsmCentralParamOk,
    CsrBtGattConnFsmCentralFail,
    CsrBtGattConnFsmCentralOk,
    CsrBtGattConnFsmCentralPending,
    CsrBtGattConnFsmPeripheralParamOk,
    CsrBtGattConnFsmPeripheralFail,
    CsrBtGattConnFsmPeripheralOk,
    CsrBtGattConnFsmPeripheralPending,
    CsrBtGattConnFsmBredrConnectOk,
    CsrBtGattConnFsmBredrConnectPending,
    CsrBtGattConnFsmBredrConnectFail,
    CsrBtGattConnFsmBredrAcceptOk,
    CsrBtGattConnFsmConnectFail,
    CsrBtGattConnFsmBredrAcceptStop,
    CsrBtGattConnFsmConnectOk,
    CsrBtGattConnFsmDisconnectReq,
    CsrBtGattConnFsmDisconnectInd,
    CsrBtGattConnFsmPurge,
};
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, ACTION_FN_TABLE) */

/*
 * Actions-per-state initialisation code
 * Format:
 *      Event, Action index, Next state
 */

/*{{__FSM_MARKER(CSR_BT_GATT_CONN, STATE_TABLES) */
static const FSM_SPARSE16_TRANSITION_T csr_bt_gatt_conn_transitions[] = {
  /* NULL */
  { GATT_CONN_EV_CENTRAL_REQ,         GATT_CONN_AC_CentralReq,           GATT_CONN_ST_CENTRAL },
  { GATT_CONN_EV_PERIPHERAL_REQ,      GATT_CONN_AC_PeripheralReq,        GATT_CONN_ST_PERIPHERAL },
  { GATT_CONN_EV_BREDR_CONNECT_REQ,   GATT_CONN_AC_BredrConnectReq,      GATT_CONN_ST_BREDR_CONNECT },
  { GATT_CONN_EV_BREDR_ACCEPT_REQ,    GATT_CONN_AC_BredrAcceptReq,       GATT_CONN_ST_BREDR_ACCEPT },
  /* CENTRAL */
  { GATT_CONN_EV_PARAM_OK,            GATT_CONN_AC_CentralParamOk,       GATT_CONN_ST_CENTRAL },
  { GATT_CONN_EV_PARAM_FAIL,          GATT_CONN_AC_CentralFail,          GATT_CONN_ST_NULL },
  { GATT_CONN_EV_CONNECT_OK,          GATT_CONN_AC_CentralOk,            GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_PENDING,     GATT_CONN_AC_CentralPending,       GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_CentralFail,          GATT_CONN_ST_NULL },
  /* PERIPHERAL */
  { GATT_CONN_EV_PARAM_OK,            GATT_CONN_AC_PeripheralParamOk,    GATT_CONN_ST_PERIPHERAL },
  { GATT_CONN_EV_PARAM_FAIL,          GATT_CONN_AC_PeripheralFail,       GATT_CONN_ST_NULL },
  { GATT_CONN_EV_CONNECT_OK,          GATT_CONN_AC_PeripheralOk,         GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_PENDING,     GATT_CONN_AC_PeripheralPending,    GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_PeripheralFail,       GATT_CONN_ST_NULL },
  /* BREDR_CONNECT */
  { GATT_CONN_EV_CONNECT_OK,          GATT_CONN_AC_BredrConnectOk,       GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_PENDING,     GATT_CONN_AC_BredrConnectPending,  GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_BredrConnectFail,     GATT_CONN_ST_NULL },
  /* BREDR_ACCEPT */
  { GATT_CONN_EV_CONNECT_OK,          GATT_CONN_AC_BredrAcceptOk,        GATT_CONN_ST_PENDING },
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_ConnectFail,          GATT_CONN_ST_NULL },
  { GATT_CONN_EV_DISCONNECT_REQ,      GATT_CONN_AC_BredrAcceptStop,      GATT_CONN_ST_DISCONNECTING },
  /* PENDING */
  { GATT_CONN_EV_CONNECT_OK,          GATT_CONN_AC_ConnectOk,            GATT_CONN_ST_CONNECTED },
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_ConnectFail,          GATT_CONN_ST_NULL },
  { GATT_CONN_EV_DISCONNECT_REQ,      GATT_CONN_AC_DisconnectReq,        GATT_CONN_ST_DISCONNECTING },
  /* CONNECTED */
  { GATT_CONN_EV_DISCONNECT_REQ,      GATT_CONN_AC_DisconnectReq,        GATT_CONN_ST_DISCONNECTING },
  { GATT_CONN_EV_DISCONNECT_IND,      GATT_CONN_AC_DisconnectInd,        GATT_CONN_ST_DISCONNECTING },
  /* DISCONNECTING */
  { GATT_CONN_EV_CONNECT_FAIL,        GATT_CONN_AC_DisconnectInd,        GATT_CONN_ST_DISCONNECTING },
  { GATT_CONN_EV_DISCONNECT_IND,      GATT_CONN_AC_DisconnectInd,        GATT_CONN_ST_DISCONNECTING },
  { GATT_CONN_EV_PURGED,              GATT_CONN_AC_Purge,                GATT_CONN_ST_NULL }
};
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, STATE_TABLES) */

/* State array declarations */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, STATE_ARRAY) */
static const FSM_SPARSE16_STATES_T csr_bt_gatt_conn_states[GATT_CONN_ST_ST_MAX+1] = {
    { &csr_bt_gatt_conn_transitions[0] },
    { &csr_bt_gatt_conn_transitions[4] },
    { &csr_bt_gatt_conn_transitions[9] },
    { &csr_bt_gatt_conn_transitions[14] },
    { &csr_bt_gatt_conn_transitions[17] },
    { &csr_bt_gatt_conn_transitions[20] },
    { &csr_bt_gatt_conn_transitions[23] },
    { &csr_bt_gatt_conn_transitions[25] },
    { &csr_bt_gatt_conn_transitions[28] },
};
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, STATE_ARRAY) */

/* FSM logging definitions */
#if defined(FSM_DEBUG_NAMES)
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, FSM_LOGGING) */
/* State names */
const char *const csr_bt_gatt_conn_state_names[] =
{
    "GATT_CONN_ST_NULL",
    "GATT_CONN_ST_CENTRAL",
    "GATT_CONN_ST_PERIPHERAL",
    "GATT_CONN_ST_BREDR_CONNECT",
    "GATT_CONN_ST_BREDR_ACCEPT",
    "GATT_CONN_ST_PENDING",
    "GATT_CONN_ST_CONNECTED",
    "GATT_CONN_ST_DISCONNECTING",
};
#define CSR_BT_GATT_CONN_STATE_NAMES_PTR (csr_bt_gatt_conn_state_names)

/* Event names */
const char *const csr_bt_gatt_conn_event_names[] =
{
    "GATT_CONN_EV_CENTRAL_REQ",
    "GATT_CONN_EV_PERIPHERAL_REQ",
    "GATT_CONN_EV_BREDR_CONNECT_REQ",
    "GATT_CONN_EV_BREDR_ACCEPT_REQ",
    "GATT_CONN_EV_PARAM_OK",
    "GATT_CONN_EV_PARAM_FAIL",
    "GATT_CONN_EV_CONNECT_OK",
    "GATT_CONN_EV_CONNECT_PENDING",
    "GATT_CONN_EV_CONNECT_FAIL",
    "GATT_CONN_EV_DISCONNECT_REQ",
    "GATT_CONN_EV_DISCONNECT_IND",
    "GATT_CONN_EV_PURGED",
};
#define CSR_BT_GATT_CONN_EVENT_NAMES_PTR (csr_bt_gatt_conn_event_names)

/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, FSM_LOGGING) */
#else
#define CSR_BT_GATT_CONN_STATE_NAMES_PTR (NULL)
#define CSR_BT_GATT_CONN_EVENT_NAMES_PTR (NULL)
#endif

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, FSM_DEFINITION) */
const FSM_SPARSE16_DEFINITION_T csr_bt_gatt_conn_fsm =
{
    (const FSM_SPARSE16_STATES_T *) csr_bt_gatt_conn_states,
    csr_bt_gatt_conn_action_fns
    FSM_LOG_INFO("CSR_BT_GATT_CONN",
    CSR_BT_GATT_CONN_STATE_NAMES_PTR,
    CSR_BT_GATT_CONN_EVENT_NAMES_PTR)
};
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, FSM_DEFINITION) */

