#ifndef _CSR_BT_GATT_CONN_GENFSM_H
#define _CSR_BT_GATT_CONN_GENFSM_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   csr_bt_gatt_conn_genfsm.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CsrBtGattConnFsmCentralReq);
extern FSM_ACTION_FN(CsrBtGattConnFsmPeripheralReq);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrConnectReq);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrAcceptReq);
extern FSM_ACTION_FN(CsrBtGattConnFsmCentralParamOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmCentralFail);
extern FSM_ACTION_FN(CsrBtGattConnFsmCentralOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmCentralPending);
extern FSM_ACTION_FN(CsrBtGattConnFsmPeripheralParamOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmPeripheralFail);
extern FSM_ACTION_FN(CsrBtGattConnFsmPeripheralOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmPeripheralPending);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrConnectOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrConnectPending);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrConnectFail);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrAcceptOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmConnectFail);
extern FSM_ACTION_FN(CsrBtGattConnFsmBredrAcceptStop);
extern FSM_ACTION_FN(CsrBtGattConnFsmConnectOk);
extern FSM_ACTION_FN(CsrBtGattConnFsmDisconnectReq);
extern FSM_ACTION_FN(CsrBtGattConnFsmDisconnectInd);
extern FSM_ACTION_FN(CsrBtGattConnFsmPurge);
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, STATE_DECLARATIONS) */
#define GATT_CONN_ST_ST_MAX 8
#define GATT_CONN_ST_NULL          ((fsm_state_t) 0)
#define GATT_CONN_ST_CENTRAL       ((fsm_state_t) 1)
#define GATT_CONN_ST_PERIPHERAL    ((fsm_state_t) 2)
#define GATT_CONN_ST_BREDR_CONNECT ((fsm_state_t) 3)
#define GATT_CONN_ST_BREDR_ACCEPT  ((fsm_state_t) 4)
#define GATT_CONN_ST_PENDING       ((fsm_state_t) 5)
#define GATT_CONN_ST_CONNECTED     ((fsm_state_t) 6)
#define GATT_CONN_ST_DISCONNECTING ((fsm_state_t) 7)
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, EVENT_DECLARATIONS) */
#define GATT_CONN_EV_CENTRAL_REQ       ((fsm_event_t) 0)
#define GATT_CONN_EV_PERIPHERAL_REQ    ((fsm_event_t) 1)
#define GATT_CONN_EV_BREDR_CONNECT_REQ ((fsm_event_t) 2)
#define GATT_CONN_EV_BREDR_ACCEPT_REQ  ((fsm_event_t) 3)
#define GATT_CONN_EV_PARAM_OK          ((fsm_event_t) 4)
#define GATT_CONN_EV_PARAM_FAIL        ((fsm_event_t) 5)
#define GATT_CONN_EV_CONNECT_OK        ((fsm_event_t) 6)
#define GATT_CONN_EV_CONNECT_PENDING   ((fsm_event_t) 7)
#define GATT_CONN_EV_CONNECT_FAIL      ((fsm_event_t) 8)
#define GATT_CONN_EV_DISCONNECT_REQ    ((fsm_event_t) 9)
#define GATT_CONN_EV_DISCONNECT_IND    ((fsm_event_t) 10)
#define GATT_CONN_EV_PURGED            ((fsm_event_t) 11)
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, ACTION_FN_INDEX) */
#define GATT_CONN_AC_MAX 22
#define GATT_CONN_AC_CentralReq          ((fsm_action_t) 0)
#define GATT_CONN_AC_PeripheralReq       ((fsm_action_t) 1)
#define GATT_CONN_AC_BredrConnectReq     ((fsm_action_t) 2)
#define GATT_CONN_AC_BredrAcceptReq      ((fsm_action_t) 3)
#define GATT_CONN_AC_CentralParamOk      ((fsm_action_t) 4)
#define GATT_CONN_AC_CentralFail         ((fsm_action_t) 5)
#define GATT_CONN_AC_CentralOk           ((fsm_action_t) 6)
#define GATT_CONN_AC_CentralPending      ((fsm_action_t) 7)
#define GATT_CONN_AC_PeripheralParamOk   ((fsm_action_t) 8)
#define GATT_CONN_AC_PeripheralFail      ((fsm_action_t) 9)
#define GATT_CONN_AC_PeripheralOk        ((fsm_action_t) 10)
#define GATT_CONN_AC_PeripheralPending   ((fsm_action_t) 11)
#define GATT_CONN_AC_BredrConnectOk      ((fsm_action_t) 12)
#define GATT_CONN_AC_BredrConnectPending ((fsm_action_t) 13)
#define GATT_CONN_AC_BredrConnectFail    ((fsm_action_t) 14)
#define GATT_CONN_AC_BredrAcceptOk       ((fsm_action_t) 15)
#define GATT_CONN_AC_ConnectFail         ((fsm_action_t) 16)
#define GATT_CONN_AC_BredrAcceptStop     ((fsm_action_t) 17)
#define GATT_CONN_AC_ConnectOk           ((fsm_action_t) 18)
#define GATT_CONN_AC_DisconnectReq       ((fsm_action_t) 19)
#define GATT_CONN_AC_DisconnectInd       ((fsm_action_t) 20)
#define GATT_CONN_AC_Purge               ((fsm_action_t) 21)
#define GATT_CONN_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(CSR_BT_GATT_CONN, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T csr_bt_gatt_conn_fsm;
/*}}__FSM_END_MARKER(CSR_BT_GATT_CONN, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _CSR_BT_GATT_CONN_GENFSM_H */

