#-*-Makefile-*-
###############################################################################
#
#                (c) Cambridge Silicon Radio Limited 2010
#
#                All rights reserved and confidential information of CSR
#
# REVISION:      $Revision: #1 $
###############################################################################
TOP := ../../..

OBJ_PATH = $(TOP)/output/$(CONFIG)/$(TARGET)/obj/src/gatt/code

include $(TOP)/local_rules.mk

MODULE_NAME := gatt

include $(TOP)/profile_managers/pm.mk
