#include "csr_synergy.h"
#if !defined(DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT) && !defined(DISABLE_AMP_FSM_SUPPORT)
#ifndef _L2CAP_CID_FSM_DEFINITIONS_H
#define _L2CAP_CID_FSM_DEFINITIONS_H
/*!
        Copyright (C) CCL, CSR plc 2010
        All rights reserved

\file   l2cap_cid_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CID_FsmDestroyCid);
extern FSM_ACTION_FN(CID_FsmConnectAclReady);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclDown);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclError);
extern FSM_ACTION_FN(CID_FsmConnectAclAbort);
extern FSM_ACTION_FN(CID_FsmConnectInd);
extern FSM_ACTION_FN(CID_FsmConnectReq);
extern FSM_ACTION_FN(CID_FsmConnectCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmConnectCfmOk);
extern FSM_ACTION_FN(CID_FsmConnectCfmNok);
extern FSM_ACTION_FN(CID_FsmConnectCfmPnd);
extern FSM_ACTION_FN(CID_FsmConnectCfmError);
extern FSM_ACTION_FN(CID_FsmConnectCfmAbort);
extern FSM_ACTION_FN(CID_FsmConnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmConnectIndRetry);
extern FSM_ACTION_FN(CID_FsmConnectRspOk);
extern FSM_ACTION_FN(CID_FsmConnectRspNok);
extern FSM_ACTION_FN(CID_FsmConnectRspPnd);
extern FSM_ACTION_FN(CID_FsmDisconnectIndAcl);
extern FSM_ACTION_FN(CID_FsmDisconnectInd);
extern FSM_ACTION_FN(CID_FsmDisconnectReq);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmOk);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmNok);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInvalidCid);
extern FSM_ACTION_FN(CID_FsmConnectIndRetryActive);
extern FSM_ACTION_FN(CID_FsmConfigInd);
extern FSM_ACTION_FN(CID_FsmConfigCfm);
extern FSM_ACTION_FN(CID_FsmConfigReq);
extern FSM_ACTION_FN(CID_FsmConfigRsp);
extern FSM_ACTION_FN(CID_FsmConfigOk);
extern FSM_ACTION_FN(CID_FsmDisconnectIndTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectReqInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectCfm);
extern FSM_ACTION_FN(CID_FsmDisconnectIndCross);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectRsp);
extern FSM_ACTION_FN(CID_FsmDisconnectRspNcp);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInternal);
extern FSM_ACTION_FN(CID_FsmMapFixedCidReq);
extern FSM_ACTION_FN(CID_FsmMapFixedCidInd);
extern FSM_ACTION_FN(CID_FsmFixedAccessOk);
extern FSM_ACTION_FN(CID_FsmFixedDisconnectAcl);
extern FSM_ACTION_FN(CID_FsmFixedDisconnectAbnormal);
extern FSM_ACTION_FN(CID_FsmAmpCreateInd);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndRetryActive);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqBusy);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndBusy);
extern FSM_ACTION_FN(CID_FsmAmpConfigLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpConfigLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReq);
extern FSM_ACTION_FN(CID_FsmAmpMoveInd);
extern FSM_ACTION_FN(CID_FsmAmpDisconnectInd);
extern FSM_ACTION_FN(CID_FsmAmpCleanupReq);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmError);
extern FSM_ACTION_FN(CID_FsmAmpCreateReq);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqVerifyOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmPnd);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmAbort);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmTimeout);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateSmCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateSmCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndRetry);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspPnd);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqVerifyOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmPnd);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveLocLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveLocLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndCollide);
extern FSM_ACTION_FN(CID_FsmAmpConfirmCfm);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmTimeout);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveRspOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveRspNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveRemLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveRemLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpConfirmInd);
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(L2CAP_CID, STATE_DECLARATIONS) */
#define CID_ST_ST_MAX 20
#define CID_ST_NULL              ((fsm_state_t) 0)
#define CID_ST_OPEN_ACL          ((fsm_state_t) 1)
#define CID_ST_CONNECT_LOCAL     ((fsm_state_t) 2)
#define CID_ST_CONNECT_REMOTE    ((fsm_state_t) 3)
#define CID_ST_CONFIG            ((fsm_state_t) 4)
#define CID_ST_OPEN              ((fsm_state_t) 5)
#define CID_ST_DISCONNECT_LOCAL  ((fsm_state_t) 6)
#define CID_ST_DISCONNECT_REMOTE ((fsm_state_t) 7)
#define CID_ST_DISCONNECT_NCP    ((fsm_state_t) 8)
#define CID_ST_DISCONNECT_INTRN  ((fsm_state_t) 9)
#define CID_ST_CONNECT_SM_ACCESS ((fsm_state_t) 10)
#define CID_ST_OPEN_FIXED        ((fsm_state_t) 11)
#define CID_ST_OPEN_AMP_ACL      ((fsm_state_t) 12)
#define CID_ST_CREATE_AMP_LOCAL  ((fsm_state_t) 13)
#define CID_ST_CREATE_AMP_REMOTE ((fsm_state_t) 14)
#define CID_ST_MOVE_AMP_LOCAL    ((fsm_state_t) 15)
#define CID_ST_MOVE_AMP_REMOTE   ((fsm_state_t) 16)
#define CID_ST_DISCONNECT_AMP    ((fsm_state_t) 17)
#define CID_ST_AMP_VERIFY_PHYS   ((fsm_state_t) 18)
#define CID_ST_AMP_SM_ACCESS     ((fsm_state_t) 19)
/*}}__FSM_END_MARKER(L2CAP_CID, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */
#define CID_EV_CID_ACL_CLOSE_IND       ((fsm_event_t) 0)
#define CID_EV_CID_ACL_READY           ((fsm_event_t) 1)
#define CID_EV_CID_ACL_CLOSE_DESTROY   ((fsm_event_t) 2)
#define CID_EV_CID_DISCONNECT_REQ      ((fsm_event_t) 3)
#define CID_EV_CID_CONNECT_REQ         ((fsm_event_t) 4)
#define CID_EV_CID_CONNECT_IND         ((fsm_event_t) 5)
#define CID_EV_SM_ACCESS_CFM_OK        ((fsm_event_t) 6)
#define CID_EV_SM_ACCESS_CFM_NOK       ((fsm_event_t) 7)
#define CID_EV_CID_CONNECT_CFM_OK      ((fsm_event_t) 8)
#define CID_EV_CID_CONNECT_CFM_NOK     ((fsm_event_t) 9)
#define CID_EV_CID_CONNECT_CFM_PND     ((fsm_event_t) 10)
#define CID_EV_CID_DISCONNECT_IND      ((fsm_event_t) 11)
#define CID_EV_CID_TIMEOUT             ((fsm_event_t) 12)
#define CID_EV_CID_INVALID_CID         ((fsm_event_t) 13)
#define CID_EV_CID_CONNECT_IND_RETRY   ((fsm_event_t) 14)
#define CID_EV_CID_CONNECT_RSP_OK      ((fsm_event_t) 15)
#define CID_EV_CID_CONNECT_RSP_NOK     ((fsm_event_t) 16)
#define CID_EV_CID_CONNECT_RSP_PND     ((fsm_event_t) 17)
#define CID_EV_CID_CONFIG_IND          ((fsm_event_t) 18)
#define CID_EV_CID_CONFIG_CFM          ((fsm_event_t) 19)
#define CID_EV_CID_CONFIG_REQ          ((fsm_event_t) 20)
#define CID_EV_CID_CONFIG_RSP          ((fsm_event_t) 21)
#define CID_EV_CID_CONFIG_OK           ((fsm_event_t) 22)
#define CID_EV_CID_CONFIG_TIMEOUT      ((fsm_event_t) 23)
#define CID_EV_CID_INTERNAL_DISC_REQ   ((fsm_event_t) 24)
#define CID_EV_CID_DISCONNECT_CFM      ((fsm_event_t) 25)
#define CID_EV_CID_DISCONNECT_RSP      ((fsm_event_t) 26)
#define CID_EV_CID_SIGNAL_NCP_IND      ((fsm_event_t) 27)
#define CID_EV_CID_MAP_FIXED_REQ       ((fsm_event_t) 28)
#define CID_EV_CID_MAP_FIXED_IND       ((fsm_event_t) 29)
#define CID_EV_CID_MAP_BROADCAST       ((fsm_event_t) 30)
#define CID_EV_CID_FIXED_ACCESS_CFM_OK ((fsm_event_t) 31)
#define CID_EV_CID_AMP_CREATE_REQ      ((fsm_event_t) 32)
#define CID_EV_CID_AMP_CREATE_IND      ((fsm_event_t) 33)
#define CID_EV_CID_AMP_CREATE_IND_RET  ((fsm_event_t) 34)
#define CID_EV_CID_AMP_MOVE_REQ        ((fsm_event_t) 35)
#define CID_EV_CID_AMP_MOVE_IND        ((fsm_event_t) 36)
#define CID_EV_CID_AMP_LOGICAL_CFM_OK  ((fsm_event_t) 37)
#define CID_EV_CID_AMP_LOGICAL_CFM_NOK ((fsm_event_t) 38)
#define CID_EV_CID_AMP_DISCONNECT_IND  ((fsm_event_t) 39)
#define CID_EV_CID_AMP_CLEANUP_REQ     ((fsm_event_t) 40)
#define CID_EV_CID_AMP_PHYS_CFM_OK     ((fsm_event_t) 41)
#define CID_EV_CID_AMP_PHYS_CFM_NOK    ((fsm_event_t) 42)
#define CID_EV_CID_AMP_VERIFY_PHYS_OK  ((fsm_event_t) 43)
#define CID_EV_CID_AMP_CREATE_CFM_OK   ((fsm_event_t) 44)
#define CID_EV_CID_AMP_CREATE_CFM_PND  ((fsm_event_t) 45)
#define CID_EV_CID_AMP_CREATE_CFM_NOK  ((fsm_event_t) 46)
#define CID_EV_CID_AMP_VERIFY_PHYS_NOK ((fsm_event_t) 47)
#define CID_EV_CID_AMP_CREATE_RSP_OK   ((fsm_event_t) 48)
#define CID_EV_CID_AMP_CREATE_RSP_PND  ((fsm_event_t) 49)
#define CID_EV_CID_AMP_CREATE_RSP_NOK  ((fsm_event_t) 50)
#define CID_EV_CID_AMP_MOVE_CFM_NOK    ((fsm_event_t) 51)
#define CID_EV_CID_AMP_MOVE_CFM_PND    ((fsm_event_t) 52)
#define CID_EV_CID_AMP_MOVE_CFM_OK     ((fsm_event_t) 53)
#define CID_EV_CID_AMP_MOVE_RSP_PND    ((fsm_event_t) 54)
#define CID_EV_CID_AMP_CONFIRM_CFM     ((fsm_event_t) 55)
#define CID_EV_CID_AMP_MOVE_CANCEL     ((fsm_event_t) 56)
#define CID_EV_CID_AMP_MOVE_RSP_OK     ((fsm_event_t) 57)
#define CID_EV_CID_AMP_MOVE_RSP_NOK    ((fsm_event_t) 58)
#define CID_EV_CID_AMP_CONFIRM_IND     ((fsm_event_t) 59)
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_INDEX) */
#define CID_AC_MAX 91
#define CID_AC_DestroyCid              ((fsm_action_t) 0)
#define CID_AC_ConnectAclReady         ((fsm_action_t) 1)
#define CID_AC_ConnectCfmAclDown       ((fsm_action_t) 2)
#define CID_AC_ConnectCfmAclError      ((fsm_action_t) 3)
#define CID_AC_ConnectAclAbort         ((fsm_action_t) 4)
#define CID_AC_ConnectInd              ((fsm_action_t) 5)
#define CID_AC_ConnectReq              ((fsm_action_t) 6)
#define CID_AC_ConnectCfmErrorSec      ((fsm_action_t) 7)
#define CID_AC_ConnectCfmOk            ((fsm_action_t) 8)
#define CID_AC_ConnectCfmNok           ((fsm_action_t) 9)
#define CID_AC_ConnectCfmPnd           ((fsm_action_t) 10)
#define CID_AC_ConnectCfmError         ((fsm_action_t) 11)
#define CID_AC_ConnectCfmAbort         ((fsm_action_t) 12)
#define CID_AC_ConnectCfmTimeout       ((fsm_action_t) 13)
#define CID_AC_ConnectIndRetry         ((fsm_action_t) 14)
#define CID_AC_ConnectRspOk            ((fsm_action_t) 15)
#define CID_AC_ConnectRspNok           ((fsm_action_t) 16)
#define CID_AC_ConnectRspPnd           ((fsm_action_t) 17)
#define CID_AC_DisconnectIndAcl        ((fsm_action_t) 18)
#define CID_AC_DisconnectInd           ((fsm_action_t) 19)
#define CID_AC_DisconnectReq           ((fsm_action_t) 20)
#define CID_AC_SmAccessCfmOk           ((fsm_action_t) 21)
#define CID_AC_SmAccessCfmNok          ((fsm_action_t) 22)
#define CID_AC_DisconnectIndInvalidCid ((fsm_action_t) 23)
#define CID_AC_ConnectIndRetryActive   ((fsm_action_t) 24)
#define CID_AC_ConfigInd               ((fsm_action_t) 25)
#define CID_AC_ConfigCfm               ((fsm_action_t) 26)
#define CID_AC_ConfigReq               ((fsm_action_t) 27)
#define CID_AC_ConfigRsp               ((fsm_action_t) 28)
#define CID_AC_ConfigOk                ((fsm_action_t) 29)
#define CID_AC_DisconnectIndTimeout    ((fsm_action_t) 30)
#define CID_AC_DisconnectReqInternal   ((fsm_action_t) 31)
#define CID_AC_DisconnectCfm           ((fsm_action_t) 32)
#define CID_AC_DisconnectIndCross      ((fsm_action_t) 33)
#define CID_AC_DisconnectCfmTimeout    ((fsm_action_t) 34)
#define CID_AC_DisconnectCfmInternal   ((fsm_action_t) 35)
#define CID_AC_DisconnectRsp           ((fsm_action_t) 36)
#define CID_AC_DisconnectRspNcp        ((fsm_action_t) 37)
#define CID_AC_DisconnectIndInternal   ((fsm_action_t) 38)
#define CID_AC_MapFixedCidReq          ((fsm_action_t) 39)
#define CID_AC_MapFixedCidInd          ((fsm_action_t) 40)
#define CID_AC_FixedAccessOk           ((fsm_action_t) 41)
#define CID_AC_FixedDisconnectAcl      ((fsm_action_t) 42)
#define CID_AC_FixedDisconnectAbnormal ((fsm_action_t) 43)
#define CID_AC_AmpCreateInd            ((fsm_action_t) 44)
#define CID_AC_AmpCreateIndRetryActive ((fsm_action_t) 45)
#define CID_AC_AmpMoveReqBusy          ((fsm_action_t) 46)
#define CID_AC_AmpMoveIndBusy          ((fsm_action_t) 47)
#define CID_AC_AmpConfigLogicalCfmOk   ((fsm_action_t) 48)
#define CID_AC_AmpConfigLogicalCfmNok  ((fsm_action_t) 49)
#define CID_AC_AmpMoveReq              ((fsm_action_t) 50)
#define CID_AC_AmpMoveInd              ((fsm_action_t) 51)
#define CID_AC_AmpDisconnectInd        ((fsm_action_t) 52)
#define CID_AC_AmpCleanupReq           ((fsm_action_t) 53)
#define CID_AC_AmpCreateCfmError       ((fsm_action_t) 54)
#define CID_AC_AmpCreateReq            ((fsm_action_t) 55)
#define CID_AC_AmpCreateCfmErrorSec    ((fsm_action_t) 56)
#define CID_AC_AmpCreateReqPhysOk      ((fsm_action_t) 57)
#define CID_AC_AmpCreateReqPhysNok     ((fsm_action_t) 58)
#define CID_AC_AmpCreateReqVerifyOk    ((fsm_action_t) 59)
#define CID_AC_AmpCreateCfmOk          ((fsm_action_t) 60)
#define CID_AC_AmpCreateCfmPnd         ((fsm_action_t) 61)
#define CID_AC_AmpCreateCfmNok         ((fsm_action_t) 62)
#define CID_AC_AmpCreateCfmAbort       ((fsm_action_t) 63)
#define CID_AC_AmpCreateCfmTimeout     ((fsm_action_t) 64)
#define CID_AC_AmpCreateIndPhysOk      ((fsm_action_t) 65)
#define CID_AC_AmpCreateIndPhysNok     ((fsm_action_t) 66)
#define CID_AC_AmpCreateSmCfmOk        ((fsm_action_t) 67)
#define CID_AC_AmpCreateSmCfmNok       ((fsm_action_t) 68)
#define CID_AC_AmpCreateIndRetry       ((fsm_action_t) 69)
#define CID_AC_AmpCreateRspOk          ((fsm_action_t) 70)
#define CID_AC_AmpCreateRspPnd         ((fsm_action_t) 71)
#define CID_AC_AmpCreateRspNok         ((fsm_action_t) 72)
#define CID_AC_AmpMoveReqPhysOk        ((fsm_action_t) 73)
#define CID_AC_AmpMoveReqPhysNok       ((fsm_action_t) 74)
#define CID_AC_AmpMoveReqVerifyOk      ((fsm_action_t) 75)
#define CID_AC_AmpMoveCfmNok           ((fsm_action_t) 76)
#define CID_AC_AmpMoveCfmPnd           ((fsm_action_t) 77)
#define CID_AC_AmpMoveCfmOk            ((fsm_action_t) 78)
#define CID_AC_AmpMoveLocLogicalCfmOk  ((fsm_action_t) 79)
#define CID_AC_AmpMoveLocLogicalCfmNok ((fsm_action_t) 80)
#define CID_AC_AmpMoveIndCollide       ((fsm_action_t) 81)
#define CID_AC_AmpConfirmCfm           ((fsm_action_t) 82)
#define CID_AC_AmpMoveCfmTimeout       ((fsm_action_t) 83)
#define CID_AC_AmpMoveIndPhysOk        ((fsm_action_t) 84)
#define CID_AC_AmpMoveIndPhysNok       ((fsm_action_t) 85)
#define CID_AC_AmpMoveRspOk            ((fsm_action_t) 86)
#define CID_AC_AmpMoveRspNok           ((fsm_action_t) 87)
#define CID_AC_AmpMoveRemLogicalCfmOk  ((fsm_action_t) 88)
#define CID_AC_AmpMoveRemLogicalCfmNok ((fsm_action_t) 89)
#define CID_AC_AmpConfirmInd           ((fsm_action_t) 90)
#define CID_AC_NULL (FSM32_ACTION_NULL)
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(L2CAP_CID, FSM_DEFINITION) */
extern const FSM_SPARSE32_DEFINITION_T l2cap_cid_fsm;
/*}}__FSM_END_MARKER(L2CAP_CID, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _L2CAP_CID_FSM_DEFINITIONS_H */

#endif
/******************************************************************************/
#if defined(DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT) && !defined(DISABLE_AMP_FSM_SUPPORT)
#ifndef _L2CAP_CID_FSM_DEFINITIONS_H
#define _L2CAP_CID_FSM_DEFINITIONS_H
/*!
        Copyright (C) CCL, CSR plc 2010
        All rights reserved

\file   l2cap_cid_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CID_FsmDestroyCid);
extern FSM_ACTION_FN(CID_FsmConnectAclReady);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclDown);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclError);
extern FSM_ACTION_FN(CID_FsmConnectAclAbort);
extern FSM_ACTION_FN(CID_FsmConnectInd);
extern FSM_ACTION_FN(CID_FsmConnectReq);
extern FSM_ACTION_FN(CID_FsmConnectCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmConnectCfmOk);
extern FSM_ACTION_FN(CID_FsmConnectCfmNok);
extern FSM_ACTION_FN(CID_FsmConnectCfmPnd);
extern FSM_ACTION_FN(CID_FsmConnectCfmError);
extern FSM_ACTION_FN(CID_FsmConnectCfmAbort);
extern FSM_ACTION_FN(CID_FsmConnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmConnectIndRetry);
extern FSM_ACTION_FN(CID_FsmConnectRspOk);
extern FSM_ACTION_FN(CID_FsmConnectRspNok);
extern FSM_ACTION_FN(CID_FsmConnectRspPnd);
extern FSM_ACTION_FN(CID_FsmDisconnectIndAcl);
extern FSM_ACTION_FN(CID_FsmDisconnectInd);
extern FSM_ACTION_FN(CID_FsmDisconnectReq);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmOk);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmNok);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInvalidCid);
extern FSM_ACTION_FN(CID_FsmConnectIndRetryActive);
extern FSM_ACTION_FN(CID_FsmConfigInd);
extern FSM_ACTION_FN(CID_FsmConfigCfm);
extern FSM_ACTION_FN(CID_FsmConfigReq);
extern FSM_ACTION_FN(CID_FsmConfigRsp);
extern FSM_ACTION_FN(CID_FsmConfigOk);
extern FSM_ACTION_FN(CID_FsmDisconnectIndTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectReqInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectCfm);
extern FSM_ACTION_FN(CID_FsmDisconnectIndCross);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectRsp);
extern FSM_ACTION_FN(CID_FsmDisconnectRspNcp);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInternal);
extern FSM_ACTION_FN(CID_FsmAmpCreateInd);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndRetryActive);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqBusy);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndBusy);
extern FSM_ACTION_FN(CID_FsmAmpConfigLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpConfigLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReq);
extern FSM_ACTION_FN(CID_FsmAmpMoveInd);
extern FSM_ACTION_FN(CID_FsmAmpDisconnectInd);
extern FSM_ACTION_FN(CID_FsmAmpCleanupReq);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmError);
extern FSM_ACTION_FN(CID_FsmAmpCreateReq);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateReqVerifyOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmPnd);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmAbort);
extern FSM_ACTION_FN(CID_FsmAmpCreateCfmTimeout);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateSmCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateSmCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpCreateIndRetry);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspOk);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspPnd);
extern FSM_ACTION_FN(CID_FsmAmpCreateRspNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveReqVerifyOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmPnd);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveLocLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveLocLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndCollide);
extern FSM_ACTION_FN(CID_FsmAmpConfirmCfm);
extern FSM_ACTION_FN(CID_FsmAmpMoveCfmTimeout);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndPhysOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveIndPhysNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveRspOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveRspNok);
extern FSM_ACTION_FN(CID_FsmAmpMoveRemLogicalCfmOk);
extern FSM_ACTION_FN(CID_FsmAmpMoveRemLogicalCfmNok);
extern FSM_ACTION_FN(CID_FsmAmpConfirmInd);
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(L2CAP_CID, STATE_DECLARATIONS) */
#define CID_ST_ST_MAX 19
#define CID_ST_NULL              ((fsm_state_t) 0)
#define CID_ST_OPEN_ACL          ((fsm_state_t) 1)
#define CID_ST_CONNECT_LOCAL     ((fsm_state_t) 2)
#define CID_ST_CONNECT_REMOTE    ((fsm_state_t) 3)
#define CID_ST_CONFIG            ((fsm_state_t) 4)
#define CID_ST_OPEN              ((fsm_state_t) 5)
#define CID_ST_DISCONNECT_LOCAL  ((fsm_state_t) 6)
#define CID_ST_DISCONNECT_REMOTE ((fsm_state_t) 7)
#define CID_ST_DISCONNECT_NCP    ((fsm_state_t) 8)
#define CID_ST_DISCONNECT_INTRN  ((fsm_state_t) 9)
#define CID_ST_CONNECT_SM_ACCESS ((fsm_state_t) 10)
#define CID_ST_OPEN_AMP_ACL      ((fsm_state_t) 11)
#define CID_ST_CREATE_AMP_LOCAL  ((fsm_state_t) 12)
#define CID_ST_CREATE_AMP_REMOTE ((fsm_state_t) 13)
#define CID_ST_MOVE_AMP_LOCAL    ((fsm_state_t) 14)
#define CID_ST_MOVE_AMP_REMOTE   ((fsm_state_t) 15)
#define CID_ST_DISCONNECT_AMP    ((fsm_state_t) 16)
#define CID_ST_AMP_VERIFY_PHYS   ((fsm_state_t) 17)
#define CID_ST_AMP_SM_ACCESS     ((fsm_state_t) 18)
/*}}__FSM_END_MARKER(L2CAP_CID, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */
#define CID_EV_CID_ACL_CLOSE_IND       ((fsm_event_t) 0)
#define CID_EV_CID_ACL_READY           ((fsm_event_t) 1)
#define CID_EV_CID_ACL_CLOSE_DESTROY   ((fsm_event_t) 2)
#define CID_EV_CID_DISCONNECT_REQ      ((fsm_event_t) 3)
#define CID_EV_CID_CONNECT_REQ         ((fsm_event_t) 4)
#define CID_EV_CID_CONNECT_IND         ((fsm_event_t) 5)
#define CID_EV_SM_ACCESS_CFM_OK        ((fsm_event_t) 6)
#define CID_EV_SM_ACCESS_CFM_NOK       ((fsm_event_t) 7)
#define CID_EV_CID_CONNECT_CFM_OK      ((fsm_event_t) 8)
#define CID_EV_CID_CONNECT_CFM_NOK     ((fsm_event_t) 9)
#define CID_EV_CID_CONNECT_CFM_PND     ((fsm_event_t) 10)
#define CID_EV_CID_DISCONNECT_IND      ((fsm_event_t) 11)
#define CID_EV_CID_TIMEOUT             ((fsm_event_t) 12)
#define CID_EV_CID_INVALID_CID         ((fsm_event_t) 13)
#define CID_EV_CID_CONNECT_IND_RETRY   ((fsm_event_t) 14)
#define CID_EV_CID_CONNECT_RSP_OK      ((fsm_event_t) 15)
#define CID_EV_CID_CONNECT_RSP_NOK     ((fsm_event_t) 16)
#define CID_EV_CID_CONNECT_RSP_PND     ((fsm_event_t) 17)
#define CID_EV_CID_CONFIG_IND          ((fsm_event_t) 18)
#define CID_EV_CID_CONFIG_CFM          ((fsm_event_t) 19)
#define CID_EV_CID_CONFIG_REQ          ((fsm_event_t) 20)
#define CID_EV_CID_CONFIG_RSP          ((fsm_event_t) 21)
#define CID_EV_CID_CONFIG_OK           ((fsm_event_t) 22)
#define CID_EV_CID_CONFIG_TIMEOUT      ((fsm_event_t) 23)
#define CID_EV_CID_INTERNAL_DISC_REQ   ((fsm_event_t) 24)
#define CID_EV_CID_DISCONNECT_CFM      ((fsm_event_t) 25)
#define CID_EV_CID_DISCONNECT_RSP      ((fsm_event_t) 26)
#define CID_EV_CID_SIGNAL_NCP_IND      ((fsm_event_t) 27)
#define CID_EV_CID_AMP_CREATE_REQ      ((fsm_event_t) 28)
#define CID_EV_CID_AMP_CREATE_IND      ((fsm_event_t) 29)
#define CID_EV_CID_AMP_CREATE_IND_RET  ((fsm_event_t) 30)
#define CID_EV_CID_AMP_MOVE_REQ        ((fsm_event_t) 31)
#define CID_EV_CID_AMP_MOVE_IND        ((fsm_event_t) 32)
#define CID_EV_CID_AMP_LOGICAL_CFM_OK  ((fsm_event_t) 33)
#define CID_EV_CID_AMP_LOGICAL_CFM_NOK ((fsm_event_t) 34)
#define CID_EV_CID_AMP_DISCONNECT_IND  ((fsm_event_t) 35)
#define CID_EV_CID_AMP_CLEANUP_REQ     ((fsm_event_t) 36)
#define CID_EV_CID_AMP_PHYS_CFM_OK     ((fsm_event_t) 37)
#define CID_EV_CID_AMP_PHYS_CFM_NOK    ((fsm_event_t) 38)
#define CID_EV_CID_AMP_VERIFY_PHYS_OK  ((fsm_event_t) 39)
#define CID_EV_CID_AMP_CREATE_CFM_OK   ((fsm_event_t) 40)
#define CID_EV_CID_AMP_CREATE_CFM_PND  ((fsm_event_t) 41)
#define CID_EV_CID_AMP_CREATE_CFM_NOK  ((fsm_event_t) 42)
#define CID_EV_CID_AMP_VERIFY_PHYS_NOK ((fsm_event_t) 43)
#define CID_EV_CID_AMP_CREATE_RSP_OK   ((fsm_event_t) 44)
#define CID_EV_CID_AMP_CREATE_RSP_PND  ((fsm_event_t) 45)
#define CID_EV_CID_AMP_CREATE_RSP_NOK  ((fsm_event_t) 46)
#define CID_EV_CID_AMP_MOVE_CFM_NOK    ((fsm_event_t) 47)
#define CID_EV_CID_AMP_MOVE_CFM_PND    ((fsm_event_t) 48)
#define CID_EV_CID_AMP_MOVE_CFM_OK     ((fsm_event_t) 49)
#define CID_EV_CID_AMP_MOVE_RSP_PND    ((fsm_event_t) 50)
#define CID_EV_CID_AMP_CONFIRM_CFM     ((fsm_event_t) 51)
#define CID_EV_CID_AMP_MOVE_CANCEL     ((fsm_event_t) 52)
#define CID_EV_CID_AMP_MOVE_RSP_OK     ((fsm_event_t) 53)
#define CID_EV_CID_AMP_MOVE_RSP_NOK    ((fsm_event_t) 54)
#define CID_EV_CID_AMP_CONFIRM_IND     ((fsm_event_t) 55)
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_INDEX) */
#define CID_AC_MAX 86
#define CID_AC_DestroyCid              ((fsm_action_t) 0)
#define CID_AC_ConnectAclReady         ((fsm_action_t) 1)
#define CID_AC_ConnectCfmAclDown       ((fsm_action_t) 2)
#define CID_AC_ConnectCfmAclError      ((fsm_action_t) 3)
#define CID_AC_ConnectAclAbort         ((fsm_action_t) 4)
#define CID_AC_ConnectInd              ((fsm_action_t) 5)
#define CID_AC_ConnectReq              ((fsm_action_t) 6)
#define CID_AC_ConnectCfmErrorSec      ((fsm_action_t) 7)
#define CID_AC_ConnectCfmOk            ((fsm_action_t) 8)
#define CID_AC_ConnectCfmNok           ((fsm_action_t) 9)
#define CID_AC_ConnectCfmPnd           ((fsm_action_t) 10)
#define CID_AC_ConnectCfmError         ((fsm_action_t) 11)
#define CID_AC_ConnectCfmAbort         ((fsm_action_t) 12)
#define CID_AC_ConnectCfmTimeout       ((fsm_action_t) 13)
#define CID_AC_ConnectIndRetry         ((fsm_action_t) 14)
#define CID_AC_ConnectRspOk            ((fsm_action_t) 15)
#define CID_AC_ConnectRspNok           ((fsm_action_t) 16)
#define CID_AC_ConnectRspPnd           ((fsm_action_t) 17)
#define CID_AC_DisconnectIndAcl        ((fsm_action_t) 18)
#define CID_AC_DisconnectInd           ((fsm_action_t) 19)
#define CID_AC_DisconnectReq           ((fsm_action_t) 20)
#define CID_AC_SmAccessCfmOk           ((fsm_action_t) 21)
#define CID_AC_SmAccessCfmNok          ((fsm_action_t) 22)
#define CID_AC_DisconnectIndInvalidCid ((fsm_action_t) 23)
#define CID_AC_ConnectIndRetryActive   ((fsm_action_t) 24)
#define CID_AC_ConfigInd               ((fsm_action_t) 25)
#define CID_AC_ConfigCfm               ((fsm_action_t) 26)
#define CID_AC_ConfigReq               ((fsm_action_t) 27)
#define CID_AC_ConfigRsp               ((fsm_action_t) 28)
#define CID_AC_ConfigOk                ((fsm_action_t) 29)
#define CID_AC_DisconnectIndTimeout    ((fsm_action_t) 30)
#define CID_AC_DisconnectReqInternal   ((fsm_action_t) 31)
#define CID_AC_DisconnectCfm           ((fsm_action_t) 32)
#define CID_AC_DisconnectIndCross      ((fsm_action_t) 33)
#define CID_AC_DisconnectCfmTimeout    ((fsm_action_t) 34)
#define CID_AC_DisconnectCfmInternal   ((fsm_action_t) 35)
#define CID_AC_DisconnectRsp           ((fsm_action_t) 36)
#define CID_AC_DisconnectRspNcp        ((fsm_action_t) 37)
#define CID_AC_DisconnectIndInternal   ((fsm_action_t) 38)
#define CID_AC_AmpCreateInd            ((fsm_action_t) 39)
#define CID_AC_AmpCreateIndRetryActive ((fsm_action_t) 40)
#define CID_AC_AmpMoveReqBusy          ((fsm_action_t) 41)
#define CID_AC_AmpMoveIndBusy          ((fsm_action_t) 42)
#define CID_AC_AmpConfigLogicalCfmOk   ((fsm_action_t) 43)
#define CID_AC_AmpConfigLogicalCfmNok  ((fsm_action_t) 44)
#define CID_AC_AmpMoveReq              ((fsm_action_t) 45)
#define CID_AC_AmpMoveInd              ((fsm_action_t) 46)
#define CID_AC_AmpDisconnectInd        ((fsm_action_t) 47)
#define CID_AC_AmpCleanupReq           ((fsm_action_t) 48)
#define CID_AC_AmpCreateCfmError       ((fsm_action_t) 49)
#define CID_AC_AmpCreateReq            ((fsm_action_t) 50)
#define CID_AC_AmpCreateCfmErrorSec    ((fsm_action_t) 51)
#define CID_AC_AmpCreateReqPhysOk      ((fsm_action_t) 52)
#define CID_AC_AmpCreateReqPhysNok     ((fsm_action_t) 53)
#define CID_AC_AmpCreateReqVerifyOk    ((fsm_action_t) 54)
#define CID_AC_AmpCreateCfmOk          ((fsm_action_t) 55)
#define CID_AC_AmpCreateCfmPnd         ((fsm_action_t) 56)
#define CID_AC_AmpCreateCfmNok         ((fsm_action_t) 57)
#define CID_AC_AmpCreateCfmAbort       ((fsm_action_t) 58)
#define CID_AC_AmpCreateCfmTimeout     ((fsm_action_t) 59)
#define CID_AC_AmpCreateIndPhysOk      ((fsm_action_t) 60)
#define CID_AC_AmpCreateIndPhysNok     ((fsm_action_t) 61)
#define CID_AC_AmpCreateSmCfmOk        ((fsm_action_t) 62)
#define CID_AC_AmpCreateSmCfmNok       ((fsm_action_t) 63)
#define CID_AC_AmpCreateIndRetry       ((fsm_action_t) 64)
#define CID_AC_AmpCreateRspOk          ((fsm_action_t) 65)
#define CID_AC_AmpCreateRspPnd         ((fsm_action_t) 66)
#define CID_AC_AmpCreateRspNok         ((fsm_action_t) 67)
#define CID_AC_AmpMoveReqPhysOk        ((fsm_action_t) 68)
#define CID_AC_AmpMoveReqPhysNok       ((fsm_action_t) 69)
#define CID_AC_AmpMoveReqVerifyOk      ((fsm_action_t) 70)
#define CID_AC_AmpMoveCfmNok           ((fsm_action_t) 71)
#define CID_AC_AmpMoveCfmPnd           ((fsm_action_t) 72)
#define CID_AC_AmpMoveCfmOk            ((fsm_action_t) 73)
#define CID_AC_AmpMoveLocLogicalCfmOk  ((fsm_action_t) 74)
#define CID_AC_AmpMoveLocLogicalCfmNok ((fsm_action_t) 75)
#define CID_AC_AmpMoveIndCollide       ((fsm_action_t) 76)
#define CID_AC_AmpConfirmCfm           ((fsm_action_t) 77)
#define CID_AC_AmpMoveCfmTimeout       ((fsm_action_t) 78)
#define CID_AC_AmpMoveIndPhysOk        ((fsm_action_t) 79)
#define CID_AC_AmpMoveIndPhysNok       ((fsm_action_t) 80)
#define CID_AC_AmpMoveRspOk            ((fsm_action_t) 81)
#define CID_AC_AmpMoveRspNok           ((fsm_action_t) 82)
#define CID_AC_AmpMoveRemLogicalCfmOk  ((fsm_action_t) 83)
#define CID_AC_AmpMoveRemLogicalCfmNok ((fsm_action_t) 84)
#define CID_AC_AmpConfirmInd           ((fsm_action_t) 85)
#define CID_AC_NULL (FSM32_ACTION_NULL)
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(L2CAP_CID, FSM_DEFINITION) */
extern const FSM_SPARSE32_DEFINITION_T l2cap_cid_fsm;
/*}}__FSM_END_MARKER(L2CAP_CID, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _L2CAP_CID_FSM_DEFINITIONS_H */

#endif
/******************************************************************************/
#if !defined(DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT) && defined(DISABLE_AMP_FSM_SUPPORT)
#ifndef _L2CAP_CID_FSM_DEFINITIONS_H
#define _L2CAP_CID_FSM_DEFINITIONS_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   l2cap_cid_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CID_FsmDestroyCid);
extern FSM_ACTION_FN(CID_FsmConnectAclReady);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclDown);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclError);
extern FSM_ACTION_FN(CID_FsmConnectAclAbort);
extern FSM_ACTION_FN(CID_FsmConnectInd);
extern FSM_ACTION_FN(CID_FsmConnectReq);
extern FSM_ACTION_FN(CID_FsmConnectCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmConnectCfmOk);
extern FSM_ACTION_FN(CID_FsmConnectCfmNok);
extern FSM_ACTION_FN(CID_FsmConnectCfmPnd);
extern FSM_ACTION_FN(CID_FsmConnectCfmError);
extern FSM_ACTION_FN(CID_FsmConnectCfmAbort);
extern FSM_ACTION_FN(CID_FsmConnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmConnectIndRetry);
extern FSM_ACTION_FN(CID_FsmConnectRspOk);
extern FSM_ACTION_FN(CID_FsmConnectRspNok);
extern FSM_ACTION_FN(CID_FsmConnectRspPnd);
extern FSM_ACTION_FN(CID_FsmDisconnectIndAcl);
extern FSM_ACTION_FN(CID_FsmDisconnectInd);
extern FSM_ACTION_FN(CID_FsmDisconnectReq);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmOk);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmNok);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInvalidCid);
extern FSM_ACTION_FN(CID_FsmConnectIndRetryActive);
extern FSM_ACTION_FN(CID_FsmConfigInd);
extern FSM_ACTION_FN(CID_FsmConfigCfm);
extern FSM_ACTION_FN(CID_FsmConfigReq);
extern FSM_ACTION_FN(CID_FsmConfigRsp);
extern FSM_ACTION_FN(CID_FsmConfigOk);
extern FSM_ACTION_FN(CID_FsmDisconnectIndTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectReqInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectCfm);
extern FSM_ACTION_FN(CID_FsmDisconnectIndCross);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectRsp);
extern FSM_ACTION_FN(CID_FsmDisconnectRspNcp);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInternal);
extern FSM_ACTION_FN(CID_FsmMapFixedCidReq);
extern FSM_ACTION_FN(CID_FsmMapFixedCidInd);
extern FSM_ACTION_FN(CID_FsmFixedAccessOk);
extern FSM_ACTION_FN(CID_FsmFixedDisconnectAcl);
extern FSM_ACTION_FN(CID_FsmFixedDisconnectAbnormal);
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(L2CAP_CID, STATE_DECLARATIONS) */
#define CID_ST_ST_MAX 12
#define CID_ST_NULL              ((fsm_state_t) 0)
#define CID_ST_OPEN_ACL          ((fsm_state_t) 1)
#define CID_ST_CONNECT_LOCAL     ((fsm_state_t) 2)
#define CID_ST_CONNECT_REMOTE    ((fsm_state_t) 3)
#define CID_ST_CONFIG            ((fsm_state_t) 4)
#define CID_ST_OPEN              ((fsm_state_t) 5)
#define CID_ST_DISCONNECT_LOCAL  ((fsm_state_t) 6)
#define CID_ST_DISCONNECT_REMOTE ((fsm_state_t) 7)
#define CID_ST_DISCONNECT_NCP    ((fsm_state_t) 8)
#define CID_ST_DISCONNECT_INTRN  ((fsm_state_t) 9)
#define CID_ST_CONNECT_SM_ACCESS ((fsm_state_t) 10)
#define CID_ST_OPEN_FIXED        ((fsm_state_t) 11)
/*}}__FSM_END_MARKER(L2CAP_CID, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */
#define CID_EV_CID_ACL_CLOSE_IND       ((fsm_event_t) 0)
#define CID_EV_CID_ACL_READY           ((fsm_event_t) 1)
#define CID_EV_CID_ACL_CLOSE_DESTROY   ((fsm_event_t) 2)
#define CID_EV_CID_DISCONNECT_REQ      ((fsm_event_t) 3)
#define CID_EV_CID_CONNECT_REQ         ((fsm_event_t) 4)
#define CID_EV_CID_CONNECT_IND         ((fsm_event_t) 5)
#define CID_EV_SM_ACCESS_CFM_OK        ((fsm_event_t) 6)
#define CID_EV_SM_ACCESS_CFM_NOK       ((fsm_event_t) 7)
#define CID_EV_CID_CONNECT_CFM_OK      ((fsm_event_t) 8)
#define CID_EV_CID_CONNECT_CFM_NOK     ((fsm_event_t) 9)
#define CID_EV_CID_CONNECT_CFM_PND     ((fsm_event_t) 10)
#define CID_EV_CID_DISCONNECT_IND      ((fsm_event_t) 11)
#define CID_EV_CID_TIMEOUT             ((fsm_event_t) 12)
#define CID_EV_CID_INVALID_CID         ((fsm_event_t) 13)
#define CID_EV_CID_CONNECT_IND_RETRY   ((fsm_event_t) 14)
#define CID_EV_CID_CONNECT_RSP_OK      ((fsm_event_t) 15)
#define CID_EV_CID_CONNECT_RSP_NOK     ((fsm_event_t) 16)
#define CID_EV_CID_CONNECT_RSP_PND     ((fsm_event_t) 17)
#define CID_EV_CID_CONFIG_IND          ((fsm_event_t) 18)
#define CID_EV_CID_CONFIG_CFM          ((fsm_event_t) 19)
#define CID_EV_CID_CONFIG_REQ          ((fsm_event_t) 20)
#define CID_EV_CID_CONFIG_RSP          ((fsm_event_t) 21)
#define CID_EV_CID_CONFIG_OK           ((fsm_event_t) 22)
#define CID_EV_CID_CONFIG_TIMEOUT      ((fsm_event_t) 23)
#define CID_EV_CID_INTERNAL_DISC_REQ   ((fsm_event_t) 24)
#define CID_EV_CID_DISCONNECT_CFM      ((fsm_event_t) 25)
#define CID_EV_CID_DISCONNECT_RSP      ((fsm_event_t) 26)
#define CID_EV_CID_SIGNAL_NCP_IND      ((fsm_event_t) 27)
#define CID_EV_CID_MAP_FIXED_REQ       ((fsm_event_t) 28)
#define CID_EV_CID_MAP_FIXED_IND       ((fsm_event_t) 29)
#define CID_EV_CID_MAP_BROADCAST       ((fsm_event_t) 30)
#define CID_EV_CID_FIXED_ACCESS_CFM_OK ((fsm_event_t) 31)
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_INDEX) */
#define CID_AC_MAX 44
#define CID_AC_DestroyCid              ((fsm_action_t) 0)
#define CID_AC_ConnectAclReady         ((fsm_action_t) 1)
#define CID_AC_ConnectCfmAclDown       ((fsm_action_t) 2)
#define CID_AC_ConnectCfmAclError      ((fsm_action_t) 3)
#define CID_AC_ConnectAclAbort         ((fsm_action_t) 4)
#define CID_AC_ConnectInd              ((fsm_action_t) 5)
#define CID_AC_ConnectReq              ((fsm_action_t) 6)
#define CID_AC_ConnectCfmErrorSec      ((fsm_action_t) 7)
#define CID_AC_ConnectCfmOk            ((fsm_action_t) 8)
#define CID_AC_ConnectCfmNok           ((fsm_action_t) 9)
#define CID_AC_ConnectCfmPnd           ((fsm_action_t) 10)
#define CID_AC_ConnectCfmError         ((fsm_action_t) 11)
#define CID_AC_ConnectCfmAbort         ((fsm_action_t) 12)
#define CID_AC_ConnectCfmTimeout       ((fsm_action_t) 13)
#define CID_AC_ConnectIndRetry         ((fsm_action_t) 14)
#define CID_AC_ConnectRspOk            ((fsm_action_t) 15)
#define CID_AC_ConnectRspNok           ((fsm_action_t) 16)
#define CID_AC_ConnectRspPnd           ((fsm_action_t) 17)
#define CID_AC_DisconnectIndAcl        ((fsm_action_t) 18)
#define CID_AC_DisconnectInd           ((fsm_action_t) 19)
#define CID_AC_DisconnectReq           ((fsm_action_t) 20)
#define CID_AC_SmAccessCfmOk           ((fsm_action_t) 21)
#define CID_AC_SmAccessCfmNok          ((fsm_action_t) 22)
#define CID_AC_DisconnectIndInvalidCid ((fsm_action_t) 23)
#define CID_AC_ConnectIndRetryActive   ((fsm_action_t) 24)
#define CID_AC_ConfigInd               ((fsm_action_t) 25)
#define CID_AC_ConfigCfm               ((fsm_action_t) 26)
#define CID_AC_ConfigReq               ((fsm_action_t) 27)
#define CID_AC_ConfigRsp               ((fsm_action_t) 28)
#define CID_AC_ConfigOk                ((fsm_action_t) 29)
#define CID_AC_DisconnectIndTimeout    ((fsm_action_t) 30)
#define CID_AC_DisconnectReqInternal   ((fsm_action_t) 31)
#define CID_AC_DisconnectCfm           ((fsm_action_t) 32)
#define CID_AC_DisconnectIndCross      ((fsm_action_t) 33)
#define CID_AC_DisconnectCfmTimeout    ((fsm_action_t) 34)
#define CID_AC_DisconnectCfmInternal   ((fsm_action_t) 35)
#define CID_AC_DisconnectRsp           ((fsm_action_t) 36)
#define CID_AC_DisconnectRspNcp        ((fsm_action_t) 37)
#define CID_AC_DisconnectIndInternal   ((fsm_action_t) 38)
#define CID_AC_MapFixedCidReq          ((fsm_action_t) 39)
#define CID_AC_MapFixedCidInd          ((fsm_action_t) 40)
#define CID_AC_FixedAccessOk           ((fsm_action_t) 41)
#define CID_AC_FixedDisconnectAcl      ((fsm_action_t) 42)
#define CID_AC_FixedDisconnectAbnormal ((fsm_action_t) 43)
#define CID_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(L2CAP_CID, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T l2cap_cid_fsm;
/*}}__FSM_END_MARKER(L2CAP_CID, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _L2CAP_CID_FSM_DEFINITIONS_H */

#endif
/******************************************************************************/
#if defined(DISABLE_L2CAP_FIXED_CHANNEL_FSM_SUPPORT) && defined(DISABLE_AMP_FSM_SUPPORT)
#ifndef _L2CAP_CID_FSM_DEFINITIONS_H
#define _L2CAP_CID_FSM_DEFINITIONS_H
/*!
        Copyright (C) CSR plc 2010
        All rights reserved

\file   l2cap_cid_fsm_definitions.h

\brief  FSM definitions.
        Contains code generated by fsmgen.pl, version Synergy-2C
*/

#include "csr_bt_core_stack_fsm.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Action function prototypes */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */
extern FSM_ACTION_FN(CID_FsmDestroyCid);
extern FSM_ACTION_FN(CID_FsmConnectAclReady);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclDown);
extern FSM_ACTION_FN(CID_FsmConnectCfmAclError);
extern FSM_ACTION_FN(CID_FsmConnectAclAbort);
extern FSM_ACTION_FN(CID_FsmConnectInd);
extern FSM_ACTION_FN(CID_FsmConnectReq);
extern FSM_ACTION_FN(CID_FsmConnectCfmErrorSec);
extern FSM_ACTION_FN(CID_FsmConnectCfmOk);
extern FSM_ACTION_FN(CID_FsmConnectCfmNok);
extern FSM_ACTION_FN(CID_FsmConnectCfmPnd);
extern FSM_ACTION_FN(CID_FsmConnectCfmError);
extern FSM_ACTION_FN(CID_FsmConnectCfmAbort);
extern FSM_ACTION_FN(CID_FsmConnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmConnectIndRetry);
extern FSM_ACTION_FN(CID_FsmConnectRspOk);
extern FSM_ACTION_FN(CID_FsmConnectRspNok);
extern FSM_ACTION_FN(CID_FsmConnectRspPnd);
extern FSM_ACTION_FN(CID_FsmDisconnectIndAcl);
extern FSM_ACTION_FN(CID_FsmDisconnectInd);
extern FSM_ACTION_FN(CID_FsmDisconnectReq);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmOk);
extern FSM_ACTION_FN(CID_FsmSmAccessCfmNok);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInvalidCid);
extern FSM_ACTION_FN(CID_FsmConnectIndRetryActive);
extern FSM_ACTION_FN(CID_FsmConfigInd);
extern FSM_ACTION_FN(CID_FsmConfigCfm);
extern FSM_ACTION_FN(CID_FsmConfigReq);
extern FSM_ACTION_FN(CID_FsmConfigRsp);
extern FSM_ACTION_FN(CID_FsmConfigOk);
extern FSM_ACTION_FN(CID_FsmDisconnectIndTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectReqInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectCfm);
extern FSM_ACTION_FN(CID_FsmDisconnectIndCross);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmTimeout);
extern FSM_ACTION_FN(CID_FsmDisconnectCfmInternal);
extern FSM_ACTION_FN(CID_FsmDisconnectRsp);
extern FSM_ACTION_FN(CID_FsmDisconnectRspNcp);
extern FSM_ACTION_FN(CID_FsmDisconnectIndInternal);
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_PROTOTYPES) */

/* State definitions */
/*{{__FSM_MARKER(L2CAP_CID, STATE_DECLARATIONS) */
#define CID_ST_ST_MAX 11
#define CID_ST_NULL              ((fsm_state_t) 0)
#define CID_ST_OPEN_ACL          ((fsm_state_t) 1)
#define CID_ST_CONNECT_LOCAL     ((fsm_state_t) 2)
#define CID_ST_CONNECT_REMOTE    ((fsm_state_t) 3)
#define CID_ST_CONFIG            ((fsm_state_t) 4)
#define CID_ST_OPEN              ((fsm_state_t) 5)
#define CID_ST_DISCONNECT_LOCAL  ((fsm_state_t) 6)
#define CID_ST_DISCONNECT_REMOTE ((fsm_state_t) 7)
#define CID_ST_DISCONNECT_NCP    ((fsm_state_t) 8)
#define CID_ST_DISCONNECT_INTRN  ((fsm_state_t) 9)
#define CID_ST_CONNECT_SM_ACCESS ((fsm_state_t) 10)
/*}}__FSM_END_MARKER(L2CAP_CID, STATE_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */
#define CID_EV_CID_ACL_CLOSE_IND     ((fsm_event_t) 0)
#define CID_EV_CID_ACL_READY         ((fsm_event_t) 1)
#define CID_EV_CID_ACL_CLOSE_DESTROY ((fsm_event_t) 2)
#define CID_EV_CID_DISCONNECT_REQ    ((fsm_event_t) 3)
#define CID_EV_CID_CONNECT_REQ       ((fsm_event_t) 4)
#define CID_EV_CID_CONNECT_IND       ((fsm_event_t) 5)
#define CID_EV_SM_ACCESS_CFM_OK      ((fsm_event_t) 6)
#define CID_EV_SM_ACCESS_CFM_NOK     ((fsm_event_t) 7)
#define CID_EV_CID_CONNECT_CFM_OK    ((fsm_event_t) 8)
#define CID_EV_CID_CONNECT_CFM_NOK   ((fsm_event_t) 9)
#define CID_EV_CID_CONNECT_CFM_PND   ((fsm_event_t) 10)
#define CID_EV_CID_DISCONNECT_IND    ((fsm_event_t) 11)
#define CID_EV_CID_TIMEOUT           ((fsm_event_t) 12)
#define CID_EV_CID_INVALID_CID       ((fsm_event_t) 13)
#define CID_EV_CID_CONNECT_IND_RETRY ((fsm_event_t) 14)
#define CID_EV_CID_CONNECT_RSP_OK    ((fsm_event_t) 15)
#define CID_EV_CID_CONNECT_RSP_NOK   ((fsm_event_t) 16)
#define CID_EV_CID_CONNECT_RSP_PND   ((fsm_event_t) 17)
#define CID_EV_CID_CONFIG_IND        ((fsm_event_t) 18)
#define CID_EV_CID_CONFIG_CFM        ((fsm_event_t) 19)
#define CID_EV_CID_CONFIG_REQ        ((fsm_event_t) 20)
#define CID_EV_CID_CONFIG_RSP        ((fsm_event_t) 21)
#define CID_EV_CID_CONFIG_OK         ((fsm_event_t) 22)
#define CID_EV_CID_CONFIG_TIMEOUT    ((fsm_event_t) 23)
#define CID_EV_CID_INTERNAL_DISC_REQ ((fsm_event_t) 24)
#define CID_EV_CID_DISCONNECT_CFM    ((fsm_event_t) 25)
#define CID_EV_CID_DISCONNECT_RSP    ((fsm_event_t) 26)
#define CID_EV_CID_SIGNAL_NCP_IND    ((fsm_event_t) 27)
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS) */

/* Event definitions */
/*{{__FSM_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */
/*}}__FSM_END_MARKER(L2CAP_CID, EVENT_DECLARATIONS EXT1) */

/* Action function index */
/*{{__FSM_MARKER(L2CAP_CID, ACTION_FN_INDEX) */
#define CID_AC_MAX 39
#define CID_AC_DestroyCid              ((fsm_action_t) 0)
#define CID_AC_ConnectAclReady         ((fsm_action_t) 1)
#define CID_AC_ConnectCfmAclDown       ((fsm_action_t) 2)
#define CID_AC_ConnectCfmAclError      ((fsm_action_t) 3)
#define CID_AC_ConnectAclAbort         ((fsm_action_t) 4)
#define CID_AC_ConnectInd              ((fsm_action_t) 5)
#define CID_AC_ConnectReq              ((fsm_action_t) 6)
#define CID_AC_ConnectCfmErrorSec      ((fsm_action_t) 7)
#define CID_AC_ConnectCfmOk            ((fsm_action_t) 8)
#define CID_AC_ConnectCfmNok           ((fsm_action_t) 9)
#define CID_AC_ConnectCfmPnd           ((fsm_action_t) 10)
#define CID_AC_ConnectCfmError         ((fsm_action_t) 11)
#define CID_AC_ConnectCfmAbort         ((fsm_action_t) 12)
#define CID_AC_ConnectCfmTimeout       ((fsm_action_t) 13)
#define CID_AC_ConnectIndRetry         ((fsm_action_t) 14)
#define CID_AC_ConnectRspOk            ((fsm_action_t) 15)
#define CID_AC_ConnectRspNok           ((fsm_action_t) 16)
#define CID_AC_ConnectRspPnd           ((fsm_action_t) 17)
#define CID_AC_DisconnectIndAcl        ((fsm_action_t) 18)
#define CID_AC_DisconnectInd           ((fsm_action_t) 19)
#define CID_AC_DisconnectReq           ((fsm_action_t) 20)
#define CID_AC_SmAccessCfmOk           ((fsm_action_t) 21)
#define CID_AC_SmAccessCfmNok          ((fsm_action_t) 22)
#define CID_AC_DisconnectIndInvalidCid ((fsm_action_t) 23)
#define CID_AC_ConnectIndRetryActive   ((fsm_action_t) 24)
#define CID_AC_ConfigInd               ((fsm_action_t) 25)
#define CID_AC_ConfigCfm               ((fsm_action_t) 26)
#define CID_AC_ConfigReq               ((fsm_action_t) 27)
#define CID_AC_ConfigRsp               ((fsm_action_t) 28)
#define CID_AC_ConfigOk                ((fsm_action_t) 29)
#define CID_AC_DisconnectIndTimeout    ((fsm_action_t) 30)
#define CID_AC_DisconnectReqInternal   ((fsm_action_t) 31)
#define CID_AC_DisconnectCfm           ((fsm_action_t) 32)
#define CID_AC_DisconnectIndCross      ((fsm_action_t) 33)
#define CID_AC_DisconnectCfmTimeout    ((fsm_action_t) 34)
#define CID_AC_DisconnectCfmInternal   ((fsm_action_t) 35)
#define CID_AC_DisconnectRsp           ((fsm_action_t) 36)
#define CID_AC_DisconnectRspNcp        ((fsm_action_t) 37)
#define CID_AC_DisconnectIndInternal   ((fsm_action_t) 38)
#define CID_AC_NULL (FSM16_ACTION_NULL)
/*}}__FSM_END_MARKER(L2CAP_CID, ACTION_FN_INDEX) */

/* State machine definition */
/*{{__FSM_MARKER(L2CAP_CID, FSM_DEFINITION) */
extern const FSM_SPARSE16_DEFINITION_T l2cap_cid_fsm;
/*}}__FSM_END_MARKER(L2CAP_CID, FSM_DEFINITION) */

#ifdef __cplusplus
}
#endif

#endif /* _L2CAP_CID_FSM_DEFINITIONS_H */

#endif
