/**
 * @file PlatformHbbTVKeyCodes.h
 * @brief Definition of the DAE/OIPF JavaScript KeyEvent constants.
 *
 * Copyright 2011 by Samsung Electronics, Inc.,
 *
 * This software is the confidential and proprietary information
 * of Samsung Electronics, Inc. ("Confidential Information").  You
 * shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement
 * you entered into with Samsung.
 */

#ifndef _PLATFORM_HBBTV_KEYCODES_H_
#define _PLATFORM_HBBTV_KEYCODES_H_

/** Used to set the user defined key range we pass into WebKit. */
#define KEYEVENT_VK_RANGE_MASK           0xFFFE0000

/**
 * An enumeration for all keys that are used in HbbTV/OIPF
 */
typedef enum EKeys
{
    KEYEVENT_VK_UNDEFINED            =   0,
    KEYEVENT_VK_CANCEL               =   3,
    KEYEVENT_VK_BACK_SPACE           =   8,
    KEYEVENT_VK_TAB                  =   9,
    KEYEVENT_VK_CLEAR                =  12,
    KEYEVENT_VK_ENTER                =  13,
    KEYEVENT_VK_SHIFT                =  16,
    KEYEVENT_VK_CONTROL              =  17,
    KEYEVENT_VK_ALT                  =  18,
    KEYEVENT_VK_PAUSE                =  19,
    KEYEVENT_VK_CAPS_LOCK            =  20,
    KEYEVENT_VK_KANA                 =  21,
    KEYEVENT_VK_FINAL                =  24,
    KEYEVENT_VK_KANJI                =  25,
    KEYEVENT_VK_ESCAPE               =  27,
    KEYEVENT_VK_CONVERT              =  28,
    KEYEVENT_VK_NONCONVERT           =  29,
    KEYEVENT_VK_ACCEPT               =  30,
    KEYEVENT_VK_MODECHANGE           =  31,
    KEYEVENT_VK_SPACE                =  32,
    KEYEVENT_VK_PAGE_UP              =  33,
    KEYEVENT_VK_PAGE_DOWN            =  34,
    KEYEVENT_VK_END                  =  35,
    KEYEVENT_VK_HOME                 =  36,
    KEYEVENT_VK_LEFT                 =  37,
    KEYEVENT_VK_UP                   =  38,
    KEYEVENT_VK_RIGHT                =  39,
    KEYEVENT_VK_DOWN                 =  40,
    KEYEVENT_VK_COMMA                =  44,
    KEYEVENT_VK_PERIOD               =  46,
    KEYEVENT_VK_SLASH                =  47,
    KEYEVENT_VK_0                    =  48,
    KEYEVENT_VK_1                    =  49,
    KEYEVENT_VK_2                    =  50,
    KEYEVENT_VK_3                    =  51,
    KEYEVENT_VK_4                    =  52,
    KEYEVENT_VK_5                    =  53,
    KEYEVENT_VK_6                    =  54,
    KEYEVENT_VK_7                    =  55,
    KEYEVENT_VK_8                    =  56,
    KEYEVENT_VK_9                    =  57,
    KEYEVENT_VK_SEMICOLON            =  59,
    KEYEVENT_VK_EQUALS               =  61,
    KEYEVENT_VK_A                    =  65,
    KEYEVENT_VK_B                    =  66,
    KEYEVENT_VK_C                    =  67,
    KEYEVENT_VK_D                    =  68,
    KEYEVENT_VK_E                    =  69,
    KEYEVENT_VK_F                    =  70,
    KEYEVENT_VK_G                    =  71,
    KEYEVENT_VK_H                    =  72,
    KEYEVENT_VK_I                    =  73,
    KEYEVENT_VK_J                    =  74,
    KEYEVENT_VK_K                    =  75,
    KEYEVENT_VK_L                    =  76,
    KEYEVENT_VK_M                    =  77,
    KEYEVENT_VK_N                    =  78,
    KEYEVENT_VK_O                    =  79,
    KEYEVENT_VK_P                    =  80,
    KEYEVENT_VK_Q                    =  81,
    KEYEVENT_VK_R                    =  82,
    KEYEVENT_VK_S                    =  83,
    KEYEVENT_VK_T                    =  84,
    KEYEVENT_VK_U                    =  85,
    KEYEVENT_VK_V                    =  86,
    KEYEVENT_VK_W                    =  87,
    KEYEVENT_VK_X                    =  88,
    KEYEVENT_VK_Y                    =  89,
    KEYEVENT_VK_Z                    =  90,
    KEYEVENT_VK_OPEN_BRACKET         =  91,
    KEYEVENT_VK_BACK_SLASH           =  92,
    KEYEVENT_VK_CLOSE_BRACKET        =  93,
    KEYEVENT_VK_NUMPAD0              =  96,
    KEYEVENT_VK_NUMPAD1              =  97,
    KEYEVENT_VK_NUMPAD2              =  98,
    KEYEVENT_VK_NUMPAD3              =  99,
    KEYEVENT_VK_NUMPAD4              = 100,
    KEYEVENT_VK_NUMPAD5              = 101,
    KEYEVENT_VK_NUMPAD6              = 102,
    KEYEVENT_VK_NUMPAD7              = 103,
    KEYEVENT_VK_NUMPAD8              = 104,
    KEYEVENT_VK_NUMPAD9              = 105,
    KEYEVENT_VK_MULTIPLY             = 106,
    KEYEVENT_VK_ADD                  = 107,
    KEYEVENT_VK_SEPARATER            = 108,
    KEYEVENT_VK_SUBTRACT             = 109,
    KEYEVENT_VK_DECIMAL              = 110,
    KEYEVENT_VK_DIVIDE               = 111,
    KEYEVENT_VK_F1                   = 112,
    KEYEVENT_VK_F2                   = 113,
    KEYEVENT_VK_F3                   = 114,
    KEYEVENT_VK_F4                   = 115,
    KEYEVENT_VK_F5                   = 116,
    KEYEVENT_VK_F6                   = 117,
    KEYEVENT_VK_F7                   = 118,
    KEYEVENT_VK_F8                   = 119,
    KEYEVENT_VK_F9                   = 120,
    KEYEVENT_VK_F10                  = 121,
    KEYEVENT_VK_F11                  = 122,
    KEYEVENT_VK_F12                  = 123,
    KEYEVENT_VK_DELETE               = 127,
    KEYEVENT_VK_NUM_LOCK             = 144,
    KEYEVENT_VK_SCROLL_LOCK          = 145,
    KEYEVENT_VK_PRINTSCREEN          = 154,
    KEYEVENT_VK_INSERT               = 155,
    KEYEVENT_VK_HELP                 = 156,
    KEYEVENT_VK_META                 = 157,
    KEYEVENT_VK_BACK_QUOTE           = 192,
    KEYEVENT_VK_QUOTE                = 222,
    KEYEVENT_VK_RED                  = 403,
    KEYEVENT_VK_GREEN                = 404,
    KEYEVENT_VK_YELLOW               = 405,
    KEYEVENT_VK_BLUE                 = 406,
    KEYEVENT_VK_GREY                 = 407,
    KEYEVENT_VK_BROWN                = 408,
    KEYEVENT_VK_POWER                = 409,
    KEYEVENT_VK_DIMMER               = 410,
    KEYEVENT_VK_WINK                 = 411,
    KEYEVENT_VK_REWIND               = 412,
    KEYEVENT_VK_STOP                 = 413,
    KEYEVENT_VK_EJECT_TOGGLE         = 414,
    KEYEVENT_VK_PLAY                 = 415,
    KEYEVENT_VK_RECORD               = 416,
    KEYEVENT_VK_FAST_FWD             = 417,
    KEYEVENT_VK_PLAY_SPEED_UP        = 418,
    KEYEVENT_VK_PLAY_SPEED_DOWN      = 419,
    KEYEVENT_VK_PLAY_SPEED_RESET     = 420,
    KEYEVENT_VK_RECORD_SPEED_NEXT    = 421,
    KEYEVENT_VK_GO_TO_START          = 422,
    KEYEVENT_VK_GO_TO_END            = 423,
    KEYEVENT_VK_PREV                 = 424,
    KEYEVENT_VK_NEXT                 = 425,
    KEYEVENT_VK_RANDOM_TOGGLE        = 426,
    KEYEVENT_VK_CHANNEL_UP           = 427,
    KEYEVENT_VK_CHANNEL_DOWN         = 428,
    KEYEVENT_VK_STORE_FAVORITE_0     = 429,
    KEYEVENT_VK_STORE_FAVORITE_1     = 430,
    KEYEVENT_VK_STORE_FAVORITE_2     = 431,
    KEYEVENT_VK_STORE_FAVORITE_3     = 432,
    KEYEVENT_VK_RECALL_FAVORITE_0    = 433,
    KEYEVENT_VK_RECALL_FAVORITE_1    = 434,
    KEYEVENT_VK_RECALL_FAVORITE_2    = 435,
    KEYEVENT_VK_RECALL_FAVORITE_3    = 436,
    KEYEVENT_VK_CLEAR_FAVORITE_0     = 437,
    KEYEVENT_VK_CLEAR_FAVORITE_1     = 438,
    KEYEVENT_VK_CLEAR_FAVORITE_2     = 439,
    KEYEVENT_VK_CLEAR_FAVORITE_3     = 440,
    KEYEVENT_VK_SCAN_CHANNELS_TOGGLE = 441,
    KEYEVENT_VK_PINP_TOGGLE          = 442,
    KEYEVENT_VK_SPLIT_SCREEN_TOGGLE  = 443,
    KEYEVENT_VK_DISPLAY_SWAP         = 444,
    KEYEVENT_VK_SCREEN_MODE_NEXT     = 445,
    KEYEVENT_VK_VIDEO_MODE_NEXT      = 446,
    KEYEVENT_VK_VOLUME_UP            = 447,
    KEYEVENT_VK_VOLUME_DOWN          = 448,
    KEYEVENT_VK_MUTE                 = 449,
    KEYEVENT_VK_SURROUND_MODE_NEXT   = 450,
    KEYEVENT_VK_BALANCE_RIGHT        = 451,
    KEYEVENT_VK_BALANCE_LEFT         = 452,
    KEYEVENT_VK_FADER_FRONT          = 453,
    KEYEVENT_VK_FADER_REAR           = 454,
    KEYEVENT_VK_BASS_BOOST_UP        = 455,
    KEYEVENT_VK_BASS_BOOST_DOWN      = 456,
    KEYEVENT_VK_INFO                 = 457,
    KEYEVENT_VK_GUIDE                = 458,
    KEYEVENT_VK_TELETEXT             = 459,
    KEYEVENT_VK_SUBTITLE             = 460,
    KEYEVENT_VK_BACK                 = 461,
    KEYEVENT_VK_MENU                 = 462,
    KEYEVENT_VK_PLAY_PAUSE           = 463
} EKeys;

#endif /* _PLATFORM_HBBTV_KEYCODES_H_ */

